### ISSUE TITLE
How to get the mask of face?

### ISSUE THREAD

**Issue by CainHu** [iperov/DeepFaceLab#101]
I have a question about the mask. There is only a dataset of images, but no mask. How can the NN learn to predict a mask? Is there a trained Mask-RCNN or FCN for getting the mask？

**Comment by iperov** [comment]
dlib/mtcnn - extracts bounding box of face in video frame
2D-FAN4 - extracts 68 landmarks from this box and extractor embeds this data into png
final mask for train constructed by cv2.fillConvexPoly cv2.convexHull from landmarks
