### ISSUE TITLE
working with RTX2070

### ISSUE THREAD

**Issue by frossi65** [iperov/DeepFaceLab#102]
i have bought a RTX2070 . i read in some post that somebody can train with this card, even before tensorflow 1.13 ,  but i haven't been able to make it work.

i was wondering if somebody can give me some advice on how to setup the system. 

i have installed  the prerequisites
CUDA 9.0
cudNN 7.1.4
Microsoft Visual Studio 2015 C++ Build Tools
Python 3.6
cmake 3.8.2+ 
tensorflow-gpu 1.11
keras-contrib

but when i launch train H128 it start asking for the options
 and at the end it says "enter any key to continue"
without any error

I have the program working on my notebook that has a gtx950. 
thanks to iperov for the great work.

**Comment by iperov** [comment]
rtx works only with cuda 10
tf 1.13 works with cuda 10 but still not released in pip

**Comment by TooMuchFun** [comment]
Try the [tf-nightly-gpu](https://pypi.org/project/tf-nightly-gpu/) package in pip. It ran without trouble when I tested in Docker on a linux hos. Keep an eye on [the CUDA 10 thread](https://github.com/tensorflow/tensorflow/issues/22706) in the official tensorflow repo. We will test and update when release ships.

What Windows support look like then... not sure. But I would expect a 1.13 release for all platforms soon. But cannot tell when all dependent other libraries (Keras, CUDA, CUDNN) will all upgrade and support new tf.

**Comment by jians5** [comment]
I have it running on an RTX 2080. It works with both Cuda 9 and Cuda 10. The only problem I've encountered is I have to use the MT extractor instead of DLIB - otherwise the whole process worked from start to finish.

**Comment by frossi65** [comment]
thanks for the answers and your support. i am running on windows10. i guess i have to wait at least for the tf-nightly-gpu for windows. i don't think it is out

**Comment by jians5** [comment]
Which version of what? I'm using the Prebuilt Windows App. I have the latest Cuda 10 and CUDNN installed, but I think that's irrelevant. Version of model? They all seem to work, h128, DF, etc.

I've been having some issues getting the model to train if I'm doing other stuff with the PC. If I close everything until the training window opens, then I'm free to use the machine after it starts, but if a YouTube video or something is playing in the background, training fails to start. It might be an overclock stability issue on my end - or just some conflict when loading the GPU memory. Thought I'd mention it in case it's relevant.

**Comment by frossi65** [comment]
i am ashamed to admit it but i did not succeed to make it work as jians5  did. Probably i have missed some steps since i am not expert at all. 
guess i have to wait for the prebuilt windows app with CUDA10.

**Comment by iperov** [comment]
@frossi65 thx for support dfl
