### ISSUE TITLE
need a tutorial for the whole faceswap

### ISSUE THREAD

**Issue by KeyKy** [iperov/DeepFaceLab#105]
Could you provide a tutorial for whole extracting, training and merging? Which commands do i need to call? Do i need to call sort after extract face from video?

**Comment by KeyKy** [comment]
@iperov do you open source your best model (MLAEF)?

**Comment by iperov** [comment]
basic tutorial available on github page, search 'tutor'

**Comment by iperov** [comment]
because SAE model better than miaef

**Comment by KeyKy** [comment]
@iperov Thank! I successfully trained a model. However, when i convert it, i found the face a little bit shaking. Do you have some idea to solve this problem? Is the keypoints alignment results to the shaking?
