### ISSUE TITLE
It's bad to dump infos in PNG files.

### ISSUE THREAD

**Issue by QuantumLiu** [iperov/DeepFaceLab#106]
DFL is a winderful lib, thank you for your work.
However, dumping training infos in PNG files is "dirty".
I wrote an extract tools by myself, and it can extract specific person's faces from videos and images. It output normal PNG file and it can't be use fo DFL.
Would you separate training infos from PNG files and sotre it into JSON or other format files?

**Comment by iperov** [comment]
no, json file is redundant and obsolete solution
