### ISSUE TITLE
Error: 'Model' object has no attribute 'random_flip' pop up while using H128

### ISSUE THREAD

**Issue by z1146335535** [iperov/DeepFaceLab#108]
## Expected behavior

H64 is work but it pop up a error when I use H128

## Actual behavior

Running trainer.

Loading model...

Model first run. Enter model options as default for each run.
Write preview history? (y/n skip:n) :
Target epoch (skip:unlimited) :
Batch_size (skip:model choice) :
Feed faces to network sorted by yaw? (y/n skip:n) :
Error: 'Model' object has no attribute 'random_flip'
Traceback (most recent call last):
  File "D:\Download\DeepFaceLab\DeepFaceLab\DeepFaceLabTorrent_build_03_01_2019\
DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Trainer.py", line 39, i
n trainerThread
    **in_options)
  File "D:\Download\DeepFaceLab\DeepFaceLab\DeepFaceLabTorrent_build_03_01_2019\
DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ModelBase.py", line 114, in
__init__
    self.onInitialize(**in_options)
  File "D:\Download\DeepFaceLab\DeepFaceLab\DeepFaceLabTorrent_build_03_01_2019\
DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\Model_H128\Model.py", line 4
9, in onInitialize
    sample_process_options=SampleProcessor.Options(random_flip=self.random_flip,
 scale_range=np.array([-0.05, 0.05])+self.src_scale_mod / 100.0 ),
AttributeError: 'Model' object has no attribute 'random_flip'
Done.

## Other relevant information
Windows 7 GTX970 CUDA9.0 tensorflow is up to date

**Comment by iperov** [comment]
unable to reproduce. All works fine at me.
