### ISSUE TITLE
When starting 4) data_src extract faces DLIB all GPU.bat, an error is reported.

### ISSUE THREAD

**Issue by yiyang74262580** [iperov/DeepFaceLab#110]
This error will be reported using MT or DLIB
Performing 1st pass...
Traceback (most recent call last):
  File "F:\DeepFaceLabTorrent_build_12_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\main.py", line 139, in <module>
    arguments.func(arguments)
  File "F:\DeepFaceLabTorrent_build_12_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\main.py", line 41, in process_extract
    manual_window_size=arguments.manual_window_size
  File "F:\DeepFaceLabTorrent_build_12_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 430, in main
    extracted_rects = ExtractSubprocessor ([ (x,) for x in input_path_image_paths ], 'rects', image_size, face_type, debug, multi_gpu=multi_gpu, cpu_only=cpu_only, manual=False, detector=detector).process()
  File "F:\DeepFaceLabTorrent_build_12_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 113, in process
    raise Exception ("Unable to start Subprocessor '%s' " % (self.name))
Exception: Unable to start Subprocessor 'Extractor'
I am using GeForce 940MX

**Comment by iperov** [comment]
did you try 'best GPU' ?

**Comment by yiyang74262580** [comment]
940 is the best GPU

**Comment by iperov** [comment]
but all and best GPu - is different scripts.
Did you try 'best GPU.bat' ?

**Comment by yiyang74262580** [comment]
I know, thank you.

**Comment by iperov** [comment]
is 'best GPU' works?

**Comment by yiyang74262580** [comment]
Wait a minute

**Comment by yiyang74262580** [comment]
![snipaste_2019-01-13_18-49-58](https://user-images.githubusercontent.com/33800842/51084402-0e900a00-1764-11e9-9042-32c17a0055a0.png)
Is this this?

**Comment by iperov** [comment]
yes, your GPU not working in DFL.
I want examine this problem. Can you install TeamViewer?

**Comment by yiyang74262580** [comment]
yes

**Comment by iperov** [comment]
![teamviewer_2019-01-13_15-01-03](https://user-images.githubusercontent.com/8076202/51084494-0cb64e80-1744-11e9-94c9-0b691be3bae7.jpg)

send this data to email deepfakescovery@gmail.com

**Comment by oracle9i88** [comment]
I donate 101 yuan by alipay, you are genius

**Comment by iperov** [comment]
thx man

**Comment by iperov** [comment]
problem fixed
