### ISSUE TITLE
[Linux] Regarding fork availability for Mac, Linux or running on AWS?

### ISSUE THREAD

**Issue by WizardOfAus** [iperov/DeepFaceLab#112]
Hi,

Was wondering if anyone managed to fork and make a version for Mac or Linux? Otherwise, is this also possible to run on a VM on AWS?

**Comment by TooMuchFun** [comment]
Its works great for me on an Ubuntu 16.04 host. Follow NVIDIA's [installation guide](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html). After that, install the `pip` dependencies and you are really to execute from script.

But the easiest way to build a solid DFL environment is inside a Docker container. You will not have to do any manual confiruation steps on the host machine, besides installing `nvidia-docker`. If you are comfortable using Docker environments, try this Dockerfile:

https://gist.github.com/TooMuchFun/5f9cc9807e9d302f6b332a3d296169d9

Please see the comment below the code for an example on how to run it. Let me know if it works for you. If there is enough interest it could probably be merged into the main fork.

**Comment by yg2dras1** [comment]
@TooMuchFun newbie here, could you please list down the steps on how to run DeepFaceLab on Ubuntu please? I don't have Windows on my machine but would really love to use DFL. thank you!

**Comment by TooMuchFun** [comment]
@yg2dras1 try the `apt-get` and `pip` steps from each `RUN` command used in [this Dockerfile](https://gist.github.com/TooMuchFun/5f9cc9807e9d302f6b332a3d296169d9).

**Comment by lbfs** [comment]
https://github.com/lbfs/DeepFaceLab_Linux I've forked the codebase and converted some of the scripts to run on Ubuntu LTS. Unsure how actively I will maintain this though and if it works on AWS since I'm not familiar enough with it.

**Comment by oracle9i88** [comment]
@ibfs wish your osx version ASAP.

**Comment by lbfs** [comment]
I have very little ability to test Mac OS in my environment. You can use homebrew to install the same dependencies that the apt install command requests. The rest of the instructions are the same except instead of using requirements-cuda9-cudnn7.txt you want to use requirements-cpu.txt

I'm not sure if using Mac OS for training is the best idea considering OpenCL and OpenGL support was dropped in Mac OS Mojave.

**Comment by oracle9i88** [comment]
@lbfs Thanks.

**Comment by oracle9i88** [comment]
@lbfs  we need main.sh file for unix version

**Comment by lbfs** [comment]
Look in my scripts directory in my repo, there is no reason to have a main.sh.

**Comment by HelpSeeker** [comment]
> Please direct any further questions to my repo to avoid spamming this one for no reason.

Then it would probably be a good idea to enable the issue section for your fork.

**Comment by oracle9i88** [comment]
> > Please direct any further questions to my repo to avoid spamming this one for no reason.
> 
> Then it would probably be a good idea to enable the issue section for your fork.

Sure， we need issue section

**Comment by lbfs** [comment]
@HelpSeeker @oracle9i88 I've enabled the issues section, I'm not sure how it got disabled, but I've reenabled it again.

**Comment by iperov** [comment]
@lbfs 
video editing now works by ffmpeg via DFL 

[lbfs.zip](https://github.com/iperov/DeepFaceLab/files/2922160/lbfs.zip)

**Comment by iperov** [comment]
@lbfs ffmpeg and ffprobe must be in env access

**Comment by lbfs** [comment]
Thank you for letting me know, I'll work on implementing this when I have time.

**Comment by lbfs** [comment]
Alright, got most of your scripts added. That makes the whole video process that much easier :+1:

**Comment by iperov** [comment]
does anyone know how to set_process_lowest_prio in linux?
```
def set_process_lowest_prio():
    if sys.platform[0:3] == 'win':
        GetCurrentProcess = windll.kernel32.GetCurrentProcess
        GetCurrentProcess.restype = wintypes.HANDLE
        
        SetPriorityClass = windll.kernel32.SetPriorityClass
        SetPriorityClass.argtypes = (wintypes.HANDLE, wintypes.DWORD)
        SetPriorityClass ( GetCurrentProcess(), 0x00000040 )
```

**Comment by lbfs** [comment]
If your talking about process priority, I think you can use 
```python
import os
os.nice(20) # -20 is highest, 20 is lowest
```

**Comment by iperov** [comment]
thx !
```
os.nice(increment)
Add increment to the process’s “niceness”. Return the new niceness.
Availability: Unix.
```
will it work on linux and mac?

**Comment by lbfs** [comment]
Possibly, some of my research leads me to believe that Mac only supports values between -10 and 10 for the os.nice()

**Comment by Tymec** [comment]
I was wondering if it's possible to setup DeepFaceLab on Jupyter Notebooks like the one provided by Google Collab or Azure ML Studio, you don't get sudo permission there so you can't install additional dependencies like snap or Anaconda, so I was wondering if there's any way to run this on the notebook.

**Comment by lbfs** [comment]
Looks like plaidML works on Linux without much hassle :D Only requirement is you need to run plaidml-setup which doesn't take too long. 

```bash
(deepfacelab) luke@spirit:/mnt/secondary/DeepFaceLab/scripts$ clear;./5_data_dst_extract_faces_S3FD_best_GPU.sh 

Performing 1st pass...
Running on NVIDIA Corporation GeForce GTX 1070 Ti (OpenCL).
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_nvidia_geforce_gtx_1070_ti.0"
  0%|                                                   | 0/622 [00:00<?, ?it/s]INFO:plaidml:Analyzing Ops: 41 of 285 operations complete
INFO:plaidml:Analyzing Ops: 124 of 285 operations complete
100%|#########################################| 622/622 [01:07<00:00,  9.20it/s]
Performing 2nd pass...
Running on NVIDIA Corporation GeForce GTX 1070 Ti (OpenCL).
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_nvidia_geforce_gtx_1070_ti.0"
  0%|                                                   | 0/622 [00:00<?, ?it/s]INFO:plaidml:Analyzing Ops: 411 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1010 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1627 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2247 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2879 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3522 of 3786 operations complete
100%|#########################################| 622/622 [01:32<00:00,  6.69it/s]
Performing 3rd pass...
Running on CPU3.
Running on CPU1.
Running on CPU0.
Running on CPU4.
Running on CPU7.
Running on CPU6.
Running on CPU2.
Running on CPU5.
100%|############################################################################################################################################################################################################################################| 622/622 [00:13<00:00, 47.19it/s]
-------------------------
Images found:        622
Faces detected:      548
-------------------------
Done.
```
