### ISSUE TITLE
It's not a technical issue，just want to help DeepFaceLab get better.

### ISSUE THREAD

**Issue by phpforlan** [iperov/DeepFaceLab#113]
Hi, I am a DeepFaceLab fans from china, many chinese programmer want to learn faceswap technology. when I research a lot of products about AI faceswap software, I think DeepFaceLab is the best. For the following reasons:

1. update most frequently
2. easiest to use
3. high quality video output

so I want to build a china DeepFaceLab official website about technology. it will help many chinese programmer. it is amazing!

now I've built a simple website. it will promotion DeepFaceLab in china.
Site URL:  http://www.deepfacelab.cn

please contact with me. thanks.
email: lubootisbadguy@gmail.com
work:  senior programmer (java、php、go)

**Comment by keyutao9** [comment]
> 嗨，我是来自中国的DeepFaceLab粉丝，很多中国程序员都想学习faceswap技术。当我研究很多关于AI faceswap软件的产品时，我认为DeepFaceLab是最好的。原因如下：
> 
> 1. 最频繁更新
> 2. 最容易使用
> 3. 高品质的视频输出
> 
> 所以我想建立一个关于技术的中国DeepFaceLab官方网站。它将帮助许多中国程序员。太神奇了！
> 
> 现在我建立了一个简单的网站。它将在中国推广DeepFaceLab。
> 网站网址：[http](http://www.deepfacelab.cn)： [//www.deepfacelab.cn](http://www.deepfacelab.cn)
> 
> 请与我联系。谢谢。
> 电子邮件：[lubootisbadguy@gmail.com](mailto:lubootisbadguy@gmail.com)
> 工作：高级程序员（java，php，go）

支持作者请主页捐款，已经开通支付宝收款，还有主页最下面有QQ群和网站，欢迎参与

**Comment by iperov** [comment]
Hi. 
what you want from me?
There are two chinese comm groups already mentioned in github page, includes QQ group for ML/AI experts.

**Comment by phpforlan** [comment]
> Hi.
> what you want from me?
> There are two chinese comm groups already mentioned in github page, includes QQ group for ML/AI experts.

Hi, iperove:
   you are frank, Let me just say what I think. First Like them, I wish you give me a authentication. in github page, Introduce http://www.deepfacelab.cn as an official chinese site.
   secondly, I am Improving http://www.deepfacelab.cn, In order to provide more chinese tutorials of DeepFaceLab. Looking forward to your giving me a chance. 

best wishes to you! thank you.

**Comment by iperov** [comment]
but your site is empty.

@keyutao9 what you think?

**Comment by TooMuchFun** [comment]
Maybe you could create a section in the README referring to these unofficial channels? It is not a good idea to add non-contributing users privileges.

It is not the time to give any official status to any site or group not directly affiliated with @iperov directly. This project is still very experimental and not ready to be supported for large groups. The core devs have better things to do.

**Comment by Arthurzhangsheng** [comment]
Frankly speaking, It's not a good idea to open a so call "official chinese site". It's dangerous to spread this tech everywhere.
@phpforlan 老哥别做被查水表的事，肯定有傻逼会拿这技术做出格的事，然后查下来一看这网站还是个百度的人开的，你就凉凉了。仅限AI圈交流吧，不要把这技术扩散到群众当中去。你想帮助iperov就捐助点钱帮助他买RTX2080ti吧

**Comment by dream80** [comment]
楼上说的有道理，给iperov捐点钱提升配置，然后他可以去优化代码。我也想搞个2080，贵啊！

**Comment by keyutao9** [comment]
> 但是你的网站是空的。
> 
> @keyutao9你怎么想？

I agree with Arthurzhangsheng

**Comment by phpforlan** [comment]
> but your site is empty.
> 
> @keyutao9 what you think?
Hi, iperov:
  I am Improving http://www.deepfacelab.cn, It will take some time. It is expected to take half a month.

@Arthurzhangsheng I know what you mean.Maybe I didn't make my words clear. deepfacelab.cn just for technology communication and publish some high-quality AI articles.Not like www.deepfakes.com.cn, teach normal people how to use DeepFaceLab software.As for donations,when I feel right, I will spare no effort to donate money.Now I'm just at the research stage of DeepFaceLab.Thanks for understanding.

**Comment by phpforlan** [comment]
> Hi.
> what you want from me?
> There are two chinese comm groups already mentioned in github page, includes QQ group for ML/AI experts.

Hi, iperov:
Maybe I can provide a Chinese translation version of github page, This is the beginning of cooperation. 
I really want to learn and improve with you! of course, it depends on you.

**Comment by iperov** [comment]
again
http://www.deepfacelab.cn/ - is EMPTY SITE. I see no comm groups, no peoples, no articles.
Why I must advertise it for free?

**Comment by phpforlan** [comment]
> again
> http://www.deepfacelab.cn/ - is EMPTY SITE. I see no comm groups, no people, no articles.
> Why I must advertise it for free?

All right.
