### ISSUE TITLE
Failing on step 6 - no CV

### ISSUE THREAD

**Issue by GantMan** [iperov/DeepFaceLab#114]
## Expected behavior
Training using step 6 should train and show CV visual of training progress

## Actual behavior

Immediately errors and shows blank CV screen with CLI error on windows.

![image](https://user-images.githubusercontent.com/997157/51334631-13d7a800-1a35-11e9-9b71-4d3f12ac6abd.png)

![image](https://user-images.githubusercontent.com/997157/51334516-cf4c0c80-1a34-11e9-8359-41c2850c1398.png)

## Steps to reproduce

*Just clicking step 6 training, any of them do it.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows
- **Python version:** 3.6.3 installed, but using the one in _internal

**Comment by iperov** [comment]
there are nothing missing in DFL prebuilt folder. All tested on clean windows.

**Comment by iperov** [comment]
looks like your system python installation overrides embedded DFL

**Comment by iperov** [comment]
i dont know how to fix it. 
setenv.bat already sets own paths in first priority.

**Comment by iperov** [comment]
`SET PATH=%BIN_DIR%\REDIST;%BIN_DIR%\CUDA;%BIN_DIR%;%BIN_DIR%\Scripts;%BIN_DIR%\CMake\Bin;%PATH%`

**Comment by iperov** [comment]
![cmd_2019-01-17_21-46-18](https://user-images.githubusercontent.com/8076202/51337724-520ab100-1aa1-11e9-955b-b0194c31f1eb.jpg)

**Comment by iperov** [comment]
may be your system has some `PYTHON_**` env variables that DFL python actualy read at first?

**Comment by GantMan** [comment]
it must be my native python getting in the way.   Since I got around it for now, I'll keep going, but if I get stuck again I'll definitely check on how to make sure the env works.

Thanks!

**Comment by iperov** [comment]
it would be good if you can research conflict embedded DFL with your system installation.

**Comment by GantMan** [comment]
Will do!  Currently trying to train for the first time.  I'll investigate further.
