### ISSUE TITLE
About SAE...

### ISSUE THREAD

**Issue by ZeroCool22** [iperov/DeepFaceLab#115]
> First train it with both style powers at 10.0+ value. **When artifacts become appearing at ~30-40k epochs, set face style to 0.0 or 0.01 and bg style to 0.1-0.3** and continue training. You can slightly vary theese values during training if something goes wrong. Track changes in preview history.

There is some way to make the .bat to ask me to change this (apart from the first time runing) or the only way is to change it in the .py?

**Comment by iperov** [comment]
Press enter in 2 seconds to override some model settings.
