### ISSUE TITLE
AVATAR conversion throws error

### ISSUE THREAD

**Issue by grssnbchr** [iperov/DeepFaceLab#12]
Hey, I get the following error when trying to convert an AVATAR model trained on 1500 and 3000 face images respectively:

```
Exception while process data [undefined]: Traceback (most recent call last):
  File "C:\deepfakes\DeepFaceLab_06_07\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 232, in subprocess
    result = self.onClientProcessData (data)
  File "C:\deepfakes\DeepFaceLab_06_07\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 150, in onClientProcessData
    image = self.converter.convert_image(image, image_landmarks, self.debug)
  File "C:\deepfakes\DeepFaceLab_06_07\_internal\bin\DeepFaceLab\models\Model_AVATAR\Model.py", line 244, in convert_image
    face_mat            = LandmarksProcessor.get_transform_mat (img_face_landmarks, self.predictor_input_size, face_type=FaceType.HALF )
  File "C:\deepfakes\DeepFaceLab_06_07\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 58, in get_transform_mat
    mat = umeyama(image_landmarks[17:], landmarks_2D, True)[0:2]
IndexError: too many indices for array
```
The error seems to be thrown multiple times, I have 40 CPUs/threads working on conversion in parallel. 

I'm using the binaries from https://rutracker.org/forum/viewtopic.php?p=75318742, 6.7.2018. 

How should I proceed?

**Comment by gessyoo** [comment]
The readme for the AVATAR model states that you can train on 1500 dst faces, but can use only 100 for conversion.  Are you trying to convert more than 100 dst images?

**Comment by grssnbchr** [comment]
Thanks for the hint, I'll try that.

**Comment by gessyoo** [comment]
yes, read the docs and comments to the model code.

**Comment by iperov** [comment]
@gessyoo is avatar example https://www.youtube.com/watch?v=3M0E4QnWMqA 100 frames long?

**Comment by gessyoo** [comment]
iperov, if I'm giving wrong advice, I apologize.

**Comment by grssnbchr** [comment]
So what is it now? The conversion actually worked with 100 dst frames (however I'm having problems converting them to mp4 now, but that's probably not related).

**Comment by oracle9i88** [comment]
why I use 100 dst frames, it's still wrong

**Comment by oracle9i88** [comment]
> So what is it now? The conversion actually worked with 100 dst frames (however I'm having problems converting them to mp4 now, but that's probably not related).

how do you resolve it?
