### ISSUE TITLE
Model face disappearance and loss_nan issues

### ISSUE THREAD

**Issue by OldYogurt** [iperov/DeepFaceLab#120]
Hey, this is my first time to learn Deepfacelab. Few days ago I used your tool make a vid Successfully. And when I try to make another vid, I had some problems in training.
This is my hardware: i7 8700K, RTX2080TI, WIN10 X64
And I've tried to run under different model types: H128(all default) H128(batch_size 2/8/16/24/32) LIAEF128(all default) LIAEF128(batch_size 2/8/16/24)
Here is screenshot: 
![1](https://user-images.githubusercontent.com/22132381/51612197-ed959900-1f5b-11e9-823f-6dfa6062bcbe.jpg)
![2](https://user-images.githubusercontent.com/22132381/51612199-ee2e2f80-1f5b-11e9-9cd3-0b8a2f7ec4a8.png)
This problem has been bothering me for nearly a week. I hope you can help me.

**Comment by iperov** [comment]
upload this workspace to google drive, and post link here

**Comment by iperov** [comment]
never seen such behaviour.

**Comment by OldYogurt** [comment]
The whole workspace? including DTS and SRC vids? Wait me a second...

**Comment by iperov** [comment]
without vids

**Comment by OldYogurt** [comment]
Oh, Okay, but it may take a few hours. I will send it to you as soon as possible after I upload it.

**Comment by iperov** [comment]
ok, also zip it with no compress, please

**Comment by GAN-er** [comment]
If plist_abs_max had ended up in 227 as a 0, we would see a division by 0 error rather than a NaN error. 
So it must have arrived there as NaN from this line:
plist_abs_max = np.mean(loss_history[ len(loss_history) // 5 : ]) * 2

which is strange as hell. 
Did you get the files yet?

python not being strongly typed is a nightmare to debug :/

**Comment by OldYogurt** [comment]
Sorry, it's hard for me to use Google on my network. I have to upload a zip file.
https://drive.google.com/open?id=1ScgD9wQ4Agu2v_9zpjpMFlQsRN_gX6Pg

**Comment by iperov** [comment]
I started to train your workspace.
All is going fine.

![python_2019-01-24_09-21-02](https://user-images.githubusercontent.com/8076202/51656145-5d863c80-1fb9-11e9-8bf1-972153431652.jpg)

**Comment by iperov** [comment]
install  teamviewer, send me id and pass to lepersorium@gmail.com
I will check some things directly on your comp.

**Comment by OldYogurt** [comment]
I'm still working. Teamviewer is not convenient for me now. Is 5:00 ETC time OK?

**Comment by iperov** [comment]
yes

**Comment by iperov** [comment]
6:00 etc now

**Comment by OldYogurt** [comment]
Oh shit.. SORRY.. How did I say ETC time (what is ETC...). I want to say PST time...

**Comment by iperov** [comment]
I cannot wait days

**Comment by OldYogurt** [comment]
I'm very sorry... Do you still have time? Or we can change the time. What time zone are you in?

**Comment by iperov** [comment]
I have 50 minutes now.

**Comment by tokenterprises** [comment]
OldYogurt, what exactly was the solution? I have attempted my first two training modes, SAE and LIAEF128, and all goes well until somewhere after 50,000 epoch. Then I have the same "nan" issue.

**Comment by iperov** [comment]
@tokenterprises

wash your eyes

**Frequency reduction for GPU**

**Comment by tokenterprises** [comment]
@iperov, thank you for the feedback. Considering you "never seen such behaviour" and now have multiple people describing this issue, I hope you see there is a common theme here.

Is reducing GPU frequency an option in DeepFaceLab, or do I need to make the changes directly through my graphic card's software? My graphics card is at factory default settings. Do you know what my be causing a normal functioning graphics card to be calculating "too fast" in DeepFaceLab? Other than GPU frequency, what else may be causing certain people to experience this problem despite many others using identical graphics cards?

**Comment by iperov** [comment]
GPU glitches is not DFL problem.

> now have multiple people describing this issue

you are wrong. DFL works fine at 95% of people.
