### ISSUE TITLE
A problem with GTX 1050 Ti support?

### ISSUE THREAD

**Issue by KantorFitz** [iperov/DeepFaceLab#121]
Hi, I'm quite new into DeepFakes so let me describe a problem I've encountered. It looks as follows:
![err1](https://user-images.githubusercontent.com/18150714/51631532-44e03d00-1f4d-11e9-8602-dfb4182fa4c6.png)

Ok, So I've figured out that the cause might just be a lack of some function in CUDA dll included in this package. The next step I did was to manually check compute capability of my GTX1050 Ti with CUDA, which appeared to be 6.1. Ok then.  I entered that value previously commenting out part of code that caused troubles to be like this:
```
#DeepFaceLab additions
def nvmlDeviceGetCudaComputeCapability(device):
    #c_major = c_int()
    #c_minor = c_int()
    #fn = _nvmlGetFunctionPointer("nvmlDeviceGetCudaComputeCapability")    
    # get the count
    #ret = fn(device, byref(c_major), byref(c_minor))    
    # this should only fail with insufficient size
    ##if (ret != NVML_SUCCESS):
    ##    raise NVMLError(ret)
    #return c_major.value, c_minor.value
    return (6, 1)
```

Now error looks like this:
![err2](https://user-images.githubusercontent.com/18150714/51632931-b40b6080-1f50-11e9-86f0-e08ce162b15c.png)

At this point I'm running whole setup with this settings (the same function as above):
`...
    return (3, 0)
`
so I can at least run it. In other words it works, but very inefficiently due to engagement of CPU only.

Here is my question, is there anything that can be done to support GTX1050 Ti? Any help would be appreciated.
Thanks in advance.

**Comment by iperov** [comment]
did you install fresh drivers from geforce.com?

**Comment by KantorFitz** [comment]
> 
> 
> did you install fresh drivers from geforce.com?

Hi, updated it few hours ago, all seem to work smoothly, thanks

**Comment by iperov** [comment]
why you didnt read

```
Prebuilt windows app:
Windows 7,8,8.1,10 zero dependency ( **just install/update your GeForce Drivers** ) prebuilt DeepFaceLab (include GPU and CPU versions) can be downloaded from
```
