### ISSUE TITLE
about use sae to train the obstructed face model.

### ISSUE THREAD

**Issue by meiyingxiaoyao** [iperov/DeepFaceLab#122]
I trained to 40K when the artifact appeared, the dst picture's the left face was covered by hair, but the artifact is very light, can not cover the left eye. Do I need to change the face and bg style to 0.0 and 0.1 immediately? Or wait until the artifact completely obscures the left eye before changing the parameters?

**Comment by meiyingxiaoyao** [comment]
I am in 1060 3g,7500，my bs was 8. in you tips，you say 30k-40k will appear artifacts,but my artifacts were too light to cover the left eye during these epoch.

**Comment by meiyingxiaoyao** [comment]
![360 20190124184852810](https://user-images.githubusercontent.com/46993987/51673414-f3958380-2008-11e9-87a8-6589b01c3b74.jpg)
my setting .

**Comment by iperov** [comment]
## Expected behavior
## Actual behavior
## Steps to reproduce

**Comment by meiyingxiaoyao** [comment]
> ## Expected behavior
> ## Actual behavior
> ## Steps to reproduce

![360 20190124190934378](https://user-images.githubusercontent.com/46993987/51674657-33aa3580-200c-11e9-8fc8-8b47061c295d.jpg)
like this.Is it enough to change the face and bg style?
