### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by JohnSnow2019** [iperov/DeepFaceLab#123]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by JohnSnow2019** [comment]
there is a vedio  on youtube ,https://www.youtube.com/watch?v=fqu60m4rWxc    the title is  DeepFaceLab raw converter mode.I wanna do the same thing,but I do not know how.Maybe you are the one who upload that vedio ,so I think you could do me a favor.    my e-mail: youusedtocallmedean@gmail.com    thanks a lot!!

**Comment by PlagueAI** [comment]
> 
> 
> there is a vedio on youtube ,https://www.youtube.com/watch?v=fqu60m4rWxc the title is DeepFaceLab raw converter mode.I wanna do the same thing,but I do not know how.Maybe you are the one who upload that vedio ,so I think you could do me a favor. my e-mail: [youusedtocallmedean@gmail.com](mailto:youusedtocallmedean@gmail.com) thanks a lot!!

![screenshot_1](https://user-images.githubusercontent.com/47086934/51804950-ea452a80-2245-11e9-9bf4-2029d5a9cbf3.png)

Option 6.
