### ISSUE TITLE
A new idea about loss

### ISSUE THREAD

**Issue by Arthurzhangsheng** [iperov/DeepFaceLab#125]
I have an idea about new type of loss, I'm not sure if this kind of loss have you already used:
First, we got a faceA through src2dst net, . Then put the faceA into src2src net, got face B. Update the src2dst net weights by minimize the difference between faceA and faceB with src2src net weights frozen.

The reason is that src2src net always generate the more realistic src face than src2dst net, so we can use it to improve the src2dst net result.

**Comment by claudetheboof** [comment]
sounds like you are talking about GAN or Generative Adversarial Network
