### ISSUE TITLE
Something is wrong with SAE converter, strange artifacts...

### ISSUE THREAD

**Issue by PlagueAI** [iperov/DeepFaceLab#126]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Just merging as usual.

## Actual behavior

**Video showing the issue:** https://streamable.com/zc68x

===== Model summary =====
== Model name: SAE
==
== Current epoch: 4481
==
== Model options:
== |== batch_size : 12
== |== sort_by_yaw : True
== |== random_flip : True
== |== resolution : 128
== |== archi : df
== |== lighter_encoder : False
== |== learn_mask : True
== |== face_style_power : 10.0
== |== bg_style_power : 10.0
== |== pixel_loss : False
== |== ae_dims : 698
== |== ed_ch_dims : 51
== |== face_type : f
== Running on:
== |== [0 : GeForce GTX 1080 Ti]

Choose mode: (1) overlay, (2) hist match, (3) hist match bw, (4) seamless (default), (5) seamless hist match, (6) raw : 2
Masked hist match? (y/n skip:y) :
y
Hist match threshold [0..255] (skip:255) :
255
Use predicted mask? (y/n skip:y) :
y
Choose erode mask modifier [-200..200] (skip:0) : 100
Choose blur mask modifier [-200..200] (skip:0) : 200
Choose output face scale modifier [-50..50] (skip:0) :
0
Transfer color from dst face to converted final face? (y/n skip:n) :
n
Degrade color power of final image [0..100] (skip:0) :
0
Export png with alpha channel? (y/n skip:n) :
n

Collecting alignments: 100%|#######################################################| 163/163 [00:00<00:00, 2087.85it/s]
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Converting:   0%|                                                                              | 0/163 [00:00<?, ?it/s]C:\Users\plague\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ConverterMasked.py:243: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_border_rect_mask_a
Converting:   2%|#7                                                                    | 4/163 [00:00<00:16,  9.85it/s]C:\Users\plague\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ConverterMasked.py:243: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_border_rect_mask_a
Converting:  71%|################################################3                   | 116/163 [00:07<00:02, 21.36it/s]C:\Users\plague\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ConverterMasked.py:243: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_border_rect_mask_a
Converting: 100%|####################################################################| 163/163 [00:09<00:00, 16.88it/s]
Done.

## Other relevant information
If i don't use any value in erode mask & blur mask it don't show the **Black Dots Artifacts**.

**Comment by ytn2001** [comment]
This situation has also appeared before, when the SRC image size is too small, it is easy to appear this hint and black spots, not just SAE.

**Comment by PlagueAI** [comment]
> 
> 
> This situation has also appeared before, when the DST image size is too small, it is easy to appear this hint and black spots, not just SAE.

I trained & merged the same dataset on LIAEF & H128 and this don't happen, only with SAE.
