### ISSUE TITLE
Note: It is recommended not to upgrade numpy to 1.16 for the time being.

### ISSUE THREAD

**Issue by ytn2001** [iperov/DeepFaceLab#127]
Yesterday, I upgraded numpy to 1.16.1 and started everything normal, but after 1 hour of training, I got a memory error. Today I downgraded numpy to 1.15.4, but the training could not run. Later I found this：
[https://github.com/numpy/numpy/issues/12837](url)
**BUG: ndarrays pickled on 1.16.0 cannot be loaded in previous versions.**

PS: I tested the previously trained model and found that numpy 1.15.4 is running normally. If I use the model trained in 1.16.1, I will get an error.

![image](https://user-images.githubusercontent.com/36368758/51903019-477fde00-23f6-11e9-8e9e-26ff8d9b9d6b.png)

**Comment by iperov** [comment]
ok
