### ISSUE TITLE
AMD OpenCL Support?

### ISSUE THREAD

**Issue by briangibb** [iperov/DeepFaceLab#129]
How difficult would it be to get it to work on Vega 64 Cards, i do have a couple of them around?

**Comment by nicolastamm** [comment]
You would need to compile Tensorflow to work with And cards. I once tried to work on a R390. Not an easy task, no support, not really worth it.

**Comment by fyby** [comment]
What about using plaidML instead of tensorflow backend for keras? It's possible and functional for faceswap. But I was unable to make It work with deepfacelab.

**Comment by iperov** [comment]
done
