### ISSUE TITLE
Error with operands cannot be broadcasted

### ISSUE THREAD

**Issue by rohit-shah** [iperov/DeepFaceLab#13]
Super excited to try this one out. I just set up everything like mentioned in the doc. Once I did, I started with extracting the face of me. 

But after 1 hour of extracting (passing first 2 steps), I get this error on the third pass: 

`ValueError: operands could not be broadcast together with shapes (5,2) (20,2)`

Here is a screenshot of the error: https://d.pr/free/i/cFqKtL

Any idea what could be the reason for this? 

I am running this on Tesla K80 GPU. Ubuntu 16.04 LTS. 

**Update:** I created a new instance, re-installed all scripts again and tried to use different images. But I still get the same error. I also tried dlib and mt but both are showing the same error. So any help I could get is greatly appreciated. Thanks in advance.

**Comment by rohit-shah** [comment]
Any help on this? Wanting to try this one out asap.

**Comment by iperov** [comment]
1 hour of extracting?
your dlib compiled without CUDA

**Comment by iperov** [comment]
try MT extractor

**Comment by rohit-shah** [comment]
Hey, thanks for the reply. As I mentioned above I already tried with MT and got the same error. I will try again by making dlib use Cuda and will report back here the results.

**Comment by mrsmith0x00** [comment]
@rohit-shah you can simply: git reset --hard COMMIT, to more old commit, eg: git reset --hard a74b57d6e5ae33a720c64d07f0738095d0ade235. Maybe this will help. I think the problem is one of the last commits.

**Comment by gessyoo** [comment]
I'm going to try moving from Windows 10 to Ubuntu 17.10 to free up some more VRAM, and I'll report if there's a similar error during extraction.

**Comment by rohit-shah** [comment]
@mrsmith0x00 Going to try that and will report back. Thanks for the tips.
@gessyoo were you able to reproduce this?

**Comment by gessyoo** [comment]
rohit-shah, I was not able to reproduce the error on Ubuntu 17.10 or 18.04 using the latest commit.  Under 18.04, I'm running a GTX 1070, Anaconda python 3.65, CUDA 9.0 and CUDNN 7.05.  The extract command worked as expected with detector dlib (compiled to use CUDA) and mt. The nvidia driver is 396.  When you ran sudo pip3 install -r requirements-gpu-cuda9-cudnn7.txt in your python environment, were there any error messages?

**Comment by gessyoo** [comment]
I installed Anaconda first, then ran sudo pip3 install -r requirements-gpu-cuda9-cudnn7.txt.

**Comment by mrsmith0x00** [comment]
So the problem in some Anaconda package. I until a bit busy, but after, all be sure to check and will create PR with fixes in the instruction. Big thanks!

**Comment by HelpSeeker** [comment]
@gessyoo 
Not related to the error, but you shouldn't run pip as root as it poses a security risk. Adding --user to the command will only install it for the current user. No elevated privileges needed.  
For software like DeepFaceLab or faceswap I'd even recommend using a virtual environment. Install virtualenv via pip, create the virtual environment via virtualenv env_dir/ and activate it with source env_dir/bin/activate. Once activated you can install all the other requirements. No need for root access or the --user option. Also if something goes wrong, you can just delete env_dir/ and start over with a clean slate.

**Comment by gessyoo** [comment]
Thanks for the tips. I resorted to using sudo just to get Ubuntu up and running ASAP, without permission errors.   I wanted more VRAM for training the models, because, for reasons known only to Microsoft, Windows 10 reserves a big chunk of VRAM from CUDA. I've been using python environments under Windows 10.

**Comment by phadeb** [comment]
Same error for me on step 4. I thought there were zero dependencies ?

**Comment by iperov** [comment]
> I thought there were zero dependencies ?

read better, its only for windows prebuilt package

**Comment by phadeb** [comment]
> read better, its only for windows prebuilt package

and i'm having the error on windows

**Comment by iperov** [comment]
windows binaries 100% tested on clean windows with latest updates.

**Comment by phadeb** [comment]
> windows binaries 100% tested on clean windows install with latest updates.

wow, this has been so thoroughly tested that nobody is having this issue whatsoever
developers with tremendous ego...

https://steamuserimages-a.akamaihd.net/ugc/861739932490930245/E7B7A3E9A483958914068E01DCF92261E63F3FDA/
