### ISSUE TITLE
Something starts making a clicking noise in my PC when I train.

### ISSUE THREAD

**Issue by hertn** [iperov/DeepFaceLab#133]
Every time I click train my PC starts making a high pitched clicking noise. I am not sure what component it could be but since I am using GPU version then I assume it is GPU. I doubt it is my SSD.

I made a recording of it which you can listen here: https://drive.google.com/file/d/1IEJ62bl9_bbsV8rHEpWg1n7IInko6Fwa/view?usp=drivesdk

Might have to turn up the volume a bit and listen for a high pitched click.

I have no idea what is going on. I have a GTX 1060 6GB

**Comment by iperov** [comment]
## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce
