### ISSUE TITLE
RuntimeWarning: invalid value encountered in multiply

### ISSUE THREAD

**Issue by PlagueAI** [iperov/DeepFaceLab#136]
I'm getting this error very often when i convert [SAE]

`Using TensorFlow backend.
===== Model summary =====
== Model name: SAE
==
== Current epoch: 5917
==
== Model options:
== |== batch_size : 16
== |== sort_by_yaw : False
== |== random_flip : True
== |== resolution : 128
== |== face_type : f
== |== archi : df
== |== lighter_encoder : False
== |== learn_mask : True
== |== face_style_power : 10.0
== |== bg_style_power : 10.0
== |== pixel_loss : False
== |== ae_dims : 512
== |== ed_ch_dims : 42
== Running on:
== |== [0 : GeForce GTX 1080 Ti]
=========================
Choose mode: (1) overlay, (2) hist match, (3) hist match bw, (4) seamless, (5) seamless hist match, (6) raw. Default - 1 : 2
Masked hist match? (y/n skip:y) :
y
Hist match threshold [0..255] (skip:255) :  230
Use predicted mask? (y/n skip:y) :
y
Choose erode mask modifier [-200..200] (skip:0) :
0
Choose blur mask modifier [-200..200] (skip:100) :
100
Choose output face scale modifier [-50..50] (skip:0) :
0
Transfer color from dst face to converted final face? (y/n skip:n) :
n
Degrade color power of final image [0..100] (skip:0) :
0
Export png with alpha channel? (y/n skip:n) :
n

Collecting alignments: 100%|#####################################################| 1155/1155 [00:01<00:00, 1071.55it/s]
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Converting:   0%|                                                                     | 2/1471 [00:00<01:31, 16.00it/s]C:\Users\PlagueAI\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ConverterMasked.py:200: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_hborder_rect_mask_a
Converting:   6%|###7                                                                | 81/1471 [00:02<00:43, 31.98it/s]C:\Users\PlagueAI\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ConverterMasked.py:200: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_hborder_rect_mask_a
Converting:   6%|####1                                                               | 89/1471 [00:02<00:43, 31.99it/s]C:\Users\PlagueAI\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ConverterMasked.py:200: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_hborder_rect_mask_a
Converting:  18%|###########8                                                       | 261/1471 [00:08<00:37, 32.01it/s]C:\Users\PlagueAI\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ConverterMasked.py:200: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_hborder_rect_mask_a`

**Comment by iperov** [comment]
upload your zipped workspace to google drive, I will check.

**Comment by PlagueAI** [comment]
> 
> 
> upload your zipped workspace to google drive, I will check.

https://drive.google.com/open?id=1fuI4AFtYtDfQFgoDTa2MyN4AUJE68yPD

**Comment by iperov** [comment]
ok I am checking

**Comment by iperov** [comment]
very strange numpy/cv2 behaviour, cannot catch this bug :(

**Comment by iperov** [comment]
sometimes
`cv2.warpAffine( prd_hborder_rect_mask_a, face_output_mat, img_size, np.zeros(img_bgr.shape, dtype=np.float32), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )`

produces nan values

**Comment by iperov** [comment]
sometimes mean every frame can work fine or fail depends on moon phase :-\

**Comment by iperov** [comment]
try last commit

**Comment by iperov** [comment]
it seems ur issue fixed

**Comment by PlagueAI** [comment]
> 
> 
> it seems ur issue is fixed

Amazing man, thx!
