### ISSUE TITLE
why does the software always call cpu calculations automatically? 

### ISSUE THREAD

**Issue by masterzht** [iperov/DeepFaceLab#139]
I have a question.Although I want to use gpu for calculations, why does the software always call cpu calculations automatically? This is very slow﻿

**Comment by iperov** [comment]
## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce
