### ISSUE TITLE
why does the software always call cpu calculations automatically

### ISSUE THREAD

**Issue by masterzht** [iperov/DeepFaceLab#140]
## Expected behavior
I have a k40 graphics card，but your software says that Tesla K40m does not meet minimum required compute capability: 3.7. Falling back to CPU mode.TeslaI k40m's compute capability is 3.5,and I want to use gpu for calculations, why does the software always call cpu calculations automatically? This is very slow﻿ 

## Actual behavior
 The software always call cpu calculations automatically

## Steps to reproduce

I just want to force the operation using gpu.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows
- **Python version:**  3.6.4

**Comment by iperov** [comment]
because
>Tesla K40m does not meet minimum required compute capability: 3.7

**Comment by iperov** [comment]
you can downgrade to tensorflow-gpu==1.10.0
this will work with 3.5
but in further updates DFL will be upgraded to 1.13.0 result it will no longer work with 1.10.0
