### ISSUE TITLE
Exception: Unable to start Subprocessor 'Extractor' when running 5) data_dst extract faces MT all GPU .bat 

### ISSUE THREAD

**Issue by CZOY08** [iperov/DeepFaceLab#141]
This is what I got when running 5) data_dst extract faces MT all GPU .bat and any MT and DLIB scripts. 

> Running extractor.
> 
> Performing 1st pass...
> Traceback (most recent call last):
>   File "E:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\main.py", line 151, in <module>
>     arguments.func(arguments)
>   File "E:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\main.py", line 41, in process_extract
>     manual_window_size=arguments.manual_window_size
>   File "E:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 426, in main
>     extracted_rects = ExtractSubprocessor ([ (x,) for x in input_path_image_paths ], 'rects', image_size, face_type, debug, multi_gpu=multi_gpu, cpu_only=cpu_only, manual=False, detector=detector).process()
>   File "E:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 113, in process
>     raise Exception ("Unable to start Subprocessor '%s' " % (self.name))
> Exception: Unable to start Subprocessor 'Extractor'

I am using Windows 10 with only one GPU (GeForce 1070 laptop version). 

The Nvidia driver is updated and works fine on other tasks like gaming or cuda but not this script.

**Comment by iperov** [comment]
install teamviewer, send me id and pass to access to deepfakescovery@gmail.com

**Comment by CZOY08** [comment]
My bad! Tures out I was using an outdated version. Just got the newest release and everything works perfectly. thx
