### ISSUE TITLE
feature request: automatic tracking in manual mode

### ISSUE THREAD

**Issue by DieselWoodard** [iperov/DeepFaceLab#142]
In manual mode, it would be nice if incorporated the dlib object tracker (dlib.correlation_tracker()).

Ex: Call `self.tracker.update(image, rect)` with manually or detected bounding rect on each frame already done, (or `self.tracker.start_track(image, rect)` if creating or reset), should probably do `start_track()` to reset instead of `update()` if `update()` returns low value (confidence).

Then instead of just using previous rect when advancing image, use rect from self.tracker.get_position().

One issue is that it needs to change to load all images, not just images without already detected faces. Might impact performance. But it should allow much faster workflow, correlation tracker usually works very good.

**Comment by iperov** [comment]
no
anyway face requires precise match of landmarks
