### ISSUE TITLE
Suggestion: Denoise extracted data_src ?

### ISSUE THREAD

**Issue by AlonDan** [iperov/DeepFaceLab#144]
If the the same principle can be apply, it will be very helpful and time-saver for some noised source files:

Since we already have this step as **.bat** file:

> 3.other) denoise extracted data_dst.bat

Which is a REAL time saver instead of do this on a different software.

Is it possible to use the same code/idea to do the same for data_src ?

I'm not a programmer so I don't know how difficult it is, that is why I'm asking.
Thanks ahead!

**Comment by iperov** [comment]
you need no denoised src faceset. 
Src faceset must be as sharp as possible.

**Comment by AlonDan** [comment]
I didn't know that, thanks for explaining this! 👍
