### ISSUE TITLE
DFL train H64 problem - Can't get it to train

### ISSUE THREAD

**Issue by tomdabomb90** [iperov/DeepFaceLab#145]
Hi, I got this problem where everything works but for some reason I get the following screen and text when trying to train:
![image](https://user-images.githubusercontent.com/47625826/52776683-6dd28a00-3042-11e9-81bb-ea9a4f27bb74.png)

Why doesn't the training window pop up and show me the progress?

**Comment by easy40** [comment]
You're running out of memory. Which GPU card do you have?

**Comment by tomdabomb90** [comment]
hey i've got Geforce 1050 2GB

**Comment by easy40** [comment]
Use the lightweight autoencoder (set lightweight autoencoder = true) when starting your run.

**Comment by tomdabomb90** [comment]
Thank you, it worked it's training now. Could you please let me know if you have any tips or tricks from your own experience that will help people like me progress and develop our skills?

**Comment by easy40** [comment]
Use SAE instead of H64. You should be able to run it as long as you use the lightweight autoencoder. It will give you more flexibility and better results. Check more info at the mrdeepfakes.com forums.
