### ISSUE TITLE
keras_contrib.layers.advanced_activations' has no attribute 'PELU'

### ISSUE THREAD

**Issue by feitiandemiaomi** [iperov/DeepFaceLab#146]
Hi , everybody , Who has encountered the problem that "AttributeError: module 'keras_contrib.layers.advanced_activations' has no attribute 'PELU'", I have uninstalled and reloaded three times. 
![default](https://user-images.githubusercontent.com/18325462/52830854-5e6c4300-310d-11e9-9432-d212a892b7b0.png)
Setting: ubuntu16.04 , tensorflow 1.10 , keras 2.2.4  , keras-contrib , py36

**Comment by iperov** [comment]
reinstall keras-contrib

**Comment by feitiandemiaomi** [comment]
@iperov I modified the 'PELU = keras_contrib.layers.advanced_activations.PELU' to 'PELU = keras_contrib.layers.advanced_activations.pelu' in nnlib.py  , and it work
