### ISSUE TITLE
png-export with alpha doesn't work

### ISSUE THREAD

**Issue by spiegelball** [iperov/DeepFaceLab#151]
## Expected behavior

Converter should be able to export final images with alpha channel if option "export png with alpha" is set to yes.

## Actual behavior

Converter exports sequence of .jpgs without alpha channel. (.jpg can't contain an alpha channel by specification).

## Steps to reproduce

1. Train model (SAE in this case).
2. Run converter with default values, set "export png with alpha" to "y".
3. .jpg sequence is exported.

## Other relevant information
- Happens with version 642b88a8d348790405a039b7f2347a13b9c384c6.

**Comment by iperov** [comment]
srsly ?
converter always exports PNG files to merged\

**Comment by spiegelball** [comment]
Now I understand. Converter writes file in the format it reads. My dst folder contains .jpgs, therefore jpgs are written and alpha misses.

**Comment by iperov** [comment]
ok will fix later
