### ISSUE TITLE
I wonder how it works, could We train a small resolution models and use a high resolution faces later proportionally to put in ? What should I read to examine that ? For example we run 128x128px and the model is created for this resolution, it knows what to use and what to remove from the picture, but the coordinates to do it we could multiply by two to get twice better resolution and take faces from other directory (256x256 and so on) ? Please give me some links to examine a code, unfortunately I dont know python, but maybe some theory of this and we will do some revolutionally? Evry cleaned pixel of PNG file can be recalculated to a new resolution cause it is propotional. It`s a simple idea, but can it be done ?

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#158]
I wonder how it works, could We train a small resolution models and use a high resolution faces later proportionally to put in ? What should I read to examine that ? For example we run 128x128px and the model is created for this resolution, it knows what to use and what to remove from the picture, but the coordinates to do it we could multiply by two to get twice better resolution and take faces from other directory (256x256 and so on) ? Please give me some links to examine a code, unfortunately I dont know python, but maybe some theory of this and we will do some revolutionally? Evry cleaned pixel of PNG file can be recalculated to a new resolution cause it is propotional. It`s a simple idea, but can it be done ? Am I wrong or multiply as twice of the coordinates will be proportionally to  a 256x256 facets folder for example ?

_Originally posted by @wasyleque in https://github.com/iperov/DeepFaceLab/issues/155#issuecomment-466718431_

**Comment by lackeyproton** [comment]
Bro, you've got to fix that title to be taken seriously.  🤣

**Comment by iperov** [comment]
## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce
