### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by fox2-1991** [iperov/DeepFaceLab#164]
I have no intention to offend. When I was training, the notebook processor clock speed was limited to 0.8Ghz. I didn't find the reason. Please help me. The power management mode is high performance, but it doesn't work. It still stays at 0.8Ghz. I am sorry for the translation from Google.

我无意冒犯，我在训练的时候，笔记本处理器主频被限制在了0.8Ghz，我没有找到原因，请帮助我，电源管理模式为高性能，但是没有工作，仍旧保持在0.8Ghz，以上对话来自谷歌翻译，我感到抱歉。

![snipaste20190226_004726](https://user-images.githubusercontent.com/47985156/53353680-3b892c80-3960-11e9-8187-ac31e244d7bb.png)

**Comment by iperov** [comment]
this is not tech support
stop flood or you will be banned
