### ISSUE TITLE
OPENCL Error: cl_mem_object_allocation_failure

### ISSUE THREAD

**Issue by Ysdf** [iperov/DeepFaceLab#167]
When I try to train with GTX 650 Ti 1GB I get this error and app crashes. Face GPU extraction works fine. 

Possible solution https://devtalk.nvidia.com/default/topic/1019997/cuda-programming-and-performance/how-to-handle-cl_mem_object_allocation_failure-errors-if-amount-of-useable-memory-is-not-known-/

**Comment by iperov** [comment]
possible solution srsly ?
decrease network size
