### ISSUE TITLE
Running extraction

### ISSUE THREAD

**Issue by bloodunderscorerelative** [iperov/DeepFaceLab#17]
When running option 3, or any option that uses the just extracted data, it gives me an error that it cannot find the utils module.

I'm using Python 2.7 and have also tried downloading 3.6.6

```
  File "C:/Python27/Scripts/DeepFaceLab-master/main.py", line 4, in <module>
    from utils import Path_utils
ImportError: No module named utils

```

It might have been asked before but cannot find it in the issues.

**Comment by gessyoo** [comment]
bloodunderscorer, the scripts were written to run under python 3.6, not 2.7.  I don't know if they will work under 2.7, so stick with 3.6. The python error message is telling you it can't find the utils directory in the expected location.  To fix this, you need to put the DeepFaceLab root dir. whatever root directory you choose, e.g. C:\DeepfaceLab, and leave all the sub- directories underneath unchanged.   Have you added the DeepFaceLab path to your user or system path?  If you're running Windows 10, download the ready to run install, much easier to get started.

**Comment by bloodunderscorerelative** [comment]
Thanks for the reply. I'll try doing it with 3.6 then and see if it helps.
If all else fails I'll try the installer. Where can I find it?

**Comment by gessyoo** [comment]
As stated front page of this repository:
Prebuilt python folder with DeepFaceLab:
Windows 7,8,8.1,10 zero dependency (just install/update your GeForce Drivers) prebuilt Python 3.6.5 embeddable folder with DeepFaceLab can be downloaded from torrent https://rutracker.org/forum/viewtopic.php?p=75318742 (magnet link inside).
