### ISSUE TITLE
Win10 runs script flicker.

### ISSUE THREAD

**Issue by yichuxue** [iperov/DeepFaceLab#171]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

I try to run:

2) extract PNG from video data_src FULL FPS.bat

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

The program flips back. Before the window exits, there is a line of information.

The message is: 此时不应有 \common

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

Running other scripts yields the same results.
The graphics driver has been updated to the latest version.

## Other relevant information
- ** 2) extract PNG from video data_src FULL FPS.bat
- ** Windows 10 x64
- ** Python 2.7
- ** GPU NVIDIA GeForce GTX 1060 and Intel(R) HD Graphics 530

**Comment by iperov** [comment]
watch tutorials

**Comment by yichuxue** [comment]
Is it necessary to install vs2015, CUDA, CUDNN first?

**Comment by yichuxue** [comment]
> 观看教程

Is it necessary to install vs2015, CUDA, CUDNN first?
