### ISSUE TITLE
YAW meaning? 

### ISSUE THREAD

**Issue by caymanlee** [iperov/DeepFaceLab#177]
thanks for all you hard work. 

" sort by face yaw", what exactly does the word "yaw" mean in this context?

also, model "LIAEF128", what is the meaning of "LIAEF"

thanks in advanced

**Comment by lackeyproton** [comment]
In the doc files for Model Types:

LIAEF128 (5GB+) - Less agressive Improved Autoencoder Fullface 128 model. Result of combining DF, IAE, + experiments. Model tries to morph src face to dst, while keeping facial features of src face, but less agressive morphing. Model has problems with closed eyes recognizing.

**Comment by caymanlee** [comment]
> In the doc files for Sorting:
> face-yaw sort by face yaw direction
> https://en.wikipedia.org/wiki/Yaw_(rotation)
> In the doc files for Model Types:
> LIAEF128 (5GB+) - Less agressive Improved Autoencoder Fullface 128 model. Result of combining DF, IAE, + experiments. Model tries to morph src face to dst, while keeping facial features of src face, but less agressive morphing. Model has problems with closed eyes recognizing.

Thank you very much, most Appreciated
