### ISSUE TITLE
How to  train  by H128

### ISSUE THREAD

**Issue by wolfking059** [iperov/DeepFaceLab#178]
When do I trying to   "train  H128(any type)",there is an error waiting for me.
eg."Sorry,this model works only on 2GB+GPU"
or"Sorry,this model works only on 4GB+GPU"
But my GPU is "Quadro P6000 6GB".
Only train type can I choose is " train H64 multi GPU",but there is an WARNING:
"You are using 2GB GPU.Result quality may be significantly decreased"
By the way,driver for GPU is from NVDIA.
How can I solve this problem?

**Comment by iperov** [comment]
download latest DFL ?
