### ISSUE TITLE
Remove or move text instructions on manual extraction

### ISSUE THREAD

**Issue by 4DeepThought2** [iperov/DeepFaceLab#183]
During manual extraction, the text instructions often get in the way of visually seeing the face, sometimes for 100s if not 1000s of frames.   A few options: 

- remove the instructions and put them as a stdout print statement on the command line
- if detection box is moved to top of extraction window, move text instructions to bottom
- add a border on top or bottom of extraction window that includes instructions, but doesnt cover actual video

Any resolution at all would be nice though.

**Comment by iperov** [comment]
post screenshot of your problem

**Comment by iperov** [comment]
I will add 'h' for hide the help.
