### ISSUE TITLE
minimum gpu requirements?

### ISSUE THREAD

**Issue by yg2dras1** [iperov/DeepFaceLab#185]
Hi guys, i've been a fan of DFL for a while now and i've been working towards being able to afford a gpu for my PC to be able to do DFL. My question is, what is the minimum gpu requirements? Would a GTX 1060, or 1070 do? For budget reasons, I cannot afford RTX...

Below are the specs of my PC:

Intel Core i5-7400 @ 3.00 GHz
8gb DDR4 ram, 2400 MHz
running of Ubuntu 16.04 LTS

I'm thinking about adding another 8gb ram too.

Thank you!

**Comment by deyu260** [comment]
The cheapest one is the p106-100 6g mine card from China Taobao, which sells for RMB 400. and with the pre-processed H128 110w model, you can get out almost half an hour of training.

**Comment by deyu260** [comment]
here is the h128 110w model download
链接：https://pan.baidu.com/s/1dWdRBV3Dajn95LPYyeqX5Q 
提取码：536h 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by oracle9i88** [comment]
1050 can do H128?

**Comment by deyu260** [comment]
> 1050 can do H128?

可以使用轻量化的h128
你在国内换p106是最好的选择 甚至是p104

**Comment by oracle9i88** [comment]
thanks，what is light H128?

**Comment by oracle9i88** [comment]
could u have SAE model？

**Comment by oracle9i88** [comment]
do u have SAE model？

**Comment by iperov** [comment]
read manual about requirements

**Comment by Vian88** [comment]
HEEEEELPP !!!!!   can i use it on my pc, with  GPU NVIDIA GeForce MX110 and Core i5 processor?
