### ISSUE TITLE
Where is the Dockerfile.cpu ? it's not in /DeepFaceLab

### ISSUE THREAD

**Issue by IFmage** [iperov/DeepFaceLab#186]
I was try to build a docker Image follow with DockerCPU.md, use " docker build -t deepfacelab-cpu -f Dockerfile.cpu ." command ,but error said no such file or directory.
I was tried to search , but  I can't find it.

**Comment by iperov** [comment]
I never use docker

**Comment by IFmage** [comment]
Thank you for answer me so fast.But 
https://github.com/iperov/DeepFaceLab/blob/a8694b73f0128cac29c1382721fc60a1ab28e711/DockerCPU.md
You mean this is useless?

**Comment by iperov** [comment]
Thats not mine.
DFL does not support docker.
