### ISSUE TITLE
Getting error after Windows Update: gpufmkmgr.pynvml.NVMLError_Unknown: Unknown Error

### ISSUE THREAD

**Issue by signupdemo** [iperov/DeepFaceLab#191]
Hello,
I have GTX1060 GPU with 6GB ram, and prebuilt windows app was working perfectly... But after the latest Windows 10 Update, something seems to be broken and Im getting this error while extracting faces:
gpufmkmgr.pynvml.NVMLError_Unknown: Unknown Error

I have tried the latest Windows build: DeepFaceLabCUDA9.2SSE
And while extracting it goes through only 1st pass, and nothing happens afterwards:

Performing 1st pass...
Running on Generic GeForce GPU #0.

Can anybody please help ?

**Comment by iperov** [comment]
reinstall video drivers from geforce.com

**Comment by signupdemo** [comment]
Whoa.. Finally all set and working..  thanks.
For anybody else having issue installing drivers from official site,
Use DDU to uninstall previous drivers, and install new downloaded drivers from geforce in safe mode with disabled signing certificate check.
