### ISSUE TITLE
SAE windows doesnt train - error

### ISSUE THREAD

**Issue by sanych10** [iperov/DeepFaceLab#200]
windows 10. cpu i97980xe. nvidia titan V 12gb
когда начинается тренировка сае модели всегда вылетает с ошибкой. сборка от 24 марта
вот скриншоты параметров модели (пробовал разные и по умолчанию)
 https://i109.fastpic.ru/big/2019/0324/49/210401b33a9260f7d9b3f3fdc7880349.png
вот сама ошибка 
 https://i110.fastpic.ru/big/2019/0324/b8/_639c6d1caa8543b7c7c17c15c0d76fb8.png

**Comment by iperov** [comment]
обнови дрова, пробуй разные сборки
