### ISSUE TITLE
DeepFaceLab Training Error "00M when allocating tensor with shape and Type float"

### ISSUE THREAD

**Issue by sagaface** [iperov/DeepFaceLab#207]
Hi. I am using the DeepFaceLabCUDA10.1AVX, the prebuild one for windows. I've done all the steps such as extracting the images and also faces. Then whenever I tried to train it, either using h64.bat or 128.bat or even the DF.bat,  I get this error. PS.I am running with everything default settings.
![Capture](https://user-images.githubusercontent.com/48969358/55039219-91dd9f80-4fe0-11e9-8120-07d9b286222b.JPG)

I have also tried multiple batch sizes and I still get the same error.

**Comment by claudetheboof** [comment]
man im keep on getting the same error does anyone know how to fix it?
