### ISSUE TITLE
Best GPU device 1 detected, but training still runs on less powerful GPU 0 device? 

### ISSUE THREAD

**Issue by gessyoo** [iperov/DeepFaceLab#21]
## Expected behavior

Have a system with a GTX 1070 installed in PCIe slot0 and GTX 1080ti installed in PCIe slot1.  When I run the training batch files to select the "best" GPU (GTX 1080ti), the GTX 1080ti is detected and the program says that the training is running on device 1 (the GTX 1080ti), but the created_vram_gb  is 8 Gb, not 11 Gb. and the training still runs on the GTX 1070, with no GPU activity on the GTX 1080ti.  Is there a way to force the training to run on GPU 1, with parameter  ---force-best-gpu-idx?  
Can CUDA_VISIBLE_DEVICES=1 force the use of GPU 1, and which script and line should include CUDA_VISIBLE_DEVICES=1? 

## Actual behavior
The best GPU is not being used, only GPU device 0.

- **Operating system and version:** Windows 10
- **Python version:** 3.6.5

**Comment by TheFeelTrain** [comment]
@iperov Need to re-open this issue. I have a GTX 980 Ti in slot 0 and a GTX 1080 in slot 1 but training/extracting uses the wrong GPU and allocates the wrong amount of VRAM.

When I use `--force-worst-gpu` it does the opposite, displays the 980 Ti and allocates 6GB but runs on the GTX 1080 (as seen below)

![](https://user-images.githubusercontent.com/12601452/49563031-dc70ca00-f8d2-11e8-8710-4665ce45949f.png)

![](https://user-images.githubusercontent.com/12601452/49563048-e98db900-f8d2-11e8-9125-26435307e229.png)

**Comment by iperov** [comment]
actually there is no --force-worst-gpu param

**Comment by TheFeelTrain** [comment]
It is tensorflow 1.12

**Comment by iperov** [comment]
same tf 1.12 doesnt support cuda 10.

**Comment by iperov** [comment]
try using tf 1.11 and cuda 9 as current repo requirements

**Comment by TheFeelTrain** [comment]
Downgraded to Tensorflow 11.1 and CUDA 9, problem persists.

**Comment by iperov** [comment]
i dont know how to help you

**Comment by gessyoo** [comment]
TheFeelTrain, I dealt with the issue by putting the1080ti in PCIe slot 0, and the1070 in PCIe slot 1.  As currently written, the code seems to default to the GPU in PCIe slot 0, regardless of whether it's the "best" GPU or not, at least on my Ryzen motherboard.  As iperov says, try creating a new environment with python=3.6, CUDA 9, Cudnn 7.05 and TF 1.8, the official requirements of the repro.

**Comment by TheFeelTrain** [comment]
I can't swap the slots because I want to use the 980 Ti as my main GPU while I train on the 1080. The code needs to be changed to choose the actual best card instead of defaulting to slot 0.

Also the Python, CUDA, and Tensorflow versions do not affect this behavior. I downgraded everything (breaking a lot of other programs and drivers in the process) only for it to be exactly the same as it was before. The actual program runs fine for me with CUDA 10 and Tensorflow 1.12 anyways. Maybe the AUR version of Tensorflow was compiled to use CUDA 10.

**Comment by iperov** [comment]
> The code needs to be changed to choose the actual best card instead of defaulting to slot 0.

then change it, if you know what to change.

**Comment by TheFeelTrain** [comment]
I don't know python. You're supposed to be the developer here :/

**Comment by gessyoo** [comment]
TheFeelTrain, the workaround is to put your 1080ti in PCIe slot 0, if you want to use it for training.  If you're using Windows 10 and are concerned about VRAM reservation, connect your monitor(s) to the 980 Ti and install the repro under Ubuntu, which has better management of GPU resources.
