### ISSUE TITLE
How to use this software in linux without desktop system which raises an error:cannot connect to X server.

### ISSUE THREAD

**Issue by Nostalgia1990** [iperov/DeepFaceLab#212]
## Expected behavior
My server  uses NVIDIA  Tesla V100 graphics and the system is  CentOS without desktop system.
Every time I I use xshell to operate the computer.
I have been using faceswap before, I just wanted to try deepfacelab recently. When I train one model ,a problem happened:cannot connect to X server. I gusess the reason is that the CentOS has no visual interface.How can I solve this problem?
![QQ截图20190330213219](https://user-images.githubusercontent.com/25590443/55277066-d21d8480-5336-11e9-8e37-c4e5055f4429.png)

I want to modify the code and cancel the visual display of some of the modules.Because I am not good at tensorflow and opencv programming, so I need help.

Perhaps the software can add an option - let the user decide whether to enable the graphics window, so that each person makes a choice according to their actual situation, which can make the software more widely used.

**Comment by oracle9i88** [comment]
https://github.com/lbfs/DeepFaceLab_Linux
and you will find the no-preview in scripts

**Comment by Nostalgia1990** [comment]
> https://github.com/lbfs/DeepFaceLab_Linux
> and you will find the no-preview in scripts

thank you. let me see.

**Comment by huanghanmei** [comment]
> 
> 
> > https://github.com/lbfs/DeepFaceLab_Linux
> > and you will find the no-preview in scripts
> 
>How do you solve it?

**Comment by beibuwandeluori** [comment]
Use interactive merger? (y/n)
you need to select n(no)!!!
