### ISSUE TITLE
convert SAE.bat fails in 3/30/19 build "Dimension 0 in both shapes must be equal"

### ISSUE THREAD

**Issue by ironpanther** [iperov/DeepFaceLab#213]
Was using this exact model just a few hours ago, did many conversions (trying different settings for best result) but latest version today doesn't even load the model  (SAE, default settings except for having 256 resolution, and learning mask)   
![Cap001](https://user-images.githubusercontent.com/41494033/55283357-de99e100-5326-11e9-8927-d9904f443e8f.jpg)

![Cap002](https://user-images.githubusercontent.com/41494033/55283359-e2c5fe80-5326-11e9-8a1f-986d97f295c5.jpg)

**Comment by iperov** [comment]
SAE should be retrained. You can use old version to finish your fake.
