### ISSUE TITLE
RCT not working in RAW Export mode

### ISSUE THREAD

**Issue by VFXDF** [iperov/DeepFaceLab#214]
When exporting in RAW mode RCT and LCT result in the same output as if you selected none. They seem to not be working in RAW, but do work well in seamless.

**Comment by iperov** [comment]
will it remove from asking

**Comment by VFXDF** [comment]
Is it not possible to have RCT in RAW mode? RCT does work well and it would be good in RAW mode.

**Comment by iperov** [comment]
because RAW is RAW
