### ISSUE TITLE
Low GPU Usage in Task Manager

### ISSUE THREAD

**Issue by jask2000** [iperov/DeepFaceLab#215]
Sorry about the stupid question I'm really an amateur. So i recently installed downloaded deepfacelab and noticed that while training or extracting faces my GPU usage doesn't go above 20% in task manager. HWMonitor shows 95 -100% usage at all times but task manager shows less than 20%. Other than this i'm not getting any errors and while training it does say running on rtx2070. I am using an i5 9400f and an RTX 2070. My card runs fine while playing games and shows much higher usage in task manager. I have not installed cuda, cudnn or anything else on my PC except for DeepFaceLabCUDA10.1SSE and latest drivers from nvidia. 

I'm not sure if task manager is showing false values or if my card is not being used properly by this program.

**Comment by rubenoid** [comment]
In task manager go to the Performance tab and click on GPU. On the right hand side you see several graphs. Click on the arrow next to 3D and select Compute_0 and you will see the same values as shown in HWMonitor.
