### ISSUE TITLE
Memory issue with extreme slowdown when converting

### ISSUE THREAD

**Issue by wesson09** [iperov/DeepFaceLab#218]
## Expected behavior

Convert on 4K with decent speed on computer with a lot of logical cores.

## Actual behavior

there is as many instances of converters as there is CPU logical cores. With 4K dest, each instance takes 2GB+ of private RAM. So it sucks dry the physical RAM and goes on SWAP, which in turn cause extreme slowdown in the process. Often it also cause the spawned process to be auto-killed as they don't respond after the 60 seconds delay.

## Steps to reproduce
Try a 4k convert on a computer with CPU with 8 cores/16 threads and 16 GB of RAM or less.

## Other relevant information
- Use prebuilt windows binaries
- Quick and dirty solving of the issue in file mainscripts/Converter.py line 153

`r = [0] if self.debug else range(min(8,multiprocessing.cpu_count()))`

Better solution would be to consider the available RAM

**Comment by iperov** [comment]
limited to 6 now
