### ISSUE TITLE
Manual Extraction: ValueError operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by Kenturin** [iperov/DeepFaceLab#220]
## Expected behavior

Manual extraction

## Actual behavior

![Operand ValueError](https://user-images.githubusercontent.com/46427725/55642706-36a96b00-579f-11e9-9944-d7cc86bf2dc0.png)

Arrays seem to be switching h,w,c values maybe?

## Steps to reproduce

Manual Extraction/Manual Re-extract Deleted Results

## Other relevant information
Windows 10 , RTX 2080 , 04/05 pre-built

**Comment by iperov** [comment]
thx, will be fixed
