### ISSUE TITLE
"Residual blocks on by default"---uses a LOT more memory, can no longer run SAE256 on a 1080

### ISSUE THREAD

**Issue by ironpanther** [iperov/DeepFaceLab#222]
I have been running the past couple versions of SAE, with "mostly default settings, but "optimizer 2" to allow 256 resolution.  Batch 6 needed.   This could run for days on end with no problems.   

I tried both "residual blocks" and "remove grey" options earlier, when they were introduced---both caused OOM errors, and I didn't use them any more.  

But now, "residual blocks" is "always on"---and it causes OOM. immediately, without even loading.  I tried reducing the complexity again and again---224 resolution, 208, down to 192.  It would load at 192, but only go a couple hours without crashing due to OOM again.    192 is already a large decrease from 256, and Batch 4 would be incredibly small/pointless.   Please remove "residual blocks"----it's not worth the massive increase in memory needed.   Very few cards have more memory than a 1080, and I don't even know if they would have enough RAM to run "256, with residual blocks on, batch 6+".  (I use Windows 7, not 10, so I can use all of my card's 8GB)  

PS---despite having made dozens of fakes on 300,000+-iteration models on SAE256, I still find H128 is superior in many situations.  H192 or H256 would be AMAZING for some fakes, if they could become available.   Is it possible to add "learn mask" to the "H" models?

**Comment by iperov** [comment]
> can no longer run SAE256

this is lie.
Decrease dims.

**Comment by iperov** [comment]
>  Please remove "residual blocks"

no.

**Comment by iperov** [comment]
>  Is it possible to add "learn mask" to the "H" models?

default models always learn mask
