### ISSUE TITLE
Announcing improved FANSeg model for converter.

### ISSUE THREAD

**Issue by iperov** [iperov/DeepFaceLab#223]
currently I am gathering edited samples by MaskEditor for training FANSeg model that will exclude obstructions such as hair, glasses, fingers, etc.

![python_2019-04-06_18-21-26](https://user-images.githubusercontent.com/8076202/55670707-cc74f100-5898-11e9-93c1-df049c4c56cd.jpg)

MaskEditor available in last mega.nz builds.

example of fake with FANSeg trained on 2k edited faces from CelebA dataset:
https://www.youtube.com/watch?v=-7CUJSUNf8Y

if you want to contribute:
I need edited faces with obstructions from porn videos.
Send them to my email deepfakescovery@gmail.com

**Comment by Tesla32X** [comment]
Will try to help you and is testing the tool. Could use a zoom feature, as I am on a 4k display and I can barely see where I am working.

**Comment by iperov** [comment]
added window zoom

**Comment by overtort** [comment]
The mask editor confirmed the error.
If the caps lock is on, hold [shift] is activated. without pressing the shift key, allowing 10 frames to be crossed.

**Comment by iperov** [comment]
@overtort then dont enable caps lock.

**Comment by iperov** [comment]
required precision of masking:
![python_2019-04-08_18-12-42](https://user-images.githubusercontent.com/8076202/55730735-f01b7100-5a29-11e9-95d0-334aea18fb20.jpg)

**Comment by oracle9i88** [comment]
FANs model does not work under Ubuntu

**Comment by iperov** [comment]
@chervonij did you test converter with FAN mask under google colab?

**Comment by chervonij** [comment]
@iperov 
Just checked. All FAN modes work under Google Colab.

**Comment by iperov** [comment]
@oracle9i88 so all works fine under linux.

**Comment by iperov** [comment]
it seems nobody want to help
