### ISSUE TITLE
Error when converting frames: no faces found. Unaltered pictures just copied to the merged folder.

### ISSUE THREAD

**Issue by fetchlister** [iperov/DeepFaceLab#224]
I have a decently trained H128 model and wanted to test the quality of the results, so I ran the convert H128 batch file with all default parameters and it keeps reporting that no faces are found even though they are obviously profile-type shots. I have tried changing the defaults from seamless to raw and all other options but to no avail. I am coming from faceswap and see no reason why it is not picking up my faces.

**Comment by iperov** [comment]
watch tutorials
