### ISSUE TITLE
SAE & H128 converting failing repeatedly

### ISSUE THREAD

**Issue by blackmagik3** [iperov/DeepFaceLab#225]
After several hours of successful SAE & H128 training, I'm trying to convert with SAE.bat. It fails at different places based on the settings. I leave them default to try to gain a baseline, but no such luck.

I'm using python-3.6.8 and have dual 2080s, Threadripper 2990WX, 64GB ram, Windows 10. I'm stuck in the mud. Any help is appreciated.

![1](https://user-images.githubusercontent.com/35750626/55751358-525c7d80-59fa-11e9-88eb-0ceff8febdbe.PNG)
![2](https://user-images.githubusercontent.com/35750626/55751361-538daa80-59fa-11e9-891d-4c032b4f6e5b.PNG)

**Comment by Greywolf22** [comment]
I had the same error with previous versions. To fix it change process priority .
Before the actual convert process start: 
1-) Press ctrl+alt+del.
2-) Find window console and python process, change their priority to high. Start converting.
3-) More python processes will be created immediately, change their priority too.

My guess, after some time cpu core or whatever goes idle

**Comment by blackmagik3** [comment]
Awesome, thanks! I'll try it now.

**Comment by blackmagik3** [comment]
No such luck as of yet. Someone mentioned it may be an issue of the multithreading. Any thoughts?

**Comment by blackmagik3** [comment]
Fixed! I had to disable hyperthreading in the BIOS. Everything is working properly now. Thanks for your input!

**Comment by iperov** [comment]
@blackmagik3 actually last DFL build has limit to 6 processes in converter
