### ISSUE TITLE
Convolutional Mesh Autoencoders?

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#226]
Not a bug, but take a look at this stuff from NRK (The Norwegian national TV) They dig into all sorts of stuff, and did this article on Fakenews.

This article is Norwegian, but use Google to translate it. The video of the news presenter in the top section is fake, including the lips and voice. 

[https://nrkbeta.no/2019/02/23/yama-kan-ikke-samisk-eller-mandarin-for-na/](https://nrkbeta.no/2019/02/23/yama-kan-ikke-samisk-eller-mandarin-for-na/)

![yama-wireframe](https://user-images.githubusercontent.com/48013922/55811481-7b0f7080-5ae9-11e9-95f5-baeb117a36e7.gif)

It this done with with mesh autoencoders instead of "hardcoding the pixels"? Found this repo when doing some research myself - [https://github.com/anuragranj/coma](https://github.com/anuragranj/coma)

**Comment by iperov** [comment]
so what they did?
what is before and what is after ?

**Comment by Tesla32X** [comment]
Don’t think they posted the source video. But from what I make of it, they overlay a mesh instead of bitmaps. This allows them to render out any resolution, and also manipulate mimics.

Since the fake they made has the same source / target actor I don’t know if they swapped the entire face or just the parts they needed to make the mimic match the new sound.

**Comment by Tesla32X** [comment]
More in this youtube clip https://youtu.be/CF_e0kMCW2o

**Comment by spiegelball** [comment]
I think those are two different technologies. The video with the mesh overlayed is done with [synthesia](https://www.synthesia.io/), which does realtime image to 3d mesh mapping. That might be something similar like the [Face2Face application ](https://niessnerlab.org/projects/thies2018face.html) with which the Obama deepfake was done. 
The repo you linked implements an approach to efficiently compress mesh data. But using this for "traditional" deepfakes would require a good image -> mesh and backwards algorithm. Keentools offers something similar as plugin for the compositing software nuke: (https://www.youtube.com/watch?v=vPAktlmMU6E)

**Comment by Tesla32X** [comment]
@spiegelball Thanks for the input. Yes, I guess this could be different technologies.

But the idea of generating a mesh instead of "dead" pixels sounds intriguing to say it the least. I honestly don't understand how this technology works, so I can't really tell if its currently possible to train for a mesh output. 

Iperov has already taken deeepfakes from 128x128 to 256x256, which for sure was a major breaktrough. But we live in a 4k world, and I really don't see how we go further to the next resolution levels anytime soon. I've tried most cards from 16 gb to 32gb configs, and we are not remotely close to bump this up to 512x512 or 1024x1024. Even if we could fit 512x512, the compute time and bs would make this close to impossible - even with the most expensive hardware available. And 512x512 would still look terrible on closeups.

However, If we could get a mesh out - things would look completely different.  (Preferably as an fbx sequence) Then we can use the more established production tools to create fakes on a whole new level. (Maya, 3ds max, Nuke - and even Daz3D as a free option)  The missing details can then be done in the shaders. 

I have worked quite a bit with photorealistic renders, and the mesh itself can be fairly low poly as long as topology is good. See below - this is quite old stuff, but still very impressive quality wise.

[Wikihuman project](http://vgl.ict.usc.edu/Data/DigitalEmily2/)

![03_Emily_model_01](https://user-images.githubusercontent.com/48013922/55873165-33432480-5b8f-11e9-8585-103d61c322fe.png)
![Cam1_FlashReference_Eyes_v06](https://user-images.githubusercontent.com/48013922/55873177-3ccc8c80-5b8f-11e9-8b25-2f3dd6974c6a.jpg)
![Cam3_FlashReference_Eyes_v06](https://user-images.githubusercontent.com/48013922/55873191-41914080-5b8f-11e9-89e9-376a7f78ec8d.jpg)

**Comment by spiegelball** [comment]
That'd be crazy. Once we can extract a good mesh from a video sequence (like the FaceBuilder plugin, but more automated) we could extract animated mesh from source and destination footage, do all the autoencoding you linked with the mesh and swap decoders like traditional deepfake. 

Then one had to evaluate if this approach excels traditional mocap and animation techniques.

**Comment by iperov** [comment]
and what difference?
shapes of faces will not be morphed same as classic face ae.

**Comment by iperov** [comment]
anyway if you want to contribute
learn machine learning
do experiments
provide results before / after.
idle talk like this one has no sense at all
