### ISSUE TITLE
Keep getting error when I train: Error: OOM when allocating tensor with shape

### ISSUE THREAD

**Issue by yg2dras1** [iperov/DeepFaceLab#227]
**### Hi guys, first time to try DFL here. I was trying out the default src and dst (robert downey jr on shia lebouf's head), and tried both train H64 and train H128 but keep getting this error right at the start.

I am using GTX 1050ti 6gb
I installed DeepFaceLabCUDA9.2SSE

I used the following steps:

2) extract images from video data_src
2) extract images from video data_src
3.2) extract images from video data_dst FULL FPS
5) data_dst extract faces MT all GPU 
6) train H164

HERE IS THE ERROR:

Model first run. Enter model options as default for each run.
Write preview history? (y/n ?:help skip:n) : y
Target iteration (skip:unlimited/default) : default
0
Batch_size (?:help skip:0) : 64
Feed faces to network sorted by yaw? (y/n ?:help skip:n) : y
Flip faces randomly? (y/n ?:help skip:y) : n
Src face scale modifier % ( -30...30, ?:help skip:0) : 0
Use lightweight autoencoder? (y/n, ?:help skip:n) : n
Use pixel loss? (y/n, ?:help skip: n/default ) : n
Using TensorFlow backend.
Loading: 100%|######################################################################| 137/137 [00:00<00:00, 630.03it/s]
Sorting: 100%|######################################################################| 64/64 [00:00<00:00, 21299.33it/s]
Loading: 100%|####################################################################| 1434/1434 [00:02<00:00, 705.14it/s]
Sorting: 100%|#######################################################################| 64/64 [00:00<00:00, 2376.82it/s]
===== Model summary =====
== Model name: H64
==
== Current iteration: 0
==
== Model options:
== |== write_preview_history : True
== |== batch_size : 64
== |== sort_by_yaw : True
== |== random_flip : False
== |== lighter_ae : False
== |== pixel_loss : False
== Running on:
== |== [0 : GeForce GTX 1050 Ti]
=========================
Starting. Press "Enter" to stop training and save model.
Error: OOM when allocating tensor with shape[64,1024,16,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model_2/conv2d_7/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_2/pixel_shuffler_2/NHWC, conv2d_7/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss/model_2_loss_1/Mean_3/_567}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4382_loss/model_2_loss_1/Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "D:\Patsoy-Home\Deepfake\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 93, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "D:\Patsoy-Home\Deepfake\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\ModelBase.py", line 362, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "D:\Patsoy-Home\Deepfake\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\Model_H64\Model.py", line 85, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.train_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mask], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "D:\Patsoy-Home\Deepfake\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\Patsoy-Home\Deepfake\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "D:\Patsoy-Home\Deepfake\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "D:\Patsoy-Home\Deepfake\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "D:\Patsoy-Home\Deepfake\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,1024,16,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model_2/conv2d_7/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_2/pixel_shuffler_2/NHWC, conv2d_7/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss/model_2_loss_1/Mean_3/_567}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4382_loss/model_2_loss_1/Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.**

**Comment by yg2dras1** [comment]
I'm wondering, is CUDA 9.2 and cuDNN required installations before I run DFL? thanks!

**Comment by iperov** [comment]
read fucking manual

**Comment by jaiksgelli** [comment]
the same problem for me, even after reducing passes to 1 .runs for some time and stops
