### ISSUE TITLE
Location of batch files source. I have a bug-fix for setenv, and other additional features if you like them.

### ISSUE THREAD

**Issue by MilkEyedMender** [iperov/DeepFaceLab#228]
## Expected behavior

Expected source tree to start at the same location as the build, or possibly has a link to another repository which hosts the batch files.

## Actual behavior

Batch files are not included, nor am I aware of any other repository.

## Steps to reproduce

N/A

## Comments

Hey iperov, awesome work on this project.

I've been modifying your batch files for some time as I like to open a single command prompt instance and run the batch files from that instead of double-clicking them in explorer. This is due to me doing other workspace work like teeing logs of the program out to the workspace folder and backing up the model at intervals, etc.

If you aren't aware, if you run this from a single instance of the command-line you will run into an error after a few runs where the scripts no longer work. I believe this is due to the way the path is set.

I normally download the new version of builds and modify them every time. I've added other features as well which I COULD submit, but this is the one that I do immediately every time regardless.

One of the other features is a user configuration .ini that allows people to override the master setenv values, as well as add their own (for example, if they want to set a base directory and then use that one of the overrides of a value that you use). The new setenv also shows the environment variables read in in a nicely formatted way, as well as fixing the bug I mentioned originally.

The latter feature doens't have to be added, or I can make a fork, but it'd be nice to be able to submit the first one.

I can:

1) Create my own repository with just the batch files. Upload the patch there and send you the link and you can pick and choose which ones you want, or start using it yourself.

2) Until you decide what you want, simply upload the fix here for you.

Thanks! I acutally have a bunch of ideas that I think would combine with yours and literally make this into a suite of tools that would make this even more unstoppable and THE ONLY choice for people to use for DeepFakes. Looking forward to your response! 

(Also, sorry about the length. I'd been wanting to ask this for a while and it's just been building up..)

**Comment by MilkEyedMender** [comment]
I'm going to get the latest version real quick and give you the updated batch.

**Comment by MilkEyedMender** [comment]
You can see the error I mentioned by:

1. Navigating to the root folder of DeepFaceLab (where all the "#) Description.bat" files are located).
2. Open a command-prompt. (If you're in explorer simply go to the address bar and type "cmd" and one will be opened already in this directory).
3. Run: "_internal\setenv.bat 1>nul" five or six times. The "1>nul" is important so you don't flood your screen.
4. You should see the following: ![image](https://user-images.githubusercontent.com/48065178/55864866-4b915000-5b4b-11e9-8117-a970ffc28541.png)

Next post will be the simplest form of the fix. 

Then I'll stop spamming you guys. Sorry. =/

**Comment by MilkEyedMender** [comment]
Here is a version which fixes the bug. It also simplifies the logic for the for statement that does the version checking for CUDNN since Windows XP and the versions after it check different. It also removes the need for the 'v' variable so the calling environment isn't polluted unnecessarily. Finally, it exits the batch file with an ERRORLEVEL of 0, which is like C-like in that it represents a success. This would allow you to do stuff like:

call _internal\setenv.bat && echo This executes on success. || echo This executes on failure.

Although I know you don't do that currently. I use it in my version that has the user configuration loading.

https://pastebin.com/raw/NzxFfFus

Thanks =)

**Comment by iperov** [comment]
wtf
all batches work fine.
DFL does not support windows XP.
I will not support any modifications.

**Comment by Secmess** [comment]
Just wanna add that this fixes my problem. Somehow the default setenv.bat is not working on my PC.

**Comment by Secmess** [comment]
Upon further checking, the simple solution to my problem was actually the formatting of the setenv.bat.

By default it was set to:
`for /f "tokens=4-7 delims=[.] " %%i in ('ver') do (if %%i==Version (set v=%%j.%%k) else (set v=%%i.%%j))
if "%v%" == "10.0" ( SET "PATH=%DP0%\CUDNN\Win10.0;%PATH%" ) else ( SET "PATH=%DP0%\CUDNN\Win6.x;%PATH%" )`

Meanwhile, separating them all into multiple lines fixed my problem:
`for /f "tokens=4-7 delims=[.] " %%i in ('ver') do @(
    if %%i==Version (
        set v=%%j.%%k) else (set v=%%i.%%j)
    ) 
    if "%v%" == "10.0" (
        SET "PATH=%DP0%\CUDNN\Win10.0;%PATH%" 
    ) else ( 
        SET "PATH=%DP0%\CUDNN\Win6.x;%PATH%" 
    )`

(and yes, even skipping the last bracket won't matter).

**Comment by iperov** [comment]
@Secmess thx
