### ISSUE TITLE
Separating expression from pose

### ISSUE THREAD

**Issue by spiegelball** [iperov/DeepFaceLab#229]
Hey.
I don't know much about ML but I got an idea on how to train model for avatar mode.

Let SRC be an image from source dataset and DST be an image from destination dataset. ROT(IMAGE) is a vector (pitch, yaw) with the rotational information of the image (can be computed via facial landmarks). We also have an encoder FEATURE = ENC(IMAGE, ROT) which brings an image and pose of face into feature space. The decoders DEC_SRC(FEATURE) and DEC_DST go from feature space to (IMAGE_PRED, ROT_PRED) by first reconstructing the image with a CNN cascade and computing ROT_PRED = ROT(IMAGE_PRED).

The dense layers in the encoder are fed with the result of the convolution cascade AND the ROT vector.

During training we minimize the error of:
- DEC_SRC(ENC(SRC, ROT(SRC))) compared with SRC for SRC images in batch
- DEC_DST(ENC(DST, ROT(DST))) compared with DST for DST images in batch
- ROT(DEC_DST(ENC(SRC, ROT(DST)))) compared with ROT(DST) for SRC AND DST from batch. This step can only done after a few thousand epochs when predicted face is clear enough for landmark detector to calculate rotation values.

Idea is, not only to train SRC and DST autoencoders, but also to learn to change pitch and yaw of predicted faces. This way during converting we can feed model with SRC image and ROT(DST) to produce an DST image with correct pitch and yaw values.

**Comment by iperov** [comment]
go ahead and test your idea and come back with amazing results.
