### ISSUE TITLE
Preview window missing if IPython is installed

### ISSUE THREAD

**Issue by waterfish1010** [iperov/DeepFaceLab#232]
Preview window, manual re-extract window etc missing if IPython is installed in windows(maybe also linux)
Everything works well after uninstall IPython

> DeepFaceLab/interact/interact.py
> try:
>     import IPython #if success we are in colab
>     from IPython.display import display, clear_output
>     import PIL
>     import matplotlib.pyplot as plt
>     is_colab = True
> except:
>     is_colab = False
>

**Comment by iperov** [comment]
DFL does not support IPython
