### ISSUE TITLE
I’m a FakeApp user and I need help

### ISSUE THREAD

**Issue by chris3726** [iperov/DeepFaceLab#240]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

I heard this GitHub is the best deepfake related website. I used Fake app about an year ago and I reseted my computer. Now I tried to reinstall it, but FakeApp website is gone and now I have weird error.

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

Training works just fine. Now I want to create a video.

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

I installed CUDA 9.0 and cuDNN, and C++. I also checked Path. Training works perfectly fine, but when I begin to make an actual video, it keep stops and tells me that there is an error. 

I’ll put the log txt right here:
undefinedffmpeg version git-2017-12-29-0c78b6a Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      56.  7.100 / 56.  7.100
  libavcodec     58.  9.100 / 58.  9.100
  libavformat    58.  3.100 / 58.  3.100
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  8.100 /  7.  8.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[image2 @ 000001e1c70ba4c0] Could find no file with path 'D:\fakes\origin\t5\workdir-1\merged\out%d.png' and index in the range 0-4
D:\fakes\origin\t5\workdir-1\merged\out%d.png: No such file or directory

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

I deleted everything and reinstalled it.
I installed different version of ffmpeg.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

My computer’s spec is:
Windows 10
I7 7700
1060 6gb
16gb ram

Thank you for your help!

**Comment by tfis2** [comment]
Download the pre Windows app, unzip and run the batch files.

https://github.com/iperov/DeepFaceLab/blob/master/doc/doc_prebuilt_windows_app.md

**Comment by chris3726** [comment]
@tfis2 I checked the link and I went to the mega link and I'm now downloading them. I see a lot of exe files, which one of them should I run?

**Comment by dpfks** [comment]
> @tfis2 I checked the link and I went to the mega link and I'm now downloading them. I see a lot of exe files, which one of them should I run?

Depends on your card. Read that page before you click on the Mega link...
Also https://mrdeepfakes.com/forums/thread-deepfacelab-explained-and-usage-tutorial
