### ISSUE TITLE
Collecting tensorflow==1.12.0   Could not find a version that satisfies the requirement tensorflow==1.12.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 2.0.0a0) No matching distribution found for tensorflow==1.12.0

### ISSUE THREAD

**Issue by ShszCraft** [iperov/DeepFaceLab#241]
## Expected behavior

*安装tensorflow==1.12.0 报错了，找不到1.12.0的版本，可以用什么版本替换？*

## Actual behavior

> pip install tensorflow==1.12.0
>  Collecting tensorflow==1.12.0
>  Could not find a version that satisfies the requirement tensorflow==1.12.0 (from versions: >1.13.0rc1, 1.13.0rc2, 1.13.1, 2.0.0a0)
> No matching distribution found for tensorflow==1.12.0

## Steps to reproduce

pip install tensorflow==1.12.0

## Other relevant information
- **pip install tensorflow==1.12.0**
- **Operating system and version:** Windows 10
- **Python version: 3.7.2

**Comment by iperov** [comment]
use python 3.6.5

**Comment by iperov** [comment]
also there are ready to use prebuilt versions for windows
