### ISSUE TITLE
Eye problems

### ISSUE THREAD

**Issue by shuai700** [iperov/DeepFaceLab#246]
Hello, ask:
I changed the resolution to 512 and the iteration has been trained to 120,000. But the eyes that were trained were the opposite. They should have looked to the left but looked to the right. What is the problem?
![512](https://user-images.githubusercontent.com/42859708/56727242-d9438100-6782-11e9-8a91-3d70bd6e4cd9.png)
![眼神](https://user-images.githubusercontent.com/42859708/56727898-37bd2f00-6784-11e9-925e-36d111fe94b0.png)

**Comment by iperov** [comment]
I dont support users modifications.
