### ISSUE TITLE
OpenCl - extract faces S3FD hangs on 3rd pass on systems with more than 4 cpu cores

### ISSUE THREAD

**Issue by cketelsen** [iperov/DeepFaceLab#247]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

extract faces finishes

## Actual behavior

extract faces script hangs on 3rd pass forever. last output:

Performing 3rd pass...
Running on CPU4.
Running on CPU5.
Running on CPU2.
Running on CPU1.
Running on CPU3.

MT extract also hangs.

I have a Ryzen 7 2700x, so 16 logical cores. When I cut the cores to 4 with no hyperthreading in BIOS, the script will successfully finish.

Issue is also discussed on mrdeepfakes forum:

https://mrdeepfakes.com/forums/thread-help-deepfacelabopenclsse-stuck-on-3rd-pass-of-extracting-faces

## Steps to reproduce

run extract faces with 16 logical cores -> hangs on 3rd pass
run extract faces with 4 logical cores -> finishes

## Other relevant information

occures with latest prebuild version (DeepFaceLabOpenCLSSE_build_04_24_2019)

**Comment by iperov** [comment]
I need teamviewer access to your comp.
Send id and pass to deepfakescovery@gmail.com

**Comment by iperov** [comment]
no feedback? close then

**Comment by cketelsen** [comment]
I sent teamviewer access to your email yesterday, maybe check your spam-folder? I will resend the email.

**Comment by iperov** [comment]
yes it is spam.

also your teamviewer is outdated.

**Comment by iperov** [comment]
i cannot connect to old version of tm

**Comment by cketelsen** [comment]
startet teamviewer 14, please try again

**Comment by iperov** [comment]
all stuck

**Comment by iperov** [comment]
ALL STUCK

**Comment by iperov** [comment]
cannot work on your fucking comp

**Comment by iperov** [comment]
all stucking

**Comment by iperov** [comment]
invite me back when I can do all what I want on your comp without stucking

**Comment by iperov** [comment]
@cketelsen did you fix teamviewer?

**Comment by cketelsen** [comment]
try again

**Comment by iperov** [comment]
fixed
