### ISSUE TITLE
Question: Any flag option to sharpen on Step 7?

### ISSUE THREAD

**Issue by unknownentity123** [iperov/DeepFaceLab#25]
Is there any way to sharpen the converted mask prior to merging with the destination video frames? OpenFaceSwap has the -sh flag on the convert.py script which will sharpen up the mask prior to merging  with the original video frame and outputting to a folder before the final video output step. Sharpening greatly enhances the final output especially around eye brows and eye details.

**Comment by unknownentity123** [comment]
@iperov Any ideas on this question?

**Comment by iperov** [comment]
no such flag, but you can code it
