### ISSUE TITLE
Fakeapp Faded Color Issues

### ISSUE THREAD

**Issue by FlyingCacti** [iperov/DeepFaceLab#251]
Firstly, I accidentally swapped two of the faces on the same model ( for curiosity ) and turns out it ruines color accuracy for ( Data A ) and now does not train accurately with faded color.

![Screenshot (16)](https://user-images.githubusercontent.com/50132294/56945584-fdc8a000-6b6a-11e9-82e2-1cd92d0f7bf3.png)

I have taken steps such as resetting the OS which has not fixed the issue, reinstalling all NVIDIA drivers and reinstalling fake-app. I have also tried resetting monitor color profiles as-well... still with no luck. Advice: Never swap data sets!

Hope anyone has any suggestions or inquiries, thanks 👍

**Comment by chervonij** [comment]
@FlyingCacti 

First, do you feel the difference between DFL and FakeApp? These are two different programs that have different developers. Why do you write your problems with FakeApp in the DFL repository?

Secondly, FakeApp is an outdated program that is not supported. Do not engage in nonsense and use DFL.

**Comment by FlyingCacti** [comment]
Thanks! At least I can get down to the nitty gritty :)
