### ISSUE TITLE
Batch Size more than 8 causes an error

### ISSUE THREAD

**Issue by youngjohan7** [iperov/DeepFaceLab#252]
Hello,

First of all, thank you so much for your work and sharing!

I've been writing a bunch describing everything, but it was getting too long, so please allow me to just summarize:

Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Ram: 16gb
GC: GTX 1660 Ti
VRam: 6gb
Os: Windows 10

As soon as I installed Windows 10, I installed DeepFaceLab by
DeepFaceLabCUDA10.1SSE_build_04_20_2019.exe
file.

Everything works fine, but when I try to have a batch size like 16, 32, 64, 128 it doesn't work and only the batch size 8 and lower works. I'll attach the error message at the end.
I believe my computer is good enough to handle a batch size much higher, but I can't seem to figure out the problem. I've googled and googled and read and tried stuff but I can't seem to fix the issue.

I'm sorry if this happens to be a dumb question.
Thank you! 

-error message when tried with batch size 128 at H128-

Starting. Press "Enter" to stop training and save model.
Error: OOM when allocating tensor with shape[128,1024,32,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model_2/conv2d_10/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_2/pixel_shuffler_5/NHWC, conv2d_10/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss/model_2_loss_1/Mean_3/_437}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2504_loss/model_2_loss_1/Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "D:\Deepfakes\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 93, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "D:\Deepfakes\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\ModelBase.py", line 362, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "D:\Deepfakes\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\Model_DF\Model.py", line 73, in onTrainOneIter
    loss_src = self.autoencoder_src.train_on_batch( [warped_src, target_src_mask], [target_src, target_src_mask] )
  File "D:\Deepfakes\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\Deepfakes\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "D:\Deepfakes\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "D:\Deepfakes\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "D:\Deepfakes\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[128,1024,32,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model_2/conv2d_10/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_2/pixel_shuffler_5/NHWC, conv2d_10/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss/model_2_loss_1/Mean_3/_437}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2504_loss/model_2_loss_1/Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Done.

**Comment by iperov** [comment]
read manual
read community guides

**Comment by youngjohan7** [comment]
@iperov 
Thank you for your reply.
I'm so sorry to bother, but I checked all the manuals that were included in the folder including the YouTube videos (all the linkes in reference 2).

I'm assuming you directed me to the reference 1 about "trimming the model" as well.
Perhaps I'm not understanding the statement correctly, but after seeing "see the description of the model options", I went to check out all the model options and tried all of them (DF, H64... SAE) and every one of them causes the same error as soon as I try a batch size bigger than 16.

I installed Cuda 10.1 and Cudnn 7.5 separately and then tried and the result was the same.

Thank you so much for your time!

Reference:
1) DeepFaceLabCUDA10.1SSE\manual_ru.pdf
Если в процессе запуска тренировки появилось много текста, содержащее одно из этих слов:
Memory Error
Allocation
OOM
значит на вашем GPU модель не запустилась, и вам нужно урезать модель, для этого смотрите описание опций моделей.

Google Translate)
If a lot of text appeared in the process of starting a workout, it contains one of these words:
Memory Error
Allocation
OOM
it means that the model did not start on your GPU, and you need to trim the model; for this, see the description of the model options.


2) DeepFaceLabCUDA10.1SSE\manual_en.txt
 You can translate manual_ru.pdf to your language via https://www.onlinedoctranslator.com

Found english tutorial here (can be outdated)
https://mrdeepfakes.com/forums/thread-deepfacelab-explained-and-usage-tutorial 

Video guides (can be outdated):

Beginners tutorial 
https://www.youtube.com/watch?v=K98nTNjXkq8

How To Make DeepFakes With DeepFaceLab - An Amatuer's Guide
https://www.youtube.com/watch?v=wBax7_UWXvc

DeepLearning series Ep 1 : DeepFaceLab Installation and Workflow TUTORIAL
https://www.youtube.com/watch?v=nboXZlXGFWM

DeepLearning series Ep 3 : DeepFake without a Graphics Card - Deepfacelab CPU Walkthrough 
https://www.youtube.com/watch?v=QFjhnJcFdZk

If you like this software, please consider a donation.

Goal: RTX 2080 TI

Donate via Yandex.Money https://money.yandex.ru/to/41001142318065

Donate via Paypal https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KK5ZCH4JXWMQS&source=url

Donate via Alipay https://i.loli.net/2019/01/13/5c3ae3829809f.jpg

bitcoin:31mPd6DxPCzbpCMZk4k1koWAbErSyqkAXr
