### ISSUE TITLE
Batch Size more than 8 causes an error #2

### ISSUE THREAD

**Issue by youngjohan7** [iperov/DeepFaceLab#256]
https://github.com/iperov/DeepFaceLab/issues/252

Good afternoon,

I'm sorry to be bothering you again with this.
Following your reply, I commented further but I suppose it is not notified as it is already closed.

Again, I'm sorry but could you please direct me on how I could fix this?

Thank you so much

------------

@iperov
Thank you for your reply.
I'm so sorry to bother, but I checked all the manuals that were included in the folder including the YouTube videos (all the linkes in reference 2).

I'm assuming you directed me to the reference 1 about "trimming the model" as well.
Perhaps I'm not understanding the statement correctly, but after seeing "see the description of the model options", I went to check out all the model options and tried all of them (DF, H64... SAE) and every one of them causes the same error as soon as I try a batch size bigger than 16.

I installed Cuda 10.1 and Cudnn 7.5 separately and then tried and the result was the same.

Thank you so much for your time!

Reference:

Reference 1)
DeepFaceLabCUDA10.1SSE\manual_ru.pdf
Если в процессе запуска тренировки появилось много текста, содержащее одно из этих слов:
Memory Error
Allocation
OOM
значит на вашем GPU модель не запустилась, и вам нужно урезать модель, для этого смотрите описание опций моделей.
Google Translate)
If a lot of text appeared in the process of starting a workout, it contains one of these words:
Memory Error
Allocation
OOM
it means that the model did not start on your GPU, and you need to trim the model; for this, see the description of the model options.

Reference 2)
DeepFaceLabCUDA10.1SSE\manual_en.txt
You can translate manual_ru.pdf to your language via https://www.onlinedoctranslator.com
Found english tutorial here (can be outdated)
https://mrdeepfakes.com/forums/thread-deepfacelab-explained-and-usage-tutorial

Video guides (can be outdated):

Beginners tutorial
https://www.youtube.com/watch?v=K98nTNjXkq8

How To Make DeepFakes With DeepFaceLab - An Amatuer's Guide
https://www.youtube.com/watch?v=wBax7_UWXvc

DeepLearning series Ep 1 : DeepFaceLab Installation and Workflow TUTORIAL
https://www.youtube.com/watch?v=nboXZlXGFWM

DeepLearning series Ep 3 : DeepFake without a Graphics Card - Deepfacelab CPU Walkthrough
https://www.youtube.com/watch?v=QFjhnJcFdZk

If you like this software, please consider a donation.

Goal: RTX 2080 TI

Donate via Yandex.Money https://money.yandex.ru/to/41001142318065

Donate via Paypal https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KK5ZCH4JXWMQS&source=url

Donate via Alipay https://i.loli.net/2019/01/13/5c3ae3829809f.jpg

bitcoin:31mPd6DxPCzbpCMZk4k1koWAbErSyqkAXr

**Comment by iperov** [comment]
did you read ISSUE INFO ?

```
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE
```

post question in the community sites

**Comment by youngjohan7** [comment]
K thx
