### ISSUE TITLE
The SampleGeneratorFace for the DST is also configured to do random flips, scaling and rotation. This seems counterproductive.

### ISSUE THREAD

**Issue by IUsedToBeAPygmy** [iperov/DeepFaceLab#258]
I notice the SampleGeneratorFace for the Destination data is also configured to do random flips / rotations / scaling.

I believe that isn't very useful as we know that the DST set is the exact set we want to match; 
we might get better results if we do not train with random transformed DST faces.

*apologies if this isn't a real "issue" but it felt worth mentioning

**Comment by iperov** [comment]
provide proofs before/after of 10 various fakes
