### ISSUE TITLE
AttributeError: 'DLIBExtractor' object has no attribute 'extract'

### ISSUE THREAD

**Issue by learning2makethings** [iperov/DeepFaceLab#262]
## Expected behavior

Trying to extract faces.

## Actual behavior

I get an error: AttributeError: 'DLIBExtractor' object has no attribute 'extract'

## Other relevant information
I think DLIBExtractor.py needs updates to line 24 function name and arguments. Currently is:
`    def extract_from_bgr (self, input_image):`

Extractor.py it tries to call it using the below.
`    def extract(self, input_image, is_bgr=True):`

**Comment by learning2makethings** [comment]
Saw the closed pull request with dlib being outdate and removed.

**Comment by jiakechong1991** [comment]
extract_from_bgr   并没有地方调用这个
