### ISSUE TITLE
error when running training script

### ISSUE THREAD

**Issue by claudetheboof** [iperov/DeepFaceLab#263]
whenvever I tried to run the Training script I gets these errors 

Running trainer.

Loading model...

Model first run. Enter model options as default for each run.
Write preview history? (y/n ?:help skip:n) :
Target iteration (skip:unlimited/default) :
0
Batch_size (?:help skip:0) : 64
Feed faces to network sorted by yaw? (y/n ?:help skip:n) : y
Flip faces randomly? (y/n ?:help skip:y) : y
Src face scale modifier % ( -30...30, ?:help skip:0) :
0
Use pixel loss? (y/n, ?:help skip: n/default ) :
n
Using TensorFlow backend.
Loading: 100%|######################################################################| 710/710 [00:01<00:00, 517.06it/s]
Sorting: 100%|#######################################################################| 64/64 [00:00<00:00, 3557.93it/s]
Loading: 100%|####################################################################| 3215/3215 [00:05<00:00, 557.63it/s]
Sorting: 100%|########################################################################| 64/64 [00:00<00:00, 736.08it/s]
===== Model summary =====
== Model name: LIAEF128
==
== Current iteration: 0
==
== Model options:
== |== batch_size : 64
== |== sort_by_yaw : True
== |== random_flip : True
== |== pixel_loss : False
== Running on:
== |== [0 : GeForce GTX 1060 6GB]
=========================
Starting. Press "Enter" to stop training and save model.
Error: OOM when allocating tensor with shape[64,512,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model_2/conv2d_11/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_2/pixel_shuffler_5/NHWC, conv2d_11/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss/model_2_loss/Mean_4/_395}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2522_loss/model_2_loss/Mean_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "C:\Users\tranb\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\mainscripts\Trainer.py", line 98, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\Users\tranb\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\ModelBase.py", line 404, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\Users\tranb\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\Model_LIAEF128\Model.py", line 80, in onTrainOneIter
    loss_src = self.autoencoder_src.train_on_batch( [warped_src, target_src_mask], [target_src, target_src_mask] )
  File "C:\Users\tranb\Downloads\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\tranb\Downloads\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\tranb\Downloads\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\tranb\Downloads\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\tranb\Downloads\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,512,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model_2/conv2d_11/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_2/pixel_shuffler_5/NHWC, conv2d_11/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss/model_2_loss/Mean_4/_395}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2522_loss/model_2_loss/Mean_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Done.
Press any key to continue . . .

**Comment by claudetheboof** [comment]
ok so after doing a bit of research , just found out that if the trai ning batch size is over 8 it will get error, does anyone know how to fix this? I even checked the [https://mrdeepfakes.com/forums/thread-deepfacelab-explained-and-usage-tutorial](url) for any information but cant seems to find a way to fix it. training with 8 isnt good enough .

**Comment by ShionWakanae** [comment]
"Bigger batch size" needs more video memory. "batchsize=8" or 4, is normal with a GeForce GTX 1060 6GB.
> training with 8 isnt good enough
maybe you need more iteration...

**Comment by claudetheboof** [comment]
huh thanks for the quick and easy explaination ... so im about to run both training on my 1060 6gb and on Google Colab, what are the best parameters to train the best model on google colab?  (I mainly doing these just for fun/ learning how machine learning work in the process)

**Comment by dogukan04** [comment]
I'm getting the same error And I couldn't find a solution. Can you help?(H128,Sae) in all of them.
![Uploading 15727062751943761559046826237942.jpg…]()

**Comment by claudetheboof** [comment]
@dogukan04 what's your gpu specs? And how many GB of RAM do you have currently? These training required lots of vram if not enough vram can be use it will automatically switch to ram which is much slower compared to vram

**Comment by claudetheboof** [comment]
So keep on experimenting with the resolution until you get it to work, you need a minimum of 6gb vram to training these kind of stuff.

**Comment by dogukan04** [comment]
I want to use train 128 but I can't use it

**Comment by dogukan04** [comment]
When auto encoder opens, quality drops and light errors occur What do I have to do?

**Comment by dogukan04** [comment]
My graphic card 1050ti   ram 8gb

**Comment by claudetheboof** [comment]
@dogukan04 what do you mean quality drop? You mean the training producing pixelated result?

**Comment by claudetheboof** [comment]
Your 1050 to only has 4gbof ram check your task manager for vram avaibility

**Comment by claudetheboof** [comment]
When training

**Comment by dogukan04** [comment]
> Your 1050 to only has 4gbof ram check your task manager for vram avaibility

Yes vram 4 gb /ram 8gb

**Comment by dogukan04** [comment]
Can I make train h128 with this card

**Comment by dogukan04** [comment]
> @ dogukan04 ne demek kalite düşüşü? Piksel sonuç üreten eğitim mi demek istiyorsun?

(Lighgter_ae:true )It works when it happens 
But the result is bad.

**Comment by claudetheboof** [comment]
The result bad could either be your gpu not capable enough to compute such thing or just needed some tweaking in the parameters.

**Comment by claudetheboof** [comment]
I'm not sure man keep on experimenting with different parameter try 64x64 reso

**Comment by dogukan04** [comment]
What's your solution?

**Comment by claudetheboof** [comment]
@dogukan04 like I said above keep on experimenting with different parameters and different model until it works your best bet right now is to try lowest solution see if it what's causing it. 64x64 should be flawless

**Comment by dogukan04** [comment]
Is there a lot of difference in image quality between H64 and h128

HD quality awareness
