### ISSUE TITLE
No CUDA device found with minimum required compute capability 3.5

### ISSUE THREAD

**Issue by shingoxy** [iperov/DeepFaceLab#264]
I was using DeepFaceLab with CUDA 10.1 version, but when I run "4) data_src extract faces MT all GPU debug.bat" to see whether my environment is OK or not. The message is shown on the screen.

My graphic card is dual GeForce 780M with a compute capability 3.0. Then How could I change the minimum required compute capability to 3.0?

**Comment by iperov** [comment]
buy card with CC 3.5
