### ISSUE TITLE
Graphiccard wrong detection

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#265]
Hi.
In each Version of DFL, my Graphiccards would be detected wrong.
Device 0 = RTX 2080 ti
Device 1 = GTX 1080 ti

in the Menu, its the wrong way up. DFL call my Device 0 GTX 1080 ti and Device 1 RTX 2080 ti.
So, if i choose best GPU, the GTX 1080 ti will be selected instead of the stronger RTX 2080

do u need additional Informations for fixing that?
Greetz

**Comment by GAN-er** [comment]
The first part of your question directly contradicts the second part so it is unclear what exactly your issue is:

> In each Version of DFL, my Graphiccards would be detected wrong.
>Device 0 = RTX 2080 ti
>Device 1 = GTX 1080 ti



Followed by:

> DFL call my Device 0 GTX 1080 ti and Device 1 RTX 2080 ti.

So which is it? 

It is not clear why you think there is something wrong about the detection of 
>Device 0 = RTX 2080 ti
>Device 1 = GTX 1080 ti
either.

**Comment by blanuk** [comment]
sorry for that
in my sytem:
dev 0 is the rtx 2080
dev 1 is the gtx 1080

dfl says the other way. dfl detect for dev 0 the gtx 1080 and for dev 1 the rtx 2080.
so if i choose a best gpu, the gtx 1080 will be choosen and not the stronger rtx 2080.

**Comment by wzfgogogo** [comment]
The source code can be modified temporarily  to handle your request.
edit 'DeepFaceLab\_internal\DeepFaceLab\nnlib.py'
add the code between two ######### lines.
this change can exchange devices' identifier directly.

    def _import_tf(device_config):
        if nnlib.tf is not None:
            return nnlib.code_import_tf

        if 'TF_SUPPRESS_STD' in os.environ.keys() and os.environ['TF_SUPPRESS_STD'] == '1':
            suppressor = std_utils.suppress_stdout_stderr().__enter__()
        else:
            suppressor = None

        if 'CUDA_VISIBLE_DEVICES' in os.environ.keys():
            os.environ.pop('CUDA_VISIBLE_DEVICES')

        os.environ['TF_MIN_GPU_MULTIPROCESSOR_COUNT'] = '2'
        os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' #tf log errors only
        import tensorflow as tf
        nnlib.tf = tf

        if device_config.cpu_only:
            config = tf.ConfigProto(device_count={'GPU': 0})
        else:
            config = tf.ConfigProto()

            if device_config.backend != "tensorflow-generic":
                #tensorflow-generic is system with NVIDIA card, but w/o NVSMI
                #so dont hide devices and let tensorflow to choose best card
                visible_device_list = ''
                for idx in device_config.gpu_idxs:
                    visible_device_list += str(idx) + ','
                config.gpu_options.visible_device_list=visible_device_list[:-1]
                ################################
                if config.gpu_options.visible_device_list=='1':
                    config.gpu_options.visible_device_list='0'
                else:
                    config.gpu_options.visible_device_list='1'
                ################################
        config.gpu_options.force_gpu_compatible = True
        config.gpu_options.allow_growth = device_config.allow_growth

        nnlib.tf_sess = tf.Session(config=config)

        if suppressor is not None:
            suppressor.__exit__()

**Comment by blanuk** [comment]
does not work:

> Traceback (most recent call last):
  File "M:\dfl_extract\_internal\DeepFaceLab\main.py", line 254, in <module>
    arguments.func(arguments)
  File "M:\dfl_extract\_internal\DeepFaceLab\main.py", line 25, in process_extract
    from mainscripts import Extractor
  File "M:\dfl_extract\_internal\DeepFaceLab\mainscripts\Extractor.py", line 10, in <module>
    import imagelib
  File "M:\dfl_extract\_internal\DeepFaceLab\imagelib\__init__.py", line 21, in <module>
    from .DCSCN import DCSCN
  File "M:\dfl_extract\_internal\DeepFaceLab\imagelib\DCSCN.py", line 4, in <module>
    from nnlib import nnlib
  File "M:\dfl_extract\_internal\DeepFaceLab\nnlib\__init__.py", line 1, in <module>
    from .nnlib import nnlib
  File "M:\dfl_extract\_internal\DeepFaceLab\nnlib\nnlib.py", line 150
    if config.gpu_options.visible_device_list=='1':
                                                  ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by blanuk** [comment]
maybee there is a option to choose the card manually in the batch file?
like:
--choosegpu 0
or something like that?

**Comment by lbfs** [comment]
The change will work. You need to fix your indentation of the code. 
Regardless, I'm pretty sure you can use --force-gpu-idx during training to change what GPU you wish to use.

**Comment by blanuk** [comment]
well, with notepad++ it works.
thanks :)
