### ISSUE TITLE
S3FD inaccuracy of easy shots.

### ISSUE THREAD

**Issue by GAN-er** [iperov/DeepFaceLab#268]
It appears that some issue was introduced in some of the later iterations of the S3FD extractor. 
Namely, some seemingly easy, unobstructed, clear shots are not being detected correctly. This is happening almost invariably in profile shots and in particular yaws, orientations:
About 45 degrees looking left or 45 looking right and about 5 to 30 degrees looking down. 
Here are some examples:
![image](https://user-images.githubusercontent.com/46759893/58205360-f5641080-7ca3-11e9-83c3-fb6c93b4027e.png)
In the above one the left eyebrow and eye and the nose are incorrectly detected as if the face is facing more to the left than what it actually does.
Here is another example:
![image](https://user-images.githubusercontent.com/46759893/58206286-07df4980-7ca6-11e9-8bb6-0beeca023019.png)
and another:
![image](https://user-images.githubusercontent.com/46759893/58206395-34936100-7ca6-11e9-9ca6-22628e066b53.png)
and another:
![image](https://user-images.githubusercontent.com/46759893/58206528-715f5800-7ca6-11e9-904e-ac6a5f054296.png)

and so on.

**Comment by iperov** [comment]
S3FD extracts MUCH better than before.
