### ISSUE TITLE
no faces found for ***.png, copying without faces

### ISSUE THREAD

**Issue by primejava** [iperov/DeepFaceLab#269]
when i run convert command，Too many “no faces found for ***.png, copying without faces” in the log
but i didn't delete anything in data_dst/aligned, and Face actually exists in the picture，

i guess maybe some package of python about face detection is too old，

this is my Server environment：
Centos7.3 python3.6.3

pip list:
absl-py (0.7.1)
asn1crypto (0.23.0)
astor (0.7.1)
attrs (19.1.0)
audioread (2.1.7)
backcall (0.1.0)
bleach (3.1.0)
certifi (2019.3.9)
cffi (1.11.2)
chardet (3.0.4)
conda (4.3.31)
cryptography (2.1.4)
cycler (0.10.0)
decorator (4.4.0)
defusedxml (0.5.0)
dlib (19.10.0)
dsw-ipykernel (0.2.0)
dsw-magic (0.0.1)
dswdlv (0.0.1)
entrypoints (0.3)
enum34 (1.1.6)
falcon (1.2.0)
future (0.17.1)
gast (0.2.2)
grpcio (1.19.0)
h5py (2.7.1)
idna (2.8)
imageio (2.5.0)
inflect (0.2.5)
ipykernel (5.1.0)
ipython (7.2.0)
ipython-genutils (0.2.0)
jedi (0.13.3)
Jinja2 (2.10.1)
joblib (0.13.2)
jsonschema (3.0.1)
jupyter-client (5.2.4)
jupyter-core (4.4.0)
jupyterlab (0.34.12)
jupyterlab-launcher (0.13.1)
jupyterlab-prometheus (0.1)
Keras (2.2.4)
Keras-Applications (1.0.7)
Keras-Preprocessing (1.0.9)
kiwisolver (1.0.1)
librosa (0.5.1)
llvmlite (0.28.0)
Markdown (3.0.1)
MarkupSafe (1.1.1)
matplotlib (2.0.2)
mistune (0.8.4)
nbconvert (5.4.1)
nbformat (4.4.0)
networkx (2.3)
notebook (5.7.8)
np-utils (0.5.10.0)
numba (0.43.1)
numpy (1.16.1)
opencv-python (4.0.0.21)
pandas (0.24.2)
pandocfilters (1.4.2)
parso (0.4.0)
pathlib (1.0.1)
pexpect (4.7.0)
pickleshare (0.7.5)
Pillow (5.4.1)
pip (9.0.1)
plaidml (0.6.0)
plaidml-keras (0.5.0)
prometheus-client (0.6.0)
prompt-toolkit (2.0.9)
protobuf (3.7.0)
ptyprocess (0.6.0)
pycosat (0.6.3)
pycparser (2.18)
Pygments (2.3.1)
pyOpenSSL (17.5.0)
pyparsing (2.3.1)
pyrsistent (0.14.11)
PySocks (1.6.7)
python-dateutil (2.8.0)
python-mimeparse (1.6.0)
pytz (2018.9)
PyWavelets (1.0.3)
PyYAML (5.1)
pyzmq (18.0.1)
requests (2.21.0)
resampy (0.2.1)
ruamel-yaml (0.11.14)
scandir (1.6)
scikit-image (0.15.0)
scikit-learn (0.21.1)
scipy (0.19.0)
Send2Trash (1.5.0)
setuptools (39.1.0)
six (1.12.0)
tensorboard (1.11.0)
tensorflow-gpu (1.11.0)
termcolor (1.1.0)
terminado (0.8.2)
testpath (0.4.2)
torch (1.0.1.post2)
torchtext (0.3.1)
torchvision (0.2.2.post3)
tornado (6.0.2)
tqdm (4.11.2)
traitlets (4.3.2)
Unidecode (0.4.20)
urllib3 (1.24.1)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.14.1)
wheel (0.33.1)

**Comment by lbfs** [comment]
I don't see how this error could occur unless you did delete faces. Is it possible you could upload a sample directory that you're having issues with? However, I have no issues on my Linux machine. 

However, on a side note, your dependencies are wildly out of date. 
Can you do a ``pip install --upgrade --force-reinstall -r requirements-cuda.txt```

**Comment by primejava** [comment]
Thank you for your answer.
