### ISSUE TITLE
error with FAN-x conversion on OpenCL

### ISSUE THREAD

**Issue by blitzenrod** [iperov/DeepFaceLab#271]
## Expected behavior

Trying to convert SAE using FAN-x on newest OpenCL build.

## Actual behavior

attribute error

## Steps to reproduce

Running converter.

Loading model...
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_tonga.0"
===== Model summary =====
== Model name: SAE
==
== Current iteration: 360
==
== Model options:
== |== batch_size : 4
== |== sort_by_yaw : False
== |== random_flip : True
== |== resolution : 128
== |== face_type : f
== |== learn_mask : True
== |== optimizer_mode : 1
== |== archi : df
== |== ae_dims : 512
== |== e_ch_dims : 42
== |== d_ch_dims : 21
== |== multiscale_decoder : True
== |== ca_weights : True
== |== pixel_loss : False
== |== face_style_power : 0.0
== |== bg_style_power : 0.0
== |== apply_random_ct : False
== Running on:
== |== [0 : Advanced Micro Devices, Inc. Tonga (OpenCL)]
=========================
INFO:plaidml:Analyzing Ops: 84 of 362 operations complete
INFO:plaidml:Analyzing Ops: 119 of 362 operations complete
INFO:plaidml:Analyzing Ops: 153 of 362 operations complete
INFO:plaidml:Analyzing Ops: 184 of 362 operations complete
INFO:plaidml:Analyzing Ops: 218 of 362 operations complete
INFO:plaidml:Analyzing Ops: 276 of 362 operations complete
INFO:plaidml:Analyzing Ops: 328 of 362 operations complete
Choose mode: (1) overlay, (2) hist match, (3) hist match bw, (4) seamless, (5) r
aw. Default - 4 :
4
Seamless hist match? (y/n skip:n) :
n
Mask mode: (1) learned, (2) dst, (3) FAN-prd, (4) FAN-dst , (5) FAN-prd*FAN-dst
(6) learned*FAN-prd*FAN-dst (?) help. Default - 1 : 4
Choose erode mask modifier [-200..200] (skip:0) :
0
Choose blur mask modifier [-200..200] (skip:0) :
0
Choose output face scale modifier [-50..50] (skip:0) :
0
Apply color transfer to predicted face? Choose mode ( rct/lct skip:None ) :
None
Apply super resolution? (y/n ?:help skip:n) :
n
Degrade color power of final image [0..100] (skip:0) :
0
Export png with alpha channel? (y/n skip:n) :
n

Collecting alignments: 0it [00:00, ?it/s]
Running on CPU0.
Using plaidml.keras.backend backend.
Exception: Traceback (most recent call last):
  File "C:\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py
", line 59, in _subprocess_run
    self.on_initialize(client_dict)
  File "C:\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\mainscripts\Converter.py",
 line 47, in on_initialize
    self.converter.on_cli_initialize()
  File "C:\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\converters\ConverterMasked
.py", line 128, in on_cli_initialize
    self.fan_seg = FANSegmentator(256, FaceType.toString( self.face_type ) )
  File "C:\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\facelib\FANSegmentator.py"
, line 25, in __init__
    exec( nnlib.import_all(), locals(), globals() )
  File "C:\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 754,
 in import_all
    nnlib.import_keras(device_config)
  File "C:\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 188,
 in import_keras
    nnlib.keras.backend.set_session(nnlib.tf_sess)
AttributeError: module 'keras.backend' has no attribute 'set_session'

**Comment by iperov** [comment]
fixed

**Comment by aaab456** [comment]
how to fix it?

**Comment by iperov** [comment]
@aaab456 what's ur problem?
