### ISSUE TITLE
Error converting H64 - OpenCLSSE

### ISSUE THREAD

**Issue by TheMadFaker** [iperov/DeepFaceLab#274]
Running converter.

Loading model...
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_tonga.0"
===== Model summary =====
== Model name: H64
==
== Current iteration: 70371
==
== Model options:
== |== batch_size : 4
== |== sort_by_yaw : False
== |== random_flip : False
== |== lighter_ae : False
== |== pixel_loss : False
== Running on:
== |== [0 : Advanced Micro Devices, Inc. Tonga (OpenCL)]
=========================
INFO:plaidml:Analyzing Ops: 85 of 158 operations complete
Choose mode: (1) overlay, (2) hist match, (3) hist match bw, (4) seamless, (5) r
aw. Default - 4 :
4
Seamless hist match? (y/n skip:n) :
n
Mask mode: (1) learned, (2) dst . Default - 1 :
1
Choose erode mask modifier [-200..200] (skip:0) :
0
Choose blur mask modifier [-200..200] (skip:0) :
0
Choose output face scale modifier [-50..50] (skip:0) :
0
Apply color transfer to predicted face? Choose mode ( rct/lct skip:None ) : RCT
Apply super resolution? (y/n ?:help skip:n) :
n
Degrade color power of final image [0..100] (skip:0) :
0
Export png with alpha channel? (y/n skip:n) :
n

Collecting alignments: 100%|################| 214/214 [00:00<00:00, 623.54it/s]
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Converting:   0%|                                      | 0/251 [00:00<?, ?it/s]E
xception while process data [C:\DeepFaceLabCLSSE02\workspace\data_dst\00003.jpg]
: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\joblib\SubprocessorBase.py",
 line 68, in _subprocess_run
    result = self.process_data (data)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 132, in process_data
    raise Exception( 'Error while converting face_num [%d] in file [%s]: %s' % (
face_num, filename_path, e_str) )
Exception: Error while converting face_num [0] in file [C:\DeepFaceLabCLSSE02\wo
rkspace\data_dst\00003.jpg]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

Exception while process data [C:\DeepFaceLabCLSSE02\workspace\data_dst\00004.jpg
]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\joblib\SubprocessorBase.py",
 line 68, in _subprocess_run
    result = self.process_data (data)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 132, in process_data
    raise Exception( 'Error while converting face_num [%d] in file [%s]: %s' % (
face_num, filename_path, e_str) )
Exception: Error while converting face_num [0] in file [C:\DeepFaceLabCLSSE02\wo
rkspace\data_dst\00004.jpg]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

Exception while process data [C:\DeepFaceLabCLSSE02\workspace\data_dst\00002.jpg
]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\joblib\SubprocessorBase.py",
 line 68, in _subprocess_run
    result = self.process_data (data)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 132, in process_data
    raise Exception( 'Error while converting face_num [%d] in file [%s]: %s' % (
face_num, filename_path, e_str) )
Exception: Error while converting face_num [0] in file [C:\DeepFaceLabCLSSE02\wo
rkspace\data_dst\00002.jpg]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

Exception while process data [C:\DeepFaceLabCLSSE02\workspace\data_dst\00001.jpg
]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\joblib\SubprocessorBase.py",
 line 68, in _subprocess_run
    result = self.process_data (data)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 132, in process_data
    raise Exception( 'Error while converting face_num [%d] in file [%s]: %s' % (
face_num, filename_path, e_str) )
Exception: Error while converting face_num [0] in file [C:\DeepFaceLabCLSSE02\wo
rkspace\data_dst\00001.jpg]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

Exception while process data [C:\DeepFaceLabCLSSE02\workspace\data_dst\00006.jpg
]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\joblib\SubprocessorBase.py",
 line 68, in _subprocess_run
    result = self.process_data (data)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 132, in process_data
    raise Exception( 'Error while converting face_num [%d] in file [%s]: %s' % (
face_num, filename_path, e_str) )
Exception: Error while converting face_num [0] in file [C:\DeepFaceLabCLSSE02\wo
rkspace\data_dst\00006.jpg]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

Exception while process data [C:\DeepFaceLabCLSSE02\workspace\data_dst\00005.jpg
]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\joblib\SubprocessorBase.py",
 line 68, in _subprocess_run
    result = self.process_data (data)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 132, in process_data
    raise Exception( 'Error while converting face_num [%d] in file [%s]: %s' % (
face_num, filename_path, e_str) )
Exception: Error while converting face_num [0] in file [C:\DeepFaceLabCLSSE02\wo
rkspace\data_dst\00005.jpg]: Traceback (most recent call last):
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\mainscripts\Converter.py", l
ine 125, in process_data
    image = self.converter.cli_convert_face(image, image_landmarks, self.debug,
avaperator_face_bgr=ava_face)
  File "C:\DeepFaceLabCLSSE02\_internal\DeepFaceLab\converters\ConverterMasked.p
y", line 408, in cli_convert_face
    new_out = cv2.warpAffine( new_out_face_bgr, face_mat, img_size, img_bgr.copy
(), cv2.WARP_INVERSE_MAP | cv2.INTER_LANCZOS4, cv2.BORDER_TRANSPARENT )
UnboundLocalError: local variable 'new_out_face_bgr' referenced before assignmen
t

Done.
Press any key to continue . . .

Windows 7, R9380, i7920

THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by iperov** [comment]
fixed, use lower case 'rct'
