### ISSUE TITLE
Vram Maxies out

### ISSUE THREAD

**Issue by itisyeetimetoday** [iperov/DeepFaceLab#275]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior
Trains the model.

## Actual behavior

Vram maxes out, oem error.

## Steps to reproduce

Run training bat files.

Windows,
1060 3gb

**Comment by iperov** [comment]
read manual

**Comment by itisyeetimetoday** [comment]
I do understand that I have to "trim" the model, however, I have tried using default values and lower batch sizes for all models, and they all display the same error. I also looking into tensorflow documentation on trimming models, however, they all involve pre-trained models or editing code.
