### ISSUE TITLE
FACES EXTRACTION NOT WORKING IN AMD 

### ISSUE THREAD

**Issue by utkdub** [iperov/DeepFaceLab#277]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*
I was trying to extract faces from images using 4) data_src extract faces S3FD all GPU 
## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*
Instead of extracting faces it shows **Advanced Micro Devices, Inc. Bristol Ridge (OpenCL) doesnt response, terminating it.** and later **Advanced Micro Devices, Inc. Iceland (OpenCL) doesnt response, terminating it.**
after 3rd pass it shows images found 819 and faces detected 0.
Basically No faces gets detected .
## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*
```
NFO:plaidml:Analyzing Ops: 173 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 175 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 415 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 415 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 649 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 651 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 909 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 908 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1179 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1180 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1442 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1442 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1718 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1718 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1985 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1985 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2263 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2264 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2533 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2534 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2802 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2801 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3086 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3087 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3348 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3349 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3624 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3623 of 3786 operations complete
Advanced Micro Devices, Inc. Bristol Ridge (OpenCL) doesnt response, terminating it.
Advanced Micro Devices, Inc. Iceland (OpenCL) doesnt response, terminating it.

Performing 3rd pass...
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
0it [00:00, ?it/s]
-------------------------
Images found:        819
Faces detected:      0
-------------------------
Done.
Press any key to continue . . .

My CPU is AMD A10 9620P RADEON R5 10 COMPUTE CORES 4C+6G 2.50GHZ
```
 problem is coming not just in _data_src extract faces S3FD all GPU_   but every other **data_src extract** (MT,S3FD) and all GPU,Best GPU and degug version too

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
8 GB DDR4 RAM
WINDOWS 10 Enterprise N 2016 LTSB

- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by iperov** [comment]
post your GPUs info

**Comment by utkdub** [comment]
[https://drive.google.com/open?id=1vxYhr2UHywAtlIfOPf0eyFJkWcGtTSIc](url)
All my CPU ,GPU info is here

**Comment by iperov** [comment]
it seems you has very old amd gpu with 2gb that is not supported by plaidml

**Comment by utkdub** [comment]
any way to come around that ? I really wanna do deep fake . Plz make it for CPU only

**Comment by iperov** [comment]
use google colab
