### ISSUE TITLE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by ankursharma12** [iperov/DeepFaceLab#281]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*
i was trying to extract faces from the images

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*
it

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*
Performing 1st pass...
Running on Advanced Micro Devices, Inc. Baffin (OpenCL).
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_baffin.0"
Running on Advanced Micro Devices, Inc. gfx902 (OpenCL).
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_gfx902.0"
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
  0%|                                                                                          | 0/138 [00:00<?, ?it/s]INFO:plaidml:Analyzing Ops: 51 of 285 operations complete
INFO:plaidml:Analyzing Ops: 51 of 285 operations complete
INFO:plaidml:Analyzing Ops: 124 of 285 operations complete
INFO:plaidml:Analyzing Ops: 124 of 285 operations complete
INFO:plaidml:Analyzing Ops: 192 of 285 operations complete
INFO:plaidml:Analyzing Ops: 238 of 285 operations complete
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
INFO:plaidml:Analyzing Ops: 50 of 285 operations complete
INFO:plaidml:Analyzing Ops: 41 of 285 operations complete
INFO:plaidml:Analyzing Ops: 109 of 285 operations complete
INFO:plaidml:Analyzing Ops: 115 of 285 operations complete
INFO:plaidml:Analyzing Ops: 152 of 285 operations complete
INFO:plaidml:Analyzing Ops: 152 of 285 operations complete
100%|################################################################################| 138/138 [01:09<00:00,  1.98it/s]
Performing 2nd pass...
Running on Advanced Micro Devices, Inc. Baffin (OpenCL).
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_baffin.0"
Running on Advanced Micro Devices, Inc. gfx902 (OpenCL).
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_gfx902.0"
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
  0%|                                                                                          | 0/138 [00:00<?, ?it/s]INFO:plaidml:Analyzing Ops: 194 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 215 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 593 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 644 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1119 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1074 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1557 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1559 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1865 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 1885 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2205 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2211 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2538 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2534 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 2962 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3007 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3423 of 3786 operations complete
INFO:plaidml:Analyzing Ops: 3499 of 3786 operations complete
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
E:\a\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\facelib\LandmarksExtractor.py:91: RuntimeWarning: overflow encountered in long_scalars
  newDim = np.array([br[1] - ul[1], br[0] - ul[0], image.shape[2]], dtype=np.int32)
E:\a\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\facelib\LandmarksExtractor.py:91: RuntimeWarning: overflow encountered in long_scalars
  newDim = np.array([br[1] - ul[1], br[0] - ul[0], image.shape[2]], dtype=np.int32)
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
INFO:plaidml:Analyzing Ops: 41 of 285 operations complete
INFO:plaidml:Analyzing Ops: 69 of 285 operations complete
INFO:plaidml:Analyzing Ops: 133 of 285 operations complete
Advanced Micro Devices, Inc. Baffin (OpenCL) doesnt response, terminating it.
INFO:plaidml:Analyzing Ops: 161 of 285 operations complete
Advanced Micro Devices, Inc. gfx902 (OpenCL) doesnt response, terminating it.

Performing 3rd pass...
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Running on CPU6.
Running on CPU7.
0it [00:00, ?it/s]
-------------------------
Images found:        138
Faces detected:      0
-------------------------
Done.
Press any key to continue . . .

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows10 
- **Python version:** 3.6.8
gpu amd ryzen rx560x

**Comment by sevenda7247** [comment]
что делать если такая ошибка =========================
Starting. Press "Enter" to stop training and save model.
INFO:plaidml:Analyzing Ops: 77 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 222 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 234 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 326 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 346 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 377 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 417 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 578 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 590 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 681 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 693 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 727 of 1560 operations complete
INFO:plaidml:Analyzing Ops: 789 of 1560 operations complete
ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
INFO:plaidml:Analyzing Ops: 74 of 160 operations complete
INFO:plaidml:Analyzing Ops: 139 of 160 operations complete
INFO:plaidml:Analyzing Ops: 74 of 160 operations complete
INFO:plaidml:Analyzing Ops: 139 of 160 operations complete
[17:28:56][#031383][0033ms][1.0000][1.0000]
