### ISSUE TITLE
Feature request: A new version of S3FD extractor

### ISSUE THREAD

**Issue by tania010** [iperov/DeepFaceLab#282]
i want to request a new/another version of S3FD face extractor which detects the hairline above the forehead and masks the face till the hairline.
sometime the src and dst have very different skin types e.g. freckles or wrinkles. and while the face is beautifully merged thanks to your hard work in conversion modes, the forehead breaks the illusion. so if the WHOLE face (including the forehead) is replaced, it would be a VERY convincing fake indeed.
thank you again for all your hard work on DFL @iperov

**Comment by TooMuchFun** [comment]
Wouldn't this proposed behavior just move the mask border outward a bit? You would end up with the same problems just a few pixels further from the face border. 

It should also be said that every additional pixel added to the algorithm will scale training training time in a geometric fashion, not additive. Tweaking the bg style power when training will get you similar results to what you want. Begin around 0.1 and increment slowly through decimals and single digits. This will get you similar results to your request but not blow out your training time.

One of the most critical parts of making a good fake is the choice of src and dst samples. You won't have much luck swapping people that look drastically different. That includes skin tones, imperfections, scene-specific lighting, skin tone, etc.

I suggest you resolve by hand when pre-processing your dst clip prior to extraction.

**Comment by TooMuchFun** [comment]
Also, please try contributing to the project before requesting features. This is a project run by volunteers and you won't find someone to go out of their way to build feature request ideas.
