### ISSUE TITLE
Which Mode will fit better?

### ISSUE THREAD

**Issue by li99yangg** [iperov/DeepFaceLab#285]

**Comment by li99yangg** [comment]
> I used to using S3FD to extract faces,and use H128 to train.Yesterday I tried to use SAE to train model,and I realized it didn't fit to train the two face with different skin-color.Today I reuse H128 to train my model.
> I want to ask which mode is better to fit and train my model?
> 我一直习惯使用S3FD去导出我视频中的脸，用H128训练模型，但是昨天我用SAE训练的时候，我发现对于两张脸肤色有一定差异的时候，SAE的效果非常差，替换效果非常明显，所以我想请问下作者能不能介绍下每一个模式的优缺点吗？

另外H128的效果我觉得一直都非常好

**Comment by claudetheboof** [comment]
https://mrdeepfakes.com/forums/thread-deepfacelab-explained-and-usage-tutorial check out this guide ... this guide should give you all the information you needed for each training types.
