### ISSUE TITLE
Resize video before merge?

### ISSUE THREAD

**Issue by TheMadFaker** [iperov/DeepFaceLab#288]
Any chance you could add the option to resize data_dst video at conversion?  If not, is there a simple way to do so and still use aligned images from high-res video?

**Comment by feepdakenoob** [comment]
Resize the video before you extract faces or after conversion. There are tools out there already to do so. Why would this be a part of faceswapping process?

**Comment by TheMadFaker** [comment]
Perhaps I'm just doing something wrong.  I have a model trained on a dst set that comes from a high-resolution video.  Training on the extracted faces from a high-res dst is giving better looking preview images, but converting gives blurry result even with 256res models unless I use lower resolution dst video, but then I have to use extracted faces from that lower-res video and lose details or at least appear to in the preview.  Also, the alignments are never 100% the same as the original extracted faces so it takes a bunch of extra training to try and let things adjust.  I tried resizing the video before converting, but then the original alignments don't work and the merged images either do not have the src face on them, or it's extremely blurry and way off the dst face position.  I assume there is information in the files that links them together for DFL.  I'm trying to figure out a way to make this work.  It seems like it should not be too difficult to implement since it can likely be done with ffmpeg.  I guess if I figure it out I'll share with others who may be interested.

**Comment by TheMadFaker** [comment]
Basically I'd like to be able to train on dst set from high-res video, which although it is scaled down to a 256x256 face gives more detail than just using extracted faces from lower-res dst, and then at convert when merging be able to choose output resolution of result video.  This would help maximize model details and minimize blurring from stretching the face onto a video that is too large.

**Comment by TheMadFaker** [comment]
Faceset it good, and has trained over 300k iterations.  The blur is coming from the face being stretched onto the high-res video.  Training on the extracted faces from the high res is better than resizing first and then extracting and training.  I think I see a way it might be possible to do what I'm trying to do

**Comment by Auroir** [comment]
Besides simply resizing your result video, this is where exporting with alpha comes in handy. 

1. Export with alpha, resize to your face frames. 
2. Make a copy of your destination frames, resize and blur to match your face quality.
3. Merge the destination frames with your face overlays.

**Comment by emran313** [comment]
> Faceset is good, and has trained over 300k iterations. The blur is coming from the face being stretched onto the high-res video. Training on the extracted faces from the high res is better than resizing first and then extracting and training. I think I see a way it might be possible to do what I'm trying to do

I'm faced with the same situation. Have you found a workaround?
