### ISSUE TITLE
Manual Re-extract Duplicates

### ISSUE THREAD

**Issue by Fakerdaker** [iperov/DeepFaceLab#289]
Running manual re-extract on a sorted aligned folder creates duplicate images.

If images in dst\aligned do not have their original filenames then DFL does not overwrite when re-extracting.

## Steps to reproduce

Sort dst using any of the sorts.
Delete a few images from dst\aligned_debug.
Run manual re-extract.
Now there are extra images in the \aligned folder.
Run "5.3.other) data_dst util recover original filename" to see which files are duplicates. 
The filename_0.jpg OR filename_1.jpg can be the outdated file.

If the aligned folder has the original filenames (#####_0.jpg) for all images, then it properly overwrites the original file.

**Comment by feepdakenoob** [comment]
You can always revert to the original filenames before doing a manual re-extract.
