### ISSUE TITLE
CONVERT not using GPU, only CPU.

### ISSUE THREAD

**Issue by Snakepit770** [iperov/DeepFaceLab#290]
Using last **prebuilt windows** binary

![Screenshot_3](https://user-images.githubusercontent.com/52167210/60026793-a75f7580-9672-11e9-9cce-661670b5910c.png)

![Screenshot_2](https://user-images.githubusercontent.com/52167210/60027735-610b1600-9674-11e9-9838-6b248c431acb.jpg)

What could be the problem?

**Windows Version:**

![Screenshot_5](https://user-images.githubusercontent.com/52167210/60028213-5309c500-9675-11e9-9f61-e2ae4c8f31ce.png)

**Nvidia drivers:** 

397.64

**Comment by feepdakenoob** [comment]
Did you grab the right version? I have the same card and have no problems.

**Comment by Snakepit770** [comment]
> 
> 
> Did you grab the right version? I have the same card and have no problems.

I grab the last version:

![Screenshot_3](https://user-images.githubusercontent.com/52167210/60135484-34402700-9778-11e9-9a11-c088474a1ffb.png)

Can you tell me your **Windows** version and **Nvidia** drivers too?

**Comment by yuemenglong** [comment]
I have the save issue (with win10 + 9900k + 2080ti)

**Comment by wzfgogogo** [comment]
Converter uses little GPU，it just loads the model and predict. Main workload is processed by openCV with CPU.
Besides you enable the 'super resolution'，because this function works with keras.

**Comment by Snakepit770** [comment]
> 
> 
> Converter uses little GPU，it just loads the model and predict. Main workload is processed by openCV with CPU.
> Besides you enable the 'super resolution'，because this function works with keras.

Sorry but you are wrong and i will let you here a proof of how much slow it's (because no GPU usage) compared to the old version:

https://www.youtube.com/watch?v=bxbIjeJULVQ (DFL old vs new.)

**Comment by Auroir** [comment]
See:
https://github.com/iperov/DeepFaceLab/blob/master/mainscripts/Converter.py#L41

**Comment by Snakepit770** [comment]
> 
> 
> See:
> https://github.com/iperov/DeepFaceLab/blob/master/mainscripts/Converter.py#L41

Well the old code have that lines too: https://privatebin.net/?c0918f870a4003a4#iuSABQ1DC0Fg7twxa6dBuLLsLLw1QfzKH95UiwLd2F0=

So, i don't understand why the **speed** difference is so big between old and new converter...

**Comment by Whatwhatio** [comment]
Same issue, using CPU when extracting faces.

DFL version: Copy of DeepFaceLabOpenCLSSE_build_06_20_2019
GPU: GeForce GTX 1080
GPU Driver: 26.21.14.3086

**Comment by tetlie** [comment]
The same is happening to me. I am quite sure mine has been running on GPU when converting before, but will now directly jump to CPU, which is very much slower, and I get the message `CPU3 doesnt response, terminating it`

It will then try another CPU and rotate through all seven a couple of times, before eventually stopping.

I run this on the Linux-fork (https://github.com/lbfs/DeepFaceLab_Linux) on a Quadro P5000 (16 GB).

**Comment by Entretoize** [comment]
Same issue on windows 10, is there a workaround ?

**Comment by Cheapfake** [comment]
My system just started doing this too. Been running on Win 10-64bit with GTX 970. NOw when I Run Merger, it goes to cpu every time. Tried re-installing, still same problem.
