### ISSUE TITLE
result.mp4  not showing up anywhere

### ISSUE THREAD

**Issue by srmmedia** [iperov/DeepFaceLab#292]
I got it all up and running and got to the final stage where I render the .mp4 file.  It took a while but after it was done it said "done"  press any key to continue . Which I did and then I look for the result.mp4 file and it is not in workspace , its not anywhere on my computer.    Could the app be rendering it as another file name somewhere else because I can not find it

**Comment by Auroir** [comment]
Can you give us your output from ffmpeg encoding? It should state where it's encoding to or why it failed. 

For example, this is encoding to "/content/test.mp4'
```
[...]
Output #0, mp4, to '/content/test.mp4':
  Metadata:
    encoder         : Lavf58.27.103
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 854x480 [SAR 1280:1281 DAR 16:9], q=22-26, 24 fps, 12288 tbn, 24 tbc (default)
    Metadata:
      encoder         : Lavc58.52.102 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=   98 fps=6.3 q=-1.0 Lsize=     135kB time=00:00:03.95 bitrate= 279.9kbits/s speed=0.255x    
video:133kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.489770%
[...]
```

**Comment by HaraHachi** [comment]
I have the same problem.
