### ISSUE TITLE
Cannot choose what GPU to work with

### ISSUE THREAD

**Issue by theburgman21** [iperov/DeepFaceLab#295]
I am using the Compiled binary release from June 20 and I trained SAE on my Radeon VII, the problem is that I have now installed a second GPU (AMD RX 480) and when I start the train SAE and Convert SAE files I now get a menu at the beggining asking me what GPU I would like to use, the problem is that if I manually select any of the GPUs (by typing 0 or 1) it doesn't detect the trained model and prompts me to enter the parameters for training, however when I hit enter or input -1 for the program to select the best GPU it will recognize the previously trained model and resume training or start converting. This is a great problem for me as it doesn't let me use the second GPU for anything at all.

![aaaaaaaaaaaaa](https://user-images.githubusercontent.com/52357440/60387918-8354c780-9aaa-11e9-825e-cbb8a97a4f34.PNG)
![bbbbbbbbbb](https://user-images.githubusercontent.com/52357440/60387919-8354c780-9aaa-11e9-882b-f470d815da89.PNG)
![cccccccc](https://user-images.githubusercontent.com/52357440/60387920-8354c780-9aaa-11e9-97df-31e7b730a164.PNG)

Help would be very appreciated
Thanks
Alex

**Comment by Auroir** [comment]
I have no way to check this but it feels like an issue with the model's saved parameters. 

If you still have this problem:
1. Make a backup of your model then clear your model folder.
2. Make a new model with the exact same parameters as the one you backed up. **Exact!**
3. Train it to at least 2 iterations then save/stop.
4. Copy all the .h5 files from your backed up model into the new model folder. **(Do not copy the .dat file, this is what we are fixing!)**
5. Restart training.

**Comment by Etren** [comment]
> I have no way to check this but it feels like an issue with the model's saved parameters.
> 
> If you still have this problem:
> 
> 1. Make a backup of your model then clear your model folder.
> 2. Make a new model with the exact same parameters as the one you backed up. **Exact!**
> 3. Train it to at least 2 iterations then save/stop.
> 4. Copy all the .h5 files from your backed up model into the new model folder. **(Do not copy the .dat file, this is what we are fixing!)**
> 5. Restart training.

Thanks for your suggestion.
I'm Trying your suggestion does not solve the problem of choosing GPU invalid when recovering training!
When trying your suggestion, I found that the file name of the newly created model file has a prefix is "1_".
I tried to rename the file names of the old model files and added the prefix "1_" to the file name. Then I resumed the training and found that although I can't choose the GPU, the model will start training directly on the second GPU.
I guess this filename prefix "1_" is the GPU's sequential code?

**Comment by kadrim** [comment]
you could deactivate one of your GPUs for openCL by doing the following:

1) Get a binary of clinfo from Github: https://github.com/Oblomov/clinfo
2) run "clinfo -l"

The output will be something like:
```
Platform #0: AMD Accelerated Parallel Processing
 +-- Device #0: Baffin
 `-- Device #1: gfx902
```

I know (via GPU-Z or any other tool) that my discrete AMD RX 560X GPU is the one called "Baffin". So i only want openCL to use that one. Adjust accordingly.

3) run "set GPU_DEVICE_ORDINAL=0"

within that terminal session only device "0" will be available to openCL. Adjust accordingly.
