### ISSUE TITLE
gpu question

### ISSUE THREAD

**Issue by liang741107** [iperov/DeepFaceLab#298]
![CD339265-D9E7-4BC8-9829-02D1FF048A3A](https://user-images.githubusercontent.com/52492073/60585238-cfad4980-9dc1-11e9-902e-9d9a5cb7be24.jpeg)
![053A8B87-9A2A-4F26-BCBD-38CC256DC780](https://user-images.githubusercontent.com/52492073/60585240-cfad4980-9dc1-11e9-952b-22defd408c58.jpeg)
![8BE76F36-D7AD-4A06-B165-AE11D90530ED](https://user-images.githubusercontent.com/52492073/60585242-d045e000-9dc1-11e9-9123-9e02381a41c7.jpeg)

my gpu is GeForce gtx1060 6g,and allready updated the newest driver.
but when I training the model,it says:”warning!! you are using 2gb gpu”
I pretty sure my gpu is 6gb.
How can I solve this problem?thanks.
my system: 
window10 
cuda10.1 
deepfacelab10.1avx(6/20)

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by deyu260** [comment]
h128最小显存需要5G，很明显 你的剩余显存只有3G多， 无关的程序占用了显存
