### ISSUE TITLE
Multi GPU Extraction long time for init

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#299]
Hi :)
If i use only best GPU for extraction, the Process starts immediatly.
For bigger Projects i use Multi GPU extraction. BUT:

Performing 1st pass...
Running on GeForce GTX 1080.
Using TensorFlow backend.
Running on GeForce RTX 2080 Ti.
Using TensorFlow backend.

just for that it can use up to 10 minutes..

Is there a fix to reduce this time?
Which information are needed to solve this?

Greetz and thanks for ur work. Already donated :)

**Comment by deyu260** [comment]
Use 2 cards of the same size to avoid this problem
