### ISSUE TITLE
convert(seamless) has Exception

### ISSUE THREAD

**Issue by zysttttttt** [iperov/DeepFaceLab#30]
## Expected behavior

convert successful

## Actual behavior

Converting:  35%|███████████████████████▌                                            | 208/601 [00:11<00:22, 17.57it/s]Exception while process data [undefined]: Traceback (most recent call last):
  File "D:\AI\fake\DeepFaceLab-master\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\AI\fake\DeepFaceLab-master\mainscripts\Converter.py", line 159, in onClientProcessData
    image = self.converter.convert_face(image, image_landmarks, self.debug)
  File "D:\AI\fake\DeepFaceLab-master\models\ConverterMasked.py", line 169, in convert_face
    out_img = cv2.seamlessClone( (out_img*255).astype(np.uint8), (img_bgr*255).astype(np.uint8), (img_face_mask_flatten_aaa*255).astype(np.uint8), (masky,maskx) , cv2.NORMAL_CLONE )
cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\core\src\matrix.cpp:465: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'cv::Mat::Mat'

Exception while process data [undefined]: Traceback (most recent call last):
  File "D:\AI\fake\DeepFaceLab-master\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\AI\fake\DeepFaceLab-master\mainscripts\Converter.py", line 159, in onClientProcessData
    image = self.converter.convert_face(image, image_landmarks, self.debug)
  File "D:\AI\fake\DeepFaceLab-master\models\ConverterMasked.py", line 169, in convert_face
    out_img = cv2.seamlessClone( (out_img*255).astype(np.uint8), (img_bgr*255).astype(np.uint8), (img_face_mask_flatten_aaa*255).astype(np.uint8), (masky,maskx) , cv2.NORMAL_CLONE )
cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\core\src\matrix.cpp:465: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'cv::Mat::Mat'

## Steps to reproduce
convert(hist-match) is OK
but convert(seamless)  and convert(seamless-hist-match) throw the exception while proccessing about 32%(always in different srcfiles)

python main.py convert --input-dir input\ --output-dir porn\ --aligned-dir sort\ --model-dir M\ --model LIAEF128 --mode seamless

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: python main.py convert --input-dir input\ --output-dir porn\ --aligned-dir sort\ --model-dir M\ --model LIAEF128 --mode seamless
- **Operating system and version:** Windows
- **Python version:** 3.6

**Comment by zysttttttt** [comment]
opencv-python (version too new)

**Comment by kyoto-shift** [comment]
Downgrading from `opencv-python==3.4.0.12` to `opencv-python==3.3.1.11` fixed the issue for me.
