### ISSUE TITLE
Issue when running data_dst extract faces MT best GPU

### ISSUE THREAD

**Issue by teamjla** [iperov/DeepFaceLab#300]
when running data_dst extract faces MT best GPU

it gives me an error:

-------------------------
Images found:        0
Faces detected:      0
-------------------------
Done.
Press any key to continue . . .

no problem executing previous batch files for data_src.

**Comment by juancano2006** [comment]
Do you have images in %WORKSPACE%\data_dst?

If you are using windows 10...

Are you sure that you executed 3.2) extract images from video data_dst FULL FPS.bat?
