### ISSUE TITLE
Can't run with RTX 2080 Ti

### ISSUE THREAD

**Issue by Kulme** [iperov/DeepFaceLab#302]
I have GTX 1080 Ti (GPU 0) and RTX 2080 Ti (GPU 1). But program doesn't choose RTX 2080 Ti.

## Expected behavior

Train data use RTX 2080 Ti.

## Actual behavior

I choose RTX 2080 Ti, but the program use my GTX 1080 Ti.

![rtx](https://user-images.githubusercontent.com/9191422/60705102-6ef04f00-9f30-11e9-9622-73c85a9484b6.png)

![gpu](https://user-images.githubusercontent.com/9191422/60705115-74e63000-9f30-11e9-8636-46e26ff23754.PNG)

## Steps to reproduce

Train H64, Choose RTX 2080 Ti (GPU 1), check task manager.

## Other relevant information
- train H64.bat
- Windows 10
- Python with prebuilt windows binary

**Comment by blanuk** [comment]
have the same situation. just choose the other one. for using the rtx, choose 0 for using the gtx use 1

**Comment by Kulme** [comment]
Thanks
