### ISSUE TITLE
CUDA synchronize error - GTX 1660-TI

### ISSUE THREAD

**Issue by RelievedStudios** [iperov/DeepFaceLab#303]
## Expected behavior
I am trying to run the 'data_src extract faces MT best GPU' bat file

## Actual behavior
output:

> Performing 1st pass...
> Running on GeForce GTX 1660 Ti #0.
> Using TensorFlow backend.
> Running on GeForce GTX 1660 Ti #1.
> Using TensorFlow backend.
> 2019-07-06 03:21:52.202643: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
> 2019-07-06 03:21:52.212639: E tensorflow/stream_executor/cuda/cuda_timer.cc:55] Internal: error destroying CUDA event in context 000001AC6AAE48B0: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
> 2019-07-06 03:21:52.221210: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 000001AC6AAE48B0: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
> 2019-07-06 03:21:52.232647: F tensorflow/stream_executor/cuda/cuda_dnn.cc:231] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.

## Steps to reproduce
N/A, no idea how it happened

## Other relevant information
- **Operating system and version:** Windows 10

**Comment by deyu260** [comment]
Maybe the graphics card is too new, the integrated environment package is not compatible

**Comment by RelievedStudios** [comment]
It has started to work now, closing issue.

**Comment by altafim** [comment]
> It has started to work now, closing issue.

how did you get it?
I have the same problem (GTX 1650)

**Comment by RelievedStudios** [comment]
> > It has started to work now, closing issue.
> 
> how did you get it?
> I have the same problem (GTX 1650)

make sure drivers are up to date, i just redownloaded it and it started to work. wish I could be more useful here

**Comment by altafim** [comment]
> make sure drivers are up to date, i just redownloaded it and it started to work. wish I could be more useful here


Could you give me the version number of your driver?
you are using DeepFaceLabCUDA9.2SSE or DeepFaceLabCUDA10.1AVX


Thank you for your help
