### ISSUE TITLE
Error when extract images from video

### ISSUE THREAD

**Issue by new9527** [iperov/DeepFaceLab#305]
![image](https://user-images.githubusercontent.com/15137602/60751966-77f52500-9ff1-11e9-9384-24cb2dd4ad94.png)
system:windows 7
cpu:e3-1230
mem:16g
video card:RTX2070
I have install the newest video card driver, how can I solve this problem?

**Comment by deyu260** [comment]
换win10就能解决了 或者自己装opencv的依赖

**Comment by new9527** [comment]
> 换win10就能解决了 或者自己装opencv的依赖

自己装了下CV2，已解决
