### ISSUE TITLE
Not training with RTX 2080 Ti (Using Windows Pre-build App)

### ISSUE THREAD

**Issue by rodrigo-barraza** [iperov/DeepFaceLab#309]
Windows 10 Pro

![image](https://user-images.githubusercontent.com/1496099/61268224-aab8bf00-a74f-11e9-9a58-04caeb1bd0bf.png)

![image](https://user-images.githubusercontent.com/1496099/61268614-d25c5700-a750-11e9-8a58-14a7f1300845.png)

I have tried all the extraction methods, and training types, and any combinations in-between.
I seem to be getting NaN issues, and the training window will be noise or just black. It seems to run fine with my GTX 1070, but as soon as I try to use the other card, it bugs out on any of the training bat.

`loss_history` seems to be returning an array of `[nan, nan]` when logged out:

![image](https://user-images.githubusercontent.com/1496099/61268700-21a28780-a751-11e9-82b1-6de28b473894.png)

If I attempt to refresh the preview, it crashes instantly. 

SOMETIMES only, `loss_history` seems not to `nan` out, and it allows me to update the preview using the key `p` without crashing, but the update will just be a black preview and will not train period.

**Comment by Auroir** [comment]
See the 2nd dst face in your preview window? It is completely messed up. Check your faces before training, it might just be that.

If it's not that, I'd suggest going back to basics:
Make sure the GPU is stable with Furmark
Make a new project/workspace
Use SAE with all the dimensions at their minimum settings. (The prompt will you a range, use the lowest.)
Redownload DFL
Disable the 1070 in device manager
etc...

If the problem isn't your invalid faces then there's likely something fundamentally wrong in your setup. Use SAE always, there's no reason not to.

**Comment by limiday** [comment]
> See the 2nd dst face in your preview window? It is completely messed up. Check your faces before training, it might just be that.
> 
> If it's not that, I'd suggest going back to basics:
> Make sure the GPU is stable with Furmark
> Make a new project/workspace
> Use SAE with all the dimensions at their minimum settings. (The prompt will you a range, use the lowest.)
> Redownload DFL
> Disable the 1070 in device manager
> etc...
> 
> If the problem isn't your invalid faces then there's likely something fundamentally wrong in your setup. Use SAE always, there's no reason not to.

@Auroir what about you email ,i have some question to ask ,thanks

**Comment by vinniejames** [comment]
My previews look ok, but im unable to train for more than a few minutes. 

Windows 10, Ryzen 3700X
GPU: AMD RX 480 8gb
Radeon Driver 19.8.1

Similar error: 
```
ModelBase.py", line 615, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer
```

```
INFO:plaidml:Analyzing Ops: 692 of 761 operations complete
Traceback (most recent call last):an].8571]
  File "X:\Folder\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\main.py", line 252, in <module>
    arguments.func(arguments)
  File "X:\Folder\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\main.py", line 134, in process_train
    Trainer.main(args, device_args)
  File "X:\Folder\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 283, in main
    lh_img = models.ModelBase.get_loss_history_preview(loss_history_to_show, iter, w, c)
  File "X:\Folder\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\models\ModelBase.py", line 615, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer
[09:57:23][#000645][1579ms][nan][nan]
Error: cannot convert float NaN to integer
Traceback (most recent call last):
  File "X:\Folder\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 144, in trainerThread
    model_save()
  File "X:\Folder\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 59, in model_save
    model.save()
  File "X:\Folder\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\models\ModelBase.py", line 409, in save
    preview_lh = ModelBase.get_loss_history_preview(self.loss_history, self.iter, preview.shape[1], preview.shape[2])
  File "X:\Folder\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\models\ModelBase.py", line 615, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer
Press any key to continue . . .
```

**Comment by rodrigo-barraza** [comment]
> See the 2nd dst face in your preview window? It is completely messed up. Check your faces before training, it might just be that.
> 
> If it's not that, I'd suggest going back to basics:
> Make sure the GPU is stable with Furmark
> Make a new project/workspace
> Use SAE with all the dimensions at their minimum settings. (The prompt will you a range, use the lowest.)
> Redownload DFL
> Disable the 1070 in device manager
> etc...
> 
> If the problem isn't your invalid faces then there's likely something fundamentally wrong in your setup. Use SAE always, there's no reason not to.

Nope, because the exact same setup works with the 1080 I have. It's 2020 now and the 2080TI is still not training with any of the options or configurations when the 1080s have no trouble with it.

**Comment by limiday** [comment]
HI: team

     We are a design company in Shenzhen, China. We want to pay to develop a tool for processing a low resolution face into a super resolution face in photo. The effect is as below. Can  do this or somebody can recommand. 
     Thanks. 
     Such as below:
     



2020-01-07 

limiday 



发件人：Rodrigo Barraza <notifications@github.com>
发送时间：2020-01-02 15:29
主题：Re: [iperov/DeepFaceLab] Not training with RTX 2080 Ti (Using Windows Pre-build App) (#309)
收件人："iperov/DeepFaceLab"<DeepFaceLab@noreply.github.com>
抄送："limiday"<limiday@163.com>,"Comment"<comment@noreply.github.com>

See the 2nd dst face in your preview window? It is completely messed up. Check your faces before training, it might just be that.
If it's not that, I'd suggest going back to basics:
Make sure the GPU is stable with Furmark
Make a new project/workspace
Use SAE with all the dimensions at their minimum settings. (The prompt will you a range, use the lowest.)
Redownload DFL
Disable the 1070 in device manager
etc...
If the problem isn't your invalid faces then there's likely something fundamentally wrong in your setup. Use SAE always, there's no reason not to.
Nope, because the exact same setup works with the 1080 I have. It's 2020 now and the 2080TI is still not training with any of the options or configurations when the 1080s have no trouble with it.
