### ISSUE TITLE
Full Face vs. Half Face

### ISSUE THREAD

**Issue by petergerten** [iperov/DeepFaceLab#31]
## Expected behavior
The main python script says `"Default 'full_face'. Don't change this option, currently all models uses 'full_face'"` so training the H128 model, I expect that the full face is used.

## Actual behavior
It seems only a 'half face' is used. 
README.md says `"DF (5GB+) - @dfaker model. As H128, but fullface model."` which indicates that there is some difference between those two models.

## Steps to reproduce
Train H128 model with default settings.

**Comment by iperov** [comment]
extract_parser.add_argument('--face-type', dest="face_type", choices=['half_face', 'full_face', 'head', 'avatar', 'mark_only'], default='full_face', help="Default 'full_face'. Don't change this option, currently all models uses 'full_face'")    

this is *extract* setting.
All faces extracted in full_face mode.
H128 uses half face of full_face.

**Comment by petergerten** [comment]
Ah - sorry my mistake. Now I understand. Thanks for the quick clarification!
