### ISSUE TITLE
bat files not working

### ISSUE THREAD

**Issue by rajakrishna** [iperov/DeepFaceLab#310]
Python 3.7.1 is already installed in my PC
I clicked on every bat file it is giving me the same error
Windows 10, GTX 1070 8gb
[
![Screenshot_2](https://user-images.githubusercontent.com/48101741/61349542-1ff8c280-a82a-11e9-8a9c-e19051aa9580.jpg)
](url)

**Comment by rodrigo-barraza** [comment]
Bat files are working perfectly fine on Windows. You need to give a lot more details my dude, about your issues.

**Comment by samgozman** [comment]
Same problem  (latest win10 pro, rx580, python etc)
