### ISSUE TITLE
Where are the bat files?

### ISSUE THREAD

**Issue by FlamesoFF** [iperov/DeepFaceLab#315]
![image](https://user-images.githubusercontent.com/5371279/61707126-0f74aa80-ad4a-11e9-923d-c8dd42e8edba.png)

**Comment by jopa79** [comment]
Read the file 
/doc/doc_prebuilt_windows_app.md

**Comment by FlamesoFF** [comment]
> Read the file
> /doc/doc_prebuilt_windows_app.md

![image](https://user-images.githubusercontent.com/5371279/77847171-5bba9900-71bb-11ea-85fa-bc0ec383a794.png)
Show me, please, where it is.

**Comment by iperov** [comment]
@FlamesoFF seriously you are waiting almost a year ?

**Comment by FlamesoFF** [comment]
@iperov I'm not waiting, lol. It's just your notification made me remember this thread.

**Comment by Syker-uk** [comment]
So, does anyone know where they are ? I'm trying to run Xseg on linux but the command is missing (no 5)Xseg_...) I just need to copy the contents of the .bat but I am unable to find it.

**Comment by gras** [comment]
The bat files are not in git.  Download the exe file from mega.nz (link in the README.md), and unzip to get the batch files.
