### ISSUE TITLE
Would this work on Nvidia Jetson Nano Developer Kit

### ISSUE THREAD

**Issue by Huntero32** [iperov/DeepFaceLab#323]
I know this really doesnt belong here, but Would this work on this? I am looking for somewhere to host it. I am new to ai and neural networks and stuff.  https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.com%2Fulk%2Fitm%2F192971902546

**Comment by Auroir** [comment]
It's not going to be fast, but if you're okay with that check these first:

This project can only train using a single GPU. I'm unclear on how they are distributing those CUDA cores, if it's show to the system as a unified device (think GTX1080 8GB) then that's ok, but if it's spread across multiple devices (think K80 24GB) then it's going to be slow on top of slow.

Obviously it has to support all the CUDA device calls. Does CUDA-X contain everything that DFL needs?
