### ISSUE TITLE
Is there similar software to fake voice?

### ISSUE THREAD

**Issue by hasnogaems** [iperov/DeepFaceLab#325]
Subj.

**Comment by Auroir** [comment]
Yes. But first I'm going to ask you to put more effort into your future tickets. Remember you are asking random people for advice, please make an attempt to meet us halfway and make a decent post.

There are indeed a few of these out there, my current favorite is TacoTron2 + Waveglow. In this setup TacoTron2 generates the "faked" mel-spectrograms, and then Waveglow turns those into audio. You have to train both models so it's a bit of an endeavor, but the results are not bad.

See: https://github.com/NVIDIA/tacotron2

Beyond this there are papers describing models that use & create audio along with faces. I do not know of any publicly available implementations of these.

**Comment by BionicPony** [comment]
TacoTron2 appears to only offer text-to-speech capabilities.  Does anyone know of a publicly available resource that would allow someone to take an audio clip and alter the voice to be more like another similar to what DFL does for video?  I'm finding a lot of links on the internet to various software solutions, but they all turn out to be either text-to-speech or not publicly available yet.
