### ISSUE TITLE
Can this run on a HP Notebook with an Intel Pentium N3700 processor?

### ISSUE THREAD

**Issue by Huntero32** [iperov/DeepFaceLab#326]
Can this work on this laptop?
https://www.walmart.com/ip/HP-15-ay070wm-15-6-Realtree-Xtra-Camo-Laptop-Windows-10-Intel-Pentium-N3710-Processor-4GB-Memory-1TB-Hard-Drive/51397785

**Comment by Huntero32** [comment]
Or what vps/vm  would I need?

**Comment by Rektroth** [comment]
It **might** be able to run.

But even if you did manage to get it working, it would be incredibly slow.
