### ISSUE TITLE
Landmakrs get corrupted after holding '.' or ',' in manual fix extractor

### ISSUE THREAD

**Issue by hogfilho** [iperov/DeepFaceLab#33]
## Expected behavior
Advance a lot of frames when hold '.' key

## Actual behavior
Advance a lot frames, but past frames landmarks get corrupted

## Steps to reproduce

Use manual fix option and hold '.' on the keyboard, then go back some frames to see landmark corruption

## Other relevant information
I tried to fix it with mutex, but cannot figure out how to fix it.

**Comment by hogfilho** [comment]
hey @iperov , it has been fixed?
or couldn't you reproduce the issue?

Thank you

**Comment by iperov** [comment]
I dont holding key and so I have no problems.

**Comment by iperov** [comment]
actually you should use either space(skip) or enter(confirm) keys
