### ISSUE TITLE
data_dst and data_src extract faces (any bat) don't work at all

### ISSUE THREAD

**Issue by Ozamatheus** [iperov/DeepFaceLab#335]
## Expected behavior

i'm following Basic workflow video and data_dst and data_src extract faces (any bat) don't work

## Actual behavior

all  images found
0 faces detected

## Steps to reproduce

-i'm using the default videos (iron man and chroma keyer guy)
-i extract images from data_src and data_dst (this bats work normally)
-i run the extract face bats, it found images but not the faces
-if i use the MANUAL.bat it work and save some faces on aligned folder, but it cost a lot of time and lost a lot of faces
-at this point i don't have enough images to proceed

## Other relevant information

my rig:
_MOBO ASUS m5a97 EVO R2.0
fx8320
Gigabyte RX580 8gb
vengeance 8gb 1600mhz 
ssd 120gb
win 10
no overclock, all drivers up to date
python last versions instaled
no firewall interruptions_

data_dst extract faces S3FD best GPU log (same result of others extract face bats):

```
Performing 1st pass...
Running on Advanced Micro Devices, Inc. Ellesmere (OpenCL).
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_ellesmere.0"
  0%|                                                                                         | 0/1538 [00:00<?, ?it/s]INFO:plaidml:Analyzing Ops: 38 of 254 operations complete
INFO:plaidml:Analyzing Ops: 89 of 254 operations complete
INFO:plaidml:Analyzing Ops: 147 of 254 operations complete
INFO:plaidml:Analyzing Ops: 47 of 254 operations complete
INFO:plaidml:Analyzing Ops: 114 of 254 operations complete
INFO:plaidml:Analyzing Ops: 147 of 254 operations complete
100%|##############################################################################| 1538/1538 [05:18<00:00,  4.82it/s]
Performing 2nd pass...
Running on Advanced Micro Devices, Inc. Ellesmere (OpenCL).
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_ellesmere.0"
  0%|2                                                                                | 5/1538 [00:00<00:52, 29.07it/s]INFO:plaidml:Analyzing Ops: 393 of 3771 operations complete
INFO:plaidml:Analyzing Ops: 830 of 3771 operations complete
INFO:plaidml:Analyzing Ops: 1312 of 3771 operations complete
INFO:plaidml:Analyzing Ops: 1783 of 3771 operations complete
INFO:plaidml:Analyzing Ops: 2273 of 3771 operations complete
INFO:plaidml:Analyzing Ops: 2745 of 3771 operations complete
INFO:plaidml:Analyzing Ops: 3228 of 3771 operations complete
INFO:plaidml:Analyzing Ops: 3698 of 3771 operations complete
INFO:plaidml:Analyzing Ops: 30 of 254 operations complete
INFO:plaidml:Analyzing Ops: 63 of 254 operations complete
INFO:plaidml:Analyzing Ops: 131 of 254 operations complete
Advanced Micro Devices, Inc. Ellesmere (OpenCL) doesnt response, terminating it.
  0%|2                                                                              | 5/1538 [01:00<5:10:02, 12.13s/it]
Performing 3rd pass...
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Running on CPU6.
Running on CPU7.
100%|####################################################################################| 5/5 [00:00<00:00,  5.12it/s]
-------------------------
Images found:        1538
Faces detected:      0
-------------------------
Done.
Pressione qualquer tecla para continuar. . .
```

ps: sorry my english XD

**Comment by Akanee31** [comment]
Graphic card ?

**Comment by Ozamatheus** [comment]
Gigabyte RX580 8gb

**Comment by XerneraC** [comment]
I'm having the same issue

**Comment by RonJacobson** [comment]
> I'm having the same issue (same GPU)
> 
> Edit: I've found a solution. You can force the face extraction to run on your CPU instead of your GPU. That fixed it for me, although it takes much longer.

how?
I'm encountering the following error:
"  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help."

installed cuda, cudnn & TF but still nothing..

**Comment by XerneraC** [comment]
> > I'm having the same issue (same GPU)
> > Edit: I've found a solution. You can force the face extraction to run on your CPU instead of your GPU. That fixed it for me, although it takes much longer.
> 
> how?
> I'm encountering the following error:
> " File "imp.py", line 243, in load_module
> File "imp.py", line 343, in load_dynamic
> ImportError: DLL load failed: The specified module could not be found.
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions. Include the entire stack trace
> above this error message when asking for help."

When using your CPU, you're limited in what options you can use. You can for example only use MT Extractor. You can enable CPU extraction by adding the --CPU-ONLY argument (I think. I'm not at my workstation at the moment). I suggest duplicating the MT extraction bat-file, and adding that argument. (I tried with S3FD first, and got an import error, so I thought you might also have tried it with S3FD)

**Comment by Ozamatheus** [comment]
> When using your CPU, you're limited in what options you can use. You can for example only use MT Extractor. You can enable CPU extraction by adding the --CPU-ONLY argument (I think. I'm not at my workstation at the moment). I suggest duplicating the MT extraction bat-file, and adding that argument. (I tried with S3FD first, and got an import error, so I thought you might also have tried it with S3FD)

you can confirm how to do this? i don't want extract 2000+ faces manually, i just extracted 600 and took like 20 minutes :C

**Comment by XerneraC** [comment]
> you can confirm how to do this? i don't want extract 2000+ faces manually, i just extracted 600 and took like 20 minutes :C

I'm not currently at home, so I can't give you exact instructions. I can try though:
In the folder, where all the .bat files are located. Find the step 5 "data_dst extract faces MT.bat" (I'm not sure on the name)(Probably works with the src extraction .bat files as well, but I didn't change them, so I can't guarantee). If you right-click it and choose "edit", you can edit the .bat file. There you will see a list of arguments (they start with 2 dashes). By adding "--CPU-ONLY" to the arguments, you should be able to extract the faces from the images.

I'll probably be able to help you better if you give me the contents of the .bat file.

**Comment by Deimos00** [comment]
same problem

> > Performing 1st pass...
> Running on Advanced Micro Devices, Inc. Ellesmere (OpenCL).
> Using plaidml.keras.backend backend.
> INFO:plaidml:Opening device "opencl_amd_ellesmere.0"
>   0%|                                                                                        | 0/12335 [00:00<?, ?it/s]INFO:plaidml:Analyzing Ops: 38 of 254 operations complete
> INFO:plaidml:Analyzing Ops: 106 of 254 operations complete
> INFO:plaidml:Analyzing Ops: 187 of 254 operations complete
>   4%|##8                                                                           | 444/12335 [01:36<43:06,  4.60it/s]INFO:plaidml:Analyzing Ops: 47 of 254 operations complete
> INFO:plaidml:Analyzing Ops: 122 of 254 operations complete
> INFO:plaidml:Analyzing Ops: 233 of 254 operations complete
> 100%|############################################################################| 12335/12335 [35:04<00:00,  5.86it/s]
> Performing 2nd pass...
> Running on Advanced Micro Devices, Inc. Ellesmere (OpenCL).
> Using plaidml.keras.backend backend.
> INFO:plaidml:Opening device "opencl_amd_ellesmere.0"
>   0%|                                                                                        | 0/12335 [00:00<?, ?it/s]INFO:plaidml:Analyzing Ops: 317 of 3771 operations complete
> INFO:plaidml:Analyzing Ops: 808 of 3771 operations complete
> INFO:plaidml:Analyzing Ops: 1331 of 3771 operations complete
> INFO:plaidml:Analyzing Ops: 1858 of 3771 operations complete
> INFO:plaidml:Analyzing Ops: 2383 of 3771 operations complete
> INFO:plaidml:Analyzing Ops: 2927 of 3771 operations complete
> INFO:plaidml:Analyzing Ops: 3430 of 3771 operations complete
> INFO:plaidml:Analyzing Ops: 38 of 254 operations complete
> INFO:plaidml:Analyzing Ops: 106 of 254 operations complete
> INFO:plaidml:Analyzing Ops: 183 of 254 operations complete
> Advanced Micro Devices, Inc. Ellesmere (OpenCL) doesnt response, terminating it.
> 
> Performing 3rd pass...
> Running on CPU0.
> Running on CPU1.
> Running on CPU2.
> Running on CPU3.
> Running on CPU4.
> Running on CPU5.
> Running on CPU6.
> Running on CPU7.
> 0it [00:00, ?it/s]
> -------------------------
> Images found:        12335
> Faces detected:      0
> -------------------------
> Done.

> 
My config 
AMD FX-8350
RX 570 4g
16 gb ( Kingston 4g 1600 x4)

**Comment by XerneraC** [comment]
To anyone having problems in here.
Attached is a zip file with two .bat files, that will extract the faces from the destination and the source on the CPU. It will take longer, but it might work. Drop those .bat files in the folder with all the other .bat files, and tr them. They might work.
[Extract faces on the CPU.zip](https://github.com/iperov/DeepFaceLab/files/3505759/Extract.faces.on.the.CPU.zip)

**Comment by Deimos00** [comment]
> nyone having problems in here.
> Attached is a zip file with two .bat files, that will extract the faces from the destination and the source on the CPU. It will take longer, but it might work. Drop those .bat files in the folder with all the other .bat files, and tr them. They might work.
> [Extract faces on the CPU.zip](https://github.com/iperov/DeepFaceLab/files/3505759/Extract.faces.on.the.CPU.zip)

thanks, but this is not a complete solution to the problem

**Comment by XerneraC** [comment]
> thanks, but this is not a complete solution to the problem

What problems are you experiencing?

**Comment by Ozamatheus** [comment]
> 
> 
> To anyone having problems in here.
> Attached is a zip file with two .bat files, that will extract the faces from the destination and the source on the CPU. It will take longer, but it might work. Drop those .bat files in the folder with all the other .bat files, and tr them. They might work.
> [Extract faces on the CPU.zip](https://github.com/iperov/DeepFaceLab/files/3505759/Extract.faces.on.the.CPU.zip)

i think training is the longest, so this will be very helpful  until next version probably. thanks a lot

**Comment by lbfs** [comment]
You shouldn't need to install anything if you're using the pre-built binary provided in the releases section.

Additionally, could anyone here do a git bisect and nail down the commit that caused you to stop being able to extract images? It would help more than saying it simply doesn't work.

**Comment by Domynis** [comment]
Hello, I have exact same problem with same specs (CPU and GPU and RAM). RX 580 supports OpenCL 2.0 so it should work. Is there any fix for it to work on GPU and not force on CPU?

**Comment by Hawk321** [comment]
I have the same problem and also a RX 580 8 GB. Any solution ?

![Screenshot_1](https://user-images.githubusercontent.com/26680543/65838684-008c1480-e306-11e9-942d-c8c79f38946a.jpg)

**Comment by Domynis** [comment]
I didn't find fix sadly 🤷‍♂️

**Comment by Ozamatheus** [comment]
now with "DeepFaceLab_OpenCL_SSE_build_10_10_2019" the problem persist. BUT the main bat choose only cpu to extract faces, so i don't have to edit the bat to foce CPU usage. It works but cost like 30 minutes to extract 800 faces. The train is working on GPU normally btw

**Comment by kadrim** [comment]
i just added a pull request for this issue.

From what i can tell the Subprocess waits for a maximum of 60 seconds for a response from the GPU but does not receive it in time. At least that is the problem with my AMD RX 560X.
After increasing that timeout to 600 seconds (10 minutes) i can successfully extract the faces.

If you want to apply my patch manually just open then file

**DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\mainscripts\Extractor.py** and change the line **305** from

`no_response_time_sec = 60 if not self.manual and not DEBUG else 999999`

to

`no_response_time_sec = 60 if not self.manual and not DEBUG else 999999`

afterwards, run the extract batch files again.

**Comment by CheungYuHui** [comment]
You guys were all using AMD graph card, even the same gpu. But I was using gtx 1050ti, so why the same problem appeared, images founded, no faces detected.

**Comment by kadrim** [comment]
@CheungYuHui and did you try the fix i proposed? does anything change with that?

**Comment by CheungYuHui** [comment]
> @CheungYuHui and did you try the fix i proposed? does anything change with that?

Still not working. But anyway, thanks.

**Comment by rubi14** [comment]
![Uploading IMG_20200927_202031.jpg…]()
Hello, tell me how to fix the error, solve the problem

**Comment by rubi14** [comment]
![IMG_20200914_150732](https://user-images.githubusercontent.com/72070891/94541466-d307dd00-0271-11eb-8862-ceb0637f463f.jpg)

**Comment by rubi14** [comment]
Hello, tell me how to fix the error, solve the problem

**Comment by mrusklon** [comment]
not work for me too, i have RTX3080

**Comment by 1070148808** [comment]
Instructions for updating:
Colocations handled automatically by placer.
100%|#####################################################################################################################| 166/166 [00:00<00:00, 185.09it/s]
Performing 3rd pass...
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Running on CPU6.
Running on CPU7.
100%|#####################################################################################################################| 166/166 [00:00<00:00, 221.90it/s]
-------------------------
Images found:        166
Faces detected:      0
-------------------------
Done.



Excuse me, I am using AMD® Renoir graphics card and AMD® Ryzen 7 4800u with radeon graphics cpu. A similar problem occurs. I don’t know how to solve it, please help


thanks a lot
