### ISSUE TITLE
How to train by using FP16??

### ISSUE THREAD

**Issue by dkny11354** [iperov/DeepFaceLab#341]
How to train SAE by using FP16? or adjust code to accomplish?

For now, RTX 2080 and 1080ti has same iteration time.  I think It's still using FP32.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: 6) train SAE
- **Operating system and version:** Windows
- **Python version:** 3.7.0

**Comment by iperov** [comment]
FP16 is not enough precision for deepfake autoencoder

**Comment by xstrauss** [comment]
so no way to work with fp16? It immediately got NaN NaN error.

**Comment by iperov** [comment]
nope
