### ISSUE TITLE
About the Precision

### ISSUE THREAD

**Issue by dkny11354** [iperov/DeepFaceLab#344]
Thanks for reply. I saw you mentioned Precision.
Is it very certain thing that's impossible to using half precision to train? or any change to use FP16 after?

According to this, I might replace RTX 2080 to 1080TI.  Actually, I don’t really want to take new RTX card for the old GTX card, but I still have to cause rtx 2080's performance is not as good as expected and Insufficient memory. So I need to make a sure. 

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**:  train SAE
- **Operating system and version:** Windows
- **Python version:** 3.7.0

**Comment by Auroir** [comment]
What are your other specs and model settings?

**Comment by dkny11354** [comment]
Mine is rtx 2080
i5 9400f
ram 2400 8g
b360 auros gaming 3 wifi
ssd 1TB

maximum batch size I can got:
== Model name: SAE
==
== Current iteration: 190723
==
== Model options:
== |== autobackup : True
== |== write_preview_history : True
== |== batch_size : 10
== |== sort_by_yaw : False
== |== random_flip : True
== |== resolution : 128
== |== face_type : f
== |== learn_mask : True
== |== optimizer_mode : 1
== |== archi : df
== |== ae_dims : 512
== |== e_ch_dims : 42
== |== d_ch_dims : 21
== |== multiscale_decoder : True
== |== ca_weights : True
== |== pixel_loss : True
== |== face_style_power : 0.0
== |== bg_style_power : 0.0
== |== apply_random_ct : False
== |== clipgrad : True
== Running on:
== |== [0 : GeForce RTX 2080]
=========================
Starting. Press "Enter" to stop training and save model.
[18:39:07][#191221][0824ms][0.0340][0.1864]

**Comment by Auroir** [comment]
And your 1080TI also trains that model at 824ms per iteration?

In any case a patch regarding 20xx cards was committed 12 days ago, how new is code you're running? Maybe it will help. https://github.com/iperov/DeepFaceLab/pull/322

**Comment by dkny11354** [comment]
I don't have 1080TI yet, but will buy a 2nd hand 1080ti if 2080 can't use in FP16.  I asked someone to train by same settings with 1080ti, and got the same iteration time. 

I checked the nvidia experience update last weekend(8/10~8/11) when I replace 2080 to 2070 which is from my friend.  It's the latest.

**Comment by Auroir** [comment]
Something seems wrong here, but you might be right since I can't test it. A 1080TI 8GB and a 2080 8GB should support the same batch sizes. Either the VRAM is there for the bits to fill or it's not, and 8GB is 8GB. The 2080's ram and gpu are better so it should process that data faster than the 1080, but they both have the memory to hold the batches. That's not a 1080TI 11GB, right? Because that would explain most of this.

In any case at least wait until a new version with the patch I referenced comes out and try it again then. The patch is in reference to memory usage, so there's hope.

**Comment by dkny11354** [comment]
1080ti has 11GB, not 8GB. That's why 1080ti 11GB can do more batch size. 

It's a good news about next patch which might improve memory usage.

**Comment by Auroir** [comment]
If they have almost the same performance in mode 1 then yes I guess the 1080TI 11GB would outperform it for this specific project. You might eventually regret not having tensor cores though, the 2080 is more future-proof.

**Comment by dkny11354** [comment]
I have heard about Mixed Precision training called Apex from nvidia these days. Does it come in handy?
