### ISSUE TITLE
Python crash at 4) data_src extract faces MT all GPU

### ISSUE THREAD

**Issue by jozisatler** [iperov/DeepFaceLab#345]
I'm currently working on DeepFaceLabOpenCLSSE and I'can past fourth step. When I run batch file called 4) data_src extract faces MT all GPU always this happens:

![crash](https://user-images.githubusercontent.com/54095559/62999608-403e9000-be6f-11e9-8eed-bde82b413332.png)

And then python crash popup shows. I even tried to run other batch files, same happens. My computer info:

Processor Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
 
Video Card AMD Radeon (TM) R7 M360
 
Video Card #2 Intel(R) HD Graphics 520
 
RAM 6.0 GB
 
Operating System Windows 10

**Comment by lbfs** [comment]
When you mean other batch files, do you mean other extract batch scripts? Can you please list some examples.

Additionally, I would try doing using the CPU for extraction, it could be that your device configuration does not work with plaidml, resulting in this issue. Secondly, you seem to have a second GPU present in your system, have you tried using it for extraction instead?

**Comment by Huntero32** [comment]
The same thing happens to me how would I use cpu?

**Comment by offface** [comment]
Follow this video for intel/radeo graphic cards, you have to make sure you download the exact version he downloads:

https://www.youtube.com/watch?v=jqq6-VGhfFc
