### ISSUE TITLE
Model information

### ISSUE THREAD

**Issue by krs1972** [iperov/DeepFaceLab#346]
Have been running some tests with DeepFaceLab (really impressive stuff) and as a VFX compositor and was wondering if there anything that can be extracted from the model folder to help with things such as relighting and mask edges.     Having no real idea of how the training produces the new images (is it a 3d model that it uses internally or a 2d one?) its hard to know what is stored and where.     I have researched the deep learning itself but it still seems like a bit of a black box.

If anyone has any clues/info it would be greatly appreciated.

**Comment by Auroir** [comment]
It's all 2D training, images are 256x256x3 arrays, 1 plane per BGR channel. Masks are 256x256x1, black & white. I think there's some 3D translation math done with facial landmarks for pitch/yaw estimation, but nothing about this is really 3D.

Stylized Adversarial AutoEncoder for Image Generation
https://www.docdroid.net/pwc97xN/31232663123450.pdf

Extracting useful info from the model folder (I.E. the *.h5 model data) is not realistic. However extracting the info from your aligned faces is very easy, all the data is embedded into the face files themselves. PNG faces have it in a custom header & JPG faces have it appended to the end of the file, both are in pickle format. If you're just looking for info on the src/dst faces that's where to look. 

That being said, with a VFX background I'd imagine that just using the "Export png with alpha channel" option when converting faces will give you enough to work with. Overlaying your faked faces on the frames with more advanced software/techniques can do wonders. Even just a simple deshake + sharpen of the faces can help a bunch.

**Getting embedded data from an aligned face in colab**
```
import os
import numpy as np

#Import DFL functions
%cd /content/DeepFaceLab/
from utils.DFLPNG import DFLPNG
%cd /content/
print('Functions imported...\n\n')

dst_face_path = '/content/workspace/data_dst/aligned'
dst_face_files = [f'{dst_face_path}/{x}' for x in os.listdir(dst_face_path)]
dst_face = np.random.choice(dst_face_files)
dst_dfl_im = DFLPNG.load(dst_face)
dst_dfl_embedded = dst_dfl_im.getDFLDictData()
print(f'Loaded dst face {dst_face.split("/")[-1]}! Showing embedded data.\n' )

for k in dst_dfl_embedded.keys():
  print(f'{k: ^30}\n{"-"*30}\n{dst_dfl_embedded[k]}\n')
```
```
Functions imported...


Loaded dst face 01328_0.png! Showing embedded data.

          face_type           
------------------------------
full_face

          landmarks           
------------------------------
[[33.327935140258774, 90.06378632506372], [36.65708006861337, 114.25916535169475], [39.98622499696819, 138.45454437832572], ...

           ie_polys           
------------------------------
None

       source_filename        
------------------------------
01328.png

         source_rect          
------------------------------
[766  80 928 341]

       source_landmarks       
------------------------------
[[764.0416959197653, 166.65048692525465], [763.5474817848411, 189.35225148801473], [763.0532676499171, 212.05401605077478], ...

      image_to_face_mat       
------------------------------
[[ 1.06209704e+00  1.69768667e-01 -8.06450520e+02]
 [-1.69768667e-01  1.06209704e+00  4.27751373e+01]]

         fanseg_mask          
------------------------------
None

        pitch_yaw_roll        
------------------------------
None
```
Note that I trimmed the landmark output, there's 68 of them, and this is an example from a google colab version that uses PNG faces. Use DFLJPG if you want to look at JPG faces, the functions are identical.

**Comment by krs1972** [comment]
Thanks so much for the response, very detailed.

Just browsing the data, the landmarks are the lines (pts) that get drawn on in the aligned_debug images so I am writing a parser at the moment that will allow me to build animated masks based on the point information for each frame for the nose, face, eyes and mouth.  It will also provide me a central tracking point to follow the face which may help with adding custom masks into the mix.

May also be able to generate motion vectors to help manage motion blur as well.   Will report back if I accomplish anything useful.

**Comment by iperov** [comment]
@krs1972 
hi
have you the code to manage motion blur?
we have landmarks across frames, so we can calculate delta offset of face for every frame.
and apply motion blur?
I need the code.

**Comment by iperov** [comment]
@krs1972 nevermind, I implemented motion blur in the next release

**Comment by krs1972** [comment]
Sorry for the slow response.   I was using compositing software (Fusion) that implements optical flow vector analysis over the Deepfake output and generates the motion blur from there.   I am guessing to generate motion blur you interpolated a number of frames before and after the seed frame (using the prev and next frames) and blended them together?

**Comment by iperov** [comment]
```
for i in io.progress_bar_generator( range(len(frames)) , "Computing motion vectors"):
                    fi_prev = frames[max(0, i-1)].frame_info
                    fi      = frames[i].frame_info
                    fi_next = frames[min(i+1, frames_len-1)].frame_info
                    if len(fi_prev.landmarks_list) == 0 or \
                       len(fi.landmarks_list) == 0 or \
                       len(fi_next.landmarks_list) == 0:
                            continue

                    mat_prev = LandmarksProcessor.get_transform_mat ( fi_prev.landmarks_list[0], s, face_type=FaceType.FULL)
                    mat      = LandmarksProcessor.get_transform_mat ( fi.landmarks_list[0]     , s, face_type=FaceType.FULL)
                    mat_next = LandmarksProcessor.get_transform_mat ( fi_next.landmarks_list[0], s, face_type=FaceType.FULL)

                    pts_prev = LandmarksProcessor.transform_points (local_pts, mat_prev, True)
                    pts      = LandmarksProcessor.transform_points (local_pts, mat, True)
                    pts_next = LandmarksProcessor.transform_points (local_pts, mat_next, True)

                    prev_vector = pts[0]-pts_prev[0]
                    next_vector = pts_next[0]-pts[0]

                    motion_vector = pts_next[0] - pts_prev[0]
                    fi.motion_power = npla.norm(motion_vector)

                    motion_vector = motion_vector / fi.motion_power if fi.motion_power != 0 else np.array([0,0],dtype=np.float32)

                    fi.motion_deg = -math.atan2(motion_vector[1],motion_vector[0])*180 / math.pi
```

**Comment by TMBdf** [comment]
> Thanks so much for the response, very detailed.
> 
> Just browsing the data, the landmarks are the lines (pts) that get drawn on in the aligned_debug images so I am writing a parser at the moment that will allow me to build animated masks based on the point information for each frame for the nose, face, eyes and mouth. It will also provide me a central tracking point to follow the face which may help with adding custom masks into the mix.
> 
> May also be able to generate motion vectors to help manage motion blur as well. Will report back if I accomplish anything useful.

I know I'm kinda digging oout old stuff by replying here and I'm not sure you'll read this but have you managed to ever get this thing to work (extract info from aligments and convert it into individual masks for each part of face like nose, eyes, mouth, eyebrows)?
