### ISSUE TITLE
Why mask in decoder?

### ISSUE THREAD

**Issue by SalahBoudj** [iperov/DeepFaceLab#347]
Hello I have a question about models in DFL, more precisely about the mask in decoder. I don't understand why a mask is created in decoder whereas there is already a mask of what we want as input of the model... Why a second loss (MAE or MSE) is needed for the mask ? Why we don't use only DSSIM masked loss for training?

Thanks a lot!

**Comment by Auroir** [comment]
This is a common technique. You'll notice while training that the face itself becomes clear faster than then area around it, that is on purpose. 

Same kinda of idea that is explained here:
https://www.lyrn.ai/2019/01/07/instagan-instance-aware-image-to-image-translation/
