### ISSUE TITLE
Model training stagnates and other error messages

### ISSUE THREAD

**Issue by Paul-0** [iperov/DeepFaceLab#35]
## Openfaceswap model training issues

LowMem training, batch size 64, ran first 23 hours then paused, and ran 8 more hours. 
Still running at this time.

****
### Expected behavior

Im trynna train a model that will be used by the openfaceswap program to convert faces from a video. The **loss value should decrease over training time**, which means a better model and a better quality faceswap.

### Actual behavior

The **loss value for both faces stagnates**, still after **23 + 8 hours of training**, and iv'e got some error messages about **keepdims** that is deprecated and about memory that could be better used but i dont know how to do that.

### Steps to reproduce

For the memory, tried to use the Original model training with batch size, 64, 32, 16, 8, 4, 2 but i got OOMed every time: LowMem model training works fine with batch size 64. **I dont know whats keepdims is at all**, and for the loss value cant do anything except waiting.

****
### Other relevant information

- Windows 10, 64bits

**Specs :** 
- GPU Nvidia Geforce GTX 1050 ti 4go
- 16go ram (**never gets over 7go/16go usage dont know why, maybe this influences the model training!!**)
- Intel 7500 smth CPU

**Useful images + log**
[log training model faceswap lowmem.txt](https://github.com/iperov/DeepFaceLab/files/2503646/log.training.model.faceswap.lowmem.txt)
![openfaceswap model train settings](https://user-images.githubusercontent.com/25486522/47323588-bf52a580-d65c-11e8-82a2-504a5b4fb3e9.png)
![memory usage](https://user-images.githubusercontent.com/25486522/47323593-c24d9600-d65c-11e8-848c-c062b2b5dbf9.png)
![gpu usage](https://user-images.githubusercontent.com/25486522/47323594-c37ec300-d65c-11e8-8a2d-8a91eca53490.png)
****
Sorry for the french text in the screenshots, but i think it's understandable. If help needed, i can translate it.

**Comment by Paul-0** [comment]
FYI, im really new to all this programming, so any help is appreciated even if it seems obvious to you.

**Comment by iperov** [comment]
this is DeepFaceLab repo, not Openfaceswap .

**Comment by Paul-0** [comment]
But can’t u help me? I’m sure u understand something there... and also the yet closed deepfakeclub website systematically redirects to ur repo
