### ISSUE TITLE
[REQUEST] Preview GUI for Converter

### ISSUE THREAD

**Issue by coinsbarboss** [iperov/DeepFaceLab#350]
Hi,

I noticed that the original faceswap project has a **PREVIEW MODE tool** 

which allows you to **configure Converter Settings** and see the **results instantly in a live session**.

This helps a lot when you need to play with 100+ configurations.

Is it possible to add such a tool to this project?

Regards

**Comment by gessyoo** [comment]
@coinsbarboss, I've found that faceswap has several useful features that DeepFaceLab lacks, including live preview, which is why I abandoned DFL in favor of faceswap.  There is an active support community, too.

**Comment by coinsbarboss** [comment]
> @coinsbarboss, I've found that faceswap has several useful features that DeepFaceLab lacks, including live preview, which is why I abandoned DFL in favor of faceswap. There is an active support community, too.

Nevertheless, the DFL quality and training results are much better than faceswap.  "Imho"

**Comment by Auroir** [comment]
This is possible, the debug converter already uses most of what this would need. But for right now just move all but the first X frame images into another folder, this way you only convert a subset of faces. Once it looks good you can move them back and do all of them.

**Comment by coinsbarboss** [comment]
> This is possible, the debug converter already uses most of what this would need. But for right now just move all but the first X frame images into another folder, this way you only convert a subset of faces. Once it looks good you can move them back and do all of them.

Debug converter require to input all configirations before seeing the rrsult. Im talking about changing every piece of config without restarting the script and seeing the result change immediately 
after each step...

**Comment by Auroir** [comment]
I understand the concept. I'm not saying it exists, which is why I offered a workaround.
