### ISSUE TITLE
2) extract images from video data_src.bat errors. 

### ISSUE THREAD

**Issue by 89deuce** [iperov/DeepFaceLab#352]
These are the errors I'm getting. What am I missing here?
Traceback (most recent call last):
  File "D:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\main.py", line 252, in <module>
    arguments.func(arguments)
  File "D:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\main.py", line 180, in process_videoed_extract_video
    VideoEd.extract_video (arguments.input_file, arguments.output_dir, arguments.output_ext, arguments.fps)
  File "D:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\VideoEd.py", line 17, in extract_video
    input_file_path = Path_utils.get_first_file_by_stem (input_file_path.parent, input_file_path.stem)
  File "D:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\utils\Path_utils.py", line 64, in get_first_file_by_stem
    for x in sorted(list(scandir(str(dir_path)))):
TypeError: '<' not supported between instances of 'nt.DirEntry' and 'nt.DirEntry'

**Comment by Auroir** [comment]
This one is on me, `sorted()` is using '<' between the objects to compare them, which isn't supported for `nt.DirEntry`.

For right now you can change line 64 in `_internal\DeepFaceLab\utils\Path_utils.py` from:
```
for x in sorted(list(scandir(str(dir_path)))):
```
to 
```
for x in list(scandir(str(dir_path))):
```

I'll fix this in a bit, thanks for the heads up!

**Comment by Auroir** [comment]
Patch submitted. Until it's pulled you can either change the line by hand (above) or you can download the patched file and swap it out:
https://github.com/Auroir/DeepFaceLab/blob/patch-3/utils/Path_utils.py

Apologies for the hiccup.

**Comment by 89deuce** [comment]
You're the man. I'll manually make the change no problem. Much appreciated!

**Comment by 89deuce** [comment]
I should add this fixed this issue 100% I'm face swapping like a champ now.
