### ISSUE TITLE
Error When Converting To Codec 

### ISSUE THREAD

**Issue by LifeOfthesea** [iperov/DeepFaceLab#354]
Hello,

I've successfully converted a fake before but this time it is giving me slight trouble. I've seen a few issues posted that sound related but have never found a solution. Could it be a dataset issue?

I can convert seamlessly as long as I do not export with png's that contain alpha. Otherwise I get this error when converting raw as well. 

Error code: "[00:29<00:39, 26.00it/s]Error: input depth must be evenly divisible by filter depth: 4 vs 3
         [[{{node model_1/conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/conv2d_1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
         [[{{node model_2/conv2d_13/Sigmoid/_295}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_222_model_2/conv2d_13/Sigmoid", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Traceback (most recent call last):
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\mainscripts\Converter.py", line 316, in main
    debug                  = args.get('debug',False)
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 258, in run
    self.on_tick()
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\mainscripts\Converter.py", line 216, in on_tick
    self.converter.on_host_tick()
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\converters\ConverterMasked.py", line 120, in on_host_tick
    self.predictor_func_host.obj.process_messages()
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\joblib\SubprocessFunctionCaller.py", line 30, in process_messages
    result = self.func ( *obj['args'], **obj['kwargs'] )
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\Model_H64\Model.py", line 124, in predictor_func
    x, mx = self.src_view ( [ face[np.newaxis,...] ] )
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: input depth must be evenly divisible by filter depth: 4 vs 3
         [[{{node model_1/conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/conv2d_1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
         [[{{node model_2/conv2d_13/Sigmoid/_295}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_222_model_2/conv2d_13/Sigmoid", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]"

I appreciate it,
Have a nice day.

**Comment by LifeOfthesea** [comment]
Sorry, meant to add that I am running the Windows Prebuilt version "DeepFaceLabCUDA10.1AVX" But I also have the same error with "DeepFaceLabCUDA9.2SSE". 

Running windows 10 with a 1070 and 7700k.

**Comment by Auroir** [comment]
One of your frames has more than one aligned face for it. Are you trying to swap more than one face at once?

If yes, then you simply cannot use alpha right now, it's not going to work. Instead convert one at a time and merge both alpha images onto your dst frame.
If no, then you need to check your dst face set again.

**Comment by LifeOfthesea** [comment]
That caught my issue, thank you. Found out scrolling through my debug more carefully that there are images which have picked up something else as a second face, after deleting those it has successfully finished.

Thank you for the help.

**Comment by Auroir** [comment]
Fantastic, glad to help. Please close when convenient.

**Comment by frrr** [comment]
Hello,
sorry in advance for my "newbieness".
I have same problem and yes that happens when sometime a second face is wrongly picked up (even if in my video I have just one actor).
How can I delete that other second buggy mask in order to let the converter go on?
Thank you.
