### ISSUE TITLE
TraceBack issue?

### ISSUE THREAD

**Issue by peninu007** [iperov/DeepFaceLab#355]
Hello!

First time trying this software so I apologise in advance if this issue is easily fixable however I haven't found an answer from issues that others presented or in the manual.

After clearing workspace and replacing the data_src/data_dst videos, I keep getting this issue when I run 2) extract image from video data_src (ATTACHED)

![c902d0b552a0c4cf71dacfdb40af1376](https://user-images.githubusercontent.com/54179200/63230393-3ec4ed00-c20c-11e9-9a4a-d4f55e62fd03.png)

Thank you so much for helping!

Other information about specs that might help:
NVIDIA GeForce GTX760 - 6038MB
DirectX 11
DeepFaceLabCUDA10.1SSE_build08_16_2019

**Comment by Auroir** [comment]
This has been patched in the repo but it looks like the prebuilt pack isn't updated quite yet.

Grab the patched file from here:
https://github.com/iperov/DeepFaceLab/blob/master/utils/Path_utils.py

Put it into `_internal/DeepFaceLab/utils/`, overwriting the existing file.

**Comment by lbfs** [comment]
This was fixed in the most recent commit, you can clone the repository and replace the DeepFaceLab folder in _internal to have the fixes.

**Comment by lbfs** [comment]
Shouldn't we be sorting by x.name and by x.is_file()? Rather than just sorting by the name?

The fix would be simple. Change the affected line to `for x in sorted(list(scandir(str(dir_path))), key=lambda x: x.name and x.is_file()):` and removing the unneeded if thereafter.

**Comment by peninu007** [comment]
Thank you so much!

Worked like a charm :)
