### ISSUE TITLE
Using MT and SF at once

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#357]
I`m searching for a faces with MT amd SF script, I made a bat file with extraction and searching files with both of methods (SF to aligned_sf and MT to aligned_mt).

> @echo off
> call _internal\setenv.bat
> 
> "%PYTHON_EXECUTABLE%" "%DFL_ROOT%\main.py" videoed extract-video ^
>     --input-file "%WORKSPACE%\data_dst.*" ^
>     --output-dir "%WORKSPACE%\data_dst" ^
>     --fps 0
> 
> call _internal\setenv.bat
> 
> "%PYTHON_EXECUTABLE%" "%DFL_ROOT%\main.py" extract ^
>     --input-dir "%WORKSPACE%\data_dst" ^
>     --output-dir "%WORKSPACE%\data_dst\aligned_sf" ^
>     --detector s3fd ^
>     --debug-dir "%WORKSPACE%\data_dst\aligned_debug_sf"
> 
> call _internal\setenv.bat
> 
> "%PYTHON_EXECUTABLE%" "%DFL_ROOT%\main.py" extract ^
>     --input-dir "%WORKSPACE%\data_dst" ^
>     --output-dir "%WORKSPACE%\data_dst\aligned_mt" ^
>     --detector mt ^
>     --debug-dir "%WORKSPACE%\data_dst\aligned_debug_mt"

All works well, but I can`t make works:
**5.3.other) data_dst sort by original filename.bat**

> @echo off
> call _internal\setenv.bat
> 
> "%PYTHON_EXECUTABLE%" "%DFL_ROOT%\main.py" sort ^
>     --input-dir "%WORKSPACE%\data_dst\aligned_mt" ^
>     --by origname
> 
> call _internal\setenv.bat
> 
> "%PYTHON_EXECUTABLE%" "%DFL_ROOT%\main.py" sort ^
>     --input-dir "%WORKSPACE%\data_dst\aligned_sf" ^
>     --by origname
> pause  

Where is the data stored about orignial filenames ?
Merging this two directories after face detection is very helpfull, please help.

**Comment by Auroir** [comment]
Is there an error message it gives you?

I wrote up how to view the embedded data in this issue, #356. Is 'source_filename' is what you are looking for?

But most importantly, why are you doing this at all? Are you training against duplicate faces then removing the extras before converting? If you give them their original filenames they are going to have duplicate names when you merge the folders, so wouldn't you lose half of the faces anyway?

**Comment by wasyleque** [comment]
My fault, sorry, i`ve sorted it, not recovered names. It was too late in night, so error occured, I corrected it to recover filenames:
**"%PYTHON_EXECUTABLE%" "%DFL_ROOT%\main.py" util ^
    --input-dir "%WORKSPACE%\data_dst\aligned_mt" ^
    --recover-original-aligned-filename 
"%PYTHON_EXECUTABLE%" "%DFL_ROOT%\main.py" util ^
    --input-dir "%WORKSPACE%\data_dst\aligned_sf" ^
    --recover-original-aligned-filename** 

And Yes I`m not copying duplicated ones, S3FD is great, but MT gives me some extra faces also which s3FD did not find.
Thanks, subject is closed
