### ISSUE TITLE
latest Build 9.2 CUDA does not work

### ISSUE THREAD

**Issue by ichibansenshi** [iperov/DeepFaceLab#358]
when i start the latest Build 9.2SSE 08_16_2019 it does not start. the terminal shows some python errors.

with Build 06_20_2019 everything works fine

**Comment by lbfs** [comment]
Please clone the repository and replace the _internal/DeepFaceLab folder with the cloned repository. There is a bug in that release that prevents the application from working correctly that was recently solved.

**Comment by Auroir** [comment]
Until the main packages are updated you can use these fixed repacks. 
http://pc.cd/K7litalK
