### ISSUE TITLE
DeepfakeLab.  Crash    2) extract images from video data_src

### ISSUE THREAD

**Issue by mrsnapers** [iperov/DeepFaceLab#359]
downloaded from rutreker.org. in the “workspace” folder are the video “Tony Stark” and “Just do it”.
I run the file “2) extract images from video 'and nothing happens.
when you press any button, the console closes
Sorry my English
![br-LGP9dSbc](https://user-images.githubusercontent.com/54273693/63265584-a0ca3480-c296-11e9-99e6-23f3904c967f.jpg)

**Comment by Deimos00** [comment]
download older version ,this bug appear in new version DeepFaceLabOpenCLSSE_build_08_16_2019

**Comment by mrsnapers** [comment]
can I have a link please?

**Comment by lbfs** [comment]
You do not need an older version. Simply download a copy of the zip from the repository using the clone button, extract it, and replace the DeepFaceLab folder in _internal/DeepFaceLab with the one you downloaded.

**Comment by lbfs** [comment]
@iperov Do you think you can pull this one from the Google Drive / Mega and replace it with a newer build, so these issues do not keep flooding?

**Comment by iperov** [comment]
new windows build has been uploaded

**Comment by mrsnapers** [comment]
@ibfs thanks for the answer. but the problem is not resolved. recorded a video of my actions.
sent by email
