### ISSUE TITLE
2DFAN-4.h5

### ISSUE THREAD

**Issue by xunkaixin** [iperov/DeepFaceLab#36]
Hi
   thanks for your work!
   how can i get 2DFAN-4.h5 file?

**Comment by iperov** [comment]
https://github.com/iperov/DeepFaceLab/blob/master/facelib/2DFAN-4.h5

**Comment by xunkaixin** [comment]
i see it, but i want to train my own file. the source file may be come from 2DFAN-4.pth.tar, i just want to know how to convert to .h5.  Thank you

**Comment by hushanxue** [comment]
> Hi
> thanks for your work!
> how can i get 2DFAN-4.h5 file?

how do you train your own file?  use mtnn ?
