### ISSUE TITLE
Do i have ti manually train it?

### ISSUE THREAD

**Issue by Huntero32** [iperov/DeepFaceLab#362]
Do I have to sit here for hours and manually click save or next? Or does it train automatically?
![Uploading 20190821_150324.jpg…]()

**Comment by lbfs** [comment]
You need to be more clear and upload a photo that is not broken. Manual intervention is not required during training, only for alignment if you are using the manual extractor.

**Comment by Huntero32** [comment]
Okay I saw the training preview and I didn't know if I had to do anything. Thanks.

**Comment by lbfs** [comment]
If you can close the issue as solved, that would be appreciated.
