### ISSUE TITLE
Wide face - part of dst person's eyes still visible.

### ISSUE THREAD

**Issue by CodingToBeWithHer** [iperov/DeepFaceLab#363]
![yodaissue](https://user-images.githubusercontent.com/14866119/63469839-78476380-c46b-11e9-9b81-2f1f178e90fe.png)
## Expected behavior

I am trying to deepfake a wide face (especially wide eyes - Yoda) and I would expect to be able to cover the dst face in full with the new src face

## Actual behavior

I can't find the way to cover dst eyes in full with the src face.
I have already increased face by 15% and tried multiple other parameter combinations but it's not enough. Increasing more causes mouth to be too large - go beyond face. Ideally I would need to just increase the size of the top part while not causing at the same time the bottom to be increased.
Or somehow remove/blur the Yoda's (dst) remaining eyes. The only way I can think of right now, is going manually and try to blur manually each photo which is not probably the way to go...

## Steps to reproduce

I have attached the photo that shows visually the problem. One can reproduce issue by taking any yoda face and trying to deepfake it.

## Other relevant information
I'm looking for a suggestion from experienced person whether it's possible to deal with this problem in any way (parameter, procedure etc.)

**Comment by lbfs** [comment]
This is not an issue with the bugs or code. Please ask for help elsewhere.
