### ISSUE TITLE
Some  merged images are reversed

### ISSUE THREAD

**Issue by dream80** [iperov/DeepFaceLab#364]
![20190822073035](https://user-images.githubusercontent.com/20279174/63475283-cdf12f80-c4ae-11e9-87ca-9460b0a0c8c7.jpg)

version ：DeepFaceLabCUDA10.1AVX_build_08_19_2019

Some  **merged** images are reversed

**Comment by mrbitfakes** [comment]
Hey i have this problem did you find a solution?

**Comment by blanuk** [comment]
have the same problem. search them manualy and invers them an copy them back, buts its a little pain...
