### ISSUE TITLE
What vm/vps should I get?

### ISSUE THREAD

**Issue by Huntero32** [iperov/DeepFaceLab#366]
The Title says it all. I am looking for a vps that I can run this on to train. What would you guys reccomend??

**Comment by lbfs** [comment]
Not really the right place to ask this, but you can use the Google Colab fork. You can also try using Paperspace as they offer hardware that seems to be compatible with machine learning. Anyways, that is all. Self-hosting the project is generally the better idea, currently.

**Comment by bbbooo313** [comment]
oubocp.com  大佬换个友链吗？
联系QQ：1297532431
