### ISSUE TITLE
AVX or SSE?

### ISSUE THREAD

**Issue by coinsbarboss** [iperov/DeepFaceLab#367]
What is the actual difference between these 2 prebuilt windows apps?
I have Tesla V100 and Tesla P100 machines.
Please advise

**Comment by dream80** [comment]
AVX

**Comment by lbfs** [comment]
AVX is supported on newer processors and is the successor to SSE, but AVX isn't supported everywhere so it makes sense to have separate builds. 

https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions#Later_versions
https://en.wikipedia.org/wiki/Advanced_Vector_Extensions
