### ISSUE TITLE
Converter skips the last frame. Last frame in aligned folder is not converted.

### ISSUE THREAD

**Issue by codedealer** [iperov/DeepFaceLab#373]
These two issues are probably related as they are similar in nature.
## Expected behavior

All frames from data_dst folder are merged, all faces in data_dst/aligned are converted. This is true at least for prebuilt 06_20_2019 version.

## Actual behavior

1. Last frame in data_dst is skipped, e.g. if data_dst contains 100 frames, merged will have only first 99 after conversion.
2. Last face in data_dst/aligned is skipped, e.g. if aligned folder contains only first 50 frames out of 100 (skipping the last 50), merged folder will have only first 49 converted with others skipped.

## Other relevant information
Prebuilt 08_24_2019 version

**Comment by iperov** [comment]
I cannot reproduce it. All fine at me.

**Comment by codedealer** [comment]
Okay, I should've counted the frames in folders rather than looking at the filenames.

So what really happens is when frames are extracted from a dst video it starts with 00001 but when the new converter makes images in merged folder it now starts with 00000 causing confusion.

**Comment by iperov** [comment]
:D

**Comment by codedealer** [comment]
I'm closing this as filenames in merged were fixed by 9f58d160a029d58ef533e94f12316e1e731c2246
