### ISSUE TITLE
How to debug data_dst faster?

### ISSUE THREAD

**Issue by dkny11354** [iperov/DeepFaceLab#375]
After extract faces in data_src, I can use 4.2.2) data_src sort by similar histogram to find the different faces which are row together and delete them. Its really useful and save lots of time.

However, when I use 5.2) data_dst sort by similar histogram, the number of arrangement will change. After the change, I don’t know the previous number of the picture. I can’t delete it in aligned_debug of data_dst and then use 5) data_dst extract faces MANUAL RE-EXTRACT DELETED RESULTS DEBUG.

Is there a better way to debug data_dst faster?

**Comment by iperov** [comment]
5.3.other) data_dst util recover original filename.bat

**Comment by dkny11354** [comment]
Thanks for reply.

I tried 5.3.other) data_dst util recover original filename.bat, but still can't make it easier. Maybe I did something wrong. Could you describe the order of the debug about data_dst ? 

Mine is 
1. check the aligned folder of data_dst and record the number of the wrong or upside down face. (but its hard to find the face which is not detected. For example,  109 110 115 116.  You need to check every pictures to find out 111, 112, 113, and 114 are missing .)

2. According to the record, delete the same number of pictures and those pictures which are not detected in aligned_debug folder. (but Need to check one by one)

Is it possible to keep original filename after sort by similar histogram in aligned folder of data_dst, like 0001-1124_0?  ( new order - original filename)
And create  simple pictures with number( new order - original filename) to replace the missing picture, so I can know what picture is missing and what picture is wrong extraction by just executing the program once?

**Comment by iperov** [comment]
what you mean 
"can't make it easier"
?
it works or not ?
Deepfaking is not easy by default.

**Comment by dkny11354** [comment]
It works, but I hope to add the original filename after 4.2.2) data_src sort by similar histogram.
I can't record new order number of wrong or upside down pictures after sorting, cause its not fit in aligned_debug folder.

**Comment by iperov** [comment]
it is already placed after all sorts
![Uploading FreeCommander_2019-08-27_13-49-23.jpg…]()
