### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by 1984dp** [iperov/DeepFaceLab#378]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

Ran "train HD64" against data set, for which it stopped around 37K iterations. 
Conditions: Used model defaults for the model. 

I then cleared the workstation, and then tried to rerun the model with the same result. 

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

Now when I run the model, it simply gives me a ValueError (see attached)
![trainingerror](https://user-images.githubusercontent.com/52768152/63720553-74299600-c81d-11e9-835a-61f397cd1bd1.jpg)

Running CPU only version. 
*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by iperov** [comment]
it seems like your gpu has not enough memory.

Try SAE model with reduced settings, 64 res, less AE dims than default, etc.

**Comment by 1984dp** [comment]
Thank you. This was the issue and is resolved.
________________________________
