### ISSUE TITLE
SAE issues in Linux

### ISSUE THREAD

**Issue by maerory** [iperov/DeepFaceLab#379]
I am trying to use the SAE model in order to do the conversion. I have trained the model for hours and the training results seem very good. However, I have a problem during the conversion process.
![image](https://user-images.githubusercontent.com/22238411/63874790-c8e92000-c987-11e9-9936-9d65419515b4.png)

Here is the model summary:
![image](https://user-images.githubusercontent.com/22238411/63875142-6d6b6200-c988-11e9-9f8b-27eff71de22a.png)

I have tried all different method for converting. The model seems to recognize the source face and is able to segment the face, but fails to transform to the source, which results in something like this:
![image](https://user-images.githubusercontent.com/22238411/63874926-12396f80-c988-11e9-9ca1-1cdd24cc4e8b.png)
This was what happened when I tried to do raw-rgb conversion using the learned mask approach. I didn't see any error in the terminal so I couldn't figure out what the problem was.

I have used the command line given in the scripts folder (7_convert_SAE). I am using python 3.6.6 on linux with exact same environment as mentioned in the installation guide.

**Comment by lbfs** [comment]
Do other conversion methods work correctly?

**Comment by maerory** [comment]
Here is the trained model and a bit of data.
Data: https://drive.google.com/file/d/1Hwv-KR_3RVMpYeMiIFLe4lHhgF7utZA0/view?usp=sharing
Model: https://drive.google.com/file/d/1k2vhMlG4T41qDYmK2fLfPGcOVgq3g8hY/view?usp=sharing

I am using the 23854ac8bc58735738143a34d59a709bcf85ff74 commit, from about 3 days ago.I am also running this model remotely, which means that I have linux server where my model and setting is located, and running it remotely with sshfs on mac.

**Comment by lbfs** [comment]
Since things seem to be working fine for me, can you try renaming all of your model files to be SAE_ rather than 01_ and then try to rerun the converter? If your using multi-gpu, you might have issues. I was able to convert fine.  

Also, you might be hitting a weird read/write bug if you're using your model remotely like that,  Is your server is accessing the model data over SSHFS?

**Comment by maerory** [comment]
Thanks lbfs, I will get back to you when I try running it again next week.

**Comment by maerory** [comment]
I have ran the model with the name changed, however, the conversion is still not working. I can't figure out why. The DF model was able to convert successfully, but SAE model is not working.
