### ISSUE TITLE
Missing binary

### ISSUE THREAD

**Issue by Petomai** [iperov/DeepFaceLab#38]
it says there is a prebuilt standalone Windows binary, but after downloading the zip there are no windows binary anywhere. There is a link to a website at the bottom but it is in Russian unfortunately.

**Comment by iperov** [comment]
look at readme

> Prebuilt python folder with DeepFaceLab:
> Windows 7,8,8.1,10 zero dependency (just install/update your GeForce Drivers) prebuilt Python 3.6.5 embeddable folder with DeepFaceLab can be downloaded from torrent https://rutracker.org/forum/viewtopic.php?p=75318742 (magnet link inside).

**Comment by signupdemo** [comment]
I downloaded the Torrent.. and went through steps to create frames, but im stuck at the extract faces part. It says "NVML shared directory not found".
Everything works using the faceswap GUI version. But I can't run this torrent folder. I need to model using DFaker full face. Plz help anybody ?
