### ISSUE TITLE
Port to Java

### ISSUE THREAD

**Issue by ShumptonLang** [iperov/DeepFaceLab#380]
Did you know that java runs on 3 billion devices? Why not DFL?

**Comment by wintdkyo** [comment]
Because most models using tensorflow uses python?

**Comment by ShumptonLang** [comment]
3 billion!!

**Comment by ShumptonLang** [comment]
also why even use tensorflow when pytorch exists?

**Comment by iperov** [comment]
ok you can train deepfake on your coffee machine, but it will take about 2 years.

**Comment by ElijahPepe** [comment]
> 
> 
> also why even use tensorflow when pytorch exists?

Because Google backs Tensorflow? It's widely more trusted and way better than Pytorch. It's useless to use Java because, guess what?

No one will benefit. The only devices that can't run DFL are devices that can't install any external programs in general.
