### ISSUE TITLE
SAE Convert crash on high amount of images

### ISSUE THREAD

**Issue by HenrikoMagnifico** [iperov/DeepFaceLab#381]
## Expected behavior

SAE Convert progressing and finishing like normal.

## Actual behavior

SAO Convert.bat script crashes after ~1900 images have been processed. I receive this error;
`019-08-31 22:35:13.314255: E tensorflow/stream_executor/cuda/cuda_driver.cc:1011] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure ::
2019-08-31 22:35:13.314268: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-08-31 22:35:13.345196: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
Press any key to continue . . .`

I have installed latest Nvidia drivers and CUDA toolkit.

## Steps to reproduce

Trying to generate images using convert_SAE.bat on Windows 10 using a GTX 1070Ti. Total amount of images: 328249. Workspace size: 83.3GB.

## Other relevant information
- **Operating system and version:** Windows 10 64-Bit Professional
- **Python version:** Prebuilt Windows Binary

Full log:
https://pastebin.com/7jf97r90

**Comment by iperov** [comment]
upload your workspace to google drive, I try to convert on my comp

**Comment by HenrikoMagnifico** [comment]
> upload your workspace to google drive, I try to convert on my comp

I am sorry, but my workspace takes up 83.3 GB since there are so many frames (I am trying to convert an entire movie).

**Comment by iperov** [comment]
then there is no chance to investigate the issue

**Comment by HenrikoMagnifico** [comment]
I can send you the workspace and the videos used for the extraction and training. The goal is to replace the face of all characters in The Fellowship of the Ring with my friend's face.

**Comment by iperov** [comment]
upload only model folder without history and data_dst folder.

**Comment by iperov** [comment]
also you can use bittorrent client (utorrent, qbittorrent) and create a torrent with magnet link, so I can download directly from you.

**Comment by HenrikoMagnifico** [comment]
I will do that. I am uploading the model folder first, and then creating a torrent if that does not yield any results.

**Comment by HenrikoMagnifico** [comment]
Here is the link to my Model folder; https://drive.google.com/drive/folders/1Skd-ftS2JGGkt-GYcSPO_25WqEQtUAsZ?usp=sharing

**Comment by iperov** [comment]
why you uploaded it not in a zip archive?

**Comment by iperov** [comment]
ok, now upload data_dst

**Comment by HenrikoMagnifico** [comment]
Here; https://drive.google.com/file/d/13EksEoSi9qfep-ChLHsoDkRctHjJxA7e/view?usp=sharing

**Comment by iperov** [comment]
cannot load in torrent.
Recreate with largest block size

**Comment by HenrikoMagnifico** [comment]
I think it would be faster if I simply uploaded the dst mp4 file to you, since all I did was 'data_dst extract faces S3FD best GPU.bat' and then trained with 'train SAE.bat'. Uploading all frames seperately would take longer with my connection than simply generating images from scratch. I just tried using a different video file (this time a 1.5 hour long video) and it's giving me the same error. It seems this error is caused by lack of memory of some kind due to the large amount of frames.

**Comment by iperov** [comment]
no, i have no time to extract.

**Comment by iperov** [comment]
Recreate torrent with largest block size

**Comment by bbbooo313** [comment]
jxgjheiqian.com  大佬换个友链吗？
联系QQ：1297532431

**Comment by antoniomtz** [comment]
@HenrikoMagnifico I'm having the same issue when using h128. I have to restart the training every 10 min or so.
Were you able to fix the issue?
