### ISSUE TITLE
REQUEST: Set Settings for Converting in bat file

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#384]
Hi there
I have a Request: Is it possible to set the Settings for Converting in the .bat file?
Reason: If i trained a batch of videos i can only convert one after another instead of set up a .bat file an let it work over night.

Maybe any chance to do that?

Greetz and thanks for the grate work :)

**Comment by iperov** [comment]
no

**Comment by sdgandhi** [comment]
@blanuk `(echo input1 && echo input2) | program.exe` will do the trick

**Comment by sdgandhi** [comment]
Or just rewrite your own .bat file by copying the existing one
