### ISSUE TITLE
Extracting issue in Openfaceswap

### ISSUE THREAD

**Issue by PlutoMaeda** [iperov/DeepFaceLab#39]
I'm just trying to extract faces from the collect frames.

Issue is that doesn't work. Text says "The specified module is untraceable" (I use it in french so i'm not sure of teh translation).

i use this guide https://adultdeepfakes.com/how-to-make-a-deepfake

**Comment by iperov** [comment]
this is DeepFaceLab repo , not Openfaceswap

**Comment by gessyoo** [comment]
PlutoMaeda, www.deepfakes.club, which was supporting Openfaceswap, closed down recently.  Try DeepFaceLab instead.  Iperov, browser requests to www.deepfakes.club are being redirected to this repro.
