### ISSUE TITLE
Chinese people need an entrance of AliPay to donate your project. 

### ISSUE THREAD

**Issue by jiadiwu** [iperov/DeepFaceLab#392]

**Comment by iperov** [comment]
Foreigners cannot use alipay anymore, because alipay now requires Chinese bank card to transfer money between alipay wallets.
Registration of a Chinese bank card requires the physical presence of a foreigner.

**Comment by iperov** [comment]
if you have global mastercard/visa card, you can donate here https://money.yandex.ru/to/41001142318065

**Comment by dream80** [comment]
Have you tried WeChat, basically all Chinese people use this app, this software can also generate QR code

**Comment by iperov** [comment]
WeChat also requires china bank cards for operations.

**Comment by ShionWakanae** [comment]
Basically Chinese people use bank cards with UnionPay(银联), most of us don't have mastercard/visa. and recently alipay and wechat QRcode is the primary way of payment. that's a part of "how China seperated from globe"......

Maybe it is possible for alipay and wechat donate with a Chinese friend's assistance?
China has enough population and interests of this project after all :)

**Comment by dream80** [comment]
Paymentwall supports international payments, supports alipay, wechat.  you may try it
![20190905121353](https://user-images.githubusercontent.com/20279174/64311679-8e126800-cfd7-11e9-8220-878c5a8b21c0.jpg)

**Comment by iperov** [comment]
@dream80 paymentwall requires a website where api will be integrated. Also it requires business company documents that I don't have

**Comment by iperov** [comment]
Thanks for support.
I will try to recover alipay in 2 weeks.

**Comment by iperov** [comment]
alipay don't accept my unionpay card :(

**Comment by iperov** [comment]
only one way to donate from China is buy bitcoin via VPN.
Bitcoin trade between citizens is legal in China.

**Comment by iperov** [comment]
donate by QQ in main page

**Comment by iperov** [comment]
changed QQ code
