### ISSUE TITLE
New idea with converter

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#394]
Can You add function which in convert mode will check if for example 2 frames without faces detected then it will copy and overwrite those frames ? 
For Example
**no faces found for 12010.png, copying without faces** (but 12009 has face and 12011 also, so lets just copy and overwrite frame 12011 to frame 12010.
It should be another script or the converter should ask about it, maybe for a max number of frames to overwrite, cause 3-4 same  frames in 24 fps movie are not a problem at all.
Is it a good idea ? Can it be done ? It would really speed up to make some better videos.

**Comment by bbbooo313** [comment]
[http://www.jxgjpingtai.com/](url)

**Comment by iperov** [comment]
no
