### ISSUE TITLE
DeepFaceLabOpenCLSSE_build_08_30_2019 missing "extract faces" batch files for CPU only

### ISSUE THREAD

**Issue by solarpass** [iperov/DeepFaceLab#397]
I installed DeepFaceLabOpenCLSSE_build_08_30_2019.exe. But there is no "4) data_src extract faces MT CPU.bat" file, and no "5) data_dst extract faces MT CPU.bat" file, as indicated in the tutorial videos.  
  
Can I just use the corresponding GPU batch file by adding "--cpu_only" argument? If so, do I need additional argument(s) for the CPU only? 
Thank you.

**Comment by bkapvt** [comment]
From the translated manual
```
extraction of persons can only be run or MT S3FD, with the first pass (1st pass) on the MT will still 

work on the CPU, but fast enough! S3FD runs completely on OpenCL and is the preferred method. 

The second pass is working on OpenCL without problems. 
```

I'm not using CLSSE build but the above sure implies that you should be using MT to extract faces. Have you tried using it?

**Comment by solarpass** [comment]
@bkapvt I've already tried it with MT, up to the "data_src extract faces MT" step. 
I just want to make sure I didn't miss any argument(s), before next step the very slow training process (30+ hours cpu only). 
In case maybe there are other arguments needed, e.g. to speed up the process.

BTW, if anyone has the CPU only related batch files, please share. 
Thank you.

**Comment by bkapvt** [comment]
What makes you think it would be faster than that?

It takes me 10-15 minutes to extract faces from a 1-2 minute video with a GTX 980ti graphics card. 

Extracting faces is a GPU intensive process, if you're using only CPU for that it doesn't surprise me that it would be quite slow. Are you limited by hardware and need to use CPU? Getting good results with just a CPU sounds like it would be almost impossible based off what I've only been able to achieve with the graphics card I have.

**Comment by solarpass** [comment]
@bkapvt It's the training process suppose to be 30+ hours (CPU), not the extracting faces. Extracting faces only took around 5+33+0.5 minutes (pass 1+2+3) in mine (CPU only). 
 
Speed is not my concern. The topic in my question is the missing batch files for CPU only (extract faces, train, convert) in the latest build. 
Thank you.
