### ISSUE TITLE
one few shot implementation, face swapping video from single image

### ISSUE THREAD

**Issue by ak9250** [iperov/DeepFaceLab#398]
recently one/few shot approaches look like they are getting good success with face swapping in video. A implementation like https://github.com/shaoanlu/fewshot-face-translation-GAN
can do face swapping in video from a single image without training face pairs for any face. 
Can this approach be used to improve face swap videos?

**Comment by solarpass** [comment]
@ak9250 The ZAO app launched last week also uses single image with very good result.

**Comment by ak9250** [comment]
@solarpass yes I think the zao app only showing cherry picked results, there is no occlusions, hard shadows, different skin tones, extreme facial expressions or rotations etc...
I got this result with the few shot face translation method
![ezgif com-resize (8)](https://user-images.githubusercontent.com/6818285/64381622-9f706a00-d001-11e9-92f8-75f623a34483.gif)
