### ISSUE TITLE
Documentation in Markdown

### ISSUE THREAD

**Issue by solo12zw74** [iperov/DeepFaceLab#399]
Excuse me to write here, cant find another way to communicate with author.

Do you have a Russian manual sources? I'd like to make it (documentation) with Markdown, not PDF. I think it will be more github-ish way. You can contact me with solo12zw74 (at) yandex.ru.

**Comment by iperov** [comment]
сорс есть в doc\

документация изначально была на гитхабе, но потом мне потребовалось более наглядная схематика с различными шрифтами и таблицы, а этого markdown не даёт.
