### ISSUE TITLE
Question for avatar model

### ISSUE THREAD

**Issue by Gregs3311** [iperov/DeepFaceLab#4]
I tried some training with the avatar model, result here:
https://youtu.be/Rk5um-dtqQc

Have you planned some further development, to convert the swapped face back into the original frames/video ? Is that even possible at the moment, as the swapped face got other head movement than the original face.

Regards

**Comment by iperov** [comment]
avatar is not face swapping model, no way to convert back to original video.
This is just simple implementation of non gan model.
Future is https://youtu.be/qc5P2bvfl44

**Comment by oracle9i88** [comment]
> I tried some training with the avatar model, result here:
> https://youtu.be/Rk5um-dtqQc
> 
> Have you planned some further development, to convert the swapped face back into the original frames/video ? Is that even possible at the moment, as the swapped face got other head movement than the original face.
> 
> Regards

can you share the avatar model to me ？
