### ISSUE TITLE
is there any way to have the dfaker model work with  a 4GB GPU?

### ISSUE THREAD

**Issue by frossi65** [iperov/DeepFaceLab#40]
## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ...

**Comment by iperov** [comment]
yes, decrease batch size manually
