### ISSUE TITLE
Can we add function ...?

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#402]
... to manual extract faces for all frames without faces found by S3FD or MT ?
... or make a list of frames in which the faces was not detected ... please

**Comment by wzfgogogo** [comment]
#!/usr/bin/python
import os
import shutil
sDir = r"X:\DeepFaceLab\workspace\data_dst"
aDir = os.path.join(sDir,"aligned")
dDir = os.path.join(sDir,"aligned_debug")
rDir = os.path.join(dDir,"remove")

if not os.path.exists(rDir):
    os.mkdir(rDir)

aDict={}
for aFilename in filter(lambda aFilename:aFilename.endswith(".jpg"),os.listdir(aDir)):
    aDict[aFilename.split("_")[0]]=None

for x in range(len(list(filter(lambda d:d.endswith(".jpg"),os.listdir(dDir))))):
    z = str(x).zfill(5)
    if z not in aDict:
        if os.path.exists(os.path.join(dDir,z+".jpg")):
            shutil.move(os.path.join(dDir,z+".jpg"),os.path.join(rDir,z+".jpg"))
