### ISSUE TITLE
Are RTX cards with Tensor Cores working now?

### ISSUE THREAD

**Issue by BionicPony** [iperov/DeepFaceLab#405]
There are two threads from last November saying that RTX cards were not able to extract faces because of a problem on Nvidia's end.  In those threads it was theorized that a future update from Nvidia would allow those cards to work with DeepFaceLab.

Does anyone know if those cards are working now?  To put it more simply, is anyone successfully using DeepFaceLab with an RTX Card (1650, 2060, 2070, etc)?

I don't want to buy and install a $1,000 card if they are still known to be incompatible with DFL.

**Comment by iperov** [comment]
RTX cards work.
Tensorcores from rtx are not used, because they work only with float16 precision that is not enough for autoencoders

**Comment by BionicPony** [comment]
Thank You!
