### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by DesignerLock** [iperov/DeepFaceLab#408]
## Expected behavior
The script "6) train SAE" will work correctly. To analyze the behaviour of individuals and the merger.
[Screenshot](https://imgur.com/a/5o9LGfS)

## Actual behavior
The script "6) train SAE" does not work with the error: "ValueError: cannot convert float NaN to integer"
[Screenshot](https://imgur.com/a/gOTWOFZ)

## Steps to reproduce
1) Open script "6) train SAE"
2) Iter 80.000+
3) Then this error appeared and the window with faces stopped working. (+-90.000) This error was already in cmd [Screenshot](https://imgur.com/a/5o9LGfS)
4) Restarted the script, the error appears, the visual window with faces is not.

## Other relevant information
- Operating system and version: Windows 10 x64

**Comment by DesignerLock** [comment]
Hello?

**Comment by square690410** [comment]
I also met that. it's gone after enabled auto backup. try that.
