### ISSUE TITLE
Step 8 - Convert to AVI or MP4

### ISSUE THREAD

**Issue by AznManDown** [iperov/DeepFaceLab#41]
After completing steps 1 - 7, I have a folder called Merged with frames of SRC overlayed into frames of the DST video.

However, when running either of the step 8 commands, to convert to AVI or MP4. The Command Prompt window pops up for a split second and then closes for either of them.

Any idea why this is?

**Comment by AznManDown** [comment]
Nevermind, figured it out. Original drt file was longer than the frames merged.

**Comment by ELVDW** [comment]
@AznManDown, I have the same problem. How did you fix it? Thanks in advance.

**Comment by AznManDown** [comment]
@ELVDW I'm not sure if it'll be the same for you, but when I looked at the workspace I noticed that the destination video clip was longer than the extracted frames that were merged. 

I had to re-extract the frames and then run the merge process again. When everything lined up, the conversion ran properly. 

Hope this helps you!
