### ISSUE TITLE
SAE training doubt.

### ISSUE THREAD

**Issue by rohit12043** [iperov/DeepFaceLab#412]
Hi !
I just wanted to ask answer for 1 error.
The error is that tensorflow is not able to allocate memory. I was training SAE Model.
I have GTX 1050 Ti oc,4gb vram.I am not able to increase batch size.
So is there a way to increase batch size by Overclocking.
THANK YOU!!.

**Comment by wintdkyo** [comment]
Overclocking will not help. because batch sizes are largely dependent on GPU memory. Most likely, there isn't a way to increase batch size with your current GPU.

**Comment by rohit12043** [comment]
Thanks for your reply.

But isn't there any way.

**Comment by realsssam** [comment]
Try reducing the batch_size and using optimizer_mode:2

**Comment by rohit12043** [comment]
Thanks.
I'll try.
