### ISSUE TITLE
SAE model training issue.

### ISSUE THREAD

**Issue by rohit12043** [iperov/DeepFaceLab#414]
Whenever I try to train SAE model, the preview window doesn't comes up.
It gets stuck at  
============== Model Summary ===============
==                                        ==
==        Model name: SAE                 ==
==                                        ==
== Current iteration: 0                   ==
==                                        ==
==------------ Model Options -------------==
==                                        ==
==        autobackup: True                ==
==       sort_by_yaw: False               ==
==       random_flip: False               ==
==        resolution: 128                 ==
==         face_type: f                   ==
==        learn_mask: True                ==
==    optimizer_mode: 1                   ==
==             archi: liae                ==
==           ae_dims: 256                 ==
==         e_ch_dims: 42                  ==
==         d_ch_dims: 21                  ==
==        ca_weights: False               ==
==        pixel_loss: False               ==
==  face_style_power: 0.0                 ==
==    bg_style_power: 0.0                 ==
==   apply_random_ct: False               ==
==          clipgrad: False               ==
==        batch_size: 4                   ==
==                                        ==
==-------------- Running On --------------==
==                                        ==
==      Device index: 0                   ==
==              Name: GeForce GTX 1050 Ti ==
==              VRAM: 4.00GB              ==
==                                        ==
============================================
Starting.Press "Enter" to stop training and save model

**Comment by Dian-Yi** [comment]
have u solved this problems? i think u python evirement is wrong. i meet the same problem,  when training the model, it always suspends in 'Staring.Press "Enter" to stop training and save model'

**Comment by rohit12043** [comment]
Sorry but I'm unable to find the solution.

**Comment by Dian-Yi** [comment]
u GPU ram is lower 8GB, so it hang at there. u should use lower memery model or better GPU

**Comment by rohit12043** [comment]
But before, It was working,suddenly It stuck at her.

**Comment by Dian-Yi** [comment]
u can change the train model to H64 and wait few minutes, it will works well.

**Comment by voltixftw** [comment]
did you find a solution?
