### ISSUE TITLE
Suddenly getting CUDA_ERROR_OUT_OF_MEMORY when converting

### ISSUE THREAD

**Issue by packageofoats** [iperov/DeepFaceLab#415]
I'm trying to convert H64 from my training, and every time it produces this error. It doesn't cancel and say "Press any key to continue", which is weird as well. It just hangs on the progress bar and nothing moving.

The full error is:
2019-09-14 13:45:35.835352: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.43G (2608267264 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU5.
Running on CPU3.
Running on CPU4.
Converting:   0%|                                                                             | 0/3456 [00:00<?, ?it/s]

I was doing it fine earlier today, but all of a sudden I'm getting this error.
I've tried different settings in the dialog.
I have multiple DFL projects I'm working on (is that the issue?), so I tried converting in another folder, and it works fine there. I also tried training the problem project, and that works fine, it's just the convert H64 one that produces this memory error.

I'm using Windows 10, graphics card is an RTX 2060. I've seen around that RTX cards can be problematic.

**Comment by no1991** [comment]
why no body help us ?

**Comment by no1991** [comment]
if guys want to tell me to reduce batch size or modify Session,
pls tell us where to find the file
