### ISSUE TITLE
Command line show   no attribute 'extract'   when I try to extract the faces 

### ISSUE THREAD

**Issue by shy0511** [iperov/DeepFaceLab#416]
I don't know how to describe it, and it just showed these:

Exception while process data [D:\DeepFaceLabTorrent\workspace\data_src\xxx.jpg]: Traceback (most recent call last):
  File "D:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\joblib\SubprocessorBase.py", line 68, in _subprocess_run
    result = self.process_data (data)
  File "D:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 156, in process_data
    rects = data.rects = self.e.extract (rotated_image, is_bgr=True)
AttributeError: 'DLIBExtractor' object has no attribute 'extract'

and then paused.
I read the source code and find nothing...Where can I find this DLIBExtractor?

**Comment by shy0511** [comment]
OK, I've solved it by myself.

I found it 
/facelib/DLIBExtractor.py line 24
def extract_from_bgr (self, input_image):

/mainscripts/Extractor.py line 154
rects = data.rects = self.e.extract (rotated_image, is_bgr=True)

just correct above to rects = data.rects = self.e.extract_from_bgr (rotated_image)

it could run, but before it done, showed that Corrupted JPG file: Unknown chunk FE
and I don't know why

**Comment by iperov** [comment]
where you found dlib extractor?

https://github.com/iperov/DeepFaceLab/tree/master/facelib
