### ISSUE TITLE
multiple faces debug 

### ISSUE THREAD

**Issue by ak0000321** [iperov/DeepFaceLab#418]
may i ask, for the case of multiple faces, most of the automatic recognition can recognize the contour of the face.
But how do you use the "data_dst extract faces manual re-extract delete result debug" tool for individual face recognition in the dst-debug folder?
The key issue is that the tool can only manually interact with one face. How do you implement multiple faces?

**Comment by halilclk** [comment]
Sorunuzun cevabını bende çok merak ediyorum
