### ISSUE TITLE
Retraining on each new version?

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#420]
Hi There

Is it possible to use one Standard for the model file?
On Version 13_09, retraining are needed, now on Version 19_09 retraining are again needed?

**Comment by realsssam** [comment]
changelog:

== 19.09.2019 ==

SAE : WARNING, RETRAIN IS REQUIRED ! 
fixed model sizes from previous update. 
avoided bug in ML framework(keras) that forces to train the model on random noise.

Converter: added blur on the same keys as sharpness

Added new model 'TrueFace'. Only for NVIDIA cards.
This is a GAN model ported from https://github.com/NVlabs/FUNIT
Model produces near zero morphing and high detail face.
Model has higher failure rate than other models.
It does not learn the mask, so fan-x mask modes should be used in the converter.
Keep src and dst faceset in same lighting conditions.
