### ISSUE TITLE
cuda_driver failed to alloc  bytes on  RTX 2080 TI and best config of training?

### ISSUE THREAD

**Issue by Vano333** [iperov/DeepFaceLab#421]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

My config network
Model name: SAE
                       ==
==             face_type: f                   ==
==            learn_mask: True                ==
==        optimizer_mode: **2**                   ==
==                 archi: df                  ==
==               ae_dims: **1024**                ==
==             e_ch_dims: **85**                  ==
==             d_ch_dims: **21**                  ==
==            ca_weights: True                ==
==            pixel_loss: False               ==
==      face_style_power: 0.0                 ==
==        bg_style_power: 0.0                 ==
==       apply_random_ct: True                ==
==              clipgrad: False               ==
==            **batch_size: 1**                   ==
==                                            ==
==---------------- Running On ----------------==
==                                            ==
==          Device index: 0                   ==
==                  Name: GeForce RTX 2080 Ti ==
==                  **VRAM: 11.00GB**             ==

## Actual behavior
Training is work but some errors but there is free memory 
and low speed of training (i think)
![Memory](https://user-images.githubusercontent.com/54908361/65322956-d5405180-dbb0-11e9-8a56-2a8df623f8e5.png)
![GPU](https://user-images.githubusercontent.com/54908361/65322976-dec9b980-dbb0-11e9-8eaa-5de53e104107.png)

2019-09-20 10:55:34.758907: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed to alloc 8589934592 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-09-20 10:55:34.762043: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed to alloc 7730940928 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-09-20 10:55:34.764516: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed to alloc 6957846528 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
[10:58:06][#000074][**1969ms**][1.6879][1.5996]
[11:13:20][#000526][**1984ms**][1.4698][1.3873]
[11:28:27][#000978][**1953ms**][1.4377][1.2750]
[11:43:35][#001429][**1953ms**][1.3739][1.2382]
[11:58:43][#001881][**1984ms**][1.2838][1.1424]
[12:13:54][#002332][**1953ms**][1.2971][1.0579]
[12:29:03][#002781][**2000ms**][1.1963][1.0402]
[12:34:12][#002934][**1984ms**][0.9680][0.6831]
## Steps to reproduce

Tell please  which network configuration is better for better quality **(excluding training time)**
            resolution     ae_dims    e_ch_dims   d_ch_dims
1:     128      1024          85               21
2:         192      1024          42               21
3:          208      880           42               21

or tell me where to read about the network configuration for better quality 
**thanks anyway**
**Спасибо за проект и работу над ним**
## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows 10 64bit Pro **32GB RAM** and 37 GB swap on SSD
- **DeepFaceLabCUDA10.1AVX_build_09_19_2019**

**Comment by TooMuchFun** [comment]
Search the Issue history for 'OOM'. 

Then give up just use default settings like everyone else. :)

**Comment by Vano333** [comment]
https://stackoverflow.com/questions/43503409/tensorflow-cuda-error-out-of-memory

There are some options:

1- reduce your batch size

2- use memory growing:

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config, ...)

3- don't allocate whole of your GPU memory(only 90%):

config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.9
session = tf.Session(config=config, ...)

how to apply these settings in this project?

**Comment by blanuk** [comment]
yout dont have to. 
ich your settings are to high, de memory will overflow and abort.
choose settings optimized for ur memory capacity.
its a little bit a try and error.

**Comment by Vano333** [comment]
figure is the training **is work** and model training for 3 days, but on start training error in command line. model training.
