### ISSUE TITLE
Stuck at "Performing 1st pass..." while trying to extract faces

### ISSUE THREAD

**Issue by SharkEzz** [iperov/DeepFaceLab#423]
Hi !

I've ran into a problem recently while trying to extract faces (I use the latest prebuild Windows binary (21/09/2019 CUDA10.1 AVX)).
I was using an RX 480 before and everything worked as they should but I switched to an RTX 2070 and now I'm stuck at the "Performing 1st pass" step while trying to extract faces, you can see it in the screenshot below.

![Sans titre](https://user-images.githubusercontent.com/27637158/65374977-18252680-dc90-11e9-8aac-917e63ff0d95.png)

I've tried S3FD and MT but the behavior is the same.
My NVIDIA driver is the latest available (Game Ready Driver version 436.30) on an up-to-date Windows 10 machine with 16Gb RAM and a Ryzen 5 1600x.

I tried reinstalling DFL, reinstalling Windows but it did not change anything...

Hope someone know how to fix this !

Thank you in advance !

**Comment by blanuk** [comment]
by the first run u have to wait. let it run a half an hour and check then if it works.
after a first run, it will starts faster
