### ISSUE TITLE
Where did the ready-to-work facets go?!

### ISSUE THREAD

**Issue by eyeballceo** [iperov/DeepFaceLab#424]
Hi everyone. I just tried the link to the mega.nz link for the facets but it appears either down or removed by the admin. Can anyone please provide another location where this data can be downloaded?

**Comment by Vano333** [comment]
https://drive.google.com/drive/folders/1LwMdfTxdOaNAHt_sGV76aQVn7XPseXJB

**Comment by eyeballceo** [comment]
Many thanks @Vano333
