### ISSUE TITLE
AVATAR model train issue

### ISSUE THREAD

**Issue by victormashkov19** [iperov/DeepFaceLab#426]
@iperov, I have tested AVATAR model.
But preview of train has error.
![047990](https://user-images.githubusercontent.com/52272321/65428508-751b0b00-de4f-11e9-8ad4-215ea4149bd7.jpg)
In the preview, 2nd and 4th column is wrong.
Can you explain the reason?

**Comment by jamesdegrandis** [comment]
@victormashkov19 
 This looks like the AVATAR stage 1 training process, I noticed the same thing when I ran it.  When you start the AVATAR stage 2 process, you _should_ notice the training updating those other columns.  Be sure to run a sufficient number of iterations on the first stage before progressing to the second.

**Comment by sdgandhi** [comment]
@victormashkov19 @jamesdegrandis is correct, if you want a more in-depth tutorial with tips and tricks, check out: https://pub.dfblue.com/pub/2019-09-24-deepfacelab-avatar-tutorial
