### ISSUE TITLE
How to feed FUNIT / TrueFace model?

### ISSUE THREAD

**Issue by Enyakk** [iperov/DeepFaceLab#430]
Should we supply the FUNIT model with standard CelebA / CelebB facesets? It seems generalization is especially important for this GAN model.

Should we stick to standard faceset approach or should the image selection be modified?

**Comment by NTU-P04922004** [comment]
I have used the same face data to train the TrueFace model (half face) and the result seems OK with some artifacts on the images.

Currently, the TrueFace model only considers two identities (src and dst), however, using more identities would get better results according to the FUNIT paper.
