### ISSUE TITLE
Dst mask not full

### ISSUE THREAD

**Issue by ydanila** [iperov/DeepFaceLab#434]
I tried to train swap on several faces and every time had same  problem with DST mask. It often doesn't contains edges of noses, cheeks, chins or eyebrows.

For this moment there is only one way to fix this - manually. What if to add tool which allows to expand mask for example +5% and this will allow to include all such cases into mask.

As I am not familliar with all details how learning masks works asking for you opinion about it. I can even try to implement this.

**Comment by tfis2** [comment]
erode with negative values didn't work?

**Comment by ydanila** [comment]
May be I don't understand how erode mask works, but I don't think that it could work.

How it looks for me. If initial data contains errors (mask doesn't covers fully face on some pictures) than learned mask could have wrong sizes, formes, radiuses, ... And if result mask has errors no magic switch can't correctly resolve and fix on convert step all wrong parts.
