### ISSUE TITLE
result jittering

### ISSUE THREAD

**Issue by Chriff** [iperov/DeepFaceLab#435]
Hi all,
i have some problems with the trained model jittering / moving / wiggeling, when merged back onto the dst-footage.
That means that the face in general does not look like it's "glued" accurately to the dst face. There is always some movement somewhere, for example in the eye-areas, or the nose does some random wiggling, etc.

What could cause this?
What settings in the encoder have an influence on that?

I don't want to show a video to avoid copyright problems, so i tried to describe it as good as i can ;)

I'm running in SAE mode.
I thought that maybe my datasets weren't properly aligned, or sth. like that.
Then i tested the H64 mode for 1 night (30.000 iterations), and even though the face is blurry, the face sticks to the dst face and doesn't jiggle around.

Also i have the impression, that when using SAE, the more iterations i run, the more the face jitters around. At 2k iterations obviously the face itself still looks bad, but the movement is more accurate and looks smoother /less jittery then after 100k iterations.

I use the latest windows build "CUDA9.2SSE_build_09_21_2019" in SAE mode.
i think i have tested out a lot of different settings, but did not use any of the "optimize" modes yet.
So with my 4GB gpu i had to somewhat reduce the DIMs, maybe too much?

Here are my latest settings, maybe you can see if sth. is wrong there.

============== Model Summary ===============
==                                        ==
==            Model name: SAE             ==
==                                        ==
==     Current iteration: 120746          ==
==                                        ==
==------------ Model Options -------------==
==                                        ==
==            autobackup: True            ==
== write_preview_history: True            ==
==           sort_by_yaw: False           ==
==           random_flip: True            ==
==            resolution: 192             ==
==             face_type: f               ==
==            learn_mask: True            ==
==        optimizer_mode: 1               ==
==                 archi: df              ==
==               ae_dims: 192             ==
==             e_ch_dims: 32              ==
==             d_ch_dims: 12              ==
==            ca_weights: True            ==
==            pixel_loss: False           ==
==      face_style_power: 0.0             ==
==        bg_style_power: 0.0             ==
==       apply_random_ct: False           ==
==              clipgrad: True            ==
==            batch_size: 3               ==
==                                        ==
==-------------- Running On --------------==
==                                        ==
==          Device index: 0               ==
==                  Name: GeForce GTX 960 ==
==                  VRAM: 4.00GB          ==
==                                        ==
============================================

Any hint is appreciated ;)
thanks

**Comment by tfis2** [comment]
Check the conversion settings/alignments.

**Comment by dogukan04** [comment]
I'm using 1050 ti 4gb vram
To use the Sae model How to set up. Help please...
