### ISSUE TITLE
Converting: Incrase for Multi CPU?

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#443]
Hi
If i start converting, there is the Output of countig Cores and startin tensor Backend.
On my 16 Core, i counts only to six? does that be a bug? or tecnical reason? or can i increase that?
normaly i get only 2/2.4 it/s. Maybe of this message for using only 6 cores?

If i sort by blur, it counts up to 32 (16 smt cores).
How can i change that for testing if it brings up some performance?
Greets and thanks for answering :)

**Comment by rsadiq** [comment]
It only DISPLAYS 6 cores no matter how many more cores you have ... But, You can check the activity of all cores via htop(linux). or task manager (windows)

**Comment by titanrw** [comment]
Actually I think it only uses 6.  But this is usually enough.  I have a 8 core 16 thread processor, and 6 conversion threads gives me 80-90% cpu usage.

You can change it if you want to experiment though.  In file "mainscripts/converter.py" around line 240 (probably varies version to version) is:

self.prefetch_frame_count = self.process_count = min(6,multiprocessing.cpu_count())

This just takes whatever the lower number is between the cpu cores that you have, and 6.  Essentially capping the value at 6, but it will use less if you don't have 6.

Change it if you want.

**Comment by blanuk** [comment]
@titanrw that brings my its up. not really much, but 2.5 instead of 2 its is better then nothing :)
thanks for that :)
