### ISSUE TITLE
Extractor check prevents manual extraction of some alignments

### ISSUE THREAD

**Issue by kcimit** [iperov/DeepFaceLab#444]
https://github.com/iperov/DeepFaceLab/blob/24eac44dd932664cf3a3fff6a017331a0791c6c2/mainscripts/Extractor.py#L245

for some edge cases, condition is not met and face is reported as not detected even if landmarks are aligned manually in gui and look ok.

No solution yet other than removing check.

**Comment by iperov** [comment]
upload the frame , I will check

**Comment by kcimit** [comment]
Ok, but have to reproduce it once more. Will keep you posted.
