### ISSUE TITLE
multiple gpus

### ISSUE THREAD

**Issue by zdd520** [iperov/DeepFaceLab#446]
I am now using two RTX8000. Although command line display USES multiple gpus, there is only one gpu in the task manager.
![XA7VC8W`}_)UMO1HL1N4G2Q](https://user-images.githubusercontent.com/24478959/66917400-e2d1e580-f04f-11e9-96f6-ec7380608ed6.png)

**Comment by gessyoo** [comment]
https://github.com/iperov/DeepFaceLab/issues/61 and https://github.com/iperov/DeepFaceLab/issues/278.
