### ISSUE TITLE
MASK DST ERROR 

### ISSUE THREAD

**Issue by DeepDownLab** [iperov/DeepFaceLab#451]
I don't know why this is happening:
![Screenshot_1](https://user-images.githubusercontent.com/56702536/67052419-87b5f680-f114-11e9-91e3-94ee44feb4eb.png)

==-------------- Model Options --------------==
==                                           ==
==       sort_by_yaw: False                  ==
==       random_flip: True                   ==
==        resolution: 128                    ==
==         face_type: f                      ==
==        learn_mask: True                   ==
==    optimizer_mode: 1                      ==
==             archi: df                     ==
==           ae_dims: 512                    ==
==         e_ch_dims: 42                     ==
==         d_ch_dims: 21                     ==
==        ca_weights: False                  ==
==        pixel_loss: False                  ==
==  face_style_power: 0.0                    ==
==    bg_style_power: 0.0                    ==
==   apply_random_ct: False                  ==
==          clipgrad: False                  ==
==        batch_size: 4                      ==
==                                           ==
==--------------- Running On ----------------==
==                                           ==
==      Device index: 0                      ==
==              Name: GeForce RTX 2060 SUPER ==
==              VRAM: 8.00GB                 ==
==                                           ==
===============================================

**Comment by sdgandhi** [comment]
You have to manually reposition the masks during extraction.
