### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by shadowzoom** [iperov/DeepFaceLab#455]
Guys, quick question. I have favorite musican, I wanna enchace old music video, there is a shitty vob quality. Can I improve face quality on the original video via faceswap if I just train it with the same person, but with hq images?

**Comment by tjess78** [comment]
Hi!
Have a look at this guide

[https://captrobau.blogspot.com/2019/05/tutorial-upscaling-video-with-topaz-ai.html](url)
Greetings!
