### ISSUE TITLE
Whats the secret to having a good mask?

### ISSUE THREAD

**Issue by SmallFoxy** [iperov/DeepFaceLab#456]
Hi folks, I have only been using DFL for a while but I cannot resolve the issue of having a hard edged mask over the destination face and also difficulty in matching skin colour. 

 I have only ran it for about 40,000 iterations and have left all settings on default except playing around with gaussian blur (to soften the edges of the mask?) 

What are ideal setting for matching skin tone please?  Sorry for coming across as a total noob but we all gotta start somewhere right?  

Thanks in advance.

**Comment by Neufunk** [comment]
More iterations for the edges. What algorithm do you use ? Be sure to try SAEHD.
For colors, I find LCT to be the more precise.

**Comment by SmallFoxy** [comment]
Thank you Neufunk, I will try for 100,000 iterations on my next attempt and see if that helps. To be honest, i've only tried once with SAEHD and the process was slow (GTX 1080) so i gave up and have been rushing through using H64 just to get the hang of things.  Of course I would not expect great results with this regarding face clarity but didn't realise the mask edges and skin tone would be so negitively affected. Thank you for your advice, I will step up my game.

**Comment by Tiger14n** [comment]
What happened did you try ?
