### ISSUE TITLE
Some side profile images get rotated on extraction

### ISSUE THREAD

**Issue by coloneldbugger** [iperov/DeepFaceLab#458]
I've noticed for awhile through all versions that some side profile extractions get rotated so the face is sideways or upside down.  Even if the proper alignment is done with a manual extraction it still rotates the face. It seems to happen only when a second eye is not visible and the mask assumes that missing eye to be lower than the eye it can lock on to.

Training on the resulting rotated alignment files results in blurry garbage.

**Comment by iperov** [comment]
upload such samples

**Comment by iperov** [comment]
and source images

**Comment by coloneldbugger** [comment]
Thank you for responding.  Here are the image files that show what I think is causing the problem.  It seems to be guessing that the missing eye is lower. Despite it getting all visible parts of the face correct the resulting alignment files end up rotated.  I have done training in the past on those rotated alignment files hoping it would train the face properly still but it does not.  I tried to manually rotate the image but learned quickly that process destroys the alignment meta data stored in the image file.

Please let me know if you require anything more from me to help with the issue.

![03152](https://user-images.githubusercontent.com/13123174/67534631-0c68bd80-f69d-11e9-8260-fcda89bf3083.png)
![03153](https://user-images.githubusercontent.com/13123174/67534632-0c68bd80-f69d-11e9-81a4-1b33391fcf3e.png)
![03154](https://user-images.githubusercontent.com/13123174/67534633-0c68bd80-f69d-11e9-8e0f-65e283624c6a.png)
![03155](https://user-images.githubusercontent.com/13123174/67534634-0c68bd80-f69d-11e9-9a53-5d4a6991fad4.png)
![03156](https://user-images.githubusercontent.com/13123174/67534635-0d015400-f69d-11e9-9f31-67adecc622e7.png)
![03152](https://user-images.githubusercontent.com/13123174/67534638-1094db00-f69d-11e9-8088-4df7ee7f47b8.jpg)
![03153](https://user-images.githubusercontent.com/13123174/67534639-112d7180-f69d-11e9-900b-19d672571acb.jpg)
![03154](https://user-images.githubusercontent.com/13123174/67534640-112d7180-f69d-11e9-8765-adedfd9ff66b.jpg)
![03155](https://user-images.githubusercontent.com/13123174/67534641-112d7180-f69d-11e9-9e78-55a1a7a45d7b.jpg)
![03156](https://user-images.githubusercontent.com/13123174/67534642-112d7180-f69d-11e9-8c31-1dc0c6666705.jpg)
![03152_0](https://user-images.githubusercontent.com/13123174/67534645-15f22580-f69d-11e9-961e-71be75dc8d4a.jpg)
![03153_0](https://user-images.githubusercontent.com/13123174/67534646-168abc00-f69d-11e9-9672-46b1e95f1973.jpg)
![03154_0](https://user-images.githubusercontent.com/13123174/67534647-168abc00-f69d-11e9-85eb-4eba934629ce.jpg)
![03155_0](https://user-images.githubusercontent.com/13123174/67534648-168abc00-f69d-11e9-9657-1f0aa8ba9a79.jpg)
![03156_0](https://user-images.githubusercontent.com/13123174/67534649-168abc00-f69d-11e9-93a5-2ccfb167eea2.jpg)

**Comment by iperov** [comment]
try last commit with the fix of umeyama

**Comment by coloneldbugger** [comment]
Worked! Thank you.
