### ISSUE TITLE
VRAM calculator for faster Model creation

### ISSUE THREAD

**Issue by Maxinger15** [iperov/DeepFaceLab#460]
Hi, 
I am trying around for about 5 hours in the last days do get the biggest possible Network to train on my RTX 2080. So I looked around if it is possible to calculate the VRAM usage of a NN. After some search I found this. https://stackoverflow.com/questions/43137288/how-to-determine-needed-memory-of-keras-model I am not really deep in AI so I can't write this feature myself. I think it will make a lot of try and error obsolete. 
@iperov what do you think?

I am looking forward to hearing from you.
Yours sincerely
Maxinger15

**Comment by iperov** [comment]
impossible
