### ISSUE TITLE
Can't do anything in alignments, keep getting "Attribute issues" related to having no copy attribute or something ..

### ISSUE THREAD

**Issue by colorsdiary** [iperov/DeepFaceLab#464]
> Traceback (most recent call last):
  File "C:\Users\ColorsDiary\faceswap\lib\cli.py", line 128, in execute_script
    process.process()
  File "C:\Users\ColorsDiary\faceswap\tools\alignments.py", line 52, in process
    job.process()
  File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs_manual.py", line 461, in process
    self.mouse_handler = MouseHandler(self.interface, self.arguments.loglevel)
  File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs_manual.py", line 768, in __init__
    self.extractor = self.init_extractor()
  File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs_manual.py", line 788, in init_extractor
    extractor.set_batchsize(plugin_type, 1)
  File "C:\Users\ColorsDiary\faceswap\plugins\extract\pipeline.py", line 166, in set_batchsize
    plugin.batchsize = batchsize
AttributeError: 'NoneType' object has no attribute 

> 'batchsize'

Here is another log note:

> Traceback (most recent call last):
>   File "C:\Users\ColorsDiary\faceswap\lib\cli.py", line 128, in execute_script
>     process.process()
>   File "C:\Users\ColorsDiary\faceswap\tools\alignments.py", line 52, in process
>     job.process()
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs.py", line 422, in process
>     self.export_faces()
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs.py", line 457, in export_faces
>     extracted_faces += self.output_faces(frame)
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs.py", line 470, in output_faces
>     faces = self.select_valid_faces(frame_fullname)
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs.py", line 487, in select_valid_faces
>     faces = self.extracted_faces.get_faces_in_frame(frame)
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\media.py", line 305, in get_faces_in_frame
>     self.get_faces(frame)
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\media.py", line 288, in get_faces
>     self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\media.py", line 288, in <listcomp>
>     self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
> AttributeError: 'NoneType' object has no attribute 'copy'

Every time I try to sort or merge or do something with alignments, it fails,
I looked up online, and it seems that I have to change or downgrade my keras version,
I'm pretty familiar with codes. I don't code at all, but I can copy and paste a command line. For the life of me, I spent a few hours to figure out that "python" is a different terminal than windows' own CMD. I tried many codes, nothing worked. I installed FaceSwap through the installer, and it seems something didn't install right .. but I don't even know how would I try to fix it.

My hardware is AMD ryzen CPU, and AMD Vega 56 GPU

**Comment by iperov** [comment]
this is not faceswap repo, this is deepfacelab
