### ISSUE TITLE
[ (Winx64) Off-Topic Q.:] Possible to use DFL for other Tensorflow (Keras) Projects ?

### ISSUE THREAD

**Issue by pwnmactep** [iperov/DeepFaceLab#468]
Hello,

i mean to use the prebuild Windows App to use it for  expl.: [https://github.com/tensorflow/models/tree/master/research/object_detection](url)

I checked the `python_console.bat` and `setenv.bat` for normal it should work..think so ;)

Any one try something like before ?

**Comment by iperov** [comment]
of course you can use it.

install python requirements of the github project through python_console.bat:
python -m pip install <package_name>

copy github folder to _internal

follow run instructions of the project and make new bat files
