### ISSUE TITLE
Manual extract error

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#470]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior
Run a manual extract on all src images without software exiting.

## Actual behavior
Software stops somewhat randomly and throws error. All progress are lost.

## Steps to reproduce
Run manual extract on images enclosed in e-mail.

## Other relevant information
- Windows 7, Dual Xeon, 64 gb ram, latest nvidia drivers.
- Windows binary
- Tried on two different Win 7 setups with different hardware -> Same error
- Tried on older versions of DFL - > Same error
- Tried latest DFL version including latest patches - > Same error

**Dump:**
Performing manual extract...
Running on GeForce GTX 1080 Ti.
Using TensorFlow backend.
 71%|##############################            | 25/35 [01:58<00:47,  4.73s/it]T
raceback (most recent call last):
  File "C:\Users\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\ma
in.py", line 250, in <module>
    arguments.func(arguments)
  File "C:\Users\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\ma
in.py", line 35, in process_extract
    'multi_gpu' : arguments.multi_gpu,
  File "C:\Users\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\ma
inscripts\Extractor.py", line 864, in main
    data = ExtractSubprocessor ([ ExtractSubprocessor.Data(filename) for filenam
e in input_path_image_paths ], 'landmarks', image_size, face_type, debug_dir, cp
u_only=cpu_only, manual=True, manual_window_size=manual_window_size).run()
  File "C:\Users\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\jo
blib\SubprocessorBase.py", line 222, in run
    self.on_result (cli.host_dict, obj['data'], obj['result'])
  File "C:\Users\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\ma
inscripts\Extractor.py", line 550, in on_result
    view_landmarks  = (np.array(self.landmarks) * self.view_scale).astype(np.int
).tolist()
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
Press any key to continue . . .

**Comment by iperov** [comment]
fixed
