### ISSUE TITLE
Request: Choose on which Card Extraction runs

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#472]
Hi there
By training we can choose on which GPU it runs.
By Extraction we only can choose all GPU or Best GPU.
Is it possible to implement a switch for choosing a GPU by ID or just to choose the worst GPU?

Reason: Training on best GPU can run at the same time as extracting on the other one.

Greets and thanks a lot :)

**Comment by iperov** [comment]
extraction runs on the same card as training

**Comment by blanuk** [comment]
on training, i can choose by     --force-gpu-idx. 
by extraction, its no a valid option. maybe u can implement that for extraction to?
it works by training and by converting. 
Thanks for the fast answer :)

**Comment by iperov** [comment]
99% users don't need this option

**Comment by blanuk** [comment]
> 
> 
> 99% users don't need this option

what if i pay for that?
its a benefit if u can train on the better card while convertig on the other... with just 2 its by converting, a lot of time goes away for that. time which i can use for training another model :)
