### ISSUE TITLE
Error: "Warning: multiple faces detected. Strongly recommended to process them separately. Warning: multiple faces detected. Motion blur will not be used."

### ISSUE THREAD

**Issue by tam96** [iperov/DeepFaceLab#473]
Help me fix issues: 

```
``
Running converter.

Use interactive converter? (y/n skip:y) :
y
Loading model...
Using TensorFlow backend.
=============== Model Summary ===============
==                                         ==
==        Model name: H64                  ==
==                                         ==
== Current iteration: 58981                ==
==                                         ==
==------------- Model Options -------------==
==                                         ==
==       sort_by_yaw: False                ==
==       random_flip: True                 ==
==        lighter_ae: False                ==
==        pixel_loss: False                ==
==        batch_size: 4                    ==
==                                         ==
==-------------- Running On ---------------==
==                                         ==
==      Device index: 0                    ==
==              Name: GeForce GTX 1060 6GB ==
==              VRAM: 6.00GB               ==
==                                         ==
=============================================
Collecting alignments: 100%|#####################################################| 1035/1035 [00:00<00:00, 1123.00it/s]
Warning: multiple faces detected. Strongly recommended to process them separately.
Warning: multiple faces detected. Motion blur will not be used.
Use saved session? (y/n skip:y) :
y
Using saved session from model/H64_converter_session.dat
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Converting:   0%|                                                                             | 0/1146 [00:00<?, ?it/s]

ConverterConfig 00001.png:
Mode: overlay
mask_mode: learned
erode_mask_modifier: 0
blur_mask_modifier: 0
motion_blur_power: 0
output_face_scale: 0
color_transfer_mode: None
sharpen_mode : None
blursharpen_amount : 0
super_resolution_mode : None
color_degrade_power: 0
export_mask_alpha: False
================
``
```

**Comment by blanuk** [comment]
you have more than one aligment for 1 frame.
sort your alingments correct and delete the doubles
means: 001_0.jpg and 001_1.jpg is one to much

**Comment by tam96** [comment]
Can you help me fix it?

**Comment by varunpro** [comment]
"you have more than one aligment for 1 frame.
sort your alingments correct and delete the doubles
means: 001_0.jpg and 001_1.jpg is one to much"

search dst folder with _1 and see what pops up ... clean up any junk

**Comment by tam96** [comment]
Can you preview my error?
Link youtube: https://youtu.be/rV0o7ErwDtQ

**Comment by varunpro** [comment]
merge folder doesn't have any converted ? run the converter in non interactive mode; even if it says multiple faces detected and check. 

Also; in Dst\aligned folder search for  _1 and see if anything pops up

**Comment by tam96** [comment]
I use DeepFaceLab_CUDA_9.2_SSE. I ran the following steps:

```
1) clear workspace
2) extract images from video data_src
3.2) extract images from video data_dst FULL FPS
4) data_src extract faces MT all GPU
4.2.2) data_src sort by similar histogram
4.2.1) data_src sort by blur
5) data_dst extract faces MT all GPU 
5.2) data_dst sort by similar histogram
5.3) data_dst sort by blur
6) train H64 (I pressed P about 4000 times)
7) convert H64
8) converted to mp4
```
Can you tell me which steps I made wrong?

**Comment by varunpro** [comment]
6 - train H64 (I pressed P about 4000 times) - wow 0_o - haven't used H64 myself; yet I would think P is just for checking the progress. 

7 - convert H64 - seems from the whole video, you only converted frame 1. of the video; you have to convert all the frames ... all the converted frames would show up in the merged folder. 

8 - converted to mp4  - will take all the merged frames in the merged folder and align them over the original video with sound. 

*the data_dst\aligned folder must have some other face... or something else showing up like a hand or watch or wall or whatever... easiest way to check that is to search with _1 and remove those frames from data_dst\aligned folder ...

**Comment by tam96** [comment]
I can not run steps: 7) convert H64. When I ran to this step, a window appeared. I do not see this window on deepfakelab's tutorial videos Youtube. 



![error 1](https://user-images.githubusercontent.com/57208724/68129422-1c5d8880-ff4c-11e9-8d43-38dc6539da3e.PNG)

After that, no process has run at all. Even I searched _1 in the dst folder and could not find the file

![error 3](https://user-images.githubusercontent.com/57208724/68129981-25028e80-ff4d-11e9-8ff9-6ce605acbb16.PNG)

I only see one file in merged (dst folder)
![error 4](https://user-images.githubusercontent.com/57208724/68130348-c689e000-ff4d-11e9-932f-eefd80b502f1.PNG)

**Comment by varunpro** [comment]
I can not run steps: 7) convert H64. When I ran to this step, a window appeared. I do not see this window on deepfakelab's tutorial videos Youtube. 

you can run step 7 without the window. After you click on 7) convert h64; write N for interactive window .

though even if windows appears, click on the window and press tab key, then press enter and wait.

**Comment by tam96** [comment]
Thank you! I can runn next step but I have a problem. When I running this step, the process has stopped. I waited for 1 hour and nothing happended. Can you tell me how to fix it?

![error 5](https://user-images.githubusercontent.com/57208724/68227763-da554500-0026-11ea-9788-8570c5d99107.PNG)
