### ISSUE TITLE
Training Fanseg - Some Clarity will be much appreciated  (^_^)

### ISSUE THREAD

**Issue by varunpro** [iperov/DeepFaceLab#475]
Downloaded the folder Fanseg 08.31.2019 from google drive. 
(https://drive.google.com/drive/folders/1eLmnIdfvdUPcKfBkuGp9t_GOw-zDnh5n)

On extraction, found it's got multiple folders, e.g. - glasses, fingers, helmet etc... in data_src folder
and also, for data_dst folder like glasses, Holi, other. 

My Setup for Training Fanseg 
----------------------------------

**for data_src -**
 
Combined all pictures from various folders in data_src 
to \workspace\data_src\aligned 
(again; e.g. - folders like glasses, fingers, helmet etc... to data_dst aligned folder)

**for data_dst -**

Added manually edited masks at my end - plus pre-existing folders - glasses, holi, other  
to \workspace\data_dst\aligned  
(combined all of them )

set the batch size as 24 (as per the instructions in the readme.txt file)
and face: full 
running the .bat file with --model DEV_FANSEG.

**Questions - 0_o**
 
1 - is the setup correct? 
2 - if yes; how many epochs to run? or till what loss values? 
3 - would the batch size 32 produce more accurate results?
4 - lastly, I read 
"Result model\FANSeg_256_full_face.h5 should be placed to DeepFacelab\facelib\ folder"; 
is that correct? 
(because i checked that location in DFL latest build and didn't see any existing FANSeg_256_full_face.h5 file in that location) 

_Any help much much; appreciated :)_

**Comment by varunpro** [comment]
update  : 

![2019-11-02 (1)](https://user-images.githubusercontent.com/56723430/68065694-f9b44f80-fd52-11e9-8a9f-e15a37937c38.png)
![2019-11-02 (2)](https://user-images.githubusercontent.com/56723430/68065698-0042c700-fd53-11e9-854d-2d36fe7278bb.png)

it is stuck at around .2600 value for straight 12 hours  :( .... is that normal?

**Comment by iperov** [comment]
data_dst is validating set, not training

**Comment by varunpro** [comment]
"data_dst is validating set, not training" 
 - appreciate the response :)

hmmm ... by that; u mean that data_dst ( which contains my manually edited masks ) is being used for validation & evaluation of existing data_src files? .... and not for training it.  yeah?   

assuming that I got you correctly, and everything is working as it should, at what point should I consider it well validated to stop? or does it jus need to be tested for its effectiveness in DFL convert to ascertain that on test dataset ?

**Comment by varunpro** [comment]
or 

did I completely mixed up the whole goddamn thing 0_o. 

As in; I need to add the manually edited masks to  data_src\aligned and put whatever I earlier put in data_src\aligned to data_dst\aligned  ?_? and re-run the whole thing again ...... !_!

**Comment by iperov** [comment]
data_src is used for training the network
data_dst is the second preview to test the network on unseen images

**Comment by varunpro** [comment]
"data_src is used for training the network
data_dst is the second preview to test the network on unseen images"

- Thanks for the clarity ^_^

I am going to re-adjust the data_src and add some new data_dst ( *unseen by the network ) and run it, again... 

and update what comes up next ...

**Comment by varunpro** [comment]
![2019-11-04](https://user-images.githubusercontent.com/56723430/68103540-43409e00-fefd-11e9-8199-40b8a34c10d7.png)

Re-adjusted the data_src and added new data_dst (*unseen by the network) and run it, again...

and it's back to 62k iteration and shows .2800ish value... 

Questions:  
------------------------------------

1 - how many epochs to run? or till what loss value? or manually check the preview window and decide?
2 - would the batch size 32 produce more accurate results?
3 - lastly, I read
"Result model\FANSeg_256_full_face.h5 should be placed to DeepFacelab\facelib\ folder";
is that correct?
(because I checked that location in DFL latest build and didn't see any existing FANSeg_256_full_face.h5 file in that location)

bonus question - what happens to the original FANSEG_256_full_face.h5?  (does it get overwritten or updated) *_*

**Comment by varunpro** [comment]
I have trained Fanseg with 2-3 sample sets ( with manually masked models) - 

confused where to where to place the resulting model file :  
1. Result model\FANSeg_256_full_face.h5 should be placed to DeepFacelab\facelib\ folder";
is that correct?
(because i checked that location in DFL latest build and didn't see any existing FANSeg_256_full_face.h5 file in that location) ? 

or 
2. "% DFL_ROOT%\nnlib\FANSeg_256_full_face.h5" ? 

Thanks in advance :)

**Comment by varunpro** [comment]
https://github.com/iperov/DeepFaceLab/issues/551#issuecomment-573304728 

"Place it in the nnlib folder"
