### ISSUE TITLE
run in python command

### ISSUE THREAD

**Issue by rookiecm** [iperov/DeepFaceLab#476]
Hi, could you give some discriptions about training and testing the code in **python command**. That is to say how to run the code from the script rather than by the **.bat** file. Thank you.

**Comment by TooMuchFun** [comment]
Something like this,

`python main.py train --training-data-src-dir path/to/src/extracted --training-data-dst-dir path/to/dst/extracted --model-dir path/to/model --model SAEHD`

There are lots other flags too. Do `python main.py train --help` to see. Same for `extract` and `convert`. Using `--help` is very similar other command line programs.
