### ISSUE TITLE
Can't convert to h64, it stop at 0% ( gtx1050ti )

### ISSUE THREAD

**Issue by Trthien98** [iperov/DeepFaceLab#477]
When I try to convert h64, the process stop at 0%, and don't run anymore. Someone hellp me.

![Untitled](https://user-images.githubusercontent.com/57248279/68065867-da70ee80-fd61-11e9-9032-bbfc7d04ccb0.png)

**Comment by TooMuchFun** [comment]
On a 1050? With 4GB? Hmm... no.

Give up and just use https://github.com/chervonij/DFL-Colab to run in Google Colab.
