### ISSUE TITLE
Extraction Issue With Titan RTX (24GB)

### ISSUE THREAD

**Issue by The-Digital-Void** [iperov/DeepFaceLab#479]
## Expected behavior

Successful extraction using either "S3FD All GPU" or "S3FD Best GPU".

## Actual behavior

DeepFaceLab appears to treat my Titan RTX as multiple cards. It would be fine if it stopped at 3, as that puts me around 18/24 GB VRAM used. But it always goes for a fourth, which pushes me at the border of my VRAM limitations. Once it starts trying to execute it gets hit with CUDA_ERROR_OUT_OF_MEMORY issues. Sometimes this will result in all of the extractions being completed eventually. However, more often than not the 1st pass will stop early and continue with those that it managed to complete. 2nd Pass has no Memory issues.

![DFL Error](https://user-images.githubusercontent.com/57318447/68085153-a9e58f00-fe0b-11e9-923f-81487eb917a6.JPG)

## Steps to reproduce

Execute the "S3FD All GPU" or "S3FD Best GPU" extractors.

## Other relevant information
-Operating System: Windows 10
-DeepFaceLab Version: DeepFaceLab_CUDA_10.1_AVX_build_10_27_2019.exe
-GPU: Titan RTX 24GB
-CPU: i9-9940X @ 3.3GHz
-RAM: 64 GB

**Comment by kl001** [comment]
This situation also happened on my 2080TI graphics card. Later I changed the S3FD to the version of 2019.10.23, and I can extract it normally.

**Comment by kilerb** [comment]
Got the same issue w/ the 10/27 version on my Titan RTX.  Was just about to leave a separate post and saw this one.  I went back to using the 10/23 version because of this.  It works fine.  Would love for them to fix this issue in future versions so we can enjoy new features when they come out.

**Comment by iperov** [comment]
try last commit

**Comment by The-Digital-Void** [comment]
Works perfectly. Thanks!

**Comment by kilerb** [comment]
Not sure what you mean?  This error only came up for me with the latest version (10/27) and that is still the latest version that's up, no?
