### ISSUE TITLE
Please update to support CUDA 10 and CUDNN 7.4.1

### ISSUE THREAD

**Issue by nobodyfromnowhere-hi** [iperov/DeepFaceLab#48]
I own an RTX 2080 and I am unable to extract using my GPU, After trying numerous thing on numerous configurations and operating systems I've come to the conclusion, after reviewing Nvidia documentation, that the current versions required by DeepFaceLab simply are incompatible with Turing GPUs. I have no trouble using DeepFaceLab with my GTX 1070 on the same configurations. 
 This link explains it https://docs.nvidia.com/deeplearning/sdk/cudnn-support-matrix/index.html 

The good news is that at least old cards will still work if you update for new hardware.

**Comment by iperov** [comment]
tensorflow will support cuda 10 only in 1.13.0 version
https://github.com/tensorflow/tensorflow/issues/22706

**Comment by tfboyd** [comment]
@nobodyfromnowhere-hi 
I started a CUDA 10 github issue for TensorFlow and users have contributed a windows build as a stop gap until we do it officially.  I hope that helps.  

https://github.com/tensorflow/tensorflow/issues/22706

**Comment by iperov** [comment]
waiting tf 1.13.0 ...
