### ISSUE TITLE
Getting errors during conversion

### ISSUE THREAD

**Issue by kilerb** [iperov/DeepFaceLab#480]
Please see attached screen grab.  Gives error at about the same point each time I try to convert.  I can continue training, but won't let me convert.  One thing I can tell you is I moved this from one computer to a different one.  Just dragged the entire folder over the network, which I've done in the past.  Not sure if that has anything to do with this.  Just want to get the video finalized.  Thanks!

![IMG_0473](https://user-images.githubusercontent.com/6969681/68341189-cb10de80-009c-11ea-9920-4b5edcaca8cd.jpg)

**Comment by iperov** [comment]
looks like error while processing specific image in data_dst\ folder
