### ISSUE TITLE
Error during extraction, occurs repeatedly with certain data_dst.mp4 extracted frames.

### ISSUE THREAD

**Issue by TMBdf** [iperov/DeepFaceLab#482]
Extraction finishes 1st pass, during 2nd pass an error occurs:

F:\DF\DFL\_internal\DeepFaceLab\mathlib\__init__.py:25: RuntimeWarning: overflow encountered in int_scalars return 0.5*np.abs(np.dot(x,np.roll(y,1))-np.dot(y,np.roll(x,1)))

Error occurs with some datasets, if it happens with certain one it can be reproduced (this one I tried 4 times, 4 times getting the same error around 3000th frame out of 7000 (always on 2nd pass).
After that 3rd pass runs and it only extracts faces found in those frames it processed.

Frames extracted as jpg.

Other relevant information
Windows 10 64bit, newest DFL version along with updates from github, GTX 1060, 4790k 16Gb of RAM.

**Comment by anonym34** [comment]
I have same problem when extracting  data_src faces with S3FD but after around 9000 frames.

DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\mathlib\__init__.py:25: RuntimeWarning: overflow encountered in int_scalars
  return 0.5*np.abs(np.dot(x,np.roll(y,1))-np.dot(y,np.roll(x,1)))
GeForce RTX 2080 Ti doesnt response, terminating it.
