### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by HrishikeshMahalle** [iperov/DeepFaceLab#486]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

![Screenshot (75)](https://user-images.githubusercontent.com/53683977/68545818-bdd65580-03f6-11ea-87fe-f5a0310ad327.png)
![Screenshot (76)](https://user-images.githubusercontent.com/53683977/68545819-bdd65580-03f6-11ea-9058-424f35705741.png)
![Screenshot (75)](https://user-images.githubusercontent.com/53683977/68545823-c62e9080-03f6-11ea-9155-fcc9c19c28a4.png)
![Screenshot (75)](https://user-images.githubusercontent.com/53683977/68545827-d0508f00-03f6-11ea-8444-23d36dd09a4d.png)

**Comment by skynetster** [comment]
What GPU do you have? I was running a 1050ti with 4gb, advice I was given was to use the SAEHD training with batch size of 2, dims 128.  which helps with the out of memory errors.

**Comment by HrishikeshMahalle** [comment]
Hello Iperov . Thank you for your email.

I am using gtx1650 4gb graphics card and my cpu is ryzen 5 3550h
