### ISSUE TITLE
How can I donate the money by ALIPay

### ISSUE THREAD

**Issue by deepfacetao** [iperov/DeepFaceLab#488]
Dear Iperov:

I am grateful for your work. It brings a lot of fun to us.

As a Chinese, I have to say donate money by paypal is not convinent. 

Can I use Alipay to donate money to your account? I notice there is a Alipay account in your manual before Oct. 08.

Best wishes,

**Comment by iperov** [comment]
China banned any foreign transactions inside alipay/wechat/etc without realname identification.

I heard that the Chinese can buy bitcoins without any problems.

**Comment by iperov** [comment]
donate by QQ in main page

**Comment by iperov** [comment]
changed QQ code
