### ISSUE TITLE
Facerelight requirements installation and running errors.

### ISSUE THREAD

**Issue by TMBdf** [iperov/DeepFaceLab#489]
For some reason pip install requirements-cuda.txt gives this error out:
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

I managed to install all requirements manually by typing pip install:
numpy==1.17.0
h5py==2.9.0
Keras==2.2.4
opencv-python==4.1.0.25
plaidml==0.6.0
plaidml-keras==0.5.0
scikit-image
tqdm
ffmpeg-python==0.1.17

and

pip install torch===1.3.1 -f https://download.pytorch.org/whl/torch_stable.html
pip install torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

not sure what to do with the line:
git+https://www.github.com/keras-team/keras-contrib.git

also any attempt to instal tensorflow-gpu==1.12.0
pip install tensorflow-gpu==1.12.0 gives out error:

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.12.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0)
ERROR: No matching distribution found for tensorflow-gpu==1.12.0

So I installed 2.0.0 pip install tensorflow-gpu==2.0.0, it uninstalled previous ones and installed this one succesfully:

Installing collected packages: opt-einsum, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, tensorboard, gast, tensorflow-estimator, tensorflow-gpu
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
  Found existing installation: gast 0.3.2
    Uninstalling gast-0.3.2:
      Successfully uninstalled gast-0.3.2
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0
  Found existing installation: tensorflow-gpu 1.14.0
    Uninstalling tensorflow-gpu-1.14.0:
      Successfully uninstalled tensorflow-gpu-1.14.0
Successfully installed cachetools-3.1.1 gast-0.2.2 google-auth-1.7.1 google-auth-oauthlib-0.4.1 oauthlib-3.1.0 opt-einsum-3.1.0 pyasn1-0.4.7 pyasn1-modules-0.2.7 requests-oauthlib-1.3.0 rsa-4.0 tensorboard-2.0.1 tensorflow-estimator-2.0.1 tensorflow-gpu-2.0.0

Then I tried running face relight but I'm still getting the following error:

Lighten the faces? ( y/n default:n ?:help ) :
n
Choose light directions manually? ( y/n default:y ) :
y
Collecting fileinfo: 100%|########################################################| 1209/1209 [00:03<00:00, 302.65it/s]
Using PyTorch backend.
Traceback (most recent call last):
  File "F:\DF\1.DFLAVX10.1_14.11\_internal\DeepFaceLab\main.py", line 302, in <module>
    arguments.func(arguments)
  File "F:\DF\1.DFLAVX10.1_14.11\_internal\DeepFaceLab\main.py", line 278, in process_relight_faceset
    FacesetRelighter.relight (arguments.input_dir, arguments.lighten, arguments.random_one)
  File "F:\DF\1.DFLAVX10.1_14.11\_internal\DeepFaceLab\mainscripts\FacesetRelighter.py", line 206, in relight
    dpr = DeepPortraitRelighting()
  File "F:\DF\1.DFLAVX10.1_14.11\_internal\DeepFaceLab\nnlib\DeepPortraitRelighting.py", line 13, in __init__
    nnlib.import_torch()
  File "F:\DF\1.DFLAVX10.1_14.11\_internal\DeepFaceLab\nnlib\nnlib.py", line 148, in import_torch
    import torch
  File "F:\DF\1.DFLAVX10.1_14.11\_internal\python-3.6.8\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed

**Comment by iperov** [comment]
prebuilt app has all necessary libs

**Comment by TMBdf** [comment]
It is a prebuilt, 13.11 release.

**Comment by iperov** [comment]
in the prebuilt app you don't need to install anything

**Comment by TMBdf** [comment]
It happens with fresh install of 13.11 release, I installed those after that error appeared to see if it would resolve it but it didn't, please look into that error more carefully and see if you spot anything that could be wrong.

**Comment by TMBdf** [comment]
I'll download new 14.11 realease and see if it fixes anything. Yesterday only 13.11 was available, perhaps there was a bug in it?

**Comment by iperov** [comment]
i dont know. All works fine at me.

**Comment by TMBdf** [comment]
Sadly it's the same thing, just run it on my aligned src and got the exact same error, perhaps I could try the SSE version but not sure if it would make any difference since my CPU supports AVX :/

**Comment by TMBdf** [comment]
Just in case somehow installing them broke something I uninstalled them, still same error:

Lighten the faces? ( y/n default:n ?:help ) :
n
Choose light directions manually? ( y/n default:y ) :
y
Collecting fileinfo: 100%|########################################################| 9317/9317 [00:32<00:00, 283.03it/s]
Using PyTorch backend.
Traceback (most recent call last):
  File "F:\DF\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\main.py", line 302, in <module>
    arguments.func(arguments)
  File "F:\DF\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\main.py", line 278, in process_relight_faceset
    FacesetRelighter.relight (arguments.input_dir, arguments.lighten, arguments.random_one)
  File "F:\DF\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\mainscripts\FacesetRelighter.py", line 206, in relight
    dpr = DeepPortraitRelighting()
  File "F:\DF\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\nnlib\DeepPortraitRelighting.py", line 13, in __init__
    nnlib.import_torch()
  File "F:\DF\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\nnlib\nnlib.py", line 148, in import_torch
    import torch
  File "F:\DF\DeepFaceLab_CUDA_10.1_AVX\_internal\python-3.6.8\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1
Press any key to continue . . .

**Comment by TMBdf** [comment]
REstared PC, updated drivers, even Windows updated itself, downloaded fresh 9.2 SSE 14.11 release, unpacked, nothing changed, new src testing dataset, same thing. Looking at this error doesn't tell what could be wrong? I'm pretty sure 1 thing is causing it and then the rest follows but what could it be?
