### ISSUE TITLE
help to understant what dont work

### ISSUE THREAD

**Issue by sweetholding** [iperov/DeepFaceLab#491]
my program dont work I get that and dont kniw if that fork. and if it dont work why? what I make wrong
it write this
  raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

**Comment by orkblutt** [comment]
Hi
AVATAR mode ?
You should consult this tuto: https://pub.dfblue.com/pub/2019-09-24-deepfacelab-avatar-tutorial
