### ISSUE TITLE
Быстрый вопрос

### ISSUE THREAD

**Issue by shadowfolder** [iperov/DeepFaceLab#5]
Приветос! Прежде чем оставить свое оборудование на пару суток для обработки видео, хотелось бы спросить, ваша сборка работает же лучше, чем https://github.com/deepfakes/faceswap верно? Увидел пример вашего видео и там нет никаких квадратиков на лице как у faceswap-a.

**Comment by bonlime** [comment]
По моему опыту лучше. Но зависит от модели, на H128 качество лишь чуть лучше, на LIAEF128 значительно лучше.

**Comment by bonlime** [comment]
Кстати  @iperov а есть какие-нибудь статьи с обяснением почему именно такая архитектура в H128 и LIAEF128?

**Comment by shadowfolder** [comment]
@bonlime что за H128 и LIAEF128? Что это за обозначения?

**Comment by bonlime** [comment]
@shadowfolder Это разные архитектуры сетей, используемые внутри DeepFace. в README этого репозитория можно посмотреть результаты. 128 в конце имени обозначает разрешение лица, а почему H или LIAEF я и сам не знаю

**Comment by iperov** [comment]
в каждой модели свои плюсы и минусы. Даже у 64 есть свой плюс - меньше микрорасколбаса черт лица. Также желательно, чтобы src лица имели одинаковое освещение, т.е. с одного дубля.
Я думаю все примеры в readme переделать либо под нового кейджа с одинаковым освещением, либо в другой фейк. Текущий кейдж собран из разных освещений, что даёт некоторый расколбас в интерполяции.

**Comment by shadowfolder** [comment]
А чего вообще только 64 и 128 пикселей делай измену лиц? Ведь если делать больше пикселей, то и качество картинки намного улучшится..

**Comment by bonlime** [comment]
Учиться очень долго будет и в память может не влезть. Наверно можно сделать какое-то постепенное улучшение разрешения, как в работах nvidia делают, но пока такого нет
