### ISSUE TITLE
Image extractation does not work (RTX 2060 Super - Windows 10) without an error message

### ISSUE THREAD

**Issue by HarrySTrueman** [iperov/DeepFaceLab#505]
Hi there,

I am totally new in DeepFaceLab and I wanted to try how it works.
I am using a AMD Ryzen 7 3700X, Windows 10, RTX 2060 Super and I downloaded the package "DeepFaceLab_CUDA_10.1_AVX_build_11_14_2019.exe" from DeepFaceLab - GoogleDrive.
I also tried the other packages with the same result.

I extracted the files and started with executing "2) extract images from video data_src.bat".
I just used the default settings the program starts working for a few seconds, and then it finishs. It looks good, but in the data_src folder there are no image files :( There is nothing else than a empty "align" folder.

![output_from_image_extraction](https://user-images.githubusercontent.com/6665735/69757725-fcda0a00-115d-11ea-96b4-e08ef09fd799.jpg)

Can someone help solving this issue?
I really want to use the tool. 

Thx,
Harry

**Comment by HarrySTrueman** [comment]
Hi, why is this issue closed without any comment? Nö solution provided?

**Comment by iperov** [comment]
read the fucking manual
