### ISSUE TITLE
Run multiple process

### ISSUE THREAD

**Issue by DarthPestilane** [iperov/DeepFaceLab#506]
I can't run the script in multiple process way.

For example I want to start script like:
```sh
$DFL_PYTHON "$DFL_SRC/main.py" extract \
    --input-dir "$DFL_WORKSPACE/data_src" \
    --output-dir "$DFL_WORKSPACE/data_src/aligned" \
    --detector s3fd
```
in two tty at the same time. But now one will be block until the other one finished.

**Comment by TooMuchFun** [comment]
Are you using a GPU for the extract? You can only run one tensorflow app per GPU. Try using _--multi-gpu_ or _--cpu-only_. I do not have multiple to test with.
