### ISSUE TITLE
Face extraction interrupted at 2nd pass

### ISSUE THREAD

**Issue by guferr** [iperov/DeepFaceLab#509]
Ps.: I actually found the issue myself and fixed it, but I'm letting this here just so if anyone has a similar problem.

The solution was to change the time "no_response_time_sec" variable from mainscripts/Extractor.py (line 309) to a greater value (like 1000).

The script was in fact running as I suspected, but because my processor is too slow the script thinks it's stuck. 

Original Issue:

I'm testing if DeepFaceLab_Linux (from the fork made by Ibfs) runs with --cpu-only in all steps in a very weak hardware:

```
Specs:` 
        
CPU: Intel(R) Celeron(R) CPU  N2940  @ 1.83GHz (4 cores)

RAM memory: 1333 Mhz DDR3 4096 MB

GPU: Intel HD Graphics for Intel Atom Processor Z3700 (integrated).

OS: Linux Mint 18 Sarah

Kernel version: 4.13.0-19-generic
```

I followed all the steps to install it with Anaconda (but used pip install with requirements-cpu.txt), set the environment variables and then I had a problem with tensorflow: 

`The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.`

Then I uninstalled tensorflow, keras and h5py using 'pip uninstall' and installed the same exact versions using conda. 

It solved this problem and the script started to work, but suddenly stopped at the second pass:

```
(deepfacelab) root@ubuntu /home/mint/DeepFaceLab_Linux/scripts # bash 4_data_src_extract_faces_MT_all_GPU.sh --cpu-only
	Performing 1st pass...
	Running on CPU0.
	Using TensorFlow backend.
		Running on CPU1.
	Using TensorFlow backend.
	100%|###########################################| 68/68 [03:20<00:00,  2.95s/it]
	Performing 2nd pass...
	Running on CPU0.
	Using TensorFlow backend.
	Running on CPU1.
	Using TensorFlow backend.
	  0%|                                                    | 0/68 [00:00<?, ?it/s]CPU0 doesnt response, terminating it.
	CPU1 doesnt response, terminating it.
	  0%|                                                    | 0/68 [01:00<?, ?it/s]
	Performing 3rd pass...
	Running on CPU0.
	Running on CPU1.
	Running on CPU2.
	Running on CPU3.
	0it [00:00, ?it/s]
	-------------------------
	Images found:        68
	Faces detected:      0
	-------------------------
	Done.
```

Searching I've found other very similar issues, but they were in the Windows version of DeepFaceLab and weren't using --cpu-only.

This message appears about 1 minutes after it gets to the second progress bar, being that in no moment the CPU usage lowers, it's 100% in both cores all the time until it claims it isn't responding.

Is there any chance that the CPU is just too slow and the software considered it a timeout and it could be forced to wait more?

Thanks.

**Comment by TooMuchFun** [comment]
Just run the scripts in CLI. Since you are alread on Linux I trust you know how. The premade scripts are not reliable. The linux ones are not tested or supported by iperov. I recommend using a classic python build, Anaconda is confusing. Ex,

`python main.py extract --input-dir path/to/faceA/images --output-dir path/to/faceB/images --detector s3fd`
