### ISSUE TITLE
RTX 2070 Super, can't extract faces.

### ISSUE THREAD

**Issue by grexter4** [iperov/DeepFaceLab#513]
Are RTX cards still not compatible with DFL? I'm using DeepFaceLabCUDA10.1AVX 10/14/19
How do I use DFL with RTX card?

**Comment by grexter4** [comment]
Can only use MT to extract, not S3FD.

**Comment by iperov** [comment]
try 9.2 build

**Comment by grexter4** [comment]
Is 9.2 better for RTX?

**Comment by grexter4** [comment]
Tried training SAE using CUDA 10.1 and got this error
 2019-12-06 02:44:05.753517: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.16G (2316197376 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

Do you think switching to 9.2 will solve this problem?
