### ISSUE TITLE
Only using CPU on windows 10 and GeForce GTX 680

### ISSUE THREAD

**Issue by Entretoize** [iperov/DeepFaceLab#515]
## Expected behavior

It is supposed to use GPU as GeForce GTX 680 support CUDA 9 (it is the case with FakeApp)

## Actual behavior

Only CPU is used and it's slow !
It is the case for face extraction or traing for example. It says "Using device CPU"

## Other relevant information
- Window 10 Pro (x64)
- GeForce GTX 680
- CUDA 9,  cudnn 10.2

**Comment by Entretoize** [comment]
I removed the line with `if cc >= tf_min_req_cap:` in device.py it seems that my graphic card has not enough memory but it works, I'll see the result.

**Comment by Entretoize** [comment]
In fact, after having removed the line it displays 
```
==------------Running On ------------==
==                                    ==
==      Device index: 0               ==
==              Name: GeForce GTX 680 ==
==              VRAM: 2.00GB
```
But still using 0% of GPU, is there another trick I can use ?

**Comment by TooMuchFun** [comment]
Try reducing the `DFL_TF_MIN_REQ_CAP` environment variable. It defaults to 35. I imagine this is because to check for device being low end. That area of code also looks for CUDA 10, so maybe try that. 

Tho, GTX 680 2GB is not enough for much fun with DFL. Almost as slow as CPU 🤣

**Comment by Entretoize** [comment]
Yes setting DFL_TF_MIN_REQ_CAP to a smaller value avoid remove the line of
code, but this is the same.
FakeApp is much faster for extracting the faces because it is using the
GPU, (but there's a python error that prevents me to train) so I'm sure the
680 can do better than CPU.
I will try Cuda 10...


Cordialement, Grégory Defaisse


Le ven. 13 déc. 2019 à 14:40, TooMuchFun <notifications@github.com> a
écrit :

**Comment by Entretoize** [comment]
Cuda 10 doesn't help...

**Comment by alexserb720** [comment]
I have the same probleme with Geforce 710m and Windows 10. Running only on CPU...
