### ISSUE TITLE
ValueError while training

### ISSUE THREAD

**Issue by Miha20** [iperov/DeepFaceLab#517]
## Expected behavior

I've been training models in H128 and SAE. I would expect the programm to go through iterations, till I end training of the model, since no iteration is specified during setup of training.

## Actual behavior

The iteration counter changes from the normal info to one with nan in it, e.g.:

from
[13:53:35][#1406393][1314ms][0.2449][0.4413]
to
[14:01:30][#1406754][1302ms][nan][nan].4881]

This happens at different times. Can be a few minutes or hours, after training is started.
Happens with H128 and SAE, have not tried other ones. But expect same outcome.

When this occurs, and I press S for saving (or the autobackup kicks in) I get the following error message:

Error: cannot convert float NaN to integer1]
Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 161, in trainerThread
    model_save()
  File "C:\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 60, in model_save
    model.save()
  File "C:\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 411, in save
    preview_lh = ModelBase.get_loss_history_preview(self.loss_history, self.iter, preview.shape[1], preview.shape[2])
  File "C:\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 649, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer
Done.

If I press P for an update of the preview, I would get:

Traceback (most recent call last):nan].4332]
  File "C:\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\main.py", line 304, in <module>
    arguments.func(arguments)
  File "C:\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\main.py", line 162, in process_train
    Trainer.main(args, device_args)
  File "C:\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 288, in main
    lh_img = models.ModelBase.get_loss_history_preview(loss_history_to_show, iter, w, c)
  File "C:\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 649, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer

If I pressed P it will continue with messages like
[18:44:23][#1402285][1280ms][nan][nan]
till I press S or autobackup kicks in and then stop.

## Steps to reproduce

No idea how to reproduce. Can't see a pattern.

## Other relevant information
Running prebuilt Windows release DeepFaceLabOpenCLSSE version 12_12_2019 (same problem in versions 11_14_2019 and 11_12_2019)
On AMD RX480

**Comment by TooMuchFun** [comment]
Sounds like something might not be right with extracted images or maybe ur hard disk permissions.

**Comment by Miha20** [comment]
What could be wrong with the extracted images and how can one fix it? I could try extracting images again, but then I have to go through all preparations of the picture again and their would be no guarantee that it would fix the problem.

Is their a way to find out, which picture(s) are causing the problem, if that is the case? So at which point the problem occurs (What pictures are used in that iteration?)?

And I don't think it's permissions. No other program has a problem, I haven't messed with them while working on extracting picture etc. and I even gave full access for testing, after you mentioned it. Same problem. :(

**Comment by square690410** [comment]
Try to enable auto backup. issue is gone after enable auto backup in my side.

**Comment by Miha20** [comment]
Autobackup is enabled. Makes no difference for me.

**Comment by rodrigo-barraza** [comment]
What card do you have? I have the same exact issue with my 2080TI but works fine on my 1080.

**Comment by Miha20** [comment]
I'm using a RX480.
Your first image doesn't show the same problem, so I guess you just wanted to show your settings?
The preview window looks to me like a broken model, which would be wierd if you just started and it happens everytime. Might be a different issue.

**Comment by pascaaaal** [comment]
Same error here, I'm using an M1 MacBook Pro with 16Gb RAM but with a Conda env. 
If I use a model that was trained on my Linux machine, the first preview is fine. But if I update the preview I get the same screen as shown below. 
If I create a new model It shows a weird screen on the first preview and then the same on the following ones.

I tried to create the dataset on my device and on the Linux machine. But the behavior is the same.

I hope this could help to further investigate the problem.
