### ISSUE TITLE
Error in main.py : wrong environment variable being read for batch size

### ISSUE THREAD

**Issue by IUsedToBeAPygmy** [iperov/DeepFaceLab#52]
if 'DFL_BATCH_SIZE' in os.environ.keys():
            arguments.batch_size = int ( os.environ['**DFL_TARGET_EPOCH**'] )

should be

        if 'DFL_BATCH_SIZE' in os.environ.keys():
            arguments.batch_size = int ( os.environ['**DFL_BATCH_SIZE**'] )

**Comment by iperov** [comment]
someone pr to fix it

**Comment by iperov** [comment]
fxd
