### ISSUE TITLE
Something about 30x version

### ISSUE THREAD

**Issue by K0923** [iperov/DeepFaceLab#5200]
I try 30x version just released several days ago. And I got stuck when initialing models. 
![image](https://user-images.githubusercontent.com/22927025/102162668-8cb33900-3ec4-11eb-934f-b5a919531928.png)

**Comment by llzzll** [comment]
i stucked at 40% with 3080

**Comment by iperov** [comment]
![fwy9iW8 1](https://user-images.githubusercontent.com/8076202/102234047-526c8a80-3f0a-11eb-85d8-86c1deb7c0f7.jpg)

**Comment by K0923** [comment]
It's working now! Thanks!
