### ISSUE TITLE
Head extraction size

### ISSUE THREAD

**Issue by zabique** [iperov/DeepFaceLab#5201]
## Expected behavior

Extract head aligned with more tight crop of the head for frontal shots, so we can use lower model resolution and faster training, rather than trying to compensate with higher res.

## Actual behavior

Frontal aligned are extracted at 40% of aligned frame, so there is ~60% of frame resolution wasted. 

## Steps to reproduce

extract head (aligned)

![head small](https://user-images.githubusercontent.com/58276510/102229614-eaa34900-3ee3-11eb-84c7-56e7e9b9e762.jpg)

**Comment by iperov** [comment]
you are showing pictures from the training window, where samples are augmented : randomly sized.

**Comment by zabique** [comment]
![head small 2](https://user-images.githubusercontent.com/58276510/102485580-ba80b500-405f-11eb-9504-ca824bd5cbf6.jpg)

this is from another extracted Head dataset

**Comment by ghost** [comment]
Did you ever find the answer?

**Comment by zabique** [comment]
> Did you ever find the answer?

it's irrelevant.

**Comment by ghost** [comment]
Then close the issue, kurva.
