### ISSUE TITLE
Problem with XSeg training

### ISSUE THREAD

**Issue by Cioscos** [iperov/DeepFaceLab#5205]
I opened XSeg trainer and initially it gives to me thes exceptions:
https://pastebin.com/EAuGBVnz

After I update Nvidia driver and I reboot pc. Then I try again and it changes error:
![IMG_20201221_145941_843.jpg](https://user-images.githubusercontent.com/36228780/102806126-99e89000-43bc-11eb-8b65-9acadceb8030.jpg)
It's an error regarding the saving of model files. 

In the end, I solved creating paging file in the hdd where DFL is located.
Now problem is that my RAM or VRAM wasn't full.
So I don't understand why I needed to to that.

**Comment by Mombin** [comment]
you should use a newer virsion than python3.6.
or size down batch size.

**Comment by Cioscos** [comment]
> you should use a newer virsion than python3.6.
> or size down batch size.

It was XSeg editor and it jever gave this problem. In fact it is lighter than other trainer. Otherwise I don't understand why I needed to activate paging file if my memory does not fill up.

Regarding python, am I wrong or is it already included in the internal folder?

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
