### ISSUE TITLE
Windows (magnet link) last release torrent link broken?

### ISSUE THREAD

**Issue by Jord4n** [iperov/DeepFaceLab#5207]
I don't think there is a problem on my end but I'm trying to D/L the latest torrent version and the link seems to be broken?

**Comment by IndeecFOX** [comment]
No. 
Work

**Comment by Jord4n** [comment]
> 
> 
> No.
> Work

You are correct.  I didn't not have a torrent client installed I forgot it wasn't going to be a file but just a link.  My bad.
