### ISSUE TITLE
This Keeps Happening:

### ISSUE THREAD

**Issue by splinterz1** [iperov/DeepFaceLab#521]
![bugged](https://user-images.githubusercontent.com/58920647/70871042-d6580380-1f92-11ea-8749-812b1093487a.png)

**Comment by iperov** [comment]
try to change mainscripts\Extractor.py

line 

```
        super().__init__('Extractor', ExtractSubprocessor.Cli, no_response_time_sec, initialize_subprocesses_in_serial=(type != 'final'))
```

to
```
        super().__init__('Extractor', ExtractSubprocessor.Cli, no_response_time_sec)
```

**Comment by splinterz1** [comment]
![extract](https://user-images.githubusercontent.com/58920647/70953608-c6f3bb80-2061-11ea-948f-20cf5e124600.png)


Thank you :)

**Comment by iperov** [comment]
ok I will revert that fix then
