### ISSUE TITLE
data_src faceset extract.bat not working

### ISSUE THREAD

**Issue by IIIDrSt0neIII** [iperov/DeepFaceLab#5212]
I have a bug that is blocking me to do the [ data_src faceset extract.bat ] process. 
here is the error code : F tensorflow/core/common_runtime/gpu/gpu_util.cc:291] GPU->CPU Memcpy failed
but the [ data_dst faceset extract.bat ] works !

I have a RTX 2060 and a i5 9600kf (no intergrated graphics)

Thanks
and sorry for my english.

**Comment by IIIDrSt0neIII** [comment]
For me the problem was the first frame (black frame)

**Comment by yang973125061** [comment]
你怎么解决的，我遇到了同样的问题
How did you solve it? I had the same problem
