### ISSUE TITLE
MemoryError when the model is doing the 15minutes autosave

### ISSUE THREAD

**Issue by joedit-cmd** [iperov/DeepFaceLab#5213]
Hi I am using Windows 10 Pro, with the 12.22 DFL version, doing a pretraining model. The model started fine, and ran for about 15 minutes, until it is trying to autosave. The model failed to save and returned with the following error:

Error:
Traceback (most recent call last):
  File "E:\DFL\DeepFaceLab_NVIDIA_1222\_internal\DeepFaceLab\mainscripts\Trainer.py", line 170, in trainerThread
    model_save()
  File "E:\DFL\DeepFaceLab_NVIDIA_1222\_internal\DeepFaceLab\mainscripts\Trainer.py", line 69, in model_save
    model.save()
  File "E:\DFL\DeepFaceLab_NVIDIA_1222\_internal\DeepFaceLab\models\ModelBase.py", line 381, in save
    self.onSave()
  File "E:\DFL\DeepFaceLab_NVIDIA_1222\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 635, in onSave
    model.save_weights ( self.get_strpath_storage_for_file(filename) )
  File "E:\DFL\DeepFaceLab_NVIDIA_1222\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 59, in save_weights
    d_dumped = pickle.dumps (d, 4)
MemoryError
Done.
Press any key to continue . . .

**Comment by varunpro** [comment]
> Hi I am using Windows 10 Pro, with the 12.22 DFL version, doing a pretraining model. The model started fine, and ran for about 15 minutes, until it is trying to autosave. The model failed to save and returned with the following error:
> 
> Error:
> Traceback (most recent call last):
> File "E:\DFL\DeepFaceLab_NVIDIA_1222_internal\DeepFaceLab\mainscripts\Trainer.py", line 170, in trainerThread
> model_save()
> File "E:\DFL\DeepFaceLab_NVIDIA_1222_internal\DeepFaceLab\mainscripts\Trainer.py", line 69, in model_save
> model.save()
> File "E:\DFL\DeepFaceLab_NVIDIA_1222_internal\DeepFaceLab\models\ModelBase.py", line 381, in save
> self.onSave()
> File "E:\DFL\DeepFaceLab_NVIDIA_1222_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 635, in onSave
> model.save_weights ( self.get_strpath_storage_for_file(filename) )
> File "E:\DFL\DeepFaceLab_NVIDIA_1222_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 59, in save_weights
> d_dumped = pickle.dumps (d, 4)
> MemoryError
> Done.
> Press any key to continue . . .

post a screenshot of your settings and the error.. if you can

**Comment by iperov** [comment]
try to increase paging file to 16gb

**Comment by joedit-cmd** [comment]
Thanks iperov and varunpro. I suspected it was due to the lack of ram, and I had 30GB of paging file already. I increased it to 35GB just now but still encountered the issue. Here is the model settings. For this machine I only have 16GB of RAM. Thanks.

==            Model name: WF-Res416-v2-AB_SAEHD ==
==                                              ==
==     Current iteration: 370426                ==
==                                              ==
==--------------- Model Options ----------------==
==                                              ==
==            resolution: 416                   ==
==             face_type: wf                    ==
==     models_opt_on_gpu: True                  ==
==                 archi: df-ud                 ==
==               ae_dims: 480                   ==
==                e_dims: 120                   ==
==                d_dims: 120                   ==
==           d_mask_dims: 40                    ==
==       masked_training: True                  ==
==           uniform_yaw: True                  ==
==             adabelief: True                  ==
==            lr_dropout: n                     ==
==           random_warp: False                 ==
==             gan_power: 0.0                   ==
==       true_face_power: 0.0                   ==
==      face_style_power: 0.0                   ==
==        bg_style_power: 0.0                   ==
==               ct_mode: none                  ==
==              clipgrad: True                  ==
==              pretrain: True                  ==
==       autobackup_hour: 0                     ==
== write_preview_history: False                 ==
==           target_iter: 500000                ==
==           random_flip: False                 ==
==            batch_size: 4                     ==
==       eyes_mouth_prio: False                 ==
==                                              ==
==----------------- Running On -----------------==
==                                              ==
==          Device index: 0                     ==
==                  Name: TITAN RTX             ==
==                  VRAM: 24.00GB               ==
==                                              ==
==================================================
Starting. Target iteration: 500000. Press "Enter" to stop training and save model.
Error:
Traceback (most recent call last):
  File "E:\DFL\DeepFaceLab_NVIDIA_1220\_internal\DeepFaceLab\mainscripts\Trainer.py", line 186, in trainerThread
    model_save()
  File "E:\DFL\DeepFaceLab_NVIDIA_1220\_internal\DeepFaceLab\mainscripts\Trainer.py", line 68, in model_save
    model.save()
  File "E:\DFL\DeepFaceLab_NVIDIA_1220\_internal\DeepFaceLab\models\ModelBase.py", line 381, in save
    self.onSave()
  File "E:\DFL\DeepFaceLab_NVIDIA_1220\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 635, in onSave
    model.save_weights ( self.get_strpath_storage_for_file(filename) )
  File "E:\DFL\DeepFaceLab_NVIDIA_1220\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 59, in save_weights
    d_dumped = pickle.dumps (d, 4)
MemoryError
Done.

**Comment by iperov** [comment]
try default model settings

**Comment by iperov** [comment]
seems like 16GB RAM is not enough for such large models

**Comment by joedit-cmd** [comment]
Thanks and yes it must be the RAM. I am able to run smaller models and the same model on another computer with more RAM. Thanks again and I will close the issue.
