### ISSUE TITLE
Windows Magnet Release Download Link not working

### ISSUE THREAD

**Issue by CyberFlo2005** [iperov/DeepFaceLab#5218]
## Expected behavior

downloading a file / get redirected

## Actual behavior
nothing
## Steps to reproduce

click on the link

## Other relevant information
- using chrome

**Comment by iperov** [comment]
works fine

**Comment by HelloZorex** [comment]
yeah having the same problem. clicking the link does nothing

**Comment by iperov** [comment]
works fine
