### ISSUE TITLE
Request - Can we have the model summary file which we already generate in DFL; act as changelog –

### ISSUE THREAD

**Issue by varunpro** [iperov/DeepFaceLab#522]
## Expected behavior

I am trying different models on my end; with different values for different iterations as training and testing the results to see how they turnout as video at end – and how that can be used in different circumstances ……

A screenshot is attached to show – how they are saved at the moment:

![2019-12-16 (2)](https://user-images.githubusercontent.com/56723430/70885383-bb22dd80-1ffe-11ea-8349-528de04989e8.png)

## Actual behavior

As probably visible from the screenshot; it’s hard to keep track of them as time goes by …
- Also, after a month or so, if I were to come as see these naming scheme again, would be even hard for me to remember what was implied at the time of running them or saving them.
- lastly, if shared with someone else to work with; if nothing else it's real cumbersome to explain to them; how & what that naming scheme means etc ….

## Request

**Can we have the model summary file which we already generate in DFL; _act as changelog_** –

Wherein if a model is run with different settings from before: 
-	it reflects the older summary and 
-	then reflects below the new summary (with new values etc…) 

## Advantages 
-	easy to share with people with transparency 
-	can always count back what actions were taken so the model ended up looking as result; anytime.
-	faster testing time of DFL settings at user end; maybe even debugging

**Comment by TooMuchFun** [comment]
Not a bad idea! Look in `Trainer.py` and `ModelBase.py` if you are wondering where to start.

**Comment by varunpro** [comment]
thanks for the support :) 

sounds like fun ^_^ . Will give it a go .
