### ISSUE TITLE
OOM Errors with Version 15.12.2019

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#523]
Hi there
 with the new version 15.12.2019 i got OOM errors. with a model, that works fine with 14.12.2019
Details: with a RTX Titan, i was able to run Batchsize 8, now, with the same settings only batchsize 4.

==-------- Model Options --------==
==                               ==
==         autobackup: True      ==
==        sort_by_yaw: False     ==
==        random_flip: True      ==
==         resolution: 240       ==
==          face_type: f         ==
==         learn_mask: True      ==
==     optimizer_mode: 1         ==
==              archi: df        ==
==            ae_dims: 512       ==
==         ed_ch_dims: 21        ==
==   face_style_power: 0.0       ==
==     bg_style_power: 0.0       ==
==    apply_random_ct: False     ==
== true_face_training: False     ==
==           clipgrad: True      ==
==         batch_size: 4         ==
==        random_warp: True      ==
==            ct_mode: none      ==
==                               ==
==--------- Running On ----------==
==                               ==
==       Device index: 0         ==
==               Name: TITAN RTX ==
==               VRAM: 24.00GB   ==
==                               ==
===================================

any ideas?

**Comment by iperov** [comment]
new feature eats more vram

**Comment by blanuk** [comment]
okay. just wondering how much more used :) i close it :)
