### ISSUE TITLE
DFL training on RTX 3090 produces error "illegal instruction, core dumped" Linux but also some Windows installations

### ISSUE THREAD

**Issue by Joe-121** [iperov/DeepFaceLab#5230]
## Expected behavior

Training SAEHD or XSeg on DFL with RTX 3090, tensorflow 2.4.0

## Actual behavior

Python throws Error code of "illegal instruction, core dumped" on last line of DFL script which says "train"
This is despite Tensorflow 2.4.0 correctly recognising the RTX 3090, and despite cuda 11.0 or 11.1 and compatible nvidia drivers (455.28) all working correctly.

## Steps to reproduce

Install DFL on Windows or Linux as per Nagadit repository but use python 3.8 instead, and cudnn 8.0.5 and cudatoolkit 11.0 from Conda or 11.1 from Nvidia direct. Tensorflow 2.4.0
Also same error on my friends Windows 10 installation of DFL for RTX 3090.

**Solution:**
This will only apply to some people out there with older CPUs, but here is what I eventually found:

This is a Tensorflow 2.4.0 problem. Even if RTX 3090 works with TF 2.4.0, older CPUs do not in Linux and on some Windows builds it seems. TF requires AVX or AVX2 support. TF 2.3 supports AVX and AVX2. The tensorflow guys forgot to include AVX support in 2.4.0, despite it being compatible! Newer CPUs with AVX2 support will be ok.
I therefore compiled my own tensorflow for my machine, and this produced TF 2.5.0 which had AVX support. I can now fully train DFL using RTX 3090!

I don't have the Windows guide to compiling TF, but for linux TF you can use: https://www.tensorflow.org/install/source
I compiled with cudnn 8.0.5 dev files (filename libcudnn8-dev_8.0.5.39-1+cuda11.1) and cudatoolkit 11.1 installed.

This produced tensorflow 2.5.0 and this works great with RTX3090 and current DFL build.

Don't think this problem is common (less so on Windows machines) but hopefully of some use to someone out there

**Comment by iperov** [comment]
so all you need is to wait official tf 2.5.0 ?

**Comment by Joe-121** [comment]
Lol I suspect you are more patient than me, iperov! I could not wait!
Also I am not 100% sure that they will fix this. So many bugs seem to need fixing in tf 2.4.0
