### ISSUE TITLE
pressing "L" key while in training preview switches to command window

### ISSUE THREAD

**Issue by frighte** [iperov/DeepFaceLab#5232]
## Expected behavior

2021 releases - pressing "L" key is supposed to change the graph granularity in the training preview window

## Actual behavior

"L" key now just switches to command window or brings it to the front. Can get around by pressing shift+L in preview window

## Steps to reproduce

Just hit L at the preview window.

**Comment by robustini** [comment]
Here the "L" key does what it's supposed to do, are you sure?

**Comment by frighte** [comment]
You may close this issue. I traced it back to the latest windows 10 edition
update which I performed as a requirement of the lastest dfl build. Seems
to work fone back on 1909
