### ISSUE TITLE
Faceset creation guide link broken.

### ISSUE THREAD

**Issue by sergiobd** [iperov/DeepFaceLab#5240]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior
I click in the link for the "faceset creation guide", and magic! a link with that content appears on my browser.
## Actual behavior
A page on the forum saying that that post does not exists appears.

## Steps to reproduce
click on the link "faceset creation guide"

## Other relevant information
None

**Comment by ThomasBardem** [comment]
It looks like the faceset guides is now a part of the main guide: https://mrdeepfakes.com/forums/thread-guide-deepfacelab-2-0-guide?pid=18459#pid18459

**Comment by iperov** [comment]
updated
