### ISSUE TITLE
what happened to "true face power"?

### ISSUE THREAD

**Issue by Quieky** [iperov/DeepFaceLab#5244]
just asking... missing true face power in the newest version, gives better results (face looking more like src), still prefer to work with older versions for this reason

**Comment by ThomasBardem** [comment]
New default architecture is LIAE-UD which doesn't have TF option, pay attention to model parameters when starting new model, DF type architectures still feature TF.

**Comment by Quieky** [comment]
thanks a lot... i feel like such a noob now lol... i mean, actually i AM a noob, but usually learning fast... i have fun working with dfl and it forces me to learn a lot about computers too :)
