### ISSUE TITLE
Issue training on GeoForce GTX 1060 with DFL 2.x

### ISSUE THREAD

**Issue by leducjjr** [iperov/DeepFaceLab#5250]
Hi, please can someone review and advise?  This looks like an issue between my hardware/software and tensorflow, but I've reached the end of my analysis effort ideas.  I've been working on this for a while now,

I'm trying different things like updating drivers, using different versions of tensorflow-gpu (which massively failed to work, haha), downgrading my CUDA setup, etc.  I'm posting here in the hopes that 1) someone may have seen this and addressed it already and will share the solution so I can fix my kit and 2) others with the same issue can find the solution. 

I know it's an issue related to tensorflow but i'm posting it here because this may also impact other DFL users who may find this thread to be useful.

## Expected behavior

In DFL 1.x I could train on my GeoForce GTX 1060 with no problem.  

## Actual behavior

When I updated by kit to use DFL 2.x and updated dependencies, I received the message below when trying to use the GPU.  

Error: No OpKernel was registered to support Op 'DepthToSpace' used by node DepthToSpace (defined at D:\adm\dfl\code\trunk\core\leras\ops\__init__.py:336)  with these attrs: [block_size=2, T=DT_FLOAT, data_format="NCHW"]

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

When I try to use the GPU I get the error message and the training session halts.

Using the CPU works, but isn't sustainable.  CPU is at 100% all the time and progress is tremendously slow.

I looked up the error message and it's coming from tensorflow code on github. I see solutions but they involve coding that I'm not comfortable applying to my local version of DFL.  

It looks like tensorflow can find what it's looking for ("NHWC") on my CPUs but not on my GPUs.  I know it's a tensorflow message because I accidentally found the source code on GitHub where the text "data_format="NCHW"" in it.  Like a doofus I forgot to bookmark the page and can't find it again.  I'm downloading the tensorflow repo now to try to provide better detail but that'll take a while. When I find the module again I'll add that info to this post as a comment.

## Steps to reproduce

Ran my handy dandy batch file

## Other relevant information
- GFX card: GeForce GTX 1060 6GB

- **Command lined used:  This is the actual command line.  I created a batch file that uses relative pathing to get to the main.py script and to reference the src and dst and model folders.

python "..\..\..\code\trunk\main.py" train --training-data-src-dir "..\..\src\kristi\faces-all" --training-data-dst-dir "..\..\dst\liliana\pics\faces" --model-dir "..\..\models\liliana\pics(kristi)" --model "SAEHD"-   

- **Operating system and version:** Windows 10
- **Python version:** Python 3.6.8
- dependencies loaded using pip: https://github.com/iperov/DeepFaceLab.git/trunk/requirements-cuda.txt
- CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
- CUDAnn = cudnn-10.2-windows10-x64-v8.0.5.39
- VC_redist.x64 downloaded and installed as per TensorFlow's documentation for Windows users

## Full session and error message

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>set DST=liliana\pics

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>set SRC=kristi

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>set SRCDIR=..\..\src\kristi\faces-all

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>set DSTDIR=..\..\dst\liliana\pics\faces

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>set MODELDIR=..\..\models\liliana\pics(kristi)

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>set MODEL=SAEHD

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>set PRGPATH=..\..\..\code\trunk

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>md "..\..\models\liliana\pics(kristi)"
A subdirectory or file ..\..\models\liliana\pics(kristi) already exists.

D:\adm\dfl\data\batch_scripts\liliana-pics(kristi)>python "..\..\..\code\trunk\main.py" train --training-data-src-dir "..\..\src\kristi\faces-all" --training-data-dst-dir "..\..\dst\liliana\pics\faces" --model-dir "..\..\models\liliana\pics(kristi)" --model "SAEHD"
Running trainer.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : new - latest
 :
0
Loading new_SAEHD model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1060 6GB

[0] Which GPU indexes to choose? :
0

Initializing models:   0%|                                                                       | 0/5 [00:00<?, ?it/s]
Error: No OpKernel was registered to support Op 'DepthToSpace' used by node DepthToSpace (defined at D:\adm\dfl\code\trunk\core\leras\ops\__init__.py:336)  with these attrs: [block_size=2, T=DT_FLOAT, data_format="NCHW"]
Registered devices: [CPU]
Registered kernels:
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_QINT8]

         [[DepthToSpace]]

Errors may have originated from an input operation.
Input Source operations connected to node DepthToSpace:
 LeakyRelu_4 (defined at D:\adm\dfl\code\trunk\core\leras\archis\DeepFakeArchi.py:58)
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1358, in _run_fn
    self._extend_graph()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'DepthToSpace' used by {{node DepthToSpace}} with these attrs: [block_size=2, T=DT_FLOAT, data_format="NCHW"]
Registered devices: [CPU]
Registered kernels:
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_QINT8]

         [[DepthToSpace]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\adm\dfl\code\trunk\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug,
  File "D:\adm\dfl\code\trunk\models\ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "D:\adm\dfl\code\trunk\models\Model_SAEHD\Model.py", line 611, in on_initialize
    model.init_weights()
  File "D:\adm\dfl\code\trunk\core\leras\layers\Saveable.py", line 104, in init_weights
    nn.init_weights(self.get_weights())
  File "D:\adm\dfl\code\trunk\core\leras\ops\__init__.py", line 48, in init_weights
    nn.tf_sess.run (ops)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'DepthToSpace' used by node DepthToSpace (defined at D:\adm\dfl\code\trunk\core\leras\ops\__init__.py:336)  with these attrs: [block_size=2, T=DT_FLOAT, data_format="NCHW"]
Registered devices: [CPU]
Registered kernels:
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_QINT8]

         [[DepthToSpace]]

Errors may have originated from an input operation.
Input Source operations connected to node DepthToSpace:
 LeakyRelu_4 (defined at D:\adm\dfl\code\trunk\core\leras\archis\DeepFakeArchi.py:58)

**Comment by leducjjr** [comment]
This message comes from the module linked to below.  Its almost as if it thinks my GPU is a CPU.  I guess that based on the comment and if statement that precedes the error being thrown.

So somehow I must fix my kit to make tensorflow - or DFL recognise my GPU as such.

      # Run this test only if only CPU device is available
      if all(x.device_type == "CPU" for x in device_lib.list_local_devices()):
...

            errors_impl.InvalidArgumentError,
            "No OpKernel was registered to support Op 'DepthToSpace'"):

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/depthtospace_op_test.py

**Comment by leducjjr** [comment]
One other thing.  This same setup works on my other machine which has a GTX 1080 Ti card.  Same specs s above but a different card.  

I don't want to shell out another $XXXX.XX for another card when this 1060 was working fine a few updates ago :P

**Comment by yangmuzhi** [comment]
So how to fix it? override the tensorflow source code?

**Comment by leducjjr** [comment]
> So how to fix it? override the tensorflow source code?

I'm not looking for that and don't think any local mods I might do will work in the long run.  I'm wondering if anyone else has this issue as well.  

I'm looking for ideas of what I can configure or (re)install that might get my cards to be recognized as you devices.  All evidence points to the idea that the setup thinks these are cpus and is looking for cpu properties that don't exist on gpu cards.

**Comment by coloneldbugger** [comment]
Did you ever find a solution to this problem? I have encountered it with CUDA 10.2 and 11.2 on Ubuntu 16.04 and 20.04

**Comment by leducjjr** [comment]
No unfortunately I did not.  I'm nervous about touching the machine that is working as expected, ha.


It's interesting this is happening on different operating systems.  That tells me it's not necessarily the drivers on my two Windows 10 machines.


This makes for a stronger case that the tensorflow code itself isn't correctly identifying the cards as gpu but as cpu.  I'm not comfortable debugging this if that's the case.


Get Outlook for Android

**Comment by coloneldbugger** [comment]
Can you share the versions of linux, tensor flow, Cuda, libcudnn, nvidia driver  you are using on a machine that has it working?  Did you use default OS package manager and packages or use NVidia installer?

**Comment by leducjjr** [comment]
Unfortunately I don't use Linux.  I have three Windows 10 machines.  I can post the machine details of the one that is working, but that may not help with your Linux issues.  It may help other Windows users though.


Get Outlook for Android

**Comment by leducjjr** [comment]
Please mark this as resolved.  I resolved the issue by taking the following actions on one of the impacted Windows 11 machines.  There's probably more than needed here to address the issue but this took are of the issue and now tensorflow recognises the GPU.

1. uninstalling Python and deleting all the associated libraries under "C:\Program Files\Python36"
2. reinstalling Python 3.6.0 (old I know but I wanted to use what last worked)
2. uninstalling CUDA 9.0
3. downloading and installing the following - CUDA 11 (cuda_11.1.1_456.81_win10.exe), cudnn (cudnn-11.1-windows-x64-v8.0.4.30.zip)
4. downloading and installing the following - CUDA 10 (cuda_10.2.89_win10_network.exe), cuda_10.2.2_win10.exe, cuda_10.2.1_win10.exe
5. running pip install on all the dependencies in the DFL requirements list for cuda

Ran the following from a Windows command prompt to ensure the GPU was recognised:
1. python
2. import tensorflow as tf
3. tf.config.get_visible_devices(device_type=None)

Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-06-27 16:07:21.338046: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
>>> tf.config.get_visible_devices(device_type=None)
2021-06-27 16:07:29.621410: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-27 16:07:29.622540: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-06-27 16:07:29.651807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.835GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-06-27 16:07:29.652023: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-27 16:07:29.665085: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-06-27 16:07:29.665249: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-06-27 16:07:29.670005: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-06-27 16:07:29.671930: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-06-27 16:07:29.679448: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-06-27 16:07:29.684936: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-06-27 16:07:29.686087: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-06-27 16:07:29.687294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
