### ISSUE TITLE
commit an error caused by color transfer mode

### ISSUE THREAD

**Issue by lz2004xxw** [iperov/DeepFaceLab#5258]
lacation : MergedMask.py  Line 302
description : After color transfer, out_face_bgr will be affine-transformed into new_out, however, the last param "cv2.BORDER_TRANSPARENT" may cause invalid value in new_out, which may cause artifacts in out_img, just as following:
![image](https://user-images.githubusercontent.com/7788572/105704687-23562980-5f4a-11eb-8775-6df8ae114023.png)

It can be solved by using "borderValue=(255,255,255)" instead of "cv2.BORDER_TRANSPARENT" or just remove "cv2.BORDER_TRANSPARENT".

**Comment by iperov** [comment]
can you test all cases, what difference with and without cv2.BORDER_TRANSPARENT ?

**Comment by lz2004xxw** [comment]
> can you test all cases, what difference with and without cv2.BORDER_TRANSPARENT ?
@param borderMode pixel extrapolation method (see #BorderTypes); when
    .   borderMode=#BORDER_TRANSPARENT, it means that the pixels in the destination image corresponding to
    .   the "outliers" in the source image are not modified by the function.
I save the affine-transformed image as .png, as following:

![messigray2](https://user-images.githubusercontent.com/7788572/105818272-ada59880-5ff1-11eb-8583-e74a3e33c2f2.png)
with cv2.BORDER_TRANSPARENT
![messigray3](https://user-images.githubusercontent.com/7788572/105818288-b1391f80-5ff1-11eb-9929-949b63b3dcff.png)
without cv2.BORDER_TRANSPARENT

I am not sure how opencv set the outlier pixel value when borderMode=BORDER_TRANSPARENT.
I save the affine-transformed image as .png, as following:

![messigray2](https://user-images.githubusercontent.com/7788572/105818272-ada59880-5ff1-11eb-8583-e74a3e33c2f2.png)
with cv2.BORDER_TRANSPARENT
![messigray3](https://user-images.githubusercontent.com/7788572/105818288-b1391f80-5ff1-11eb-9929-949b63b3dcff.png)
without cv2.BORDER_TRANSPARENT

I am not sure how opencv set the outlier pixel value when borderMode=BORDER_TRANSPARENT.

**Comment by iperov** [comment]
I need examples using DFL, not random examples.

**Comment by lz2004xxw** [comment]
> I need examples using DFL, not random examples.

Following is out_face_bgr‘s affine-transformed result
![messigray11](https://user-images.githubusercontent.com/7788572/105820006-ee9eac80-5ff3-11eb-89ef-08d45e25cfde.png)
with BORDER_TRANSPARENT
![messigray4](https://user-images.githubusercontent.com/7788572/105820039-fbbb9b80-5ff3-11eb-935f-753009f43ba1.png)
without BORDER_TRANSPARENT

**Comment by lz2004xxw** [comment]
fixed
