### ISSUE TITLE
Merging stuck @100% using merge quick96

### ISSUE THREAD

**Issue by BjarneDesmetBrainJam** [iperov/DeepFaceLab#5259]
Training succeeds, merging is stuck at 100%.
Merging completed but is not exporting the video into the workspace. 
Left it do his thing but keeps stuck at this point and no error is thrown.

I am using the interactive merger. 

Anybody has this problem? 
Thanks!

**Comment by wangjinyu124419** [comment]
https://mrdeepfakes.com/forums/threads/merge-quick96-stuck-at-0-and-hourglass-icon.7767/

**Comment by wangjinyu124419** [comment]
https://mrdeepfakes.com/forums/threads/merge-quick96-stuck-at-0-and-hourglass-icon.7767/#post-44312
