### ISSUE TITLE
Request - Does support face expression emulation in future or have any suggestion in this case ?

### ISSUE THREAD

**Issue by square690410** [iperov/DeepFaceLab#526]
After running several times.
mask feature is great but face expression emulation is little weak.
I try to use true face. (src open mouth and teeth , dst is close mouth). 
the effect doesn't expect.

**Comment by TooMuchFun** [comment]
get more better facial expressions in src face set. increase encoder dimensions.

**Comment by kevinfishburne** [comment]
Should you increase ae_dims, e_ch_dims, or d_ch_dims? I've been having the same issue.
