### ISSUE TITLE
settings for highend workstations

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#527]
Hi :)
i found 2 settings (converter and extraction) which doubles the speed on my system.
could u do a list which settings i can change to use the fuul power?
one i found was the used cores in the converter file and the extraction file.
Converting increased from 2.5 it/s to over 5 it/s.

I know, u have to set the settings for common systems. but it scale not as it should :/

My sys: 32core and 64gb ram, 2x rtx 2080ti.

Greets and thanks for any inputs :)

**Comment by TooMuchFun** [comment]
It is not very possible to compile this type of list. There are too many variables to predict things like this. Data and computer specs vary too much to even make guesses. Please experiment with yours and report back.
