### ISSUE TITLE
3090 only quick96 works

### ISSUE THREAD

**Issue by Nde917** [iperov/DeepFaceLab#5272]
Just wanted let you know
I have no luck with SAEHD (it starts then crashes with long error list), with my nw 3090 i only have luck with quick96, anyone else?

running the latest win10, i9-9900k, 32GB ram.
build_01_04_2021

**Comment by jasonlbx13** [comment]
I meet the same error, Increase virtual memory may be helpful

**Comment by Nde917** [comment]
> 
> 
> I meet the same error, Increase virtual memory may be helpful

Thanks this helped!
