### ISSUE TITLE
blending face seems unnatural between fake face and target bg, any help?

### ISSUE THREAD

**Issue by lvZic** [iperov/DeepFaceLab#5274]
![temp4cj (1)](https://user-images.githubusercontent.com/7788572/106884742-a6cb0400-671c-11eb-8315-f808dfad881b.png)

 I have tried all the color transfer modes, the blending color gap still exists.

**Comment by Dian-Yi** [comment]
the same issue as you

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
