### ISSUE TITLE
Can't train after Dec 23 changes

### ISSUE THREAD

**Issue by nhojyer07** [iperov/DeepFaceLab#528]
I can't train or convert even with a new model after some commits on Dec 23. The error is this:

...
Time to end session: 12 hours
Traceback (most recent call last):
  File "DeepFaceLab/main.py", line 19, in <module>
    multiprocessing.set_start_method("spawn")
  File "/usr/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

**Comment by bladenow** [comment]
me too
![QQ20191224-0](https://user-images.githubusercontent.com/46339824/71370536-25341780-25e9-11ea-9cef-9337e7756106.png)

**Comment by TooMuchFun** [comment]
might be a colab environment issue. i get for extract step in colab too.

**Comment by iamdylanavery** [comment]
same issue here, glad it's not just me

**Comment by varunpro** [comment]
same here : -
 
/content
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Creating workspace archive ...
Archive created!
Time to end session: 12 hours
Traceback (most recent call last):
  File "DeepFaceLab/main.py", line 19, in <module>
    multiprocessing.set_start_method("spawn")
  File "/usr/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set  

plus 
![2019-12-24](https://user-images.githubusercontent.com/56723430/71393650-93053100-2633-11ea-947a-f2685ff703e3.png)

**Comment by varunpro** [comment]
its working now :) 

![2019-12-24 (1)](https://user-images.githubusercontent.com/56723430/71401276-5f380480-264f-11ea-8dcb-6c2271b800bd.png)
