### ISSUE TITLE
Code guidelines

### ISSUE THREAD

**Issue by jmhummel** [iperov/DeepFaceLab#5287]
Hi @iperov, I'm interested in working on this project, and contributing improvements to the general code quality, such as refactoring functions to be more pythonic, updating code to better conform to PEP8 style/coding conventions, adding unit tests, etc.

I wanted to reach out before I started, so I could find out how open you'd be to Pull Requests of this nature. I want to make sure that the time I spend making changes will lead to accepted Pull Requests.

What are your thoughts on code quality / refactor PRs?
Do you had any specific tasks that you wanted assistance with?

**Comment by iperov** [comment]
> functions to be more pythonic, updating code to better conform to PEP8 style/coding conventions, adding unit tests, etc.

thanks, but such modifications are not required. And I have no time to check and accept PRs.
Also users will not be happy to meet new bugs (which are inevitable in refactoring) without new useful functionality.
DFL is not about user convenience.
So if you want to help, it is better to discover and experiments with new deepfake methods.

**Comment by jmhummel** [comment]
> I have no time to check and accept PRs. Also users will not be happy to meet new bugs

If you're concerned about bugs, and time spent reviewing PRs, then let me assist with the development of a CI/CD (continuous integration) pipeline. I could set up a Github Actions workflow for automated testing, and begin writing unit tests covering the code. This effort would be focused on lowering the risk of future bugs, and saving you time.

With a CI/CD pipeline, we could even automate the creation of the Windows distributable, saving you even more time.

I've built these out for many projects in my main role as a software engineering consultant, and seen the outcomes good CI/CD leads to: 

1. Less time wasted by devs on bugs and process.
2. Less bugs which make ultimately make their way into our client's code.

This would be something that would have a long-term, positive effect on the future of DFL, and I'm willing to take the lead on this effort.

> it is better to discover and experiments with new deepfake methods.

With regards to refactoring/code style, I believe that we can make model exploration/development easier with improvements to the overall code structure. Better separation of components/modules will make it easier to test things in isolation. In conjunction with unit testing/code coverage (via CI/CD), it could reduce the effort needed to review PRs for model improvement. 

I want to continue encouraging this project's success, and I believe that improvements like these will have a strong positive effect on:

- Lowering your workload spent on repository maintenance.
- Raising the quality of outside Pull Requests with automated tests/checks
- Reducing the risk of bugs in the future
- Improving the readability of code, so that more outside developers can assist with model development.

**Comment by iperov** [comment]
as I said
it is better to discover and experiments with new deepfake methods.
Convenient software not so important.

Currently I am working on new deepfake-related software with GUI.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
