### ISSUE TITLE
Python crashes when doing merge quick96

### ISSUE THREAD

**Issue by AnkurSaini07** [iperov/DeepFaceLab#5288]
## Expected behavior
I am on windows system and I have rtx 3070 card I am using **DeepFaceLab_NVIDIA_build_01_04_2021**  build.
After finishing training successfully I ran the **7) merge Quick96** file, it loads the alignment successfully but after computing motion vector it stuck at 100% and a popup opens which shows **Python has stopped working.**

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior
[](url)
![image](https://user-images.githubusercontent.com/33354822/110216982-a10d3d80-7ed7-11eb-83cf-19d34c147c9b.png)

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

After finishing Training run merge quick 96 file.

## Other relevant information
OS Windows 10
python 3.6.8

**Comment by Bropx024** [comment]
Hey man, did you fix this? I am getting the same issue
