### ISSUE TITLE
converted to mov(lossless+alpha) - No alpha channel in output

### ISSUE THREAD

**Issue by ankurspadale** [iperov/DeepFaceLab#529]
## Expected behavior

Exported .mov/.mp4 file should have alpha channel in it to work with Video Processing tools later like Adobe after effects, etc.

## Actual behavior

Exported .mov/.mp4 file DOES NOT HAVE alpha channel in it. Only RGB color space it has.

## Steps to reproduce

Train, then convert with (lossless+alpha).

## Other relevant information
![Capture](https://user-images.githubusercontent.com/18092535/71416045-d1770c00-2684-11ea-9da2-c34353e72efc.PNG)

- **Operating system and version:** Windows 10 for convert, and Google Collab for training

**Comment by TooMuchFun** [comment]
Convert exports the PNGs with alpha. The movie making is ffmpeg and not DFL code. If you want to use special ffmpeg options you must customize the batch files on your own.

**Comment by ankurspadale** [comment]
> Convert exports the PNGs with alpha. The movie making is ffmpeg and not DFL code. If you want to use special ffmpeg options you must customize the batch files on your own.


![image](https://user-images.githubusercontent.com/18092535/71445897-e8306800-2743-11ea-8892-2313a35e94f1.png)

What you are saying is about "7) convert SAE.bat".

The issue is about "8) converted to mov(lossless+alpha).bat" which converts to movie, not exports to PNGs.
