### ISSUE TITLE
Running merge quick69 has stuck in computing motion vector ....

### ISSUE THREAD

**Issue by tuanpvse** [iperov/DeepFaceLab#5292]
I'm running merge quick69 and stuck in this computing motion vector. I don't know how to fix because it isn't report any error

Running merger.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : lananh - latest
 : 0
0
Loading lananh_Quick96 model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1060 6GB

[0] Which GPU indexes to choose? : 0
0

Initializing models: 100%|###############################################################| 4/4 [00:00<00:00, 11.19it/s]
=============== Model Summary ===============
==                                         ==
==        Model name: lananh_Quick96       ==
==                                         ==
== Current iteration: 53918                ==
==                                         ==
==------------- Model Options -------------==
==                                         ==
==        batch_size: 4                    ==
==                                         ==
==-------------- Running On ---------------==
==                                         ==
==      Device index: 0                    ==
==              Name: GeForce GTX 1060 6GB ==
==              VRAM: 6.00GB               ==
==                                         ==
=============================================
[y] Use interactive merger? ( y/n ) : y
[24] Number of workers? ( 1-24 ?:help ) : 24
24
Collecting alignments: 100%|######################################################| 2768/2768 [00:07<00:00, 357.98it/s]
Computing motion vectors: 100%|##################################################| 2790/2790 [00:01<00:00, 1637.43it/s]

**Comment by Bropx024** [comment]
Hey @tuanpvse , I too am getting this error / issue, how did you resolve this? Thanks

**Comment by Mshriver2** [comment]
> Hey @tuanpvse , I too am getting this error / issue, how did you resolve this? Thanks

@Bropx024 did you ever figure this out?

**Comment by ytric** [comment]
I got the same issue here

```
`Running merger.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : saksa - latest
 :
0
Loading saksa_Quick96 model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : NVIDIA GeForce RTX 3070 Ti

[0] Which GPU indexes to choose? :
0

Initializing models: 100%|###############################################################| 4/4 [00:00<00:00, 14.80it/s]
================== Model Summary ==================
==                                               ==
==        Model name: saksa_Quick96              ==
==                                               ==
== Current iteration: 21126                      ==
==                                               ==
==---------------- Model Options ----------------==
==                                               ==
==        batch_size: 2                          ==
==                                               ==
==----------------- Running On ------------------==
==                                               ==
==      Device index: 0                          ==
==              Name: NVIDIA GeForce RTX 3070 Ti ==
==              VRAM: 5.32GB                     ==
==                                               ==
===================================================
[y] Use interactive merger? ( y/n ) :
y
[24] Number of workers? ( 1-24 ?:help ) :
24
Collecting alignments: 100%|##########################################################| 44/44 [00:00<00:00, 360.33it/s]
Computing motion vectors: 100%|####################################################| 107/107 [00:00<00:00, 6288.05it/s]

`
```
