### ISSUE TITLE
Tensorflow Error At Start of Training

### ISSUE THREAD

**Issue by sourcesync** [iperov/DeepFaceLab#5309]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

I expected not to see any Tensorflow errors at the start of training.

## Actual behavior

I got the following error:

  File "/home/george/anaconda3/envs/dfl/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/george/anaconda3/envs/dfl/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/george/anaconda3/envs/dfl/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/george/anaconda3/envs/dfl/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'DepthToSpace' used by node DepthToSpace (defined at /Projects/xtr/DeepFaceLab/core/leras/ops/__init__.py:336)  with these attrs: [T=DT_FLOAT, data_format="NCHW", block_size=2]
Registered devices: [CPU]
Registered kernels:
  device='GPU'; T in [DT_QINT8]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]

         [[DepthToSpace]]

Errors may have originated from an input operation.
Input Source operations connected to node DepthToSpace:
 LeakyRelu_4 (defined at /Projects/xtr/DeepFaceLab/core/leras/archis/DeepFakeArchi.py:58)

## Steps to reproduce

I wrote my own bash script which performs all the necessary steps.  

Here is the training command in my script:

DeepFaceLab/main.py train --training-data-src-dir $workspace_dir/data_src/aligned --training-data-dst-dir $workspace_dir/data_dst/aligned --pretraining-data-dir pretrain --model-
dir workspace/model --model SAEHD

## Other relevant information

Python 3.8 via Anaconda
Ubuntu Linux 18.04
I cloned the latest repo as of 04/14/2021
I used the requirements-cuda.txt to pip install the python dependencies

**Comment by luisdemarchi** [comment]
@gosha1128 did you get through this problem? I got the same error using a macOS with m1 architecture

**Comment by gosha1128** [comment]
I did...I believe I had to install the right version of CUDA.  I don't
remember which and I no longer have access to that machine.  Sorry I can't
be more helpful.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
