### ISSUE TITLE
 Trained on colab with some warnings

### ISSUE THREAD

**Issue by bladenow** [iperov/DeepFaceLab#531]
The problem is solved！
Please close！

**Comment by chervonij** [comment]
@bladenow 
This is just warnings, not errors.
Don't create issue if all works fine.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
I have to direct most outputs in collab to devnull because of the annoyance for most notebooks for most anything I run there.
