### ISSUE TITLE
 F tensorflow/core/common_runtime/dml/dml_upload_heap.cc:56] HRESULT failed with 0x887a0005: chunk->resource->Map(0, nullptr, &upload_heap_data)

### ISSUE THREAD

**Issue by fmj4912** [iperov/DeepFaceLab#5321]
## Expected behavior
Train model

## Actual behavior
When training model (Both Quick96 and SAEHD) the console will give me an error after training for some time (very random, sometimes it lets me train for hours, sometimes within minutes).

This started happening a week after using the program and googling the error does not give me anything relevant

	================== Model Summary ===================
	==                                                ==
	==        Model name: vas_Quick96                 ==
	==                                                ==
	== Current iteration: 1774                        ==
	==                                                ==
	==---------------- Model Options -----------------==
	==                                                ==
	==        batch_size: 4                           ==
	==                                                ==
	==------------------ Running On ------------------==
	==                                                ==
	==      Device index: 0                           ==
	==              Name: NVIDIA GeForce GTX 1060 6GB ==
	==              VRAM: 5.16GB                      ==
	==                                                ==
	====================================================
	Starting. Press "Enter" to stop training and save model.
	[18:15:56][#002900][0305ms][0.5700][0.5533]
	[18:19:16][#004034][0189ms][0.5084][0.4724]
	2021-04-30 18:20:51.793210: F tensorflow/core/common_runtime/dml/dml_upload_heap.cc:56] HRESULT failed 		with 0x887a0005: chunk->resource->Map(0, nullptr, &upload_heap_data)
	Press any key to continue . . .

What could be the reason for this error?

## Steps to reproduce
Just starting training and it will happen eventually

## Other relevant information
- **Operating system and version:** Windows 10

**Comment by RoWTobi** [comment]
I also have the same on my 1080 :(

**Comment by fmj4912** [comment]
> I also have the same on my 1080 :(
> I think I fixed it by doing tenorflow update (in the project). Simply go to the folder "DeepFake\ _internal\python-3.6.8", open the terminal and enter "python -m pip install tensorflow". I hope this could help you :)

Thanks! I will try this! and update my comment

**Comment by fmj4912** [comment]
Okay so updating it did get rid of this error, but I got other errors instead. I then also realised I was a bit stupid and had installed the directx 12 one instead of DeepFaceLab_NVIDIA_up_to_RTX2080Ti

Since using this instead and updating I havent got any errors. So if others are facing the same issue try this. I'm closing this issue as it seems to be working for me now.
