### ISSUE TITLE
GenericXSeg_04_30_2021 - why just one 'XSeg_256.npy' file with no supporting data files?

### ISSUE THREAD

**Issue by Orchoidizer** [iperov/DeepFaceLab#5326]
Is there any instructions on how to implement the 'GenericXSeg_04_30_2021'? 
Why is it just one 'XSeg_256.npy' file with no other supporting data files? 
Where does it go?

**Comment by iperov** [comment]
try last build

**Comment by Orchoidizer** [comment]
> 
> 
> try last build

Brilliant! Thank you as always for your hard work and sharing it to the world

**Comment by shafeeqjadoon** [comment]
@iperov what about one for linux, there is no "generic xseg".Do I just convert the .bat for windows to .sh for linux?

**Comment by iperov** [comment]
i dont support linux
