### ISSUE TITLE
Issue extracting latest release on Win10, 30 series build

### ISSUE THREAD

**Issue by fakinlike90** [iperov/DeepFaceLab#5343]
While trying to install the latest build of the Windows RTX 3000 series release, I am running into the issue below:

<img width="884" alt="Capture" src="https://user-images.githubusercontent.com/85262518/120565743-97a24d00-c3c2-11eb-83da-d8a53ed95cb3.PNG">

**Comment by fakinlike90** [comment]
The first part of both errors is "Cannot open output file"

**Comment by labels168** [comment]
Restricted long directory, please try to unzip the compressed file in the following directory.

**Comment by labels168** [comment]
For example: c:\

**Comment by fakinlike90** [comment]
Got it. Thanks
