### ISSUE TITLE
Missing .bat files?

### ISSUE THREAD

**Issue by Hapekk** [iperov/DeepFaceLab#5345]
I recently download DFL using torrent (DeepFaceLab_NVIDIA_up_to_RTX2080Ti_build_06_02_2021.exe). 
I can't run it bcz of this error.

'_internal\setenv.bat' is not recognized as an internal or external command,
operable program or batch file.
'""' is not recognized as an internal or external command,
operable program or batch file.

I found out I might be missing .bat files.
![GIT](https://user-images.githubusercontent.com/85490373/121003927-5b8a3600-c78e-11eb-8f3d-af02f5fb55fd.png)

So my question is do I need to download the whole DFL exe file?

**Comment by ReynoJ** [comment]
Same issue here, downloaded via the MEGA and extracted it onto the C:\. Not sure how to proceed.

**Comment by iTaKK** [comment]
The bat files are 1 folder back

**Comment by Hapekk** [comment]
I know that, but I'm missing for example setenv.bat 
https://www.youtube.com/watch?v=8W9uu-pVOIE
Compared to this video I'm missing 4 files

**Comment by iperov** [comment]
I just checked the build

![explorer_2021-06-09_20-48-06](https://user-images.githubusercontent.com/8076202/121395996-fe47dd80-c963-11eb-9e8e-45ca36628f52.jpg)
