### ISSUE TITLE
RTX 3070 Ti VRAM/Merge issue

### ISSUE THREAD

**Issue by MaDaZi** [iperov/DeepFaceLab#5354]
I switched graphics card from 2070 super to 3070 ti. I am using the latest RTX3000 DFL build with the latest nvidia drivers. 

The VRAM is shown to be 6.43GB, which of course is incorrect. It should be 8gb.

When trying to merge, it gets stuck after computing motion vectors.

Steps to reproduce:
- Using a 3070 ti.

PC specs:
- AMD Ryzen 9 5950X
- Windows 10 pro
- 32GB ram

![merge](https://user-images.githubusercontent.com/86497522/123485869-4b39de00-d60b-11eb-80b8-f0a18179363c.jpg)

**Comment by iperov** [comment]
it is correct. shows available ram, not total.

**Comment by iperov** [comment]
use 8 workers
