### ISSUE TITLE
Looks like my Model is corrupt, can i restore it?

### ISSUE THREAD

**Issue by Nde917** [iperov/DeepFaceLab#5357]
Hello, i just did a 4hour train SAEHD, when i came back monitor was black but train was still running i could hear the GPU fan,
i pressed Enter and the Noise stopped slowly. I waited a bit and did a cold restart, but now i get this error if i try to train further:

Loading Model1_SAEHD model...
Traceback (most recent call last):
  File "F:\DFL\DFL_07_01_2021\_internal\DeepFaceLab\mainscripts\Merger.py", line 52, in main
    cpu_only=cpu_only)
  File "F:\DFL\DFL_07_01_2021\_internal\DeepFaceLab\models\ModelBase.py", line 144, in __init__
    model_data = pickle.loads ( self.model_data_path.read_bytes() )
_pickle.UnpicklingError: invalid load key, '\x00'.

looks like the Model is damaged? Any way i can safe it?
I run on latest WiN10 with 32GB Ram and rtx 3090 and latest nvidia driver.

**Comment by benx13** [comment]
did you find any solution?
