### ISSUE TITLE
The Parameter --force-model-name doesn't work in merging

### ISSUE THREAD

**Issue by dsyrock** [iperov/DeepFaceLab#5363]
So I edit the Merger.py a little:

Before:

model = models.import_model(model_class_name)(is_training=False,
                                                                                   saved_models_path=saved_models_path,
                                                                                   force_gpu_idxs=force_gpu_idxs,
                                                                                   cpu_only=cpu_only)

After:

model = models.import_model(model_class_name)(is_training=False,
                                                                                   saved_models_path=saved_models_path,
                                                                                   force_gpu_idxs=force_gpu_idxs,
                                                                                   force_model_name=force_model_name,
                                                                                   cpu_only=cpu_only)

Now it works.

**Comment by iperov** [comment]
thanks, fixed
