### ISSUE TITLE
rtx 3060 low usage

### ISSUE THREAD

**Issue by MoAliHub** [iperov/DeepFaceLab#5380]
usage of my gpu is only 3-4% while extract images or training which makes it take long time to extract or train , any solutions ?

**Comment by Cregrant** [comment]
DFL uses only a single cpu core to extract images, so the GPU is not busy at all. I suggested an improvement to get a ~ 1.5x gain, but iperov deleted my post bruh.

**Comment by Cregrant** [comment]
> usage of my gpu is only 3-4% while extract images or training which makes it take long time to extract or train , any solutions ?

DFL uses only a single cpu core to extract images, so the GPU is not busy at all. I suggested an improvement to get a ~ 1.5x gain, but iperov deleted my post bruh.

**Comment by facialmist1** [comment]
My solution is to split the files appropriately to save time, and specify those folders in multiple scripts to process them in parallel. Then combine the results into one folder.
5) data_dst faceset extract DST-1.bat
    --input-dir "%WORKSPACE%\data_dst" ^
    --output-dir "%WORKSPACE%\data_dst\aligned" ^
5) data_dst faceset extract DST-2.bat
    --input-dir "%WORKSPACE%\data_dst2" ^
    --output-dir "%WORKSPACE%\data_dst2\aligned" ^

**Comment by Cregrant** [comment]
> to save time

Also try to replace Extractor file inside the _internal\DeepFaceLab\mainscripts directory.
Just rename my file from **.txt** to **.py** and put there.
[Extractor.txt](https://github.com/iperov/DeepFaceLab/files/7082936/Extractor.txt)

**Comment by Showstoppah** [comment]
> > to save time
> 
> Also try to replace Extractor file inside the _internal\DeepFaceLab\mainscripts directory.
> Just rename my file from **.txt** to **.py** and put there.
> [Extractor.txt](https://github.com/iperov/DeepFaceLab/files/7082936/Extractor.txt)

Bro, ty!

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.

**Comment by Cregrant** [comment]
If anyone here is still interested in DFL, I have released my whole optimized version instead of this old `Extractor.txt` replacing.
https://github.com/Cregrant/DeepFaceLab
