### ISSUE TITLE
Holes in convert

### ISSUE THREAD

**Issue by Jengall** [iperov/DeepFaceLab#54]
## Expected behavior
I expect the face mask to be filled

## Actual behavior

While my DF training go really well I have some hole in the mask during the conversion

Here is a screenshot of debug

![tony_cyr](https://user-images.githubusercontent.com/11194459/40500669-bf567f46-5f85-11e8-84a2-23ef9f6b0a67.png)

## Steps to reproduce

No idea

## Other relevant information
python main.py convert --input-dir %DstPics% --output-dir %DstPics%\convpic --model-dir %model% --model DF --aligned-dir %DstHS% --debug

Do you have any idea on how to fix ? how to bypass ? is there a way to deactivate the predicted mask (if it is the faulty thing? )
Thx for help

**Comment by iperov** [comment]
upload your workspace to google drive

**Comment by Jengall** [comment]
sorry to ask silly question. What do you mean by workspace ? Model ? pics ? something else ?

**Comment by iperov** [comment]
yes all related to this fake

**Comment by Jengall** [comment]
ok, i ll do that, back in few min

**Comment by Jengall** [comment]
here it is 
https://drive.google.com/open?id=1W70oypnS0P80vdjHY1_dQd0tvX6l-rz5

**Comment by Jengall** [comment]
sorry
https://goo.gl/d3nPMi
I thought you only need the "convert" part

**Comment by iperov** [comment]
looks like not enough dst faces to learn common facial states

**Comment by Jengall** [comment]
Ok, thank you for your time
There was a time when you could change the mask used (predicted or not)  don't you think this feature is usefull ?

**Comment by iperov** [comment]
using mask extracted from dst frame produces jittering due to low resolution of landmarks (from 64x64 faces)

**Comment by Jengall** [comment]
Do you think i can try to add some dst HS with the current model or should I retrain a really new model ?

**Comment by Jengall** [comment]
Ok you are right, i add some face ysterday and today it s nice, thx, feel free to close the bug

**Comment by iperov** [comment]
and what's your videocard ?

**Comment by iperov** [comment]
Try to retrain with latest commit.
There was bug in generator that skips half of all faces
