### ISSUE TITLE
GTX 1060 6GB, can't extract data_dst faces.

### ISSUE THREAD

**Issue by JailSeed** [iperov/DeepFaceLab#540]
Hello! I tried 9.2 and 10.1 CUDA builds but the problem still exists. I tried different "data_dst extract" bats files, but everywhere I got: "Images found: 0, Faces detected: 0".

**Comment by Miha20** [comment]
You did extract the images from the data_dst beforehand?

**Comment by JailSeed** [comment]
> You did extract the images from the data_dst beforehand?

Firstly I extracted images from data_scr and only then tried data_dst

**Comment by Miha20** [comment]
Might have been unclear:
Did you do
3.2) extract images from video data_dst FULL FPS
before
5) data_dst extract faces ...
?

**Comment by JailSeed** [comment]
> Might have been unclear:
> Did you do
> 3.2) extract images from video data_dst FULL FPS
> before
> 5) data_dst extract faces ...
> ?

Thanks, i forgot to do it :D
