### ISSUE TITLE
Not able to detect GPU - Build_10_09_2021

### ISSUE THREAD

**Issue by exploreTech32** [iperov/DeepFaceLab#5405]
## Expected behavior
DeepFaceLab_NVIDIA_RTX3000_series_build_10_09_2021 should be able to detect installed GPU

## Actual behavior
DeepFaceLab_NVIDIA_RTX3000_series_build_10_09_2021 is not able to detect GPU, **while the older build (build_09_06_2021) is able to detect them.**

## Steps to reproduce
GPU: 3060 RTX 12 GB
Windows 10 Home
Nvidia Studio Driver

**Comment by zabique** [comment]
Exactly same problem here. 
RTX3090
windows 11 home
latest Nvidia drivers reinstalled, rebooted.

**Comment by NvrTdp** [comment]
Tried Game Ready Driver? Looks like it works for several 3000 users. Might be a problem with Studio.

**Comment by exploreTech32** [comment]
@iperov Thanks for the quick fix.

Its working now with new build. Closing the issue.
