### ISSUE TITLE
Export Mask only (alpha) not working

### ISSUE THREAD

**Issue by kilerb** [iperov/DeepFaceLab#541]
I might be missing something, but I've done this in previous versions with success.  In the latest version, I click B during conversion to set export_alpha_mask to TRUE...  It puts a checkerboard behind the mask as expected...  But when I export by clicking "converted to mov(lossless+alpha)" after, like I've done in the past, the final mov file has the background back behind the mask.  Normally it is just the mask and I can import it into premiere as an overlay.  Has anything changed?  Using the same steps I always have.  Thanks!

**Comment by kilerb** [comment]
I believe I figured out the problem.  After a bunch of experimenting, if the mask isn't in the very first frame, this function does not work.  At least from all the tries I gave it.

**Comment by Heisen-burger** [comment]
It happens to me too. It's like a kind of image cache because it also happens if i import in vegas the first frame that doesn't contains a mask . The mask images are also not used if i use ffmpeg command to join lossless png to mov/mp4.
Does somebody know how to avoid this annoying issue?

**Comment by iamdylanavery** [comment]
I had this same issue with one deepfake and thought I was doing something wrong, but then on the second one this issue was gone.  Sure enough, on the first see-fake, there wasn't a mask on the first image, and on the second there was.

**Comment by iperov** [comment]
I just checked it. All works fine.
PNGs are exported correctly with transparency channel.
mp4 is produced with png video codec.
Just check alpha channel in your video editor program.

**Comment by Heisen-burger** [comment]
> I just checked it. All works fine.
> PNGs are exported correctly with transparency channel.
> mp4 is produced with png video codec.
> Just check alpha channel in your video editor program.

Hello, the PNG are exported correctly with alpha channel, but if the first frame has not to be  a mask to make the bug happen. Now it imports all frames as overlay of the original dst_video and not mask only .
Do this try:
1- do some training but the face to be replaced should not be on the first frame
2- do a first convert SAEHD without the "export mask alpha" setting
3- do convert SAEHD with "export mask alpha" setting
4- check merged folder, now should contain the pngs with alpha channel correctly
5- import the  frame (this should not be a mask but a original frame) from merged folder or do onvert to mov/mp4 with alpha channel
the result mov/mp4 or the frames imported are not the frame with alpha channel but they are the mask but overlayed on the original dst_video
It's a kind of cache that doesn't import the actual pngs but got them from the cache

**Comment by iperov** [comment]
check last commit.
Now convert all frames with export mask. Mask will be included in frames even without faces.

**Comment by Heisen-burger** [comment]
i'll check, thank u
