### ISSUE TITLE
DFL 1.0 for my Radeon RX 6800XT GPU

### ISSUE THREAD

**Issue by Devlin556** [iperov/DeepFaceLab#5411]
Hi! 
I can't find DFL1.0 download, where can I find it? I have Radeon RX 6800XT and I need to use OpenCL, because the latest DFL doesn't work perfectly on my GPU and I think it uses GPU not correct.

Thank you!

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
