### ISSUE TITLE
Converter:  Using face scale results in unwanted 'jitter'.

### ISSUE THREAD

**Issue by titanrw** [iperov/DeepFaceLab#542]
Using face scale during conversion seems to result in unwanted face jitter.

This example is using the included source and destination videos.  Only trained to 20,000 iters, but I think it's clear enough.  DFL version 1229 and SAEHD model.

The face scale parameters seem to be reversed now.  It used to be positive face scale resulted in upsized (larger) faces.  Now positive face scale makes the face smaller.  Negative face scale numbers makes the face bigger.

The two sequential frames used are 00252 and 00253.

This is with zero face scale:

[https://imgur.com/8wEhKPc](https://i.imgur.com/8wEhKPc.gif)

Alignment seem perfect from frame to frame.

This is with negative face scale, making the face bigger:

[https://imgur.com/zDQ8AbO](https://i.imgur.com/zDQ8AbO.gif)

There seems to be a lot of sideways shifting of the face.  The face can end up jittering all over the place when using face scale now.  I'm not sure why.

I realize in this example, you would not want any face scale at all.  However some models / projects require slight face scale to make it look right.

Let me know if anything is not clear.

And happy new year.

**Comment by titanrw** [comment]
As a follow-up, I found that the Dec 15 version of DFL behaves 'normally'.  Positive face scale amounts result in a larger face, and there isn't the face 'jitter' as shown here.

Of course the SAEHD model changed between these two versions resulting in an error with a model trained on 1229 but converting on 1215.  Copying the SAEHD model.py from the 1229 version into the 1215 directory seems to work though.  The 1229 model can be loaded by the 1215 converter and face scale works as it did before without jitter.

I'm not sure what changed between the Dec 15 version and the Dec 29 version, but something changed the way face scale works during conversion.

**Comment by deepfaceswap12345** [comment]
I'm getting exactly the same behavior described above, even with a brand new trained model from scratch using SAEHD and the new merger (from the DeepFaceLab_NVIDIA_build_01_23_2020 build).

Does the DeepFaceLab_NVIDIA_build_02_01_2020 or the DeepFaceLab_NVIDIA_build_02_01_2020 fix this issue?

Thanks!
