### ISSUE TITLE
Crash when using "6) export AMP as dfm.bat"

### ISSUE THREAD

**Issue by BlankFX1** [iperov/DeepFaceLab#5422]
## Expected behavior

I trained an AMP Model in SRC-SRC-Mode and am trying to convert it to an dfm-File for using it in DeepFaceLive.

What I did:
- Start "6) export AMP as dfm.bat"
- Choose AMP-Model
- "Export Quantized?" = no

I expected the tool to convert the AMP Model to a dfm-File.

## Actual behavior

Instead it crashed and gave me the following output:

> Choose one of saved models, or enter a name to create a new model.
> [r] : rename
> [d] : delete
>
> [0] : SiaV2 - latest
> [1] : SiaV1
>  : 0
> Loading SiaV2_AMP model...
> [n] Export quantized? ( y/n ?:help ) :
> n
> Initializing models: 100%|####################################################################################################################################################################################| 4/4 [00:00<00:00,  7.81it/s]
> ================ Model Summary =================
> ==                                            ==
> ==            Model name: SiaV2_AMP ==
> ==                                            ==
> ==     Current iteration: 220536              ==
> ==                                            ==
> ==-------------- Model Options ---------------==
> ==                                            ==
> ==            resolution: 320                 ==
> ==             face_type: wf                  ==
> ==     models_opt_on_gpu: True                ==
> ==               ae_dims: 256                 ==
> ==            inter_dims: 320                 ==
> ==                e_dims: 72                  ==
> ==                d_dims: 72                  ==
> ==           d_mask_dims: 22                  ==
> ==          morph_factor: 0.5                 ==
> ==           uniform_yaw: True                ==
> ==         blur_out_mask: False               ==
> ==            lr_dropout: n                   ==
> ==           random_warp: True                ==
> ==               ct_mode: none                ==
> ==              clipgrad: False               ==
> ==       autobackup_hour: 1                   ==
> == write_preview_history: True                ==
> ==           target_iter: 0                   ==
> ==       random_src_flip: False               ==
> ==       random_dst_flip: True                ==
> ==            batch_size: 11                  ==
> ==             gan_power: 0.0                 ==
> ==        gan_patch_size: 40                  ==
> ==              gan_dims: 16                  ==
> ==                                            ==
> ==---------------- Running On ----------------==
> ==                                            ==
> ==          Using device: CPU                 ==
> ==                                            ==
> ================================================
> Dumping .dfm to S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\workspace\model\SiaV2_AMP_model.dfm
> Failed to convert node 'Slice_3' (fct=<bound method Slice.version_1 of <class 'tf2onnx.onnx_opset.tensor.Slice'>>)
> ''
> Traceback (most recent call last):
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 294, in tensorflow_onnx_mapping
>     func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 343, in version_1
>     _ = GraphBuilder(ctx).make_slice(kwargs, name=node.name)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph_builder.py", line 40, in make_slice
>     starts = self.convert_to_attribute(kwargs.pop("starts"))
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph_builder.py", line 224, in convert_to_attribute
>     res = const_node.get_tensor_value(as_list=True)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph.py", line 317, in get_tensor_value
>     raise ValueError("get tensor value: '{}' must be Const".format(self.name))
> ValueError: get tensor value: 'Slice_3/begin_Concat__109' must be Const
> Failed to convert node 'Slice_2' (fct=<bound method Slice.version_1 of <class 'tf2onnx.onnx_opset.tensor.Slice'>>)
> ''
> Traceback (most recent call last):
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 294, in tensorflow_onnx_mapping
>     func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 343, in version_1
>     _ = GraphBuilder(ctx).make_slice(kwargs, name=node.name)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph_builder.py", line 41, in make_slice
>     ends = self.convert_to_attribute(kwargs.pop("ends"))
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph_builder.py", line 224, in convert_to_attribute
>     res = const_node.get_tensor_value(as_list=True)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph.py", line 317, in get_tensor_value
>     raise ValueError("get tensor value: '{}' must be Const".format(self.name))
> ValueError: get tensor value: 'Add__133' must be Const
> Failed to convert node 'concat_3' (fct=<bound method ConcatV2.version_1 of <class 'tf2onnx.onnx_opset.tensor.ConcatV2'>>)
> 'OP=Concat\nName=concat_3\nInputs:\n\tSlice_2:0=N/A, None, None\n\tSlice_3:0=N/A, None, None\n\tconcat_3/axis:0=Const, [], 6\nOutpus:\n\tconcat_3:0=[-1, -1, 10, 10], 1'
> Traceback (most recent call last):
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 294, in tensorflow_onnx_mapping
>     func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 274, in version_1
>     if inp.is_const() and inp.get_tensor_value(as_list=False).size == 0:
> AttributeError: 'NoneType' object has no attribute 'is_const'
> Traceback (most recent call last):
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 343, in <module>
>     arguments.func(arguments)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 154, in process_exportdfm
>     ExportDFM.main(model_class_name = arguments.model_name, saved_models_path = Path(arguments.model_dir))
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\ExportDFM.py", line 22, in main
>     model.export_dfm ()
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\Model_AMP\Model.py", line 629, in export_dfm
>     output_path=output_path)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\convert.py", line 153, in _convert_common
>     g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 535, in process_tf_graph
>     output_names, initialized_tables, outputs_to_values, outputs_to_dtypes, op_cnt, attr_cnt)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 637, in process_parsed_graph
>     raise exceptions[0]
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 294, in tensorflow_onnx_mapping
>     func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 343, in version_1
>     _ = GraphBuilder(ctx).make_slice(kwargs, name=node.name)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph_builder.py", line 40, in make_slice
>     starts = self.convert_to_attribute(kwargs.pop("starts"))
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph_builder.py", line 224, in convert_to_attribute
>     res = const_node.get_tensor_value(as_list=True)
>   File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph.py", line 317, in get_tensor_value
>     raise ValueError("get tensor value: '{}' must be Const".format(self.name))
> ValueError: get tensor value: 'Slice_3/begin_Concat__109' must be Const

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*
Tried the above mentioned steps and settings, also tried with another AMP-Model (SiaV1 which had an higher resolution) with the exact same outcome.

## Other relevant information
**Operating system and version:** Windows, macOS, Linux 
- Windows 10, Ryzen 3950x, 64 GByte RAM, 700 GByte Paging File, RTX 3080 Ti

- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)
- tested using Windows Build DeepFaceLab_NVIDIA_RTX3000_series_build_10_20_2021

(Sorry for the size text format above, was unable to fix it.)

**Comment by ValentinKovalev** [comment]
I have faced the same problem on Nvidia 1650 4GB

**Comment by zabique** [comment]
same problem on 3090. trained on vanilla RTX 3000 build.

**Comment by Dalka0064** [comment]
the same problem on 1660Ti 6G on both windows10 and ubuntu 20.04

**Comment by BlankFX1** [comment]
Any chance this will get adressed?

**Comment by zabique** [comment]
https://github.com/iperov/DeepFaceLab/commit/388964e8d08cad8b1bb1faa012777e9fe8973950
fixed
