### ISSUE TITLE
Not working on RTX3070 8GB

### ISSUE THREAD

**Issue by 515621078** [iperov/DeepFaceLab#5423]
## Expected behavior

Running **train SAEHD.bat**, Expected to show the training window.

## Actual behavior

Running **train SAEHD.bat**,
After **Starting. Press "Enter" to stop training and save model.**,
The program stoped at **Press any key to continue...**

## Steps to reproduce

2 GPUs, same config works on **GTX1060 6GB**, but not on **RTX3070 8GB**.
This problem only happens to my RTX3070 via SAEHD (Fine for Quick96)

### train SAEHD.bat via RTX3070

    Running trainer.

    Choose one of saved models, or enter a name to create a new model.
        r  rename
        d  delete

        0  ZsyJrn - latest

    0
    Loading ZsyJrn_SAEHD model

    Choose one or several GPU idxs (separated by comma).

        CPU : CPU
        0  NVIDIA GeForce RTX 3070
        1  NVIDIA GeForce GTX 1060 6GB

    0 Which GPU indexes to choose?
    0

    Caching GPU kernels
    Initializing models: 100
    Loading samples: 100
    Loading samples: 100
    Model Summary 

        Model name: ZsyJrn_SAEHD            

        Current iteration: 1725                    

        Model Options 
                                      
            resolution: 128
            face_type: f
            models_opt_on_gpu: True
            archi: liae-ud
            ae_dims: 256
            e_dims: 64
            d_dims: 64
            d_mask_dims: 22
            masked_training: True
            eyes_mouth_prio: False
            uniform_yaw: False
            blur_out_mask: True
            adabelief: True
            lr_dropout: n
            random_warp: True
            random_hsv_power: 0.1
            true_face_power: 0.0
            face_style_power: 0.0
            bg_style_power: 0.0
            ct_mode: rct
            clipgrad: False
            pretrain: False
            autobackup_hour: 4
            write_preview_history: False
            target_iter: 0
            random_src_flip: False
            random_dst_flip: True
            batch_size: 2
            gan_power: 0.0
            gan_patch_size: 16
            gan_dims: 16
                                                
        Running On
                                                
            Device index: 0                       
                Name: NVIDIA GeForce RTX 3070 
                VRAM: 6.44GB                  
                                                
    Starting. Press "Enter" to stop training and save model.
    Press any key to continue...

### train SAEHD.bat via GTX1060

    Running trainer.

    Choose one of saved models, or enter a name to create a new model.
        r  rename
        d  delete

        0  ZsyJrn - latest

    0
    Loading ZsyJrn_SAEHD model...

    Choose one or several GPU idxs (separated by comma).

        CPU  CPU
        0  NVIDIA GeForce RTX 3070
        1  NVIDIA GeForce GTX 1060 6GB

    0 Which GPU indexes to choose? : 1
    1

    Caching GPU kernels
    Initializing models: 100
    Loading samples: 100
    Loading samples: 100
    Model Summary

        Model name: ZsyJrn_SAEHD

        Current iteration: 1725

        Model Options

            resolution: 128
            face_type: f
            models_opt_on_gpu: True
            archi: liae-ud
            ae_dims: 256
            e_dims: 64
            d_dims: 64
            d_mask_dims: 22
            masked_training: True
            eyes_mouth_prio: False
            uniform_yaw: False
            blur_out_mask: True
            adabelief: True
            lr_dropout: n
            random_warp: True
            random_hsv_power: 0.1
            true_face_power: 0.0
            face_style_power: 0.0
            bg_style_power: 0.0
            ct_mode: rct
            clipgrad: False
            pretrain: False
            autobackup_hour: 4
            write_preview_history: False
            target_iter: 0
            random_src_flip: False
            random_dst_flip: True
            batch_size: 2
            gan_power: 0.0
            gan_patch_size: 16
            gan_dims: 16

        Running On

            Device index: 1
                Name: NVIDIA GeForce GTX 1060 6GB
                VRAM: 4.71GB
                                                   

    Starting. Press "Enter" to stop training and save model.
    [09:12:13][#002544][0317ms][0.9735][1.0236]

### Python version: 3.9.7

**Comment by zabique** [comment]
U need separate build for 3000 series - it's on MEGA

**Comment by 515621078** [comment]
@zabique I am using 3000 series build.

**Comment by 515621078** [comment]
> U need separate build for 3000 series - it's on MEGA

@zabique I am using 3000 series build.
