### ISSUE TITLE
SAEH blurred result

### ISSUE THREAD

**Issue by ShinyMen** [iperov/DeepFaceLab#543]
Hello, I have a problem that I cannot solve I use the SAEHD train I am at 100k iterations but I have some faces especially the close-ups which are blurry .. I have already done other tests but I can't seem to have a clear face. Thanks to help me.

My settings 

=============== Model Summary ================
==                                          ==
==         Model name: SAEHD                ==
==                                          ==
==  Current iteration: 99769                ==
==                                          ==
==------------- Model Options --------------==
==                                          ==
==        sort_by_yaw: False                ==
==        random_flip: True                 ==
==         resolution: 128                  ==
==          face_type: f                    ==
==         learn_mask: True                 ==
==     optimizer_mode: 2                    ==
==              archi: df                   ==
==            ae_dims: 256                  ==
==         ed_ch_dims: 21                   ==
==         lr_dropout: False                ==
==        random_warp: True                 ==
== true_face_training: False                ==
==   face_style_power: 0.0                  ==
==     bg_style_power: 0.0                  ==
==            ct_mode: none                 ==
==           clipgrad: False                ==
==         batch_size: 6                    ==
==                                          ==
==--------------- Running On ---------------==
==                                          ==
==       Device index: 0                    ==
==               Name: GeForce GTX 1060 6GB ==
==               VRAM: 6.00GB               ==
==                                          ==
==============================================

**Comment by TooMuchFun** [comment]
Disable ` random_warp` and run training again for awhile.
