### ISSUE TITLE
RuntimeWarning in src extraction

### ISSUE THREAD

**Issue by joedit-cmd** [iperov/DeepFaceLab#544]
![Extract error](https://user-images.githubusercontent.com/59481836/71735524-b0e54980-2e1c-11ea-9860-7a4870cd92eb.jpg)
Hi, received a few error messages when trying to extract from source video/frames.

Tried: 
- different built - Dec 29, Dec 26, older build
- Updating to latest nvidia driver

Error seems to be persistent every time when I try it, but the exact file/frame causing the issue seems to be somewhat random.

Thanks.

**Comment by wuffenberg** [comment]
Your faceset seems to have a bad quality, when you only get 519 faces out of 4448 frames. Try to refine your faceset by enlarging, deinterlacing, upscaling or simply use another faceset in HQ.
