### ISSUE TITLE
Openfaceswap gui issue when training

### ISSUE THREAD

**Issue by badat1223** [iperov/DeepFaceLab#545]
![20200104_200733](https://user-images.githubusercontent.com/59473294/71771102-cdbd7200-2f2d-11ea-8e1e-adfcddc4667a.jpg)
It just gets stuck on this part then nothing happens no matter how long i leave it for of any one has any ideas it would be  a good help thanks.

**Comment by TooMuchFun** [comment]
Wrong project. Perhaps you are looking for deepfakes/faceswap?

**Comment by badat1223** [comment]
Possibly, no problem will look up that project and post it on there

**Comment by gessyoo** [comment]
@badat1223, I can understand why you ended up here, the now-defunct website, https://www.deepfakes.club/openfaceswap-deepfakes-software/, re-directs to this repro.  Openfaceswap is no longer supported or developed, there's no help available.  Try Deepfacelab or Faceswap instead.

**Comment by Kabilan21** [comment]
Hi ,this can be solved by reducing the batch size.set batch size=16
