### ISSUE TITLE
train H64 uses CPU instead of GPU

### ISSUE THREAD

**Issue by Aletv90** [iperov/DeepFaceLab#546]
Hi everybody!
I'm new here, as I'm new in Deepfacelab use
I have a problem that don't know how to solve and hope that somebody here can gime some useful info!
when I'm using train H64, I see that my pc is working with cpu instead of gpu
I've installed cuda 9,2

I was wondering if working with gpu will be faster that cpu...
and also if someone can give some suggestions about the best batch size to use...I wrote 20 and it worked, now I'm trying 12 but I don't personally think that is a problem...but I'll really appreciate some suggestions about

here're the features of my pc (I try to write everything, don't know what is useful or not :D)
windows 10
intel core i7
mainboard asus g750jz
ram 16gb
nvidia geforce gtx 880m 4gb

## Expected behavior
process should runs on gpu, but it runs only on cpu

## Actual behavior
process run on cpu

![Immagine](https://user-images.githubusercontent.com/59513217/71770429-af0aab80-2f2c-11ea-99e8-b559a45df5a7.png)

## Steps to reproduce

I've tried to check device.py but don't know properly what parts I can change and in case, how...

## Other relevant information
I've installed cuda 10, but with cuda 9.2 it's faster, 14-15 s/iteration while with cuda 10 it was around 30 s...
nvidia drivers are updated to latest version

**Comment by Miha20** [comment]
Do you use the cuda build or the opengl one? And which version?

**Comment by Aletv90** [comment]
on nvidia card I have cuda 9.2 file version 1.0.7
previously I forgot that I have also a second graphic card, together to the processor unit, here the features
![image](https://user-images.githubusercontent.com/59513217/72062277-c43e5c00-32d7-11ea-8c5b-4c0a8de4ea1d.png)

intel is GPU 0
nvidia is GPU 1

**Comment by Miha20** [comment]
There are nowadays 2 builds of DeepFaceLab (Prebuilt Windows Releases): DeepFaceLab_CUDA and DeepFaceLab_OpenCL
And then there is the version of the builds. These can be seen at the end of the install file e.g. 11_14_2019 or when installed in "changelog_en" (date at the top).
So did you download "DeepFaceLab_CUDA" or "DeepFaceLab_OpenCL" and what is the version of the one you have?

**Comment by Aletv90** [comment]
I've downloaded cuda version 9.2 sse date 27-10-2019
recently I tried also with cuda build 29-12-2019
but always same problem, it works with cpu and not with gpu...
I searched also for my card's compute capability, wich is 3.0, it should be enough I think...
should I have to try with open cl version?
