### ISSUE TITLE
Problems during SE trainer just says press key to continue after loading samples

### ISSUE THREAD

**Issue by Pixilist** [iperov/DeepFaceLab#5465]
Initializing models: 100%|###############################################################| 5/5 [00:01<00:00,  2.89it/s]
Loading samples: 100%|###########################################################| 8398/8398 [00:07<00:00, 1089.96it/s]
Loading samples: 100%|###########################################################| 4779/4779 [00:04<00:00, 1077.81it/s]
Press any key to continue . . .

**Comment by Pixilist** [comment]
doesnt matter which trainer happens on every one

**Comment by Pixilist** [comment]
sae trainer*

**Comment by ForgottenGold** [comment]
Hello @Pixilist.
Could you please share your solution to this problem if you did.
Thanks in advance.
