### ISSUE TITLE
Exact params for training command? (res/opt/dims/batchsize)

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [iperov/DeepFaceLab#547]
Hello, I am trying to find the params for these, the SAEHD model specifically, so that I can bypass having to skip/enter each one sequentially once the initial command is run.

I was able to find the commands for fps/bitrate on converting, but that is ffmpeg mainly. I am assuming that for the training params, I will need to have some sort of python function to pipe them with the command?? I don't know, I didn't find much while searching through issues, and when looking at the code, I see references to all of these, but I am not sure what the correct procedure is for piping them in initially. Thank you.

**Comment by wuffenberg** [comment]
You can try to read the input from a text file. Here is a simple example to start from:

Create a text file, for example: _in.txt_ and write the commands there as you would enter them in the cmd window:
![image](https://user-images.githubusercontent.com/60057801/73109169-b822e300-3f02-11ea-8167-e6c131525a7c.png)

Start a cmd window and go to the DFL directory
type:
_"train SAEHD.bat" < in.txt_
and the input will be read from in.txt

good luck
