### ISSUE TITLE
Error: No training data provided.

### ISSUE THREAD

**Issue by BrianStark** [iperov/DeepFaceLab#5485]
Good afternoon,

I tried to run the program but I keep getting the same error continuously,
I reinstalled my Windows 11 to see if that was the issue, and even tried it with Windows 8 and 10.
But I keep getting this error, it would be really nice if there is a solution for it.

could it be that my system is not good??
I have a computer with the parts:

CPU:          AMD Ryzen Threadripper 2990WX 32-Core Processor
RAM:         128 GB
GPU:          NVIDIA GeForce RTX 2080 Ti
SSD:          GIGABYTE GP-AG42TB (2TB)

(GPU i'm going to upgrade to 2x NVIDIA GeForce RTX 3090)

Thanks in advance for the help.

Running trainer.

[new] No saved models found. Enter a name of a new model : new_model
new_model

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : NVIDIA GeForce RTX 2080 Ti

[0] Which GPU indexes to choose? :
0

[0] Autobackup every N hour ( 0..24 ?:help ) :
0
[n] Write preview history ( y/n ?:help ) :
n
[0] Target iteration :
0
[n] Flip SRC faces randomly ( y/n ?:help ) :
n
[y] Flip DST faces randomly ( y/n ?:help ) :
y
[8] Batch_size ( ?:help ) :
8
[128] Resolution ( 64-640 ?:help ) :
128
[f] Face type ( h/mf/f/wf/head ?:help ) :
f
[liae-ud] AE architecture ( ?:help ) :
liae-ud
[256] AutoEncoder dimensions ( 32-1024 ?:help ) :
256
[64] Encoder dimensions ( 16-256 ?:help ) :
64
[64] Decoder dimensions ( 16-256 ?:help ) :
64
[22] Decoder mask dimensions ( 16-256 ?:help ) :
22
[n] Eyes and mouth priority ( y/n ?:help ) :
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) :
n
[n] Blur out mask ( y/n ?:help ) :
n
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[y] Use AdaBelief optimizer? ( y/n ?:help ) :
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) :
0.0
[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) : y
[n] Enable pretraining mode ( y/n ?:help ) : y
Initializing models: 100%|############################################################| 5/5 [00:03<00:00,  1.52it/s]
Loading samples: 0it [00:00, ?it/s]
Error: No training data provided.
Traceback (most recent call last):
  File "D:\Ai FaceFake 2\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug)
  File "D:\Ai FaceFake 2\_internal\DeepFaceLab\models\ModelBase.py", line 193, in __init__
    self.on_initialize()
  File "D:\Ai FaceFake 2\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 684, in on_initialize
    generators_count=src_generators_count ),
  File "D:\Ai FaceFake 2\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 48, in __init__
    raise ValueError('No training data provided.')
ValueError: No training data provided.

**Comment by BarisTalayoglu** [comment]
hello,did you find anything i keep getting the same error

**Comment by BrianStark** [comment]
No not yet, i'm tying to search into the software to find something that could be a problem so it can be fixt, but i still haven't found anything i'm open for suggestions.

**Comment by callanrocks** [comment]
Trying turning off enable pretraining mode.

**Comment by BrianStark** [comment]
I have tried but I keep getting the same error.
I have copied the models folder from the old one to the new one and then it works.
But it is not how it's supposed to be.
So I got two RTX 3090 graphics cards now to see if that fixes the problems.

**Comment by BrianStark** [comment]
We'll it worked for 4 hours, now i got new problems.
There i go again searching 😔

**Comment by ntmatter1** [comment]
I had this issue as well with a new setup, and had this issue when trying to use a pre-trained model.  When I went through the settings and turned "pretrain mode" back on, then it worked.  As it turned out, there was a typo in my source folder for "aligned", and thus no training data.  Fixed the typo, works just fine.

**Comment by BrianStark** [comment]
I solved my 6) train SAEHD issue by reducing the number of worker, I edited DeepFaceLab_NVIDIA_up_to_RTX2080ti_series \_internal\DeepFaceLab\models\Model_SAEHD\Model.py by just changing the line 669 to

cpu_count = multiprocessing.cpu_count() // 2

I solved my 5.XSeg) train issue by reducing the number of worker, I edited DeepFaceLab_NVIDIA_up_to_RTX2080ti_series \_internal\DeepFaceLab\samplelib\SampleGeneratorFaceXSeg.py by just changing the line 212 to

for i in range(multiprocessing.cpu_count() // 2):

If the program uses multiprocessing.cpu_count() it uses all the Logical processors and that gives me the problem that the main os will overpower DeepFaceLab resolting the crash

**Comment by Sacramar** [comment]
I had this problem and I followed this path and found the zip file model_saehd.zip here, I unpacked it and Seahd starts working, but there was another problem in the lack of a swap file, but this is no longer a problem

**DeepFaceLab_NVIDIA_up_to_RTX2080ti_series\ _internal\DeepFaceLab\models\Model_SAEHD**

**Comment by AndyNope** [comment]
> 

Where have you done this?
