### ISSUE TITLE
Gigapixel upscaling the source method not working (restoring metadata error)

### ISSUE THREAD

**Issue by mpmo10** [iperov/DeepFaceLab#549]
So i followed all the instructions on how to upscale using gigapixel. used "4.2.other) data_src util faceset metadata save", then upscaled the aligned images in src using gigapixel, then renamed the new upscaled folder to "aligned" and moved the metadata file there. But when i click the restore bat file "4.2.other) data_src util faceset metadata restore" i get this error and no image processes

Is this a bug? 
![Screenshot (1319)](https://user-images.githubusercontent.com/52265226/72046985-f5685d80-32d2-11ea-8e0e-8f65779a164c.png)

**Comment by The-Digital-Void** [comment]
GigaPixel AI Video Beta will let you upscale it before you extract frames if it is a video. I wouldn't necessarily upscale the aligned images, but rather scale the images/videos you're extracting from such that the face, on average, is naturally close to 256x256.

**Comment by TooMuchFun** [comment]
Cant give you exact directions. try these instructions from [this forum post](https://rutracker.org/forum/viewtopic.php?p=78535390#78535390) 

```1) run 'data_src util faceset metadata save.bat'
2) launch Topaz Gigapixel
3) open 'data_src\aligned\' and select all images
4) set output folder to 'data_src\aligned_topaz' (create folder in save dialog)
5) set settings as on screenshot https://i.imgur.com/kAVWMQG.jpg
you can choose 2x, 4x, or 6x upscale rate
6) start process images and wait full process
7) rename folders:
data_src\aligned -> data_src\aligned_original
data_src\aligned_topaz -> data_src\aligned
8) copy 'data_src\aligned_original\meta.dat' to 'data_src\aligned\'
9) run 'data_src util faceset metadata restore.bat'
images will be downscaled back to original size (256x256) preserving details
metadata will be restored```

**Comment by mpmo10** [comment]
> Cant give you exact directions. try these instructions from [this forum post](https://rutracker.org/forum/viewtopic.php?p=78535390#78535390)
> 
> ```
> 1) run 'data_src util faceset metadata save.bat'
> 2) launch Topaz Gigapixel
> 3) open 'data_src\aligned\' and select all images
> 4) set output folder to 'data_src\aligned_topaz' (create folder in save dialog)
> 5) set settings as on screenshot https://i.imgur.com/kAVWMQG.jpg
> you can choose 2x, 4x, or 6x upscale rate
> 6) start process images and wait full process
> 7) rename folders:
> data_src\aligned -> data_src\aligned_original
> data_src\aligned_topaz -> data_src\aligned
> 8) copy 'data_src\aligned_original\meta.dat' to 'data_src\aligned\'
> 9) run 'data_src util faceset metadata restore.bat'
> images will be downscaled back to original size (256x256) preserving details
> metadata will be restored
> ```

i did these exact same steps in the first place

**Comment by sloflo** [comment]
@mpmo10 Had the same issue. I tried running training anyways and that console output gave me the fix. Turns out there was a bunch of hidden files created in the aligned folder.  Just delete them all and try again.  view > options > change folder options > view > show hidden files  (Or use the command line)
