### ISSUE TITLE
i have intel 520,is it going to work or should i switch to colab for high end gpu

### ISSUE THREAD

**Issue by tyler2269** [iperov/DeepFaceLab#5493]
should works

_Originally posted by @iperov in https://github.com/iperov/DeepFaceLab/issues/5327#issuecomment-836642595_

**Comment by iperov** [comment]
no its very slow gpu

**Comment by tyler2269** [comment]
@iperov so colab is a better option as they provide us with tesla k80

**Comment by tyler2269** [comment]
@iperov if you don't mind can i ask which deepfacelab build should i use for colab.
