### ISSUE TITLE
Noise appeared on white background when using seamless converter

### ISSUE THREAD

**Issue by shun115** [iperov/DeepFaceLab#55]
I use LIAEF128 on training and using seamless converter,
noise appeared on white background. 

### sample1

https://gyazo.com/2946e4665176d4212078688c78836184

### sample2

https://gyazo.com/29d965c2702c933a46463044ee241d20

### convert command:
```
$ python3 main.py convert --input-dir ./outputs/targets --output-dir outputs/out03_seamless --aligned-dir ./outputs/aligned_targets --model-dir workspace/model --model LIAEF128 --ask-for-params
Choose mode: (1) hist match, (2) hist match bw, (3) seamless (default), (4) seamless hist match : 3
Choose erode mask modifier [-100..100] (default 0) :
Choose blur mask modifier [-100..200] (default 0) :
Export png with alpha channel? [0..1] (default 0) :
Transfer color from original DST image? [0..1] (default 0) :
Running converter.
```

When I use hist converter, noise does not appeared.
But I want to use seamless converter because of quality.

Would you tell me how to remove noise when seamless converting?
or change any parameters?

**Comment by shun115** [comment]
thank you for your reply.

72 pixel per inch.

**Comment by iperov** [comment]
-_-
 frame resolution?

**Comment by shun115** [comment]
1920x1080.
thx

**Comment by iperov** [comment]
noise appears on all converted frames?

**Comment by shun115** [comment]
No, not all frames.

**Comment by iperov** [comment]
then these are buggy frames, which have wrongly detected face points

**Comment by shun115** [comment]
OK, thank you.
This model loss is 0.026, is it enough?

**Comment by iperov** [comment]
100k epochs often enough

**Comment by shun115** [comment]
OK, Thank you for your reply!
