### ISSUE TITLE
DX12 Version still using AMD GPU when CPU is selected

### ISSUE THREAD

**Issue by AlexAwesome88** [iperov/DeepFaceLab#5528]
Using prebuild windows DX12 Version

The Nvidia version really is CPU only when an AMD GPU is installed. But the DX12 Version is using some parts of the GPU even when CPU is selected (e.g. on face extraction)

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows 10 
- **Python version:** 3.6.4

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?

**Comment by AlexAwesome88** [comment]
Only a workaround to use the Nvidia Cuda part.
