### ISSUE TITLE
Random GPU Sync Error

### ISSUE THREAD

**Issue by The-Digital-Void** [iperov/DeepFaceLab#553]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Behavior

When Training:

This seems to be somewhat random, but I get a "GPU Sync Failed" error.

Booting up training seems to allow things to go forward for anywhere between 10 minutes to 3 hours. Sometimes it works continually, but this is somewhat rare. Restarting my computer seems to allow a higher chance of success for a period.

![image](https://user-images.githubusercontent.com/57318447/72253199-0238ca00-35cf-11ea-84ac-a90a7f7cc733.png)

## Steps to reproduce

I'm not sure how to reproduce it, since it seems random. However, it does appear to increase in likelihood with each instance that I stop training and then start it up at some point before restarting my computer.

## Other relevant information
-Operating system: Windows 10 Pro
-Python version: Prebuilt Windows Binary

**Comment by varunpro** [comment]
have you tried running it at lower batch size for a couple of hours and see ? 
(if that works, then you can try running it a batch size 16 with opt mode 2 and see)

Also is your Gpu overclocked ? or overheating ? have you tried undervolting it? 

I might start there ..
