### ISSUE TITLE
Traininig uses CPU not GPU. Is it how its supposed to be?

### ISSUE THREAD

**Issue by Glaewion** [iperov/DeepFaceLab#554]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

I want to run the program with my GPU, i bought a new graphic card for this, but it is not using GPU while training.

## Actual behavior
firstly, before i write here, i searched every topics.

When i run the Train SAEHD, it first says this error (photo 1):
![1](https://user-images.githubusercontent.com/59828194/72260992-055ea500-3625-11ea-81e2-9b4754d44a04.jpg)

tensorflow/stream_executor/cuda/cuda_driver.cc806] failed to allocate 2.43 G (2608267264 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

and i get rid of this error doing these-unfortunately it just helps the erase the error, nothing more.(before that photo, train was also not work, reducing batch size helped to work but..):
https://github.com/iperov/DeepFaceLab/issues/369#issuecomment-524539937

> try batch size of 2, dims 128
----
> Try lowering the batch size, i.e start from 4 and double until you get the error.
> 
> If this doesn't work, changing line 144 in `nnlib.py` to `config.gpu_options.allow_growth = False` seemed to stop this error appearing for me."

Train model is working but it's not using my GPU now. It uses RAM and CPU. Is it should be like this or how can i work my GPU? This is how i train now;
![2](https://user-images.githubusercontent.com/59828194/72261394-ca10a600-3625-11ea-9fda-45891aaa231a.png)

IT uses shared GPU Ram but not processor. Also not actual G-RAM it uses from my normal RAM.

## Other relevant information
Batch size=6 
 **Operating system and version:** 
AMD Ryzen 3600 processor
Nvidia RTX 2060 6GB Graphic card
DFL build is the latest one (10.1)
Windows 10 64-bit, (i formatted several days ago, is it possible any other driver or program missing?)
**Python version:**
Python 3.8 64 bit.

**Comment by simonskoog** [comment]
Try to run this bat-file and try again
DeepFaceLab_DIRECTORY\_internal\setenv.bat  
  
It might be necessary to:
First, make sure you have CUDA Toolkid from Nvidia installed:
https://developer.nvidia.com/cuda-downloads

And that you have CDNN installed and moved to the correct directories:
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html

**Comment by wuffenberg** [comment]
Looking at your fast iteration times of around 800ms, I am sure DFL is using your GPU. Try to use another GPU monitor (maybe from the GPU card vendor), don't trust the Windows monitor.
