### ISSUE TITLE
Can I run the whole pipeline on a remote server with no GUI?

### ISSUE THREAD

**Issue by young169** [iperov/DeepFaceLab#5552]
cannot connect to X server localhost:11.0

**Comment by young169** [comment]
And besides, why I still use CPU to extract faces though I set "--force-gpu-idxs 0,1,2,3", intending to train on 4 2080Ti?

**Comment by chanmankong** [comment]
Have you solve your problem? I ran into the same problem. My server has no GUI. When I trained xseg, there is an error "cannot connect to x server".

**Comment by young169** [comment]
> Have you solve your problem? I ran into the same problem. My server has no GUI. When I trained xseg, there is an error "cannot connect to x server".

This problem was caused by memory staff, not x server. The "--no-preview" option should fix the GUI problem, as I know.

**Comment by MonikaDobreva** [comment]
Do you know how to check progress when training without GUI?
