### ISSUE TITLE
SAEHD training loads but nothing happens

### ISSUE THREAD

**Issue by MllGll** [iperov/DeepFaceLab#5557]
**DeepFaceLab_DirectX12_build_05_04_2022**
Windows 11 Pro x64
Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
NVIDIA GeForce GTX 1650 (Driver 516.94)
11.84 GB RAM 
```
Running trainer.

[new] No saved models found. Enter a name of a new model :
new

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : NVIDIA GeForce GTX 1650
  [1] : Intel(R) UHD Graphics 630

[1] Which GPU indexes to choose? : 0
0

[1] Autobackup every N hour ( 0..24 ?:help ) :
1
[n] Write preview history ( y/n ?:help ) :
n
[0] Target iteration :
0
[n] Flip SRC faces randomly ( y/n ?:help ) :
n
[y] Flip DST faces randomly ( y/n ?:help ) :
y
[4] Batch_size ( ?:help ) :
4
[128] Resolution ( 64-640 ?:help ) :
128
[wf] Face type ( h/mf/f/wf/head ?:help ) :
wf
[liae-ud] AE architecture ( ?:help ) :
liae-ud
[256] AutoEncoder dimensions ( 32-1024 ?:help ) :
256
[64] Encoder dimensions ( 16-256 ?:help ) :
64
[64] Decoder dimensions ( 16-256 ?:help ) :
64
[22] Decoder mask dimensions ( 16-256 ?:help ) :
22
[y] Masked training ( y/n ?:help ) :
y
[n] Eyes and mouth priority ( y/n ?:help ) :
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) :
n
[n] Blur out mask ( y/n ?:help ) :
n
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[y] Use AdaBelief optimizer? ( y/n ?:help ) :
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) :
0.0
[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
[n] Enable pretraining mode ( y/n ?:help ) :
n
Initializing models: 100%|###############################################################| 5/5 [00:03<00:00,  1.59it/s]
Loading samples: 100%|##############################################################| 869/869 [00:06<00:00, 127.56it/s]
Loading samples: 100%|##############################################################| 199/199 [00:01<00:00, 121.62it/s]
Press any key to continue. . .
```

**Comment by CodeSmith2000** [comment]
That means that it crashed. Your using a GTX 1650, so you only have 4gb of VRAM. It's not likely your model is going to be close to that. You will need to tone down the model parameters, create the model again but this time change "Place models and optimizer on GPU" to no, there is no way that it will work if it is set to yes. Also set batch size to 1. If it fails, try using Quick 96 instead of SAEHD.

**Comment by davepastry** [comment]
I'm having this issue as well (on my 3090 so it's not VRAM) and it seems to be related to the current nvidia drivers, rolling back solves the issue, this is a problem for me as I sort of need the latest drivers, hopefully it gets corrected soon.

**Comment by MllGll** [comment]
> That means that it crashed. Your using a GTX 1650, so you only have 4gb of VRAM. It's not likely your model is going to be close to that. You will need to tone down the model parameters, create the model again but this time change "Place models and optimizer on GPU" to no, there is no way that it will work if it is set to yes. Also set batch size to 1. If it fails, try using Quick 96 instead of SAEHD.

Thanks, your instructions worked for me, even with resolution in 224!
