### ISSUE TITLE
Best version of DFL to use?

### ISSUE THREAD

**Issue by skynetster** [iperov/DeepFaceLab#556]
Currently using DFL 10.1 for NVidia with 1080ti (11gb) on windows plaftorm, and achieving some nice results, using trainSAEHD and convertSAEHD to avoid out_of_memory errors

Is there a benefit (speed/accuracy) in moving to a later build AND/or the Open GL version?

**Comment by TooMuchFun** [comment]
Use the newest builds. Without then no bug fixes and then no one knows how to help.  Stay up to date unless u are editing code local yourself and know what you are doing in there.
