### ISSUE TITLE
RTX 2060 vs RTX 3060 Which One is better ?

### ISSUE THREAD

**Issue by jacksparrow757** [iperov/DeepFaceLab#5566]
Hi all,

Could anyone please suggest which gpu is better for DFL either rtx 2060 or rtx 3060? Is currently 3060 supported?

**Comment by CodeSmith2000** [comment]
3060 is supported, I use one. In general the 3060 will have more computational power than a 2060, so it would render each frame faster. The biggest difference would be VRAM. 2060 comes in 6gb and 12gb versions while the 3060 comes in 8gb and 12gb. In this application, the more VRAM the better. So discounting the 6 and 8gb models and just putting the two 12gb models head to head, 3060 would be better. It is also more expensive, so its up to you to decide what your speed is worth. This is a place to post code bugs and other such issues regarding the code repository, this is not a deepfake forum.

**Comment by jacksparrow757** [comment]
Thanks for the quick response. I am sorry if I have posted in the wrong place. I am closing the thread :)
