### ISSUE TITLE
whats the meaning of "Enable 'true face' training? (y/n, ?:help skip:n) :"  when in training？

### ISSUE THREAD

**Issue by Dian-Yi** [iperov/DeepFaceLab#557]
Thansk for u work. i have same problems in your work.
the option :"Enable 'true face' training, Is the samples without flip or warp translating when training ? why training the face with the extra background, not using the only faces(masked face)?

**Comment by TooMuchFun** [comment]
In the initial commit says is based off of this https://github.com/NVlabs/FUNIT

**Comment by Dian-Yi** [comment]
> In the initial commit says is based off of this https://github.com/NVlabs/FUNIT

thanks for u answwer, but i cant understand why not using face without background for training, because i find extra pixels without face will influence the generated face's edge when training.
