### ISSUE TITLE
is there a way to restore a corrupted model?

### ISSUE THREAD

**Issue by benx13** [iperov/DeepFaceLab#5570]
Had this model going for two weeks suddenly electricity gets cut something got wrong now getting unpicking error 
`invalid load key '\x00'`

**Comment by benx13** [comment]
I have 
<img width="527" alt="Screen Shot 2022-10-17 at 6 16 24 AM" src="https://user-images.githubusercontent.com/32802278/196094757-f970256e-851c-4dc6-8e2e-ea278c6e5854.png">
is there at least some way to recover some parts of it?

**Comment by CodeSmith2000** [comment]
This is an obvious question, but did you have auto backup turned on?

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.

**Comment by sanyue6686** [comment]
Did the problem get resolved? I'm having the same problem and would like to get help
