### ISSUE TITLE
I can't save pictures after training，but training haven't problem; Maybe something was wrong

### ISSUE THREAD

**Issue by 1910412171** [iperov/DeepFaceLab#5584]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by 1910412171** [comment]
Sorry，I am not 100% fluent，，

**Comment by ghost** [comment]
I can sense that you are not in full working order, please close the issue.
