### ISSUE TITLE
Conversion fails due to OpenCV error -215:Assertion failed

### ISSUE THREAD

**Issue by TheFeelTrain** [iperov/DeepFaceLab#56]
Conversion fails about halfway due to the following error.

```
Exception while process data [undefined]: Traceback (most recent call last):
  File "/mnt/Storage/DeepFaceLab/utils/SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "/mnt/Storage/DeepFaceLab/mainscripts/Converter.py", line 159, in onClientProcessData
    image = self.converter.convert_face(image, image_landmarks, self.debug)
  File "/mnt/Storage/DeepFaceLab/models/ConverterMasked.py", line 173, in convert_face
    out_img = cv2.seamlessClone( (out_img*255).astype(np.uint8), (img_bgr*255).astype(np.uint8), (img_face_mask_flatten_aaa*255).astype(np.uint8), (masky,maskx) , cv2.NORMAL_CLONE )
cv2.error: OpenCV(3.4.4) /io/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'
```

Retrying always fails at the same amount of progress. Happens when running this command:

`python main.py convert --input-dir workspace/data_dst --output-dir workspace/output --aligned-dir workspace/data_dst/aligned --model-dir workspace/model --model H128 `

I've tried using multiple OpenCV, Keras, and Python versions. Still happens regardless.

## Other Information

- **Operating system:** Arch Linux 
- **Python version:** 3.7.1

**Comment by iperov** [comment]
upload your workspace folder

**Comment by TheFeelTrain** [comment]
I don't really feel comfortable doing that. 
It is a pretty standard setup, about 500 faces in data_src and 300 in data_dst.

**Comment by iperov** [comment]
so what you want ? I cannot reproduce your bug. All works fine at me.

**Comment by NetroScript** [comment]
I had a similar error in the faceswap repo, there it was caused by using the seamless option in the masked converter when the detected face was mostly out of bounds (f.e. only chin and mouth visible), my solution there was a check if it can seamlessClone and if not use the non seamless method.

**Comment by iperov** [comment]
anyway I cannot reproduce without buggy workspace folder

**Comment by lewddev** [comment]
I assume it happens when the seamless clone working outside image. ( x < 0 or x > image_width, y < 0 or y > image_height)

**Comment by iperov** [comment]
sure, but I need images and model (workspace) to reproduce it.

**Comment by TheFeelTrain** [comment]
Not sure why you need a workspace to reproduce it. As lewddev says, it happens when the destination face is partially outside the edge of the image. It seems like you would just need to do a check that works around being outside of bounds.

**Comment by iperov** [comment]
How I can fix it without indicator "fixed or not" ?
no workspace - no fix.

**Comment by TheFeelTrain** [comment]
Get a frame of literally any face that is partially outside the bounds of the frame, then attempt to do a conversion on it. You wouldn't even need a trained model. It would take you all of 5 minutes to get.

**Comment by iperov** [comment]
Enough man. No

**Comment by TheFeelTrain** [comment]
Why did you create an open source project if you're not even going to maintain it? 
I'm reporting an actual issue and you're just ignoring it. 2 other people have commented with the same error. 

Either maintain your software or close it down. You're an awful developer and you should be ashamed.

**Comment by iperov** [comment]
@TheFeelTrain 
1) opensource mean many people can maintain it. It doesnt force main developer to maintain it.
2) I asked 3rd times your buggy workspace but you declined it.
3) You spent my time to nothing and insulting me. Im blocking you from this repo.

**Comment by iperov** [comment]
can anyone upload workspace with this bug  ?

**Comment by steveyjharrison** [comment]
> @TheFeelTrain
> 
> 1. opensource mean many people can maintain it. It doesnt force main developer to maintain it.
> 2. I asked 3rd times your buggy workspace but you declined it.
> 3. You spent my time to nothing and insulting me. Im blocking you from this repo.

Wow. I agree with TheFeelTrain. You are an awful developer. He gave you all the info you needed to fix this issue. Yet cause you want to be lazy, you demand his private workspace (or you won't fix the issue). Treat your users with respect, and maybe they will be nice to you. He took time out of his day to help you fix YOUR software. Yet you block him for honest criticism. Pathetic.

**Comment by iperov** [comment]
@steveyjharrison off
