### ISSUE TITLE
Как работать с программой? Плохая документация.

### ISSUE THREAD

**Issue by RandGor** [iperov/DeepFaceLab#560]
В документации написаны какие-то команды, а куда их писать - не написано. В торрентах валяется большой архив с теми батниками. Скачал подходящий для OpenCL.
У меня видюха RX 580 на 8 GB от Gigabyte. 
Запускал батники поэтапно, но каждый раз на 4-м этапе, в 3-м шаге программа останавливалась и ничего не делала. В "avatar only" всё прошло успешно, но лица не выделились вообще.

**Comment by Sacmi** [comment]
@RandGor ты все батники подряд запускал что ли?

**Comment by RandGor** [comment]
> @RandGor ты все батники подряд запускал что ли?

Ты читать умеешь? ПОЭТАПНО! Это означает, что я запускал ВСЕ ПОДРЯД?

**Comment by Sacmi** [comment]
> 
> 
> > @RandGor ты все батники подряд запускал что ли?
> 
> Ты читать умеешь? ПОЭТАПНО! Это означает, что я запускал ВСЕ ПОДРЯД?

> поэтапный; по этапам, в несколько последовательных этапов 
Можно запускать все подряд поэтапно. Сначала первые 1), потом 2) и так далее. Это и будет поэтапно.

**Comment by RandGor** [comment]
Плохая в общем либа, не работает

**Comment by iperov** [comment]
напиши лучше

**Comment by RandGor** [comment]
Удаляй репозиторий, не позорься. Хайп поднял только. Ещё агришься на моё замечание.

**Comment by iperov** [comment]
м  нет, пожалуй я лучше тебя удалю нахуй
