### ISSUE TITLE
merge Quick96 does not initialize merging

### ISSUE THREAD

**Issue by GweiloSONE** [iperov/DeepFaceLab#5619]
It collects everything and then does nothing. No files generated in data_dst/merged

Any help would be appreciated - I am new lol

Below is a full copy of the Quick96 cmd

================================================

Running merger.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : Fany candid - latest
 :
0
Loading Fany candid_Quick96 model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : NVIDIA GeForce RTX 3080

[0] Which GPU indexes to choose? :
0

Initializing models: 100%|###############################################################| 4/4 [00:00<00:00, 11.53it/s]
================ Model Summary =================
==                                            ==
==        Model name: Fany candid_Quick96     ==
==                                            ==
== Current iteration: 100146                  ==
==                                            ==
==-------------- Model Options ---------------==
==                                            ==
==        batch_size: 4                       ==
==                                            ==
==---------------- Running On ----------------==
==                                            ==
==      Device index: 0                       ==
==              Name: NVIDIA GeForce RTX 3080 ==
==              VRAM: 9.24GB                  ==
==                                            ==
================================================
[y] Use interactive merger? ( y/n ) :
y
[20] Number of workers? ( 1-20 ?:help ) :
20
Collecting alignments: 100%|#####################################################| 17915/17915 [17:07<00:00, 17.44it/s]
Computing motion vectors: 100%|################################################| 30615/30615 [00:13<00:00, 2282.93it/s]
Running on CPU1.
Running on CPU0.
Running on CPU4.
Running on CPU7.
Running on CPU2.
Running on CPU10.
Running on CPU3.
Running on CPU8.
Running on CPU6.
Running on CPU9.
Running on CPU11.
Running on CPU12.
Running on CPU15.
Running on CPU18.
Running on CPU5.

**Comment by lost2407** [comment]
Hello , i have the exact same issue as you. 
It seem you have found a way to make it work.
Could you tell me how did you do ?
