### ISSUE TITLE
convert SAEHD on 2nd GPU

### ISSUE THREAD

**Issue by wuffenberg** [iperov/DeepFaceLab#563]
In Converter.py is a comment

           #model process ate all GPU mem,
            #so we cannot use GPU for any TF operations in converter processes
            #therefore forcing active_DeviceConfig to CPU only
            nnlib.active_DeviceConfig = nnlib.DeviceConfig (cpu_only=True)

but what about if there is a 2nd GPU available? Can this be used for conversion instead of the rather slow CPU based conversion? Any possibility to modify the scripts accordingly?

(And thanks for your great SW - I have already donated and keep using it since weeks.)
Tom

**Comment by blanuk** [comment]
that is a great idea, but i think he wouldnt do that because its to much work and he removed the double card training.
BUT: i think that would be another 100 Bucks Donation worth

**Comment by blanuk** [comment]
Here it goes. with DFL2 its possible :)

**Comment by wuffenberg** [comment]
Tell me more, please. Did you manage to convert on a 2nd GPU instead of the CPU?
Where to find the DFL2 code, I cannot see any branch or fork..?

**Comment by blanuk** [comment]
its the cuda build.

**Comment by wuffenberg** [comment]
I am using DeepFaceLab_CUDA_build_01_11_2020  which includes CUDA9.2, and yes, the covert_SAEHD.bat uses my RTX2060S, but only to store the model in the VRAM. The calculation/conversion seems to be running only on the CPU, because processor load goes to 100%, while the GPU1 is used only little, and GPU2 is completely unused:
![image](https://user-images.githubusercontent.com/60057801/73060956-4d898d00-3e99-11ea-8441-847e3185cbe4.png)

![image](https://user-images.githubusercontent.com/60057801/73061381-5464cf80-3e9a-11ea-8b2b-2dfb3eb696fc.png)

![image](https://user-images.githubusercontent.com/60057801/73061349-42832c80-3e9a-11ea-8356-0a29058903ec.png)

That's why I was wondering if the converter.py script can be modified in such a way that the conversion uses the GPU2 DSPs instead of the CPU.
Hope I made the issue clear.

**Comment by blanuk** [comment]
sure, us the nvidia build with newest date and not the cuda build

**Comment by wuffenberg** [comment]
@iperov @blanuk : Kudos to you!! I confirm that convert now works waaayyy faster with the usage of 2 GPUs. Perfect! And second donation is on the way ;)

But now there is another [issue when training with 2GPUs](https://github.com/iperov/DeepFaceLab/issues/574)
