### ISSUE TITLE
Why is deepfakeclub website redirecting to this repo?

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [iperov/DeepFaceLab#57]
Since when has the site been gone, and does deepfakeclub forum now endorse using this application? what happened to openfaceswap? does anyone use that anymore?

**Comment by iperov** [comment]
owner decided to close his site

his message to me :

> Hey, I closed my site and redirected all my traffic to your github. Around 3000 a day from google alone, but the google ranks will drop now that I redirected. Have fun!

And I dont what is OpenFaceSwap, never use it.
