### ISSUE TITLE
Mem usage 

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#571]
First of all, thanks for great update. It looks very promising!

I did some testing after you released this yesterday, and wonder if this is normal behaviour:

Quick96 is faster on 1 GPU than on 2. (Actually it seems twice as fast in single mode, around 100 ms/it on Gtx 1080ti, but then 220 ms/it when I use both cards)

When running SAEHD with two cards (identical), only memory from 1 card is used. And on average it seems to be using only half of what is available looking on the graph. When upping batch size I still get OOM.

Here are GPU loads, mem usage etc.
![Gpu mem usage](https://user-images.githubusercontent.com/48013922/72985178-adbef700-3de5-11ea-8cb3-88db9a4573a4.PNG)
![GPU usage](https://user-images.githubusercontent.com/48013922/72985180-b1527e00-3de5-11ea-99d6-408e67b8c02f.PNG)
![CPU mem usage](https://user-images.githubusercontent.com/48013922/72985186-b4e60500-3de5-11ea-8b6f-cedbf0730a76.PNG)

**Comment by iperov** [comment]
is sli disabled?

**Comment by iperov** [comment]
I already tested new dfl on mining farm, all works fine.

**Comment by iperov** [comment]
> Quick96 is faster on 1 GPU than on 2

it should not be faster. MultiGPU just divides batch across gpus.

**Comment by Tesla32X** [comment]
Ah. I restarted and it all seems fine now. My bad.
