### ISSUE TITLE
how to setup GPU for training?

### ISSUE THREAD

**Issue by flydragon2018** [iperov/DeepFaceLab#5714]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

training with GPU

## Actual behavior

the default device is running on CPU

## Steps to reproduce

I am using  DeepFaceLab_Linux.
I could use GPU to extract images etc. 

## Other relevant information
 
what is the configuration file or  device parameter for training   scripts, like  

5_XSeg_train.sh
6_train_Quick96.sh

**Comment by flydragon2018** [comment]
never mind.   I should look into the deepfacelab codes.
currently  I only look for the scripts in deepfacelab_linux.

**Comment by armaankachhawa** [comment]
;HTTP:{app 
{m/N 💯    
//
//
.
.
Rttu: [ rotation : 180 ]
ll
(atternation 🔢  ) 
.
.
.
.
.
 so bro fixed the title 👍

**Comment by flydragon2018** [comment]
my local configuration problem? 
when I continue to train the model, now It prompts to select GPU index for training.
