### ISSUE TITLE
NVIDIA Cache rewritten for every training with 2 GPUs

### ISSUE THREAD

**Issue by wuffenberg** [iperov/DeepFaceLab#574]
## Expected behavior
As in the previous DFL versions, the NVIDIA Cache under "_internal\_e\u\Appdata\Roaming\NVIDIA" was only initialized after new installation upon model first run. All further runs like training, .. kept the cache unchanged.

## Actual behavior
This is still the same if you run the training only on one GPU. If you choese two GPUs (0,1), then large parts of the cache are rewritten, which takes a lot of time (>10 minutes).

## Steps to reproduce
Train new model with only GPU0: 
"_Caching GPU kernels..._" (thats ok)
next train will skip this and start immediately with "_Initializing models_"

Train above model with only GPU1:
Cache for GPU1 is created (thats ok)
next train will skip this and start immediately with "_Initializing models_"

Train above created model with GPU0 and GPU1 (0,1)
Cache for GPU0GPU1 is created (thats ok)
**BUT:** if you run train again, the cache is somehow recreated and it takes long time (>10 min) before "_Initializing models_"

Maybe an issue in the nn.py script

## Other relevant information
Win7 x64
  [0] : GeForce RTX 2060 SUPER
  [1] : GeForce GTX 1050 Ti

**Comment by iperov** [comment]
1) this is nvidia problem, not miine
2) you should not train on different gpus. 2060 is much faster than 1050

**Comment by wuffenberg** [comment]
Now I tried to train only on single 2060 and you are fully right: that works 3x faster than on 2060 and 1050 together - surprise! (500ms vs. 1500ms).
Thanks for the hint. Issue closed.
