### ISSUE TITLE
Windows VM

### ISSUE THREAD

**Issue by JakubReha** [iperov/DeepFaceLab#576]
Hi,
I am trying to run the DeepFaceLab_1.0_CUDA_build_11_14_2019 on a Windows 2012 R2 VM with NVIDIA Tesla P4. I ran setenv.bat but when I try to extract faces from the videos ((4) data_src extract faces S3FD all GPU) I get this error:
<img width="664" alt="Screenshot 2020-01-24 at 17 15 18" src="https://user-images.githubusercontent.com/44469049/73121126-0b367d80-3f77-11ea-974a-7d94f5042a2c.png">

**Comment by TooMuchFun** [comment]
Have you try other windows version? 2012 is a very old release. MS has free VMs you can download and test with. But NVIDIA is not very interested in VM support on Windows. Hyperv is lame

**Comment by JakubReha** [comment]
yeah I tried 2019, it gives the same error

**Comment by wuffenberg** [comment]
Might be that your filepaths are too deep/long (mavimum of 256 chars for ntfs). Try to rename the folder to something shorter, eg DFL9.2 and move it to the root directory C: 
Does that work?

**Comment by iperov** [comment]
VM is not supported
