### ISSUE TITLE
Can't override model trainer settings in Ubuntu

### ISSUE THREAD

**Issue by youmebangbang** [iperov/DeepFaceLab#581]
With Ubuntu, when pressing Enter at the option to override settings before training the program skips user input and begins training with the first run settings instead.  Windows release seems to work fine though.

**Comment by wuffenberg** [comment]
maybe this topic and (possible) solution will help?
[The new convert (or merge saehd) has a problem with overwriting settings](https://github.com/iperov/DeepFaceLab/issues/579)

**Comment by youmebangbang** [comment]
> maybe this topic and (possible) solution will help?
> [The new convert (or merge saehd) has a problem with overwriting settings](https://github.com/iperov/DeepFaceLab/issues/579)

that is for converter, this problem is for trainer

**Comment by orkblutt** [comment]
@youmebangbang can you please test the fix from this:
https://github.com/iperov/DeepFaceLab/pull/585/files

**Comment by seven110** [comment]
Fixed it for me running Centos7 and the latest git pull with this fixed placed on top.
Thanks.

**Comment by youmebangbang** [comment]
> @youmebangbang can you please test the fix from this:
> https://github.com/iperov/DeepFaceLab/pull/585/files

Yes it works, thank you so much!
