### ISSUE TITLE
Extractor slower than it can be

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#582]
On the newest DFL Version, the Extractor only use half of the usable VRAM.
I can start 2 Instances multigpu of extracting at the same time and this way, it nearly doubles the speed of extraction.
Is it possible to just double the workers in the code? If yes, where?
as u can see, it works fine with the double of load :)
![two](https://user-images.githubusercontent.com/50863475/73139474-9b0b2300-406e-11ea-92ca-e826e982026b.jpg)

Another try: 3 Instances on the Titan and 2 Instances on the 2080ti:
it uses for each Instance 5GB VRAM. so, 2080ti is full, works with about 60-70% CUDA load and the RTX ises 15GB and have a load of 80-90%

**Comment by iperov** [comment]
vram usage is nothing.
Extractor is slow but very accurate.
Compare with /faceswap shit.

**Comment by blanuk** [comment]
i dont know what u mean, iperov. i mean it actually scale not as good as it could, thats why im asking. as u can see on the picture above, double of speed is possible without an error. my question is why does it not scale to use more cuda load. is it because of compatibility with slower cards? is there set a limit in code? If yes, where is this set in the code?

**Comment by iperov** [comment]
I can set 2 instances per >= 11GB gpu.
It gives only +20% overall speed boost.

but if that GPU is used by windows,
we will get this error:

![NVIDIA Share_2020-01-27_13-04-51](https://user-images.githubusercontent.com/8076202/73161780-c8ef7680-4105-11ea-8ac6-e3794e11d4c8.jpg)

thus DFL will be unstable for most users.
Better is stable version than 20% boost.

Adding option 'instances per GPU' will be also redundant.

**Comment by blanuk** [comment]
can i try it on my sys?
maybe u run out of RAM? (I had to upgrade up to 128GB to avoid out of memory)

**Comment by iperov** [comment]
no. I have 64gb.

**Comment by blanuk** [comment]
well, so i use the workaround.
Thanks anyway :)
