### ISSUE TITLE
DFL2.0 with CUDA 10.2?

### ISSUE THREAD

**Issue by wuffenberg** [iperov/DeepFaceLab#584]
CUDA10.2 supports the Turing Architecture (which add support for the tensor cores).
Is it possible to use DFL2.0 with CUDA10.2? 
Would the DFL processing speed increase by that?

If yes, any word on how to add CUDA10 in the project? Can I somehow do this with my local DFL2.0 verison installed on Win7?

**Comment by iperov** [comment]
you dont know what is cuda
