### ISSUE TITLE
Multi GPU broken in latest GAN DFL release

### ISSUE THREAD

**Issue by mpmo10** [iperov/DeepFaceLab#588]
First issue is that i cannot increase batch size more than when using my rtx titan alone, which is 8 batch size. (before the latest release, i could go up to 30). Now when using RTX titan + 2080 ti in multi gpu, anything above 8 batch size gives OOM. Same as using rtx titan alone.

Second issue is that it is going at 8000 ms in multi gpu mode compared to 2000 ms when using rtx titan alone, here's proof. It's using 10/11 gb of 2080 ti, and 17/24 gb of rtx titan. 99% cpu usage, 37,000 mb of ram 

https://cdn.discordapp.com/attachments/606447508004143124/671755575021010968/Screenshot_284.png

**Comment by iperov** [comment]
all works fine

**Comment by mpmo10** [comment]
> all works fine

8000 ms per iteration is fine? multi gpu is literally making my training slower and i can't go higher batch size compared to using a single titan....so there's no point in multi gpu in the latest release

**Comment by iperov** [comment]
i cannot explain same things to everyone every time
just don't use if it not for you
