### ISSUE TITLE
DFL 2.0 Latest Release Multi-GPU 1/28/2019

### ISSUE THREAD

**Issue by ajgoyt** [iperov/DeepFaceLab#589]
Hello - Multi gpu is not working correctly, **it is working but it's not up to our satisfaction**, We understand this is a new release and their will be issues. I am just letting you know what we are seeing while testing the latest release.  

My PC specs:
AMD RYZEN 3900x 12 core 
64gb 3400mhz Patriot ram
1 tb WD M2 drive
Twin NVIDIA RTX2060 Supers (8gb Vram each)
OS Windows 10 64bit
No other programs or antivirus running

1. Iteration speed - very slow even when leaving the stock out of the gate settings.

2. Resources - on the latest release we are still seeing CPU fluctuation between 50-100% spikes every 1-2 seconds.

3. Use able VRAM in Multi gpu - when monitoring both GPU's the VRAM is appears to be only using a max of 35% but very's between each GPU and is consistently 
between alternating between each GPU 0-10 -25%-35%, this pattern seems to be following a similar pattern as the CPU.

4.  The option too change resolution comes up after restarting training, dont think this is correct.

5. On very 1st run the option to save a backup model is bypassed, if training is stopped and restarted you can then save a backup.

Thank you and I look forward to your reply.

**Comment by iperov** [comment]
try 1/30 build

**Comment by elemantalcode** [comment]
1/30 build test with extracting src faces only:

`Thu Jan 30 20:36:20 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   79C    P0    44W /  70W |   5441MiB / 15109MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   80C    P0    62W /  70W |   5459MiB / 15109MiB |     73%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   80C    P0    49W /  70W |   5441MiB / 15109MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   77C    P0    56W /  70W |   5441MiB / 15109MiB |     67%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       859      C   /bin/python3.6                              5131MiB |
|    0       860      C   /bin/python3.6                                99MiB |
|    0       861      C   /bin/python3.6                                99MiB |
|    0       862      C   /bin/python3.6                                99MiB |
|    1       859      C   /bin/python3.6                                99MiB |
|    1       860      C   /bin/python3.6                              5149MiB |
|    1       861      C   /bin/python3.6                                99MiB |
|    1       862      C   /bin/python3.6                                99MiB |
|    2       859      C   /bin/python3.6                                99MiB |
|    2       860      C   /bin/python3.6                                99MiB |
|    2       861      C   /bin/python3.6                              5131MiB |
|    2       862      C   /bin/python3.6                                99MiB |
|    3       859      C   /bin/python3.6                                99MiB |
|    3       860      C   /bin/python3.6                                99MiB |
|    3       861      C   /bin/python3.6                                99MiB |
|    3       862      C   /bin/python3.6                              5131MiB |
+-----------------------------------------------------------------------------+`

Interestingly, when running extract on src AND dst at same time:

`Thu Jan 30 20:38:36 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   81C    P0    83W /  70W |  10891MiB / 15109MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   80C    P0    79W /  70W |  10889MiB / 15109MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   80C    P0    67W /  70W |  10879MiB / 15109MiB |     92%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   78C    P0    44W /  70W |  10889MiB / 15109MiB |     79%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       859      C   /bin/python3.6                              5131MiB |
|    0       860      C   /bin/python3.6                                99MiB |
|    0       861      C   /bin/python3.6                                99MiB |
|    0       862      C   /bin/python3.6                                99MiB |
|    0      2505      C   /bin/python3.6                              5151MiB |
|    0      2506      C   /bin/python3.6                                99MiB |
|    0      2507      C   /bin/python3.6                                99MiB |
|    0      2508      C   /bin/python3.6                                99MiB |
|    1       859      C   /bin/python3.6                                99MiB |
|    1       860      C   /bin/python3.6                              5149MiB |
|    1       861      C   /bin/python3.6                                99MiB |
|    1       862      C   /bin/python3.6                                99MiB |
|    1      2505      C   /bin/python3.6                                99MiB |
|    1      2506      C   /bin/python3.6                              5131MiB |
|    1      2507      C   /bin/python3.6                                99MiB |
|    1      2508      C   /bin/python3.6                                99MiB |
|    2       859      C   /bin/python3.6                                99MiB |
|    2       860      C   /bin/python3.6                                99MiB |
|    2       861      C   /bin/python3.6                              5131MiB |
|    2       862      C   /bin/python3.6                                99MiB |
|    2      2505      C   /bin/python3.6                                99MiB |
|    2      2506      C   /bin/python3.6                                99MiB |
|    2      2507      C   /bin/python3.6                              5139MiB |
|    2      2508      C   /bin/python3.6                                99MiB |
|    3       859      C   /bin/python3.6                                99MiB |
|    3       860      C   /bin/python3.6                                99MiB |
|    3       861      C   /bin/python3.6                                99MiB |
|    3       862      C   /bin/python3.6                              5131MiB |
|    3      2505      C   /bin/python3.6                                99MiB |
|    3      2506      C   /bin/python3.6                                99MiB |
|    3      2507      C   /bin/python3.6                                99MiB |
|    3      2508      C   /bin/python3.6                              5149MiB |
+-----------------------------------------------------------------------------+`

**Comment by elemantalcode** [comment]
Running 1/30 build single extract faces on data_src:

Thu Jan 30 20:36:20 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   79C    P0    44W /  70W |   5441MiB / 15109MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   80C    P0    62W /  70W |   5459MiB / 15109MiB |     73%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   80C    P0    49W /  70W |   5441MiB / 15109MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   77C    P0    56W /  70W |   5441MiB / 15109MiB |     67%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       859      C   /bin/python3.6                              5131MiB |
|    0       860      C   /bin/python3.6                                99MiB |
|    0       861      C   /bin/python3.6                                99MiB |
|    0       862      C   /bin/python3.6                                99MiB |
|    1       859      C   /bin/python3.6                                99MiB |
|    1       860      C   /bin/python3.6                              5149MiB |
|    1       861      C   /bin/python3.6                                99MiB |
|    1       862      C   /bin/python3.6                                99MiB |
|    2       859      C   /bin/python3.6                                99MiB |
|    2       860      C   /bin/python3.6                                99MiB |
|    2       861      C   /bin/python3.6                              5131MiB |
|    2       862      C   /bin/python3.6                                99MiB |
|    3       859      C   /bin/python3.6                                99MiB |
|    3       860      C   /bin/python3.6                                99MiB |
|    3       861      C   /bin/python3.6                                99MiB |
|    3       862      C   /bin/python3.6                              5131MiB |
+-----------------------------------------------------------------------------+

Running both data_src extract and data_dst extract in parallel:

Thu Jan 30 20:38:36 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   81C    P0    83W /  70W |  10891MiB / 15109MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   80C    P0    79W /  70W |  10889MiB / 15109MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   80C    P0    67W /  70W |  10879MiB / 15109MiB |     92%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   78C    P0    44W /  70W |  10889MiB / 15109MiB |     79%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       859      C   /bin/python3.6                              5131MiB |
|    0       860      C   /bin/python3.6                                99MiB |
|    0       861      C   /bin/python3.6                                99MiB |
|    0       862      C   /bin/python3.6                                99MiB |
|    0      2505      C   /bin/python3.6                              5151MiB |
|    0      2506      C   /bin/python3.6                                99MiB |
|    0      2507      C   /bin/python3.6                                99MiB |
|    0      2508      C   /bin/python3.6                                99MiB |
|    1       859      C   /bin/python3.6                                99MiB |
|    1       860      C   /bin/python3.6                              5149MiB |
|    1       861      C   /bin/python3.6                                99MiB |
|    1       862      C   /bin/python3.6                                99MiB |
|    1      2505      C   /bin/python3.6                                99MiB |
|    1      2506      C   /bin/python3.6                              5131MiB |
|    1      2507      C   /bin/python3.6                                99MiB |
|    1      2508      C   /bin/python3.6                                99MiB |
|    2       859      C   /bin/python3.6                                99MiB |
|    2       860      C   /bin/python3.6                                99MiB |
|    2       861      C   /bin/python3.6                              5131MiB |
|    2       862      C   /bin/python3.6                                99MiB |
|    2      2505      C   /bin/python3.6                                99MiB |
|    2      2506      C   /bin/python3.6                                99MiB |
|    2      2507      C   /bin/python3.6                              5139MiB |
|    2      2508      C   /bin/python3.6                                99MiB |
|    3       859      C   /bin/python3.6                                99MiB |
|    3       860      C   /bin/python3.6                                99MiB |
|    3       861      C   /bin/python3.6                                99MiB |
|    3       862      C   /bin/python3.6                              5131MiB |
|    3      2505      C   /bin/python3.6                                99MiB |
|    3      2506      C   /bin/python3.6                                99MiB |
|    3      2507      C   /bin/python3.6                                99MiB |
|    3      2508      C   /bin/python3.6                              5149MiB |
+-----------------------------------------------------------------------------+
