### ISSUE TITLE
Color Transfer by Neural Networking

### ISSUE THREAD

**Issue by lewddev** [iperov/DeepFaceLab#59]
I found this paper looks very interesting and we may use this for better color transferring.

![image](https://user-images.githubusercontent.com/39359850/49712869-1518f680-fc79-11e8-9981-244654340f39.png)

Reference:
https://arxiv.org/abs/1710.00756
https://liaojing.github.io/html/data/color_supp.pdf
https://www.reddit.com/r/MachineLearning/comments/748cco/r_neural_color_transfer_between_images/
https://github.com/luanfujun/deep-photo-styletransfer

**Comment by iperov** [comment]
no demo how it works in video.
No source code in tf or keras.
