### ISSUE TITLE
Encoder dims can't be changed after restarting a model train.

### ISSUE THREAD

**Issue by tokafondo** [iperov/DeepFaceLab#592]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Change encoder dims after stopping training.

## Actual behavior

When changing training options after thousands of iterations, several options can be changed but not encoder dims.

## Steps to reproduce

- Start training a model from scratch from processed facesets. 
- Set train options as needed.
- Stop training when desired.
- Restart training the same model.
- Before 2 seconds, press enter to change train parameters.
- No "encoder dims" option is shown. 

## Other relevant information

I don't really know if this is a bug or something that can be changed after train has started, so I post it as a bug. Thanks for you hard work.

**Comment by TooMuchFun** [comment]
Dims and things like this define how your model is shaped in the begining. Once you create a model you cannot change the shape of the network.

**Comment by tokafondo** [comment]
Thank you. I will think twice next times before starting training.
