### ISSUE TITLE
Mask Export Doesn't Seem To Work

### ISSUE THREAD

**Issue by kilerb** [iperov/DeepFaceLab#593]
I know you made a few changes to this, so maybe I'm doing something wrong...  But I've exported DFL masks to Adobe Premiere many times in the past.  I train saehd, then merge saehd.  Click B for 'show alpha mask' so it's just the face on a checkerboard.  Everything is just like it used to be.  I export MOV lossless.  It now creates 2 files just like the changelog said it would.  1 is result.mov which is just the entire video, background and mask together.  And the 2nd one is result_mask.mov and according to the changelog I can put that in as the mask layer....  But I've tried twice now and that layer is just a black background with a completely white mask.  It used to be the face.  Did I miss a step or is something wrong?  Included a screen capture.  
Thanks!  (This is with the 1/28 version btw...  Just noticed 1/29 is out.)
![cap](https://user-images.githubusercontent.com/6969681/73410462-2971e580-42b7-11ea-9e1f-e501fe0c70a8.jpg)

**Comment by iAmien** [comment]
I don't think it is a bug, but I'm also trying to figure out how to use a mask layer in Premiere

**Comment by kilerb** [comment]
I’ve done it so many times on previous versions.  Neither of the two files
that exports become a usable overlay layer.  There might be something new
that we have to do in the new version. But I’m not sure.

**Comment by iperov** [comment]
using mask work in AfterEffects.

result_mask.mp4-> Effect -> Keying -> Extract , hide layer
result.mp4 -> Effect -> Channel -> Set matte -> use for luminance

![2020-01-30_14-53-17](https://user-images.githubusercontent.com/8076202/73443538-51714f80-4370-11ea-8709-b3a43fded1b0.gif)

**Comment by kilerb** [comment]
What about adobe premiere? That’s where I’ve always imported the overlay in
the past.  Neither of the files seems to work properly in there like it
used to. Thanks!

**Comment by iperov** [comment]
I dont know.
I dont use premiere

**Comment by iperov** [comment]
perhaps you just don't know how to use black/white video file as mask for another layers in Premiere

**Comment by kilerb** [comment]
That’s possible. In the past versions, it wasn’t black-and-white. It was
the actual face floating around on a black background.  Then I would just
import it over the original video and the new face would be there and I
could adjust it the way I want.  How can the completely white face do that?

**Comment by iperov** [comment]
> How can the completely white face do that?

already told.

**Comment by kilerb** [comment]
OK thanks… I will see if those similar features are in adobe premiere. If
not I will try after effects. Thanks!

**Comment by iperov** [comment]
using mask as separated file is much better,
because I received same question from many users: "where is the exported mask"

**Comment by iAmien** [comment]
@kilerb , i figured it out from iperov's settings, try this

![image](https://user-images.githubusercontent.com/9248489/73444506-5c70b380-4361-11ea-8a47-1a0cf3fadb48.png)

**Comment by kilerb** [comment]
Hi Amien.   Are you sure that is correct? It looks like you have V3
invisible. There is a line through the eye.   And it looks like that is the
timeline you put the luminance matte on.  Then you put the original video
above it which isn’t masked. Is that all correct? It seems like you can’t
even anything below V4.  Because that’s just the regular video, right? Let
me know if I’m getting this wrong. I’m trying it on mine right now and it
doesn’t seem to do anything.

**Comment by kilerb** [comment]
I guess my question is what are you doing to the line V4?  You put the
luminance mask on V3 right?  But V4 seems to be blocking everything and
it's not a mask.  Let me know what I'm missing.  Thanks! :)

**Comment by iAmien** [comment]
@kilerb yes 100% , i followed iperov's instructions, note that the result_mask is hidden there too
The luminance matte is on result.mp4 (white selected clip)

> using mask work in AfterEffects.
> 
> result_mask.mp4-> Effect -> Keying -> Extract , hide layer
> result.mp4 -> Effect -> Channel -> Set matte -> use for luminance

**Comment by kilerb** [comment]
Got it!  Thanks guys!

**Comment by iAmien** [comment]
@kilerb how do you feather & crop the mask/face layer in premiere?

**Comment by kilerb** [comment]
I haven’t been doing either of those things. I like to have the face is
separate so when I have multiple faces on the screen at the same time they
can all be independent of each other. I can adjust the color and brightness
a little if need be. And if I discover one of the older faces on the screen
doesn’t look as good I can go back and retrain or convert again.  If you
keep putting masks on top of the same video, you are stuck with whatever
you settle with the first time.

**Comment by turnip26** [comment]
> I know you made a few changes to this, so maybe I'm doing something wrong... But I've exported DFL masks to Adobe Premiere many times in the past. I train saehd, then merge saehd. Click B for 'show alpha mask' so it's just the face on a checkerboard. Everything is just like it used to be. I export MOV lossless. It now creates 2 files just like the changelog said it would. 1 is result.mov which is just the entire video, background and mask together. And the 2nd one is result_mask.mov and according to the changelog I can put that in as the mask layer.... But I've tried twice now and that layer is just a black background with a completely white mask. It used to be the face. Did I miss a step or is something wrong? Included a screen capture.
> Thanks! (This is with the 1/28 version btw... Just noticed 1/29 is out.)
> ![cap](https://user-images.githubusercontent.com/6969681/73410462-2971e580-42b7-11ea-9e1f-e501fe0c70a8.jpg)

Hi, I wanted to know how to do this too and after some digging the tutorial below tells you how ....

https://photography.tutsplus.com/tutorials/how-to-use-luma-matte-transitions-premiere-pro--cms-30584
