### ISSUE TITLE
RuntimeWarning: divide by zero encountered in float_scalars

### ISSUE THREAD

**Issue by park-youngsin** [iperov/DeepFaceLab#595]
I'm getting this error very often when i train [SAEHD]
I used DFL version 2.0 on linux

============== Model Summary ===============
==                                        ==
==            Model name: new_SAEHD       ==
==                                        ==
==     Current iteration: 0               ==
==                                        ==
==------------ Model Options -------------==
==                                        ==
==            resolution: 256             ==
==             face_type: f               ==
==     models_opt_on_gpu: True            ==
==                 archi: dfhd            ==
==               ae_dims: 512             ==
==                e_dims: 128             ==
==                d_dims: 96              ==
==           d_mask_dims: 32              ==
==           use_float16: True            ==
==            learn_mask: True            ==
==            lr_dropout: False           ==
==           random_warp: True            ==
==             gan_power: 0.0             ==
==       true_face_power: 0.0             ==
==      face_style_power: 0.0             ==
==        bg_style_power: 0.0             ==
==               ct_mode: rct             ==
==              clipgrad: False           ==
==              pretrain: False           ==
==            autobackup: True            ==
== write_preview_history: False           ==
==           target_iter: 0               ==
==           random_flip: False           ==
==            batch_size: 30              ==
==                                        ==
==-------------- Running On --------------==
==                                        ==
==          Device index: 1               ==
==                  Name: Quadro RTX 8000 ==
==                  VRAM: 47.46GB         ==
==          Device index: 2               ==
==                  Name: Quadro RTX 8000 ==
==                  VRAM: 47.46GB         ==
==          Device index: 3               ==
==                  Name: Quadro RTX 8000 ==
==                  VRAM: 47.46GB         ==
==                                        ==
============================================
Starting. Press "Enter" to stop training and save model.

Trying to do the first iteration. If an error occurs, reduce the model parameters.

[14:10:40][#000002][4892ms][5.5684][5.6426]                                     
[14:11:56][#000017][4997ms][3.5254][3.9082]/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:243: RuntimeWarning: divide by zero encountered in float_scalars
  a = (aStdSrc / aStdTar) * a
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:243: RuntimeWarning: invalid value encountered in multiply
  a = (aStdSrc / aStdTar) * a
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:244: RuntimeWarning: divide by zero encountered in float_scalars
  b = (bStdSrc / bStdTar) * b
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:244: RuntimeWarning: invalid value encountered in multiply
  b = (bStdSrc / bStdTar) * b
[14:21:32][#000130][4818ms][3.5234][3.9355]/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:243: RuntimeWarning: divide by zero encountered in float_scalars
  a = (aStdSrc / aStdTar) * a
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:243: RuntimeWarning: invalid value encountered in multiply
  a = (aStdSrc / aStdTar) * a
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:244: RuntimeWarning: divide by zero encountered in float_scalars
  b = (bStdSrc / bStdTar) * b
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:244: RuntimeWarning: invalid value encountered in multiply
  b = (bStdSrc / bStdTar) * b
[14:24:55][#000170][4856ms][3.5566][3.9727]/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:243: RuntimeWarning: divide by zero encountered in float_scalars
  a = (aStdSrc / aStdTar) * a
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:243: RuntimeWarning: invalid value encountered in multiply
  a = (aStdSrc / aStdTar) * a
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:244: RuntimeWarning: divide by zero encountered in float_scalars
  b = (bStdSrc / bStdTar) * b
/home/admin1/app/DeepFaceLab-master/core/imagelib/color_transfer.py:244: RuntimeWarning: invalid value encountered in multiply
  b = (bStdSrc / bStdTar) * b
[14:25:57][#000180][4843ms][3.5565][3.9571]

**Comment by orkblutt** [comment]
hi,
can you try without color transfer for the first iterations and then turn it on ?

What mother board are you using for 3x RTX 8000 ?

**Comment by blanuk** [comment]
== use_float16: True ==
is removed in the actual version, so better dont use it anymore :)
