### ISSUE TITLE
Question about random warp and lr-dropout

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#596]
Shoud any of these parameters increase the model size drastically? When lr-dropout is disabled and random warp is enabled, I can run a bs of 10. With lr-dropout enabled, and random warp disabled I can’t start the same project with bs 4 or even 2.

**Comment by danhoeg** [comment]
you need random warp to generalize; once the face is sufficiently trained, disable it and you should be able to get more sharpness/less iterations.

**Comment by danhoeg** [comment]
look at iperov's git

**Comment by Tesla32X** [comment]
I know, which is why I would like to disable random warp. But then I get OOM on lower bs.

**Comment by iperov** [comment]
random warp just changes input samples only (random warped or not)

lr_dropout requires extra vram of [model_size]*1

**Comment by Tesla32X** [comment]
Ok, thanks for clearing that.
