### ISSUE TITLE
Why HALF-FACE Model need a mask layer?

### ISSUE THREAD

**Issue by Jasas9754** [iperov/DeepFaceLab#6]
It seems necessary for full-face(exclude background).
But H64, H128, why need it? it's slow and it eats VRAM. And having a mask layer does not particularly improve quality.

for convert process?

I would appreciate it if someone could explain the thing.

Thank you

**Comment by iperov** [comment]
> And having a mask layer does not particularly improve quality.

seriously?

**Comment by iperov** [comment]
then use faceswap, it hasnt mask and produces much more flickering

**Comment by Jasas9754** [comment]
Thank you
