### ISSUE TITLE
What is the full name of LIAEF and MIAEF

### ISSUE THREAD

**Issue by Arthurzhangsheng** [iperov/DeepFaceLab#60]
Hi, I'm an AI researcher, too. Very curious about the full name of **LIAEF** and **MIAEF**?
As I known, **AE** means autoencoder, does **IAE** refers to Implicit Autoencoders?
Besides, what's the letter **L**,**M**,**F** stands for?

Thanks for reply~

**Comment by iperov** [comment]
first was AutoEncoder/
Then one man in faceswap repo created Improved AutoEncoder https://github.com/deepfakes/faceswap/pull/251 which agressively morfing face to face. Also it was half face model.

Then I created my own repo DeepFaceLab from scratch with better architecture than faceswap.
My first models was half and full face models.
H - mean half face model (H64, H128)
F - mean Full face model. 
DF - Dfaker's Fullface

Full face of course doesnt mean really full face, just wider than regular half face.

then I was continue researching near IAE, new better model I called " Less agressive IAE Full face model"
Then I was searching new model which will morph B/W face and colorize it. I didnt think about good name, so I just called next letter after L - MIAEF :D
Sry bad english in time sentences :D

If you can port BicycleGAN to keras, it would be great. I would use it as new avatar model.

**Comment by Arthurzhangsheng** [comment]
HAHAHA......, **M** is the next version of **L**, you are very interesting :D

**Comment by TooMuchFun** [comment]
@iperov is this keras port of BicycleGAN helpful?

https://github.com/manicman1999/BicycleGAN-Keras

**Comment by iperov** [comment]
cool, but i have no time to adapt it to dfl

**Comment by KeyKy** [comment]
@Arthurzhangsheng Where do you find the model of MIAEF
