### ISSUE TITLE
Where to find changelog

### ISSUE THREAD

**Issue by wuffenberg** [iperov/DeepFaceLab#604]
Where to find changelog without downloading the full DFL.exe? Couldn't locate it on github..?

**Comment by wa407** [comment]
就在这里就有啊，若没有找到只能是你不够认真。

**Comment by wuffenberg** [comment]
First: write in English
Second: only relevant answers please, otherwise keep your messages for yourself...

**Comment by TooMuchFun** [comment]
Read the git commit log. 

Also, don't be toxic. Thx.

**Comment by wuffenberg** [comment]
I mean this short text file
[changelog.txt](https://github.com/iperov/DeepFaceLab/files/4153650/changelog.txt)

Not this : https://github.com/iperov/DeepFaceLab/commits/master

So is the short text file also available here somewhere?

And I don't accept comments like the one from wa407. This is not preschool here...

**Comment by TooMuchFun** [comment]
> So is the short text file also available here somewhere?

Not currently, sorry.
