### ISSUE TITLE
Can DeepFaceLab support Nvidia RTX NVLink for more VRAM ?

### ISSUE THREAD

**Issue by videoprice** [iperov/DeepFaceLab#605]
Hi, Want to ask about Nvidia RTX NVLink. If I connect 2xRTX 2080TI 11GB I got 22GB Vram with RTX NVLink. 
Can DeepFaceLab support this RTX NVLink future?
Thanks,
Richard

**Comment by blanuk** [comment]
that would be interessting

**Comment by iperov** [comment]
no

**Comment by capsmanofficial** [comment]
WHY ?

**Comment by iperov** [comment]
BECAUSE CUDA DOES NOT SUPPORT
