### ISSUE TITLE
Multi gpu doesn't work at the train stage.

### ISSUE THREAD

**Issue by wjstk16** [iperov/DeepFaceLab#61]
I used the DF model to train with the multi-cpu option, but the terminal displays 'multi-gpu = False' and only use a single gpu.

Is there anything I can do to use multiple gpu options?

**Comment by iperov** [comment]
multigpu at trains works only with same videocards (model + VRAM)

**Comment by iperov** [comment]
multigpu is no longer supported

**Comment by MehdyAmazigh** [comment]
Why was it removed ? 
Could we get a pre-built version for OpenCL that work with multi-gpu ?
