### ISSUE TITLE
DPI AWARE

### ISSUE THREAD

**Issue by Jasas9754** [iperov/DeepFaceLab#61]
Hi,

dpi aware is this necessary for master? it's very inconvenient on the 4K monitor. Of course, we can use the old code.  Just for newcomers.

And there is a suggestion. I wish there were more images in the preview window. I use it this way now. 
`test_A   = sample[0][1][0:10]`
However, I hope it will be longer by horizontal and not vertical.

Thank you

**Comment by iperov** [comment]
@andenixa what you can say about your PR and 4K monitors issue ?

**Comment by iperov** [comment]
@Jasas9754 can you post screenshot ?

**Comment by Jasas9754** [comment]
![image](https://user-images.githubusercontent.com/39510919/40643342-c8f7e098-635a-11e8-85a6-10346dd1217e.png)

As you can see, it is too small to see properly.

**Comment by iperov** [comment]
I will remove this suxx from repo.

**Comment by iperov** [comment]
done.
More images - declined.

**Comment by Jasas9754** [comment]
Thank you. can you tell me why suggestion was rejected? And how should I modify the code to use it personally? I'm sorry if this makes you uncomfortable.

**Comment by iperov** [comment]
of couse you can modify for yourself
