### ISSUE TITLE
cannot reshape array of size 884736 into shape (3,3,128,2048) errors + errors when attempting model name change

### ISSUE THREAD

**Issue by TMBdf** [iperov/DeepFaceLab#614]
**Expected behavior:**

Models trained on the same version of DFL are being pretrained with the same data_src and data_dst dataset, training is saved, stopped and later user should be able to start it again without any issues, no matter if the files remained in folder or were moved to another folder and then brought back into the model folder. Files are being moved all, except for SAEHD_default_options file which is left in the folder.

----------

**Actual behavior:**

Sometimes models will start, get to 2/5 initialization and crash, outputing this error:

Initializing models:  40%|#########################2                                     | 2/5 [00:00<00:00,  6.40it/s]Error: cannot reshape array of size 884736 into shape (3,3,128,2048)
Traceback (most recent call last):
  File "F:\DF\DFL 2.0\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "F:\DF\DFL 2.0\_internal\DeepFaceLab\models\ModelBase.py", line 173, in __init__
    self.on_initialize()
  File "F:\DF\DFL 2.0\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 692, in on_initialize
    do_init = not model.load_weights( self.get_strpath_storage_for_file(filename) )
  File "F:\DF\DFL 2.0\_internal\DeepFaceLab\core\leras\layers.py", line 67, in load_weights
    w_val = np.reshape( w_val, w.shape.as_list() )
  File "<__array_function__ internals>", line 6, in reshape
  File "F:\DF\DFL 2.0\_internal\python-3.6.8\lib\site-packages\numpy\core\fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "F:\DF\DFL 2.0\_internal\python-3.6.8\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 884736 into shape (3,3,128,2048)

-----

**Steps to reproduce:**

Start training, save/stop it, do nothing or move models, sometimes it works, sometimes it does not.

On one occasion I managed to fix this error by restoring SAEHD_default_options file from Model folder which I thought was irrelevant, this fixed the issue but few hours later I again cannot start training of the model that I was training few hours ago, no updates in the meantime, no changes to OS, app, no restarts of the pc, suddenly models don't want to train, new models start training and work normally. I suspect it might be happening when model is moved to another folder and then copied back to the model folder (SAEHD_default_options file is left in place).

On another occasion (just now when I'm editing) I thought that maybe when you move the model files into another folder (instead of leaving them in the model folder and just letting multiple models be there) then starting a new one (that also generate new SAEHD_default_options file) and then bringing one of the previous models back into the model folder it might cause issues but I did just that and now it works so it's really hard to tell exactly why this happens...

I also tested if changing dfl folder name doesn't have any effect because I changed it - it does not, reverted to the old name (which was DFL 2.0 as opposed to new DFL2.0) and error still happening, fresh model I just started works without issues even after change so that's probably not the case.

Names of the individual model files weren't changed, also noticed that trying to change a name (in this example I named model 256test1) results in error, example:

Enter the name of the model you want to rename : 256test1
256test1
Enter new name of the model : test2
test2
Error: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "F:\DF\DFL2.0\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "F:\DF\DFL2.0\_internal\DeepFaceLab\models\ModelBase.py", line 101, in __init__
    model_filename, remain_filename = filepath_name.split('_', 1)
ValueError: not enough values to unpack (expected 2, got 1)

----------

**Other relevant information:**
Windows 10 Pro
GTX 1060 6GB
drivers up to dates (no updates or new installations done before the error started showing up)
DFL 2.0, google drive stable release from February 3rd 2020.

I hope this can be fixed as it's really annoying and I never know if it's just a random bug or if some update now requires model retraining as the "cannot reshape array of size 884736 into shape (3,3,128,2048)" error seems to be typical of situations where models are incompatible. I could also mention issues with odd/broken results of using TrueFace but that's for another issue.

**Comment by TMBdf** [comment]
I also tested if changing dfl folder name doesn't have any effect because I changed it - it does not, reverted to the old name (which was DFL 2.0 as opposed to new DFL2.0) and error still happening, fresh model I just started works without issues even after change so that's probably not the case.

**Comment by siu531023** [comment]
Only d_dims seems to refer to SAEHD_default_options.dat.
If the model you want to retrain and the value of d_dims of SAEHD_default_options are different, you will get an error.

To resolve this error, create a new model with the same value as d_dims of the model you want to retrain.
Fixing Model.py can solve that too, but wait for an update.

**Comment by TMBdf** [comment]
Thanks, I hope this will be resolved quickly (I mean it's just a matter or renaming that file to correspond to the model it's for).
