### ISSUE TITLE
Export alpha to png option

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#616]
Has the option to export alpha as png been removed from the manual merger?

I see the masks in a separate folder, but these don’t look like the png dump option that was previously available.

**Comment by TMBdf** [comment]
Yes, it was changed, now the merger outputs black and white mask/matter images and a result_mask.mp4 file which you can use in your video editing software to generate a proper mask.

**Comment by Tesla32X** [comment]
Ok, thanks.  It was a very useful feature.
