### ISSUE TITLE
Errors while using RCT color transfer

### ISSUE THREAD

**Issue by TMBdf** [iperov/DeepFaceLab#617]
I'm training a standard model with following parameters:

=================== Model Summary ====================
==                                                  ==
==            Model name: 128 DF 256 64 64 16_SAEHD ==
==                                                  ==
==     Current iteration: 137765                    ==
==                                                  ==
==----------------- Model Options ------------------==
==                                                  ==
==            resolution: 128                       ==
==             face_type: f                         ==
==     models_opt_on_gpu: True                      ==
==                 archi: df                        ==
==               ae_dims: 256                       ==
==                e_dims: 64                        ==
==                d_dims: 64                        ==
==           d_mask_dims: 16                        ==
==            learn_mask: False                     ==
==            lr_dropout: False                     ==
==           random_warp: False                     ==
==             gan_power: 5.0                       ==
==       true_face_power: 0.0                       ==
==      face_style_power: 1.0                       ==
==        bg_style_power: 1.0                       ==
==               ct_mode: rct                       ==
==              clipgrad: True                      ==
==              pretrain: False                     ==
==            autobackup: True                      ==
== write_preview_history: False                     ==
==           target_iter: 0                         ==
==           random_flip: False                     ==
==            batch_size: 10                        ==
==       autobackup_hour: 0                         ==

Once RCT color transfer is enabled following errors are displayed but training continues and effects of color transfer are visible:

F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: divide by zero encountered in float_scalars
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: invalid value encountered in multiply
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: divide by zero encountered in float_scalars
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: invalid value encountered in multiply
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in less
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in greater
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: divide by zero encountered in float_scalars
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: invalid value encountered in multiply
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: divide by zero encountered in float_scalars
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: invalid value encountered in multiply
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in less
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in greater
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: divide by zero encountered in float_scalars
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: invalid value encountered in multiply
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: divide by zero encountered in float_scalars
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: invalid value encountered in multiply
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in less
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in greater
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: divide by zero encountered in float_scalars
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: invalid value encountered in multiply
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: divide by zero encountered in float_scalars
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: invalid value encountered in multiply
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in less
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in greater
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: divide by zero encountered in float_scalars
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:243: RuntimeWarning: invalid value encountered in multiply
  a = (aStdSrc / aStdTar) * a
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: divide by zero encountered in float_scalars
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:244: RuntimeWarning: invalid value encountered in multiply
  b = (bStdSrc / bStdTar) * b
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in less
  scale_range = (max([mn, 0]), min([mx, 255]))
F:\DF\DFL2.0\_internal\DeepFaceLab\core\imagelib\color_transfer.py:320: RuntimeWarning: invalid value encountered in greater
  scale_range = (max([mn, 0]), min([mx, 255]))

I've been experiencing following errors even with other/older models in DFL 1.0 but never really though about reporting them to get to know what causes them, why the models seems to work/train fine despite them and if there is something that can be done to fix them.

DFL 2.0 03.02.2020 version
Win 10 Pro
GTX 1060 6GB
16GB RAM

**Comment by wuffenberg** [comment]
Did you already try with a reduced GAN Power? 5.0 seems awfully high to me.
