### ISSUE TITLE
Suggestion: Bring back RankSRGAN upscaling method.

### ISSUE THREAD

**Issue by TMBdf** [iperov/DeepFaceLab#618]
While RankSRGAN was fairly slow compared to FaceEnhancer it did provide alternative look that worked much better on low resolution models (especially when used with sharpening).

FaceEnhancer produces much more grainy/noisy output whereas RankSRGAN was better at only refining edges thus giving appearance of higher resolution while keeping skin/texture fairly soft.

Therefore I want to suggest bringing back RankSRGAN as a toggable option as an additional upscaling method that could be used together with FaceEnhancer.

**Comment by TooMuchFun** [comment]
Feel free to take a shot at merging it back in, otherwise this is why the DFL-1.0 branch exists.

**Comment by TMBdf** [comment]
I'm not a programmer, I tried but the addition of FaceEnhancer power settings instead of on/off state introduced more changes to the code, I did try to keep both at set FE as mode 2 and Rank as mode 1 but I get errors, maybe you could do it (if you know how to code).

**Comment by TMBdf** [comment]
I've spent few days now trying to get it working without any luck. Face Enhancer really doesn't offer good quality, I've tested it with multiple datasets and models, maybe with high resolution models trained with GAN, sure but for low res models trained as is it really doesn't help give the face such nice "finish" RankSRGAN gave, I sincerely want to ask iperov to give us this option back even if it will slow down merging.
