### ISSUE TITLE
Convert failure!!!

### ISSUE THREAD

**Issue by visonpon** [iperov/DeepFaceLab#62]
## Expected behavior

 convert A's face to B's image.

## Actual behavior
*I have my own training dataset consist of A and B, after trained for some epoch  and use the trained model to convert , the swapped results are still the original images .*

## Steps to reproduce
***Extract:**
python3 main.py extract --input-dir A --ouput-dir A_e.
python3 main.py extract --input-dir B --ouput-dir B_e 
**Training:**
python3 main.py train --traing-data-src-dir A_e --training-data-dst-dir B_e --model LIAEF128 --model-dir ./models
**Convert:**
python3 main.py convert --input-dir  A aligned-dir A_e output-dir ./ouputs --model LIAEF128 --model-dir ./models
*
*When test on my trained model , the results still the original images and have no swapped effect, i don't know why, thanks*

**Comment by iperov** [comment]
A - Cage, B - Trump

python3 main.py convert --input-dir B --aligned-dir B_e --output-dir ./ouputs --model LIAEF128 --model-dir ./models

**Comment by visonpon** [comment]
@iperov So what's the difference between the command if I replace B with A  and I have tried as you said, but the results are still the original images. thanks.

**Comment by iperov** [comment]
big difference.
you must train A - Cage, B - Trump
