### ISSUE TITLE
Sugestion: Extract and search for faces in one .bat file

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#620]
As in title, before I could do extract and search for faces in one bat file, now the script waits for choosing a Graphic Card, how can I get around this ? It would be a great function, cause script is wasting time waiting to click enter after dst frames extraction;)
1 step is always extract faces from DST
2 step is always search for faces
3 step in 99% is sort by similiar histogram
I had it before in one bat file and it was great.

**Comment by wuffenberg** [comment]
you may try this procedure:
[https://github.com/iperov/DeepFaceLab/issues/547](https://github.com/iperov/DeepFaceLab/issues/547)
