### ISSUE TITLE
Suggestion: Add gaussian noise

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#621]
I guess its kind of counterproductive as the sole purpose of the autoencoder is to rebuild the images without noise, but sometimes the images are so clean that they stand out from the original and ruin the effect. Could it be an idea to have an option to add gaussian noise option on merge?

**Comment by wuffenberg** [comment]
Did you already try the option _**bicubic_degrade_power**_ in the converter?

**Comment by TooMuchFun** [comment]
Sounds like something you should do in post production after a merge. Such a subjective loss would be very hard to do in DFL that satisfies everyone.

**Comment by Tesla32X** [comment]
> Sounds like something you should do in post production after a merge. Such a subjective loss would be very hard to do in DFL that satisfies everyone.

Will give it a shot with the Alphas, thx.

**Comment by Tesla32X** [comment]
> Did you already try the option _**bicubic_degrade_power**_ in the converter?

What does this option actually do?

**Comment by wuffenberg** [comment]
I tried it, and it "pixelates" the face. Could be the option you are looking for, try it.

**Comment by kilerb** [comment]
Maybe I’m missing something, but why don’t you just apply motion blur? Best
step is still available during conversion, no?

**Comment by Tesla32X** [comment]
> I tried it, and it "pixelates" the face. Could be the option you are looking for, just try it out.

Hm, actually this function seems to do the opposite. As I see it, It degrades or pixelates the underlaying image, to better match the look of the generated fake. Adjust to 100 and you will see. As for the denoise option, it does the same; Denoise the underlaying image, to better match the noiseless fake. This is probably my best option to solve my problem. Still wish I could do the opposite, and just add noise/grain to the face, to avoid degrading the original.

**Comment by Tesla32X** [comment]
> Maybe I’m missing something, but why don’t you just apply motion blur? Best step is still available during conversion, no?
> […](#)

Motion blur or sharpness is not the issue. Most movies have noise or grain. When the autoencoder rebuilds the image, the result is noiseless. This makes the face too clean compared to the original. As suggested, noise/grain could be added in post, but I think it would be valuable as an option in the merger.
