### ISSUE TITLE
suggestion: all train & merge parameters in same range 0..100

### ISSUE THREAD

**Issue by wuffenberg** [iperov/DeepFaceLab#622]
Currently, the train SAEHD and merge SAEHD options have very different parameter ranges,  making it hard to remember the right settings.
I suggest to harmonize them all in a range of 0..100 (or -50..+50 for certain params where negative values are needed):

**Examples:**
**SAEHD train**
GAN power ( **0.0 .. 10.0** )
True face power. ( **0.0000 .. 1.0**  )
Face style power ( **0.0 .. 100.0** )
Background style power ( **0.0 .. 100.0** )

**SAEHD merger**
erode mask modifier ( **-400..400** ) 
blur mask modifier ( **0..400** ) 
motion blur power ( **0..100** ) 
output face scale modifier ( **-50..50** ) 
super resolution power ( **0..100** ) 
image degrade by denoise power ( **0..500** ) 
image degrade by bicubic rescale power ( **0..100** ) 
Degrade color power of final image ( **0..100** )

**Comment by TMBdf** [comment]
Some settings need their own range like erode and face scale because they need negative values but I agree on the rest, they should all have range from 0 to 100 (GAN, TrueFace, Style Power, Blur Mask, Motion Blur, Super Res, Image/color degrade and bicubic blur).

**Comment by TooMuchFun** [comment]
Please use Issue template.

**Comment by wuffenberg** [comment]
> 
> 
> Please use Issue template.

I think the issue is clearly described

**Comment by wuffenberg** [comment]
Closed without comment? Not good
