### ISSUE TITLE
Model Collapse with LIAEHD on Multi-GPU, Win 10

### ISSUE THREAD

**Issue by MrWig** [iperov/DeepFaceLab#623]
## Expected behavior

DFL 2.0 Multi-GPU fake on windows 10

## Actual behavior
Model collapse has become inevitable on an LIAEHD model after ~340,000 iterations. Several datasets were used to pretrain the model and bias it towards the intended results

## Steps to reproduce
Model first collapsed around 450,000 iterations. I reverted to a backup of the model from 340,000 iterations and collapse started to occur after a further 20,000 iterations.

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*
After noticing collapse in the model around 440,000 iterations I stopped training and attempted to resolve the issue by running both BG and Face Style at 100% for several iterations. This did not work and resulted in the final two screenshots below.

I then reverted to a backup of the model at 340,000 iterations but the collapse returned again after about 20,000 iterations. This has occurred now on three different src/dst datasets.

## Other relevant information
- Model settings:
============= Model Summary =============
==                                     ==
==            Model name: LIAEHD_SAEHD ==
==                                     ==
==     Current iteration: 444902       ==
==                                     ==
==----------- Model Options -----------==
==                                     ==
==            resolution: 192          ==
==             face_type: f            ==
==     models_opt_on_gpu: True         ==
==                 archi: liaehd       ==
==               ae_dims: 512          ==
==                e_dims: 80           ==
==                d_dims: 80           ==
==           d_mask_dims: 16           ==
==           use_float16: False        ==
==            learn_mask: False        ==
==            lr_dropout: False        ==
==           random_warp: False        ==
==       true_face_power: 0.0          ==
==      face_style_power: 0.0        ==
==        bg_style_power: 0.0        ==
==               ct_mode: none         ==
==              clipgrad: True         ==
==              pretrain: False        ==
==            autobackup: True         ==
== write_preview_history: False        ==
==           target_iter: 0            ==
==           random_flip: True         ==
==            batch_size: 16            ==
==             gan_power: 0.0          ==
==       autobackup_hour: 2            ==
==                                     ==
==------------ Running On -------------==
==                                     ==
==          Device index: 0            ==
==                  Name: TITAN RTX    ==
==                  VRAM: 23.76GB      ==
==          Device index: 1            ==
==                  Name: TITAN RTX    ==
==                  VRAM: 23.76GB      ==
==                                     ==
=========================================

Windows 10, prebuilt binary

![Screenshot 2020-02-13 13 00 01](https://user-images.githubusercontent.com/56610223/74605118-dcea2080-5092-11ea-9abb-59a14f28b400.png)
![Screenshot 2020-02-15 13 50 51](https://user-images.githubusercontent.com/56610223/74605108-be842500-5092-11ea-8016-4252780f8972.png)
![Screenshot 2020-02-15 13 51 03](https://user-images.githubusercontent.com/56610223/74605109-bf1cbb80-5092-11ea-8f78-33ec50208f83.png)

Also with the earlier commits of DFL 2.0 I was able to train this multi-gpu model at BS 22, in the more recent commits I've had to lower batch size to 16 to prevent OOM

**Comment by wuffenberg** [comment]
I don't have an answer for your problem, but why is the result picture (5) always extremely similar to  your dst in 3 and 4? Should'nt it be similar to the src face in 1 and 2?

**Comment by MrWig** [comment]
I switched the DST set when I noticed some artifacts in the output, so those last two screen shots have only run for a few hundred iterations. The likeness hasn't had time to transfer yet, but I was more concerned about seeing if the collapse would go away or not. It didn't unfortunately.

Also, I don't know if it matters, but I'm running both of these GPUs in TCC Mode and not WDDM mode. It allows all of the vram on the cards to be dedicated to training.

**Comment by blanuk** [comment]
maybe try to use ct_mode. and update to newer version. 03.02.2020 doesnt have float16 integration anymore

**Comment by MrWig** [comment]
Thanks. I am using the latest version and commit, it's just that the model was initially trained on an older release and then migrated to the new version.

I'm going to try switching to WDDM mode and training a new model.

**Comment by wuffenberg** [comment]
but TCC mode generally should rather help to keep from OOMs compared to WDDM, or did you make different observations?
With my RTX2060S I cannot use TCC, so I added _HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDriver\TdrDelay_ **0x7FFF** 
which sets the WDDM timeout error to approx 32 seconds. 
Not sure though, whether it really helped, but I feel a little more robustness when starting more complex models. Before, they tend to crash within less than 5 seconds after train start, but now this period has extended. (Now they crash after 30 seconds, har har)

**Comment by MrWig** [comment]
Yes, I'm running TCC mode to help run at higher batch sizes. I figure it shouldn't have anything to do with collapse but thought I'd point it out just in case.

I'd prefer to keep the cards in TCC since I can use 100% of the nvram on Win 10.

**Comment by kilerb** [comment]
The real question is why are you turning Dr Evil into Rogan when I’ve
already done it so many times? 🤣😂🤣

**Comment by gessyoo** [comment]
I was happy to see multi-GPU implemented in DFL 2, but I've seen very little tangible benefit using 2 x RTX 2080ti to train a model.  I realize the code is still experimental, but I've been unable to train a model at a higher resolution or with a bigger batch size with DFL 2.

**Comment by TooMuchFun** [comment]
Facial obstructions in src can cause collapse. Overtraining too.

**Comment by MrWig** [comment]
Thanks for the info. I trained on the Flickr set and it does have facial obstructions, perhaps that is part of the issue. I’ve also probably over trained.

**Comment by MrWig** [comment]
> I was happy to see multi-GPU implemented in DFL 2, but I've seen very little tangible benefit using 2 x RTX 2080ti to train a model. I realize the code is still experimental, but I've been unable to train a model at a higher resolution or with a bigger batch size with DFL 2.

I’ve been able to double my batch size with multi-GPU but it also doubles to 2.5 times the iteration.

**Comment by MrWig** [comment]
> The real question is why are you turning Dr Evil into Rogan when I’ve already done it so many times? 🤣😂🤣
> […](#)

Great minds think alike. But thank you for making me aware. Nice work btw. I had a feeling this idea would occur to someone else although I’m taking a different angle on it haha

**Comment by MrWig** [comment]
My guess is this was a case of overtraining and having obstructions in my src dataset so I’m going to close out the issue

Thanks everyone for the advice and information.

—wig
