### ISSUE TITLE
papers

### ISSUE THREAD

**Issue by an1018** [iperov/DeepFaceLab#624]
Hi
    Did you have any published papers, or reference papers about DeepFaceLab?
I will be looking forward to your reply.

**Comment by wuffenberg** [comment]
Some scripts have an internal reference to certain papers, just search for "https" references inside the .py scripts:

![image](https://user-images.githubusercontent.com/60057801/74655365-86f9a380-518c-11ea-99cb-9f9523626408.png)

**Comment by SDeron** [comment]
hey！ who are you？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wuffenberg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月17日(星期一) 晚上8:53
收件人:&nbsp;"iperov/DeepFaceLab"<DeepFaceLab@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [iperov/DeepFaceLab] papers (#624)




Some scripts have an internal reference to certain papers, just search for "https" references inside the .py scripts:

**Comment by an1018** [comment]
@wuffenberg Thanks,but what I want to ask is that is there any published paper on this deepfacelab project?
@iperov Could you help me ?
