### ISSUE TITLE
(suggestion): export multiple masks and coordinates information 

### ISSUE THREAD

**Issue by yuri-carrara** [iperov/DeepFaceLab#631]
I wonder if it's possible to export multiple masks that only include eyes, mouth and nose. For external software purposes.
plus some ASCII coordinates that track eyes position , nose and mouth.
This way it can be much easier to adjust in POST

**Comment by iperov** [comment]
You don't need any mask in AfterEffects.
Just track your own mask.
also 'Face Tracking' function in AfterEffects will give you landmarks of eyes and mouth.

**Comment by yuri-carrara** [comment]
I know I was just hoping to get something a bit more advanced, since we have already all these kind of informations (very accurate informations, I think we could also get to the point where we can isolate smaller features like eyebrows). there are so many benefits that we could get,like stick noises to blend the skin better around the edges, get motion and flickers adjustments, distortions adjustemnts, lights adjustments.. . plus tracking things twice is never a good approach, once a track is done I wouldn't track on top of it.
I just see a lot of potential in a features likes this one

**Comment by iperov** [comment]
AAE provides better subpixel tracking
