### ISSUE TITLE
Shaking face if output_face_scale is <>0

### ISSUE THREAD

**Issue by tfis2** [iperov/DeepFaceLab#634]
Shaking face if output_face_scale is <>0

Only @0 face is stable, tested all mask/color and merge modes.

**Comment by wuffenberg** [comment]
yes, I had the same effect, at least in an older version. Did not try this in the latest releases.

**Comment by tfis2** [comment]
Yeah, it was there in an older version, then has been fixed, now it's back (version from 2/25)

**Comment by iperov** [comment]
unable to reproduce the issue
all works fine

**Comment by GeoffreyOlivier** [comment]
Same problem, may be beacause I had other picture of face in my folder ?!
