### ISSUE TITLE
'models_opt_on_gpu' option is now available for multigpus ,  Application error.

### ISSUE THREAD

**Issue by ytn2001** [iperov/DeepFaceLab#639]
![image](https://user-images.githubusercontent.com/36368758/75468655-86e97700-59c8-11ea-84f4-bfa63a25bcb3.png)
![image](https://user-images.githubusercontent.com/36368758/75468695-95379300-59c8-11ea-8e22-7245322371e2.png)
**multigpus ,  Application error.
onegpu，Running normally.**

**Comment by Tesla32X** [comment]
I am getting this as well

**Comment by iperov** [comment]
fixed in git
