### ISSUE TITLE
Preview window shows only 2 columns

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#640]
with the version 27.02.2020 the preview window shows only 2 columns (src)
Tested Res: 400 and 512.
with 256 it works fine :) (shows all 5 columns)

**Comment by wuffenberg** [comment]
I'd assume that then the preview window would be larger than your screen. (Assuming a FHD 1080 screen you can show max 2x512=1024 plus a few pixels for window header and border)..?

**Comment by blanuk** [comment]
nope. (4k screen)
i have to push the space key :)

**Comment by lzhbrian** [comment]
@blanuk is this solved? How did you solve it?

**Comment by CodeSmith2000** [comment]
I have the same problem, only two columns at a time. Not only that, but if I set the batch size to higher than 1 it WILL run but it will not have more than one row and will not let me see the other rows ever. The preview window is only on a small part of my screen but still will only show "src-src" or "dst-dst" windows individually and at only one row. It will switch between views by me pressing space key only but that doesn't help the rows. It is very annoying not to see my progress all at once in front of me. 512x512 at 52,000it SAEHD
