### ISSUE TITLE
Extractor is running on CPU even though it says it's using the GPU

### ISSUE THREAD

**Issue by theinterestingstory** [iperov/DeepFaceLab#643]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

For the extractor to run on the GPU not the CPU.

## Actual behavior

Extractor says it's running on the GPU but it's on the CPU.

## Steps to reproduce

When choosing GPU:

```
$ ~/DeepFaceLab$ python3 main.py extract --input-dir ./workspace/img/ --output-dir ./workspace/img2/
Choose detector type.
[0] S3FD
[1] manual
[0] : 0
0

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2070 SUPER

[0] Which GPU indexes to choose? : 0
0

[n] Write debug images to img2_debug? ( y/n ) : n
Extracting faces...
Running on GeForce RTX 2070 SUPER
  1%|#1                                                                                                                                                                 | 50/6904 [00:47<1:47:23,  1.06it/s]
```

and when choosing CPU:

```
$ ~/DeepFaceLab$ python3 main.py extract --input-dir ./workspace/img/ --output-dir ./workspace/img2/
Choose detector type.
[0] S3FD
[1] manual
[0] : 0
0

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2070 SUPER

[0] Which GPU indexes to choose? : CPU
CPU

[n] Write debug images to img2_debug? ( y/n ) : n
Extracting faces...
Running on CPU3
Running on CPU4
Running on CPU0
Running on CPU5
Running on CPU7
Running on CPU1
Running on CPU2
Running on CPU6
  1%|#2                                                                                                                                                                 | 52/6904 [00:33<1:14:33,  1.53it/s]
```

## Other relevant information
- **Operating system and version:**

I have a 2070 Super and a 3900x (12 cores this only shows 8), and I'm using Ubuntu 19.10. I know it's using the CPU because my GPU activity is nothing and my CPU activity is off the charts and the fan is going wild for both CPU and GPU selections.

I also tried `--force-gpu-idxs 0` to no avail.

- **Python version:** Python 3.7.5

**Comment by iperov** [comment]
Running on GeForce RTX 2070 SUPER

all works fine

**Comment by theinterestingstory** [comment]
Thanks for the response.

But I don't believe it is. It says it is, but it's not. Also, you can see that when selecting the CPU, I assume it's going nearly 50% faster, and I don't think this wouldn't happen.

![ss](https://user-images.githubusercontent.com/10492556/75627116-848b4680-5b9b-11ea-9919-0021af1eb2ed.png)

**Comment by iperov** [comment]
I don't support linux

write in linux forks
