### ISSUE TITLE
data_src extract very slow

### ISSUE THREAD

**Issue by labileslama** [iperov/DeepFaceLab#644]
data_src extract full_face S3FD is very slow even tho i have an RTX 2070 SUPER.
The GPU utilization is also very low according to Task Manager.

Does anyone have an idea what could cause this problem?

![slow](https://user-images.githubusercontent.com/61655770/75626838-34c47380-5bcb-11ea-8d77-a86bf7af8ab9.PNG)

**Comment by blanuk** [comment]
u have to change to cuda at the graphs.
this speed is normal

**Comment by labileslama** [comment]
> u have to change to cuda at the graphs.
> this speed is normal

how do change to cuda?

**Comment by blanuk** [comment]
click in the task manager by the gpu on video encode and then choose cuda

**Comment by iperov** [comment]
speed is normal

> click in the task manager by the gpu on video encode and then choose cuda

wtf ?

**Comment by blanuk** [comment]
Iperov, just to see the cuda loadin the taskmanager graph.

**Comment by labileslama** [comment]
> Iperov, just to see the cuda loadin the taskmanager graph.

I checked and CUDA usage is about 90%

**Comment by labileslama** [comment]
> speed is normal
hm okay, i thought it would be way faster on a 2070 SUPER compared to my old 1060 but apparently it doesn't make that big of a difference after all
