### ISSUE TITLE
--force-gpu-idxs seems to be broken

### ISSUE THREAD

**Issue by seven110** [iperov/DeepFaceLab#646]
When trying to use "--force-gpu-idxs 0"
Fails with:
  File "/home/dfl/DeepFaceLab.latest/core/leras/device.py", line 66, in get_devices_from_index_list
    if device.index in idx_list:
TypeError: 'in <string>' requires string as left operand, not int

Thanks,
S.

**Comment by iperov** [comment]
fix

**Comment by Secmess** [comment]
It seems this problem again appears again?
I directly clone from master and I got this on my Colab:

![image](https://user-images.githubusercontent.com/24835551/120800045-b5f67d00-c569-11eb-8f97-b9d4af66dc9f.png)

**Comment by ryutaaoki** [comment]
same here.
