### ISSUE TITLE
Merging: Progress_bar not set

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#651]
Hi there

by converting i have now this:

Collecting alignments: 100%|######################################################| 4992/4992 [00:13<00:00, 359.98it/s]
Computing motion vectors: 100%|##################################################| 5326/5326 [00:03<00:00, 1401.78it/s]
Running on CPU1.
Running on CPU5.
Running on CPU7.
Running on CPU0.
Running on CPU6.
Running on CPU2.
Running on CPU4.
Running on CPU3.
Initializing models: 100%|###############################################################| 1/1 [00:00<00:00,  2.86it/s]
progress_bar not set.100%|###############################################################| 1/1 [00:00<00:00,  2.86it/s]
progress_bar not set.
progress_bar not set.

anny idea?

**Comment by TooMuchFun** [comment]
Same for me. On Colab.

**Comment by Tesla32X** [comment]
Getting this as well

**Comment by TMBdf** [comment]
Same here.

**Comment by codedealer** [comment]
Appears to happen only when merging FANseg
