### ISSUE TITLE
Malware on latest built?

### ISSUE THREAD

**Issue by Greifenstein666** [iperov/DeepFaceLab#652]
In the 
DeepFaceLab_NVIDIA_build_03_07_2020.exe

the file
4.2) Data_src sort.bat
shows me an Malware.Ransom.Agent.Generic

Anyone can confirm?

**Comment by TooMuchFun** [comment]
Copy paste the contents of the file? The .bat files are just text files you can open and edit in Notepad.

**Comment by Greifenstein666** [comment]
Ok good hint, it just calls another file, so Idk why it was labeled as potentially harmful
