### ISSUE TITLE
labelme error when running 5. XSeg) data_dst edit.bat

### ISSUE THREAD

**Issue by gessyoo** [iperov/DeepFaceLab#657]
## Expected behavior

Trying to run the new XSeg editor 

## Actual behavior
 XSeg editor won't run.  Executable file labelme.exe appears to be missing from the pre-built Windows 10 release.  The Command-line error is: "'labelme' is not recognized as an internal or external command, operable program or batch file."   

## Steps to reproduce
run 5. XSeg) data_dst edit.bat

Running latest Windows 10 build.

**Comment by iperov** [comment]
fixed, dl last build
