### ISSUE TITLE
I get error when trying to use new xseg split and edit

### ISSUE THREAD

**Issue by relentlessink** [iperov/DeepFaceLab#658]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Trying to run the new XSeg split and edit

## Actual behavior

When I run 5.XSeg) data_dst split.bat it says 0 frames processed no matter if I try it on photos from data_dst/aligned or data_src/aligned

When I run 5.XSeg) data_dst edit.bat I getthis error:

Fatal error in launcher: Unable to create process using '"d:\developpython\projects\deepfacelab\builds\deepfacelab_nvidia\_internal\python-3.6.8\python.exe"  "E:\DeepFaceLab_NVIDIA_build_03_15_2020\DeepFaceLab_NVIDIA\_internal\python-3.6.8\Scripts\labelme.exe" "E:\DeepFaceLab_NVIDIA_build_03_15_2020\DeepFaceLab_NVIDIA\_internal\..\workspace\data_dst\aligned"\ --autosave ': The system cannot find the file specified.

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

Running latest Windows 10 prebuilt (15.03.2020)

**Comment by iperov** [comment]
redownload last release
