### ISSUE TITLE
odd color with aef models and histogram match

### ISSUE THREAD

**Issue by tfis2** [iperov/DeepFaceLab#66]
Hi, when using H128 histogram match works fine (it seems the colors were reduced but works).  Seamless  tends to flicker. When using LAEF or MAEF + Hist match the colors become posterized (like changing bit depth to 256 colors). I tried all options but never got a good result when using histogram match / histogram match bw with AEF models. Seamless  is ok, but flickers a lot. So I did stop testing AEF and go for H128 instead. Did I do something wrong?
Thanks

**Comment by iperov** [comment]
Nothing wrong.
Every model and converter options good for specific scene/light/src/dst conditions.
These fakes trained on LIAEF 
https://www.youtube.com/watch?v=3BtyODN4Bgw
https://www.youtube.com/watch?v=uGwFl8i2DYQ

**Comment by tfis2** [comment]
Thanks.
So it seems H128 is more robust when it comes to different light conditions in src/dst data.

**Comment by iperov** [comment]
because it is a half face.

**Comment by tfis2** [comment]
Thanks
