### ISSUE TITLE
Face Jitter when Changing Face Scale

### ISSUE THREAD

**Issue by Fijitrix** [iperov/DeepFaceLab#661]
This only started happening in the most recent builds of DFL, but I've noticed that if I try to merge a project with a face scale other than 0, the result will jitter like crazy once merged into a video file. This occurs when adjusting face scale up or down. 

This is makes many projects impossible to make realistic due to an either over or undersized face compared to head. I've tried this with new models and old ones, and different src and dst files. It just seems to be a issue with DFL 2.0

**Comment by iperov** [comment]
thank you very much
finally I found the bug
wait new release
