### ISSUE TITLE
Videos won't play on iPhone

### ISSUE THREAD

**Issue by kilerb** [iperov/DeepFaceLab#662]
Last time output videos didn't play on the iphone on a recent version someone suggested doing this...
If you're on PC you can try editing VideoEd file in F:\DF\DFL2.0\_internal\DeepFaceLab\mainscripts and change line from
output_kwargs.update ({"c:v": "libx265",
to
output_kwargs.update ({"c:v": "libx264",

But in the latest versions it already says libx264 and still won't download to the iphone or play.  Doesn't even show up in my photos album, just like when it was 265.  Any fix for that?  Tried exporting MOV file as well... 
 For some reason the iPhone says it's downloading them from my google drive, appears to download 100%, and then there's just no video in the folder.  On older versions I've done this a million times and the video always shows in the photos album and plays...  Thanks!

**Comment by iperov** [comment]
no

**Comment by wuffenberg** [comment]
You still could run the video through an Apple Video editor/converter app before you put it on your phone.
