### ISSUE TITLE
Doesn't use full potential of the CPU/GPU

### ISSUE THREAD

**Issue by Hanswursthund** [iperov/DeepFaceLab#664]
I have a problem with the AMD version of DeepFaceLab. When I run the Training, my GPU (Vega 56) is boosting every ~15sec. Other than that the usage is only a few percent higher than in Idle. My CPU (Ryzen 5 3600) usage is the same as in Idle. Is that normal? Only my Ram (16gb ddr4 3000mhz) and vram (8gb) are at >90% the whole time. Could the ram be a bottleneck? 
I am using the 1.0 Version of the software because I didn't see any downloads of the 2.0 Version for Amd.
Greetings
Ole
PS: Because of the low usage the process takes very long as well (<100 Iterations/hour).

**Comment by iperov** [comment]
amd version is no longer supported
