### ISSUE TITLE
Xseg split can't work

### ISSUE THREAD

**Issue by allen651212** [iperov/DeepFaceLab#665]
I use these scripts, but "Xseg split" can't work correctly.
5) data_dst extract whole_face MANUAL.bat
5.XSeg) data_dst split.bat

The console show:
Processing: 100%|#####################################################################################################################################################| 22/22 [00:00<00:00, 203.69it/s]
Images processed: 0
Done.

Version: DeepFaceLab_NVIDIA_build_03_18_2020

**Comment by iperov** [comment]
because nothing was saved before.

Just go next step.

also I am working on more convenient XSegEditer

**Comment by iperov** [comment]
ah wait, there is real bug

**Comment by iperov** [comment]
because nothing was saved before.

Just go next step.

also I am working on more convenient XSegEditer

**Comment by allen651212** [comment]
Now I get it!
Thank you!
