### ISSUE TITLE
AMD GPU

### ISSUE THREAD

**Issue by afishwithdream** [iperov/DeepFaceLab#666]
hey guy,will it work on amd gpu?

**Comment by SharkEzz** [comment]
AMD support has been dropped. You can still use the old DFL in Google Drive as newer version won't work anymore.

**Comment by afishwithdream** [comment]
sad to hear that.
any,thanks for answering :)

SharkEzz <notifications@github.com> 于2020年3月21日周六 下午8:32写道：

**Comment by Subash-Chandra** [comment]
close your issue friend.

**Comment by iperov** [comment]
now works, download DX12 build
