### ISSUE TITLE
Remove lens distortion from src images before training?

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#667]
Question: Would it make sense to remove lens distortion before you extract the faces and start training? When src images are collected from a huge variety of sources, lens distortion is quite a big variable.

I guess todays method is to train with uncorrected images, and then rebuild uncorrected. 

It would be interesting to know if likeness would be any better if all src images were corrected for lens distortion before you train. 

In most compositing workflows, you always undistort -> -apply changes -> redistort.

Not sure if this applies to machine learning?

**Comment by iperov** [comment]
vice versa
I think lens distortion in src images helps NN to generalize such distortions.

and I dont know how to estimate distortions only by photo and match other photo.

**Comment by Tesla32X** [comment]
I tried some manual corrections with the lens correction tool in Photoshop.  Sometimes distortion is very visible, other times you can barely tell. Obviously it depends on the lens used, and where the face is located in the image. 

I will test and see if just correcting the dst would make any visible difference. ffmpeg has an option for this ->  http://www.ffmpeg.org/ffmpeg-all.html#lenscorrection

Also found this. A more complex method - not sure if it makes any sense.
https://arxiv.org/pdf/1808.06210.pdf
