### ISSUE TITLE
How can I do if just want to control the face but don't swap it.

### ISSUE THREAD

**Issue by tutan123** [iperov/DeepFaceLab#67]
I don't want to change the face , and i want to control the face when moving and speaking.
Like this https://www.youtube.com/watch?v=Rk5um-dtqQc

**Comment by tfis2** [comment]
I think you'll have to us the AVATAR model.

**Comment by Wiiplay123** [comment]
Is there a way to make the AVATAR model put the altered face back on the original video?

**Comment by carson-fitzgibbon** [comment]
Yes, you train the model with the source as images of the person you want to control and the destination as the images of yourself (or whoever will be controlling the face). Then convert normally using the AVATAR model you trained with the input being the frames from the video you want to manipulate and the output being where your newly generated frames will go.

**Comment by ZIMMM** [comment]
Hey dont really understand your process there could you explain it a litlle more clearly ?
