### ISSUE TITLE
Newest update not being able to use Full Face images...

### ISSUE THREAD

**Issue by mpmo10** [iperov/DeepFaceLab#675]
Giving me this error when i use the aligned src that i always use, full face. This is the latest dfl with xseg and whole face. Previous versions works fine.
![2020-03-25 04_52_00-](https://user-images.githubusercontent.com/52265226/77490584-b4550380-6e54-11ea-9042-1154c0a3ca08.png)

**Comment by iperov** [comment]
read the changelog.

== 15.03.2020 ==
removed support of extracted(aligned) PNG faces. Use old builds to convert from PNG to JPG.
