### ISSUE TITLE
changelog.html could show the latest changelog 

### ISSUE THREAD

**Issue by varunpro** [iperov/DeepFaceLab#676]
## Expected behavior

changelog.html is a shortcut in the web browser - when you click it - it shows the latest changelog.

## Actual behavior

changelog.html opens the weblink for the same date as downloaded DFL zip file from Gdrive.

## Steps to reproduce

Click on the changelog.html inside the DFL zip file between 3/24 or 3/25 version.

## the advantage would be 

- without downloading the whole zip file, we can see what's the change in the changelog.html and download only if the change is relevant to work in progress.

- also perhaps easier to update for the developer too .

Thanks for the good work :)

**Comment by wuffenberg** [comment]
Fully agree and also raised this on Feb 04 in https://github.com/iperov/DeepFaceLab/issues/604

However there is one workaround: if you follow iperov, you will always get an email notification about the newest release including the changelog

**Comment by TooMuchFun** [comment]
If u want you can copy-paste the contents of the release notes he puts in commit history or the Releases section and make a PR? If u want it you can maintain it.
