### ISSUE TITLE
Prioritize the training of the mouth

### ISSUE THREAD

**Issue by brunodbrazil** [iperov/DeepFaceLab#677]
I realize that it always takes a long time to train your mouth clearly. Teeth are always the last to become sharp. Is it possible to insert the option to prioritize the training of the mouth just as there is the option to train the eyes with priority?

**Comment by capsmanofficial** [comment]
mouth and teeth are good when photos of src are good. if the photos of src are blurred the result is blurred

**Comment by iperov** [comment]
if you don't know how ML works, don't suggest such things
