### ISSUE TITLE
SAEHD stuck

### ISSUE THREAD

**Issue by ilkiwer** [iperov/DeepFaceLab#684]
Hello. 
I'm trying to use "train SAEHD" on my pc, but I can't start it. It asks me all the questions about batch size, iterations etc. but get stuck, always, at initializing models 40% 2/5. The timer of the elapsed time also doesn't work.
With quick96 everything goes well, but SAEHD can't be used. What's the problem?

I'm running it on a GTX 1660

**Comment by JoeMamaSoFat69** [comment]
I have the exact same issue, have you figured it out at all?

**Comment by ilkiwer** [comment]
> I have the exact same issue, have you figured it out at all?

Not at all. Still waiting for a solution :)

**Comment by TooMuchFun** [comment]
Pots summary.txt output.

In future use issue template. Thx. It is there for a reason.

**Comment by ilkiwer** [comment]
Hello, I didn't use the template because I was writing from my mobile through the app, and I couldn't find it there. I apologize.
That said, where can I find the summary.txt file? I ran a search in the folder but nothing came out.

**Comment by TheMaskedAvengers** [comment]
Same exact issue and also at 40% exactly, timer frozen.... - also no idea where to find summary.txt....

**Comment by TheMaskedAvengers** [comment]
Weirdly I found a work around - suspect it's memory related (astounding as my machine is a high end gaming rig..but still...Figured it might be RAM or VRAM

I closed Chrome as it has a bit of a memory leak if left open and that instance had been left open for months in case it was RAM, and I switched off my second monitor, and reduced the resolution down a lot on my main display...

After which it ran fine....

I do suspect something is wrong here as at my specs, and using more or less default settings I can't see how this should be necessary. Still it did the job!

**Comment by caohuajia** [comment]
I have the same problem on GTX1650 4G.

**Comment by ilkiwer** [comment]
Hello. I resolved the issue, finally, with the last update.

**Comment by marshalleq** [comment]
Hi, can you explain what you mean by the last update?  The last update of DFL?  Or of the Nvidia driver?  or of something else?  Thanks.

**Comment by ilkiwer** [comment]
> Hi, can you explain what you mean by the last update? The last update of DFL? Or of the Nvidia driver? or of something else? Thanks.

Hey, I'm not sure, some time has passed, but I am positive it was the latest DFL update.
