### ISSUE TITLE
Erode options during Merging

### ISSUE THREAD

**Issue by Fijitrix** [iperov/DeepFaceLab#685]
So I have gotten used to the workflow of WF training/merging and then compositing in DaVinci Resolve. One killer option during manual compositing that would be incredible to have in the interactive merging tool on DFL would be the ability to control the erode radius on both sides of the x and y axis for a total of 4 adjustable erode parameters instead of just a single all encompassing one. This would help a lot with scenarios that for example, might have tattoos or bangs on the forehead and could have a positive erode number on the forehead to preserve those details and a negative erode on the chin area if the face shape doesn't totally match the src face.

I know this isn't really an issue, more so a request or feature suggestion but I'm not sure where else to write this.

**Comment by iperov** [comment]
nobody need x/y erode
