### ISSUE TITLE
XSEG won't allow me to use full face, only whole face

### ISSUE THREAD

**Issue by kilerb** [iperov/DeepFaceLab#686]
In the latest 3/30/20 version, I tried to use XSEG to mask out an object in fromt of the face...  for a full face model (since there are no fan options now during conversion.)  I blocked out some obstructions in XSEG and then clicked XSEG)train.bat.  It automatically chooses WF as face type and starts trying to train.  But it's a full face.  Won't let me pick F because it just moves on automatically.  Not sure if it's a bug or I'm doing something wrong, but I've tried multiple times and it does that each time.  Thanks.

![error](https://user-images.githubusercontent.com/6969681/78211814-e8d34b80-7462-11ea-8b1b-7066461f8cbe.png)
(I'm not hitting enter or WF...  Just chooses it for me)

**Comment by iperov** [comment]
fixed in last commit
