### ISSUE TITLE
Export of alpha

### ISSUE THREAD

**Issue by Eleganze** [iperov/DeepFaceLab#69]
Is there a particular workflow needed to export the faces in separate files, as illustrated in the example? When I enable this when converting, all I get is a black layer mask. What am I doing wrong?

**Comment by iperov** [comment]
its used in manual composing layers in video editors such as sony vegas or AE

**Comment by Eleganze** [comment]
Yes, but my export is not a face but just a black area where the face should be.

**Comment by iperov** [comment]
load merged png in photoshop

**Comment by Bruheim** [comment]
![mask](https://user-images.githubusercontent.com/45300615/50101566-3e122c00-0223-11e9-9d61-580d8c3fe2e0.jpg)
This is what I got.

**Comment by Eleganze** [comment]
![mask](https://user-images.githubusercontent.com/37071118/50101670-82053100-0223-11e9-9e3d-8d63649181a1.jpg)
This is what I got!

**Comment by iperov** [comment]
very strange,
what i got
![photoshop_2018-12-17_20-46-13](https://user-images.githubusercontent.com/8076202/50101740-d36dea00-023c-11e9-90bc-2e317433cbde.jpg)

**Comment by Eleganze** [comment]
Yes, that was what I was hoping for :-) What I have looks inverted

**Comment by iperov** [comment]
can you upload your workspace? I will check in my comp.

**Comment by Eleganze** [comment]
Weired! I restarted my computer and run the convert script again. Now the faces come up as your example. I wonder if I have mixed up two different releases. I will try some more, and uload workspace if I manage to get this error again. Now it seems to work fine!
