### ISSUE TITLE
Could not find the Qt platform plugin "windows" in ""

### ISSUE THREAD

**Issue by heisdansh** [iperov/DeepFaceLab#690]
## Expected behavior

5.XSeg) data_dst mask for XSeg trainer - edit
and
5.XSeg) data_src mask for XSeg trainer - edit

both start normally

## Actual behavior

5.XSeg) data_dst mask for XSeg trainer - edit
and
5.XSeg) data_src mask for XSeg trainer - edit
 wont't start repeatedly throws 
"
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

"
## Steps to reproduce

In my case simply launching these files.

## Other relevant information
I have tried commands to very windows files and all of them seem to be fine.
also DeepFaceLab_NVIDIAa\_internal\python-3.6.8\Lib\site-packages\PyQt5\Qt\plugins\platforms
and all the pluggins seem to be intact.

get the same error on both 03 18 and 03 30 builds that i tried.

![err](https://user-images.githubusercontent.com/63120880/78392751-6d53d480-75f1-11ea-999c-cb0bc08bb593.png)

![Annotation 2020-04-03 212454](https://user-images.githubusercontent.com/63120880/78392918-b146d980-75f1-11ea-9d85-bc66565b81fd.png)

**Comment by iperov** [comment]
send teamviewer access id and pass to my email deepfakescovery [@] gmail.com 
I will check the problem on your comp

**Comment by heisdansh** [comment]
Thanks, I contacted you.

**Comment by iperov** [comment]
fixed, dl last build

**Comment by heisdansh** [comment]
Thanks so much! Everything works as intended now!

**Comment by william69-prog** [comment]
I need new I’d and codes sent

**Comment by codeironside** [comment]
can i get the solution to this error please 
am facing the same issue

**Comment by iperov** [comment]
prebuild windows binary works fine
