### ISSUE TITLE
Merge Quick96 produces frames with original dst face

### ISSUE THREAD

**Issue by glueydoob1** [iperov/DeepFaceLab#695]
Hi, Everything seems to have worked up to to step 6- train Quick96. I did 120k iterations. I try to run step 7 to merge, and it simply keeping the original dst video face. It doesn't use the src face on any of the frames. I get this line: "no faces found for xxxxx.png, copying without faces" for all the frames.
thanks

**Comment by boyit1309** [comment]
can i get how you fix this ? i also get this error 
after learning through Quick96, I put on the merge. As a result, it writes "no faces found for 00001.png, copying without faces" and a window with hot keys appears. Inside the data_dst folder, a merged folder appeared, containing one frame that really does not contain the desired face, as well as a merged_masked folder, respectively containing a file with a black square. That's all. My dst video contains more than just the face I'm about to replace. How then to replace the face with a video in which there are other faces? (P.S. in the frame where there is a face that I am going to replace, while other faces do not fall. P.P.S. In the aligned folder, I deleted the frames without the face that I want to replace). Tell me what's wrong?
