### ISSUE TITLE
XSeg editor: 'view trained mask' mode shows just black image

### ISSUE THREAD

**Issue by rocketsvm** [iperov/DeepFaceLab#698]
I masked a few faces, trained an XSeg mask, then ran the editor again (I suppose that's how it should be done) to see how a new mode works, but it shows empty black square. Trained mask works when training SAEHD model, didn't try merger yet.

**Comment by iperov** [comment]
to view trained masks they should be applied first

5.XSeg.optional) trained mask for data_dst - apply.bat

**Comment by Lee-qian-gay** [comment]
so how to apply now?
