### ISSUE TITLE
Upside down side faces

### ISSUE THREAD

**Issue by Kirin-kun** [iperov/DeepFaceLab#7]
Sometimes, for some reason, dlib extractor puts the face upside down. It does this for some side faces. I guess it depends on the exact angle. I get things likes this:

![ginny00521_0](https://user-images.githubusercontent.com/36699120/41506836-95d78d88-7225-11e8-8bee-c6bf0895526c.png)

Question: should I keep them for conversion? I understand deleting them from the training set, but at convert time, will it be converted correctly?

**Comment by iperov** [comment]
> but at convert time, will it be converted correctly?

no.

**Comment by Kirin-kun** [comment]
Understood.

**Comment by RonyOficial** [comment]
What should we do when we receive these "errors", whenever something crosses in front of the face, such as wet hands etc, this happens
