### ISSUE TITLE
Unspecified launch failure when training

### ISSUE THREAD

**Issue by anchpop** [iperov/DeepFaceLab#706]
## Expected behavior

I'm trying to run `6) Train SAEHD.bat`. I would expect this to train the NN.

## Actual behavior

It trains for a short time, then crashes with an "unspecified launch failure".
https://pastebin.com/13pVRABy

## Steps to reproduce

I don't think I did anything unusual. I didn't even use my own videos for the source, I'm just using what came in the prebuilt windows binary. I can upload my workspace folder if you like so you can see it. My graphics card is a GTX 1060 with 3gb of vram, and that's what I'm using to train. Is it possible that this is caused by not having enough vram?

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: I'm running `6) train SAEHD.bat` which opens in the normal windows command line. 
- **Operating system and version:** Windows 10
- **Python version:** I'm using the prebuilt windows binary

**Comment by Nevertoodeep** [comment]
Yes 3 gb is not sufficient with those settings. Put models_opt_on_gpu: false, if you want to have more juice. Or maybe lower the resolution, if not just try Quick96 model instead.

**Comment by anchpop** [comment]
I appreciate it, thank you @Nevertoodeep.
