### ISSUE TITLE
when i use the "pretrained DF.wf.288res.384.92.72.22",occur this error

### ISSUE THREAD

**Issue by chinasilva** [iperov/DeepFaceLab#708]
## Expected behavior

![image](https://user-images.githubusercontent.com/16743182/78898796-f615b900-7aa6-11ea-84a2-44d56a8945ae.png)

Press enter in 2 seconds to override model settings.Error: pretraining_data_path is not defined
Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 57, in trainerThread
    debug=debug,
  File "/content/DeepFaceLab/models/ModelBase.py", line 177, in __init__
    self.on_initialize_options()
  File "/content/DeepFaceLab/models/Model_SAEHD/Model.py", line 114, in on_initialize_options
    raise Exception("pretraining_data_path is not defined")
Exception: pretraining_data_path is not defined
Traceback (most recent call last):

## How to solve
what should i do 
1.set "pretrain"= False ? if do this,use pickle.dump() to change  this file "SAEHD_default_options.dat"?

## other question
I'd like to know what dataset this model was trained from.

**Comment by Nevertoodeep** [comment]
Looks like you are not running the latest dfl notebook.
https://colab.research.google.com/github/chervonij/DFL-Colab/blob/master/DFL_Colab.ipynb#scrollTo=WTuyUxgdLA13

**Comment by iperov** [comment]
model is in pretraining mode.
You have to disable pretraining mode in order to use it in your fake.

**Comment by chinasilva** [comment]
@iperov thank u ，i have solve this problem by modify file，the pretrain model data，how many src and dst ，and there are the same data?

**Comment by onefish51** [comment]
How do you modify(new_SAEHD_data.dat) file? I export model to dfm format , this error occurred !

see  #5394

**Comment by fungtion** [comment]
Reload the previous trained model,  and when it prompts "Press enter in 2 seconds to override model settings." then click `Enter`, then you get the dat file modified

**Comment by pawelofficial** [comment]
/hi, for less technical or familiar users, the original how to solve explanation in more detail is following
-> go to python file Model.py that your terminal threw an exception on ( for me C:\dfl\DeepFaceLab_DirectX12_build_05_04_2022\DeepFaceLab_DirectX12\_internal\DeepFaceLab\models\Model_SAEHD\Model.py ) 
-> find a exception message string ( pretraining_data_path is not defined )
-> do what originally was said - change the pretrain option to False (    self.options['pretrain']=False  ) - put it one line above the if clause that raises the exception 

`

        self.options['pretrain']=False # dirty fix 
        if self.options['pretrain'] and self.get_pretraining_data_path() is None:
            raise Exception("pretraining_data_path is not defined")
`

**Comment by ShawnLeung-SII** [comment]
> 

Good question and good answer, helps a lot. In Model.py 62 lines, exchange the code like this:
Original: default_pretrain           = self.options['pretrain']           = self.load_or_def_option('pretrain', False)
After: default_pretrain           = self.options['pretrain']           = False
That's really work for me.
