### ISSUE TITLE
Xseg images not fully loading on Mac

### ISSUE THREAD

**Issue by TalosOfCrete** [iperov/DeepFaceLab#709]
## Expected behavior

I am attempting to open the Xseg editor for my "head" extracted images.  I do this by entering the following command (my name excluded):
 
`python main.py xseg editor --input-dir /Users/[my name]/Desktop/workspace/data_dst/aligned`

The expected behavior is for all of the images to load and for the interface to open.

## Actual behavior

The progress bar hits 99% (or some other percentage depending on number of images) and stops.  It appears to successfully load the images, but never progresses to the interface.  However, interestingly enough, when an invalid directory is entered, the interface does appear, albeit without any images.

![Screen Shot 2020-04-09 at 9 28 47 PM](https://user-images.githubusercontent.com/32628941/78956826-28c0b100-7aa9-11ea-8a1b-2c51abf2317d.png)

Even given over 10 minutes, the progress bar fails to complete and the interface fails to show.  No error message is thrown in the terminal, and the application must be force quitted.

The following is an image of what occurs when the following command is entered into the terminal, which contains an invalid directory:

`python main.py xseg editor --input-dir /Desktop/workspace/data_dst/aligned`

![Screen Shot 2020-04-09 at 9 31 14 PM](https://user-images.githubusercontent.com/32628941/78956942-87862a80-7aa9-11ea-878d-c895546f5b71.png)

Do note that this is taking place in a local Anaconda environment, in which all requirements have been installed at the correct versions via Conda (or pip if unavailable there).

## Steps to reproduce

To fully reproduce this error, use MacOS and attempt to run the first command given (adjusted for your system, of course) on a directory filled with images extracted as "Head".  The steps to reproduce the curious result are also detailed above.

It is entirely possible that this issue merely has something to do with the fact that I am executing the commands directly from the command line, as I am required to do in lieu of the ability to run .bat files.  Or, it could be a MacOS compatibility issue, seeing as this issue has not appeared for my friends on Windows.  However, I cannot be certain of any of this due to the lack of any error messages or verbose dumping (I have attempted to force it to dump verbose, but those attempts have been unsuccessful; this can be tried again if required).

## Other relevant information
- **Operating system and version:** MacOS 10.12.6 
- **Python version:** 3.7.4

**Comment by iperov** [comment]
I don't support macos. If you are familiar with coding and python, you can investigate the issue and propose the fix.

**Comment by iperov** [comment]
try only one picture in aligned folder

**Comment by TalosOfCrete** [comment]
Unfortunately, that presented the same result.  However, I inserted print commands into the functions of the script (having it print the name of the function upon execution), and the following came up when entering a valid directory:
![Screen Shot 2020-04-10 at 7 09 34 PM](https://user-images.githubusercontent.com/32628941/79030526-04bfa700-7b5f-11ea-91af-fc7d638345c4.png)

I added another code block to test if the hide() function (`self.loading_frame.hide()`) is working correctly for the "loading_frame" QFrame, which was as follows:
`if self.loading_frame.isVisible:
            print("loading frame is visible after hide()")
        else:
            print("loading frame is apparently invisible after hide()")`
This was the result of using a correct directory, print statements in functions to determine if they are in fact being executed, and adding the above code:
![Screen Shot 2020-04-10 at 7 19 03 PM](https://user-images.githubusercontent.com/32628941/79030789-777d5200-7b60-11ea-915f-05d4319f7875.png)


From this, I conclude that there is an issue solely with the loading function; specifically, it appears to be unable to be closed.  I further conclude this from the fact that the subsequent functions ("on_loader_finish", "process_next_image") appear to be executed due to their print statements being logged.  However, I am unable to ascertain why the hide() function is failing on the loading frame.

Since you are evidently more experienced in PyQT than I, what do you make of this?

**Comment by TalosOfCrete** [comment]
Closing due to both inactivity and the receipt of a working alternative xseg editor from a friend.  Issue is still worth investigating, however.

**Comment by acheong08** [comment]
@TalosOfCrete What is the alternative xseg editor?
