### ISSUE TITLE
Upload Prebuilt windows app to Google Drive plase.

### ISSUE THREAD

**Issue by ZeroCool22** [iperov/DeepFaceLab#71]
It's more easy to bypass the limit than MEGA. Thx!

**Comment by oneduality** [comment]
I notice Mega is once again where it's being uploaded, this is unfortunate. I easily hit my limit and had to pay for a one month subscription to download it.

Sorry I know this is an old topic, but it's relevant.

**Comment by iperov** [comment]
any alternatives?
google drive is no more applicable for mass hosting files

**Comment by oneduality** [comment]
I was just looking around, I've used this a couple of times but I don't know how well it would work.. may suffice as a mirror if nothing else.. 

https://www.filehosting.org/

"You don't need any kind of premium-accounts. Our service is completely free for everyone. You can upload any type of file (movies, music, documents, images, zip files and more). Any file in any format can be uploaded and downloaded for free. We have no file size limit. There are no restrictions on the number of times a file can be downloaded.

Files can be downloaded from any computer from our high speed servers. You don't need any special software installed to be able to download your files. You decide who you want to share your files with. Keep your files private, or send your download links only to friends or family. Alternatively you can choose to share your download links on blogs, forums and social networking sites. So try our free and simple filehosting service now."

**Comment by kilerb** [comment]
I just downloaded the latest version without having to login or make an
account at MEGA.  It downloaded fast too.  Why does it make you login?

**Comment by oneduality** [comment]
Your IP is limited to a certain amount per day and I use it for downloading other things, I was also trying multiple versions.

I hit my limit and would have needed to wait 24 hours, but I had a project I was working on and needed to grab the latest.. I was unable to without subscribing to increase the limit.. 

I'm sure I could have found a way around it ( VPN/Proxy .. etc ) but this was a work device and I couldn't easily go that route so the best option was to sign up and pay for a month.

**Comment by kilerb** [comment]
Ahhhh...  Gotcha... Yeah, VPN would solve that, but easier is always
better!  Wasn't even aware the files were moved until I saw this email!
Hahaha...  I was wondering why there weren't any new versions on the google
drive that I bookmarked.

**Comment by hamac2003** [comment]
I would really appreciate it if the prebuilt windows app was moved to a hosting service other than mega (such as google drive). Mega is a pain in the rear end to deal with, and I don't understand what anyone stands to gain from hosting it there (other than mega).

**Comment by iperov** [comment]
@hamac2003 
Google drive has a new traffic quota, no user can download from it last time. SO I removed it from download list.

**Comment by hamac2003** [comment]
@iperov, I still don't like it, but it's nice to hear that there was a reason. Thanks for the explanation!
