### ISSUE TITLE
Multi-graphics training is very slow

### ISSUE THREAD

**Issue by bladenow** [iperov/DeepFaceLab#711]
Examples:
1 graphics card,
DF, 128 res, bs8, each iter takes 300 ms,

3 graphics cards, DF, 128 res, bs8, each iter takes 1400 ms,

If you use more graphics cards, DF, 128 res, bs8, each iter will take more time.

Can you optimize multi-graphics training？

![1](https://user-images.githubusercontent.com/46339824/79037073-acd97c80-7c00-11ea-9ab6-966f0e62e4fc.jpg)

![3](https://user-images.githubusercontent.com/46339824/79037080-b236c700-7c00-11ea-86fa-be541a92c4d6.jpg)

**Comment by iperov** [comment]
multigpu is not designed to speed up the training
only to increase batch size

**Comment by orkblutt** [comment]
Can you try without model on GPUs ?

**Comment by bladenow** [comment]
@iperov

**Comment by bladenow** [comment]
@orkblutt @iperov    Just to improve batch size, not speed.Haha, so cool!

**Comment by fuorissimo** [comment]
> 
> 
> multigpu is not designed to speed up the training
> only to increase batch size

But how? And what's the point of increasing the batch size if time doubles? It makes no sense. Then the multiGPU function is completely useless if there is no improvement. What a disappointment, I bought 2 cards for nothing.


https://github.com/iperov/DeepFaceLab/issues/959
