### ISSUE TITLE
Subprocesses unable to start during faceset enhancer on Linux

### ISSUE THREAD

**Issue by TalosOfCrete** [iperov/DeepFaceLab#715]
## Expected behavior

The faceset enhancer is supposed to launch and begin processing the images in the target directory.

## Actual behavior

Upon executing, this is the output:
`[CPU] : CPU
  [0] : GeForce GTX 1060 6GB

[0] Which GPU indexes to choose? : 
0

Enhancing faceset in data_src/aligned
Processing to data_src/aligned_enhanced
Running on GeForce GTX 1060 6GB.
Traceback (most recent call last):
  File "DeepFaceLab/main.py", line 314, in <module>
    arguments.func(arguments)
  File "DeepFaceLab/main.py", line 238, in process_faceset_enhancer
    force_gpu_idxs=arguments.force_gpu_idxs
  File "/lustre/work/[my group name]/[my name]/DeepFaceLab/mainscripts/FacesetEnhancer.py", line 143, in process_folder
    result = FacesetEnhancerSubprocessor ( image_paths, output_dirpath, device_config=device_config).run()
  File "/lustre/work/[my group name]/[my name]/DeepFaceLab/core/joblib/SubprocessorBase.py", line 219, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.`

## Steps to reproduce
I recognize that this is an unusual setting for DFL.  However, seeing as this is a Linux release, I expected it to work given the correct dependencies.  The following steps were taken in the creation of the **dfl** Anaconda environment in order to run the software:

1. The conda environment was created
2. Python 3.6.9 was installed (same as Colab)
3. All dependencies were installed with the versions indicated by the `requirements-cuda.txt` file **except** for the following:

- Labelme was installed with the highest version afforded by Conda (3.21.1)
- Tensorflow-gpu was installed as version 1.13.1 (the closest Conda offered to 1.13.2)
   - It is possible that this is part of the cause of the issue; however, installing 1.13.2 via pip led even the face extractor to break
- CuDNN and Cuda toolkit were also installed via Conda as early attempts to tackle this issue
- ffmpeg-python was skipped due to its lack of Conda implementation (will consider installing via pip, but did not want to risk breaking environment further)

4. A SLURM job was requested for a GTX 1060
5. The module for CUDA 10 was loaded (it would otherwise be CUDA 9.2)
6. The Anaconda module was loaded and the **dfl** environment was activated
7. The script to initiate the faceset enhancer was executed with the correct directory entered

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: `python DeepFaceLab/main.py facesettool enhance --input-dir workspace/data_src/aligned/` 
- **Operating system and version:** Linux Scientific release 6.10 (Carbon)
- **Python version:** 3.6.9
- As you could probably surmise, these jobs are taking place at an HPC cluster.  This means that I am submitting requests for GPUs, connecting to them when they become available, giving them access to the relevant directories and Anaconda environments, and running the scripts.  **This worked with no issue in DFL 1.x, and no other scripts in DFL 2.x are having this problem.**
- Note the fact that it is able to correctly read the GPU that it is running on, but seems unable to start the processes anyway
- Earlier tracebacks for this issue also pointed to a Python library relating to multiprocessing and Tensorflow complaining about not being able to colocate nodes and devices (I have not been able to replicate these since)
   - The error about Tensorflow appeared to involve my messed up Conda environment, which I have since deleted and replaced with the process described above
   - The error about multiprocessing took place when I attempted to run this on Python 3.7; after noticing the version on Colab, I downgraded it
   - There are **no** pip-installed packages in my environment

**Comment by iperov** [comment]
I don't support linux.

**Comment by TalosOfCrete** [comment]
Well, even though you don’t offer official support, isn’t this issue worth looking into?  The libraries are very much the same between Windows and Linux, the only difference being that bat files are used instead of the command line to launch scripts.  Perhaps you could still lend a hand, even though you don’t officially support this platform?

**Comment by iperov** [comment]
no. I cannot reproduce it on windows, thus no support.

**Comment by TalosOfCrete** [comment]
Well, could you at least help me fix the problem myself?  I can’t seem to fully understand the error message, and you of course are much more familiar with this code than I.  I understand that you can’t reproduce it and don’t have a Linux VM, but perhaps some guidance could be given?
