### ISSUE TITLE
Xseg fails to start

### ISSUE THREAD

**Issue by NuclearSnow** [iperov/DeepFaceLab#719]
on a fresh download of the latest and on a fresh download and install of the 13_4_2020 build, faces extracted, faceset tidied up and re-extract deleted debugs, open xseg and its able to open the first time, edit in xseg on dst, close xseg and try to open edit xseg to do src face and i get the below error.  only current way round this below issue is to then re-install either build, copy the workspace folder across and re-edit masks. 

DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Shell Dlg 2", pointsize=12, pixelsize=16, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("NotoSans", lfWidth=0, lfHeight=-16) dpi=144
Traceback (most recent call last):
  File "C:\Users\User\Videos\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\XSegEditor\XSegEditor.py", line 1326, in resizeEvent
    if self.loading_frame is not None:
AttributeError: 'MainWindow' object has no attribute 'loading_frame'
Press any key to continue . . .

**Comment by capsmanofficial** [comment]
https://www.youtube.com/watch?v=1smpMsfC3ls

**Comment by NuclearSnow** [comment]
> https://www.youtube.com/watch?v=1smpMsfC3ls

That's not the problem, the problem is once the xseg window has been closed it then doesn't reopen throwing up that it hasn't got an attribute for a main window to open in, so it will never open again until DFL is reinstalled

**Comment by NuclearSnow** [comment]
Latest update fixed issue
