### ISSUE TITLE
Crash when renaming a model

### ISSUE THREAD

**Issue by spiceygas** [iperov/DeepFaceLab#725]
## Expected behavior

When renaming a model, the program should succeed without any issue.

## Actual behavior

When renaming a model, the program crashes.

## Steps to reproduce

1. Create a new model named:  ```Pretrain - LIAEHD Female```
2. After training the model, save and exit.
3. Execute Script 6 to Train SAEHD.
4. Choose [r] to rename a model.
5. Type in a new name.  For example: ```LIAEHD Jane```
6. Crash

```
Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : Pretrain - DFHD Female - latest
[1] : Pretrain - LIAEHD Female
 : r
r
Enter the name of the model you want to rename : Pretrain - LIAEHD Female
Pretrain - LIAEHD Female
Enter new name of the model : LIAEHD Jane
LIAEHD Jane
Error: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\DeepFaceLab 2.0\2020-04-15 DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "D:\DeepFaceLab 2.0\2020-04-15 DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 109, in __init__
    model_filename, remain_filename = filepath_name.split('_', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## Other relevant information
- Operating system and version: Windows 10 Pro v1903
- Python version: Prebuilt Windows Binary

**Comment by iperov** [comment]
model files were renamed manually,
thus broken normal program logic

**Comment by notosapien** [comment]
I also had this problem, I hope this information will help anyone. After many test I've found out that in my model folder I've created a folder to temporary move files in and out sometimes, It seems like you should not have a folder in "model" folder only models.
