### ISSUE TITLE
deepface train mode turn off pc 

### ISSUE THREAD

**Issue by moekali** [iperov/DeepFaceLab#726]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

when i click on train so my computer turn off after maybe 5 mn or 15 mn or 1 mn train

============ System Information ============
git_commits:         2b66013 Bugfix: logger - Still output crash report if system information fails to load. 3f0a016 bugfix: Extract - raise error if Keras fails to import. ff8d851 Cli Restructure + Multi-Mask Select on Extract (#1012). add55cc - Catch Frame count mismatch when analysing presentation time stamps - Don't output a crash report when a FaceswapError is generated. 9461c59 Bugfixes and minor updates:   - Remove preview option from effmpeg tool   - Remove json filetypes from GUI for alignments files   - Capture and raise empty timelapse folder errors   - Move convert to use centralized ImagesLoader
gpu_cuda:            10.2
gpu_cudnn:           7.6.5
gpu_devices:         GPU_0: GeForce RTX 2080 Ti
gpu_devices_active:  GPU_0
gpu_driver:          442.92
gpu_vram:            GPU_0: 11264MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_conda_version:    conda 4.8.3
py_implementation:   CPython
py_version:          3.7.7
py_virtual_env:      True
sys_cores:           16
sys_processor:       Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
sys_ram:             Total: 32699MB, Available: 27176MB, Used: 5522MB, Free: 27176MB
## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows 10
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by iperov** [comment]
software cannot turn off your pc

**Comment by medesoz** [comment]
Had the same problem but it can be kinda fixed if u lower your maximum CPU power (for me 80%) but still don't know why this is happening because if I run stress test it have no problem

**Comment by iperov** [comment]
> if I run stress test 

stress test programs are nothing compared to DFL.
