### ISSUE TITLE
Error when trying to continue training avatar

### ISSUE THREAD

**Issue by Eleganze** [iperov/DeepFaceLab#73]
## Expected behavior
Continue training on existing models 

## Actual behavior
From a blank setup, the training starts and the model files are created. If I stop training, and then try to start it again it throws an error. I have had this error on all releases. 

## Steps to reproduce
See above.

![image](https://user-images.githubusercontent.com/37071118/50191627-05f80f80-032f-11e9-813d-caacf3cd821b.png)

The model files that are created:
![image](https://user-images.githubusercontent.com/37071118/50191813-c41b9900-032f-11e9-82c4-19d8a1c1e61c.png)

**Comment by overlander23** [comment]
I'm getting this same layer mismatch error while trying to convert an Avatar model, as well.  Could it be a Keras issue?  Has anyone successfully used Avatar mode with the latest builds?

**Comment by Thunder-z** [comment]
@overlander23 HI.
This error occurs when I run 6) train H128 best GPU.bat.
pickle.unpicklingError:invalid load key，‘0x00’ 
But the file "H128_data.dat" in the folder “DeepFaceLabTorrent\workspace\model”.
Do you have any idea about this?

**Comment by Eleganze** [comment]
I just tried running this on a completely new computer, and then things works fine. So this is obviously a local error of some kind. Could be related to Keras, but I don’t know.

**Comment by iperov** [comment]
I just checked AVATAR, all works fine.

**Comment by overlander23** [comment]
On a dual 980ti system, multi-GPU AVATAR training createed the truncated file sizes.  Using Best-GPU on the same system yielded the correct model file sizes as posted by @iperov.

**Comment by Eleganze** [comment]
I have a dual 1080ti setup. Will try using only one card.

**Comment by zhangdanfeng888** [comment]
> I just successfully trained, converted and started training again using single GPU processing with AVATAR. MultiGPU, no go.

Hey man, do you have the avatar model now? If do, can you send the model to me? There is no avatar model now in the rep. My email address is 18625801456@163.com. Thanks a lot!

**Comment by deyu260** [comment]
> I just successfully trained, converted and started training again using single GPU processing with AVATAR. MultiGPU, no go.


Are you still training on multiple gpu? Whether the efficiency problem is solved, only one gpu is loaded at the same time.

**Comment by deyu260** [comment]
> I have a dual 1080ti setup. Will try using only one card.

Do you have the efficiency stack of trying too many cards? Please give me some experience you use.
