### ISSUE TITLE
Memory error with XSeg train(ing)

### ISSUE THREAD

**Issue by Pylon69** [iperov/DeepFaceLab#730]
## Expected behavior

Expect "5.XSeg) train.bat" to run just like the tutorial

## Actual behavior

"5.XSeg) train.bat," after you've selected face type and started the training before sampling even starts I get a memory error.
![Memory error](https://user-images.githubusercontent.com/49879045/80451984-7f414280-8925-11ea-85a8-de2230e948e0.png)

I've tried my GPU and CPU and they both result in the same memory error

## Steps to reproduce

Following the Mini Tutorial step by step.

## Other relevant information

Ryzen 1600
GTX 1070ti
16gb 3000mhz ram

**Comment by Pylon69** [comment]
Sorry. Found the problem.
I was running everything on my slave drive rather than my OS drive.
Just moving it to the drive with my OS on fixed the memory error.

**Comment by whatsis1** [comment]
I have the same exact problem. I tried @Pylon69 solution but it did not work for me.

AMD 3900x
RTX 2070 Super
32GB 3600mhz

**Comment by Ananth-Eswar** [comment]
> I have the same exact problem. I tried @Pylon69 solution but it did not work for me.
> 
> AMD 3900x
> RTX 2070 Super
> 32GB 3600mhz

I am also having same problem, moving also not working and buddy, by the way, I'm also having the SAME SPECS AS YOU. That's great. If you're on WhatsApp or something, give id, we'll discuss the problems and pieces of stuff of DFL in the future .
