### ISSUE TITLE
Quick96 Model Training Issue

### ISSUE THREAD

**Issue by SuppleCowChunks** [iperov/DeepFaceLab#733]
Just upgraded my version of DFL to the 4-20-2020 version from an old version from December. My DFL Computer is using a GTX 1050Ti with 4GB of VRAM, so I was going to utilize the Quick96 model. When training, src and dst values do not decrease, right away they go up to values between 9.0-11.0 and stay there. Doesn't matter how many iterations it goes through they stay at that value. Hoping that it was an issue with the build and my computer I downloaded DFL version 4-13-2020. I encountered the same issue. I then attempted Quick96 from my December version of DFL, that also didn't work. However, the H128 model works from December. I cannot test out SAEHD as I do not have enough VRAM.

I am running on Windows 10, Nvidia Driver 441.20, with CUDA Toolkit 10.2.89-441.22

**Comment by NintendObi-Wan** [comment]
Mine does the same, Although I am using an AMD Graphics card. Do the training models go black after many iterations? Also is your data_src video in pretty dark lighting?

**Comment by ghost** [comment]
Did you ever find the answer?
