### ISSUE TITLE
OOM error with xSeg training method

### ISSUE THREAD

**Issue by Impl0sioN** [iperov/DeepFaceLab#739]
![errore](https://user-images.githubusercontent.com/64840503/81059403-a624e900-8ed0-11ea-82c4-3e3bf312669e.JPG)

OOM when allocating tensor with shape.
In xSeg train i can't reduce model parameters (resolution) that probably could solve that problem.

**Comment by iperov** [comment]
2gb is not enough

**Comment by Impl0sioN** [comment]
what is the minimum GB to build this train? what are the minimum requirements?
