### ISSUE TITLE
Different trains overlap others?

### ISSUE THREAD

**Issue by ZeroCool22** [iperov/DeepFaceLab#74]
I trained on H128 method and it ofc. created the respective models.

Now, if i want to train (same data) on MIAEF128 i will lose my previews trained models in H128 or it will just create new models for MIAEF128 without overlaping/delete the previews models? Thx.

**Comment by tfis2** [comment]
it will just create new models for MIAEF128 without overlaping/delete the previews models
this

**Comment by ZeroCool22** [comment]
> 
> 
> it will just create new models for MIAEF128 without overlaping/delete the previews models
> this

That's great. Thx.
