### ISSUE TITLE
SAEHD Merge Fails when using old dataset.

### ISSUE THREAD

**Issue by mhamzahkhan** [iperov/DeepFaceLab#748]
I'm trying to use a dst faceset I created in March with an older version of DeepFaceLab, against a new src faceset. I have done the training, and the preview looks good, but when I try to merge it I get an exception. I'm guessing this is due to some format incompatibility?

## Expected behavior

Merge complete successfully.

## Actual behavior

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mhamzahkhan/DeepFaceLab/core/joblib/SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "/home/mhamzahkhan/DeepFaceLab/merger/InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [/home/mhamzahkhan/workspace/data_dst/00134.png]: Traceback (most recent call last):
  File "/home/mhamzahkhan/DeepFaceLab/merger/InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "/home/mhamzahkhan/DeepFaceLab/merger/MergeMasked.py", line 328, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/home/mhamzahkhan/DeepFaceLab/merger/MergeMasked.py", line 100, in MergeMaskedFace
    wrk_face_mask_a_0 = np.pad (wrk_face_mask_a_0, input_size)
TypeError: pad() missing 1 required positional argument: 'mode'

## Steps to reproduce

Attempt to merge SAEHD.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)** p:ython3.6 /home/mhamzahkhan/DeepFaceLab/main.py merge --input-dir /home/mhamzahkhan/workspace//data_dst --output-dir /home/mhamzahkhan/workspace//data_dst/merged --output-mask-dir /home/mhamzahkhan/workspace//data_dst/merged_mask --aligned-dir /home/mhamzahkhan/workspace//data_dst/aligned --model-dir /home/mhamzahkhan/workspace//model --model SAEHD

- **Operating system and version:** Linux 
- **Python version:** 3.6

**Comment by Vano333** [comment]
> /workspace//data_dst

> /workspace//model

Maybe ist a copy paste error(double slash)?
