### ISSUE TITLE
Attempting to create throws TypeError: argument should be a path or str object, not <class 'NoneType'>

### ISSUE THREAD

**Issue by carson-fitzgibbon** [iperov/DeepFaceLab#75]
## Expected behavior

Using the create function through the following command: "python C:\Users\Carson\Desktop\DeepFaceLab-master\main.py convert --output-dir C:\face-swap\outputs --input-dir C:\face-swap\data\scene --model-dir C:\face-swap\models\LIAEF128 --model LIAEF128", where the output-dir argument is my destination for the newly generated swapped images and the input-dir argument is the full set of images from the video onto which new faces will be drawn.

## Actual behavior

The following error occurs:

> (face-swap) C:\Users\Carson>python C:\Users\Carson\Desktop\DeepFaceLab-master\main.py convert --output-dir C:\face-swap\outputs --input-dir C:\face-swap\data\scene --model-dir C:\face-swap\models\LIAEF128 --model LIAEF128
Running converter.
Error: argument should be a path or str object, not <class 'NoneType'>
Traceback (most recent call last):
  File "C:\Users\Carson\Desktop\DeepFaceLab-master\mainscripts\Converter.py", line 213, in main
    aligned_path = Path(aligned_dir)
  File "C:\Users\Carson\Anaconda3\envs\face-swap\lib\pathlib.py", line 969, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\Carson\Anaconda3\envs\face-swap\lib\pathlib.py", line 651, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\Carson\Anaconda3\envs\face-swap\lib\pathlib.py", line 643, in _parse_args
    % type(a))
TypeError: argument should be a path or str object, not <class 'NoneType'>

## Steps to reproduce

I generated this model with batch size 4 and extracted the images using the tools provided by DeepFaceLab.

## Other relevant information
It looks like some sort of alignment data is required for this to function, even though the --aligned-dir argument is shown as optional in the usage. I couldn't find any explanation for what the aligned directory was or what generated it, so I'm stuck.

I don't believe this is a major bug, it's a mix of me not knowing what the alignment data is supposed to be as well as the command not requiring it as an input in order to launch, thus generating an exception.

**Comment by iperov** [comment]
fixed. 
--aligned-dir is extracted dst faces

**Comment by iperov** [comment]
also you can use windows app

**Comment by carson-fitzgibbon** [comment]
Updated and used the extracted dst faces for --aligned-dir and it worked as expected!

An additional question unrelated to this bug: when I convert it seems to not recognize a bunch of faces from the dst even though when I originally extracted the faces it recognized almost all of them. What could be causing this?

**Comment by carson-fitzgibbon** [comment]
Is there any particular reason why the convert function can't re-extract the dst faces temporarily for use as alignment data? I have my destination faces mixed in with other training data of that same person from other videos they were in. I think it would make more sense to have a "default" alignment option that temporarily extracts faces from the destination frames and uses them for alignment, then deletes them when finished rather than the end user having to keep a separate group of aligned faces AND training faces.

**Comment by iperov** [comment]
` re-extract the dst faces temporarily for use as alignment data`

srsly ?

**Comment by carson-fitzgibbon** [comment]
What do you mean seriously? Yes. As I understand it, in order to get alignment data, I have to keep a set of faces extracted from the destination video as well as a set of the same person's faces in the training data, which typically INCLUDES the already extracted destination faces. It's an extra level of workspace complexity and another thing an end user has to do and keep in order. If I were to just use the current extracted dst faces I would have a person's faces both from the video as well as other sources that aren't useful in that particular destination's alignment.

From my understanding: the alignment data is the extracted faces from the destination VIDEO, meaning it cannot be destination faces from other sources (like google images). I have a folder of George Bush's face that I use as training data for when I will place my own face onto his. This data is frames from a video of a speech he made as well as many other images of him on the internet. Having to copy-paste or re-extract the faces from the video and putting them in as alignment data means keeping even more images and folders on hand when the program could just as easily re-extract the faces itself from the destination frames, use that temporary alignment data, then delete it when finished.

**Comment by iperov** [comment]
re-extract is suxx and obsolete solution used in faceswap repo.
