### ISSUE TITLE
3) cut video has an error when i use it

### ISSUE THREAD

**Issue by thebrax2000** [iperov/DeepFaceLab#757]
usage: main.py videoed cut-video [-h] --input-file INPUT_FILE
                                 [--from-time FROM_TIME] [--to-time TO_TIME]
                                 [--audio-track-id AUDIO_TRACK_ID]
                                 [--bitrate BITRATE]
main.py videoed cut-video: error: argument --input-file: expected one argument
Press any key to continue . . .
Terminate batch job (Y/N)?

this is what it says when i try to use it

**Comment by iperov** [comment]
drop video on batch file

**Comment by nirajansolta** [comment]
how?
