### ISSUE TITLE
Preventing aligned faces from being resized

### ISSUE THREAD

**Issue by firion1234** [iperov/DeepFaceLab#76]
I am a traditional sculptor and would like to utilize this software to extract facesets for portrait work. Is there a way the end user can have the aligned faces come out the same size as the source image? Or at least 512x512? As it is 256x256 is too small to work from. Thank you!

**Comment by iperov** [comment]
try modify Extractor.py image_size=256

**Comment by firion1234** [comment]
It worked! Thank you very much for the help and the terrific software! This is going to exponentially speed up my least favorite part of being a sculptor, gathering reference.
