### ISSUE TITLE
Random graphics glitches after Merge in Colab

### ISSUE THREAD

**Issue by dmfp** [iperov/DeepFaceLab#763]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Merge with no graphics glitches introduced.

## Actual behavior

Random graphics glitches appear after Merge in Colab. Investigation by Colab developer points to possible main repo codebase issue with Linux environment: https://github.com/chervonij/DFL-Colab/issues/14#issuecomment-631403096

## Steps to reproduce

Issue demo workspace package:
https://drive.google.com/open?id=16g5NnE9mF4sRToSdMSC-0WZ_1FZG_PkJ

More examples:
https://mrdeepfakes.com/forums/thread-problems-with-merge-black-masks-spots-and-other-stuff

## Other relevant information
Google Colab

**Comment by birdstream** [comment]
I run DFL on my Linux desktop and can confirm this. The workaround for now is to set the denoise filter to some value like 5.

**Comment by dmfp** [comment]
Yep, I tried denoise values between 1-10 too which eliminates ~90-95% of the artifacts but not entirely, often leaving rainbow colored box outlines around the overlayed face area.

This is perhaps helpful for @iperov in debugging the exact stage where the glitches are introduced.

**Comment by iperov** [comment]
this problem occur only in Linux
I cannot investigate and fix it

**Comment by dmfp** [comment]
You made commits to this repo as "fix for linux" before. You include "requirements-colab.txt" in the codebase. Are you terminating support for Colab/Linux?

**Comment by iperov** [comment]
colab is used for training. I don't merge in colab.

**Comment by dmfp** [comment]
I am speechless.

So you will only fix bugs you encounter in your personal use?

You should not list Linux and Colab versions as 'releases' on the main page if that is the case - they are merely installers / script-wrappers based on the same exact codebase. And if you are not willing to fix bugs that affect these 'releases', they are at best 'unsupported wrappers'.

Have invested weeks learning to use DFL, training models in Colab, only to be told bugs will not be fixed simply because the creator-developer does not use a 'release' the same way users do?

To prevent others from suffering the same pain and disappoint, I sincerely urge you to clearly label the Linux and Colab versions 'unsupported'.

Thanks.

**Comment by dmfp** [comment]
I am speechless.

So you will only fix bugs you encounter in your personal use?

You should not list Linux and Colab versions as 'releases' on the main page if that is the case - they are merely installers / script-wrappers based on the same exact codebase. And if you are not willing to fix bugs that affect these 'releases', they are at best 'unsupported wrappers'.

Have invested weeks learning to use DFL, training models in Colab, only to be told bugs will not be fixed simply because the creator-developer does not use a 'release' the same way users do?

To prevent others from suffering the same pain and disappointment, I sincerely urge you to clearly label the Linux and Colab versions 'unsupported'.

Thanks.

**Comment by iperov** [comment]
initially DFL created for windows.
Colab and Linux "forks" made by other users.
Colab works fine for extract and training.
Nobody use colab for merging, because it is interactive.
You can use CPU for merging on your linux windows emulator.

**Comment by iperov** [comment]
and this is open source.
I don't owe anyone anything.

**Comment by dmfp** [comment]
It is not an issue of you owing anyone anything.

It is an issue of you supporting Linux/Colab half-heartedly and your attitude towards ur community of users who spend time to troubleshoot and put together workspaces for your investigation.

You first said "I cannot investigate and fix it", but when pointed out you have made fixes for Linux before, you say "I don't merge in colab".

So you CANNOT investigate or you WON'T?

If bugs start showing up in the Trainer in Linux too, what will you do?

Will you say Linux and therefore "I cannot investigate"?
Or will you investigate just because "I use it too"?

PS. Again I urge you to label Linux / Colab variants 'unsupported' as far as your codebase is concerned. You can let future forks that are actually properly adapted to the various OS/environments claim to be 'releases'.

**Comment by dmfp** [comment]
PPS. I tried using Merge in Parallels on my Mac - Mac user whole reason why I have to use Colab - but it crashed and I never get to be able to select 'CPU'.

I asked on the mrdeepfakes forum if that was expected behavior because I do not have a Nvidia GPU, and was told-off by tutsmybarreh your 'official' guide support forum moderator and had my question closed -- "only Nvidia GPU" he said.

**Comment by birdstream** [comment]
@dmfp As frustruating as this problem is I wouldn't bash the author of this awesome piece of software, though. The only reason it also runs on linux is because it's written in Python. The linux fork of this project is actually just a bunch of bash scripts that replace the Windows *.bat ones. I'm not so good at programming but I like challenges and if @iperov could point me in the right direction (like what libs/requirements is involved in the merger) I could at least have a look at it :)

**Comment by iperov** [comment]
this is a bug with opencv on linux
idk how to reproduce it on windows

**Comment by TooMuchFun** [comment]
@dmfp 

Learn to code or fuck off.

**Comment by edchansta** [comment]
@iperov 
As birdstream rightly pointed out, u graciously open-sourced ur work, and I wud like say a big thank u in this regard. I wasn't expecting u alone to fix all of DFL's bugs, u certainly don't owe anyone anything indeed. I was just taken aback by what I read as u brushing off the problem simply becoz it is a Linux/Colab problem or that u don't use Merge there. Maybe you did not intend it that way.

I had invested weeks on learning and training in DFL; first raised the issue on mrdeepfakes (had a really bad experience with moderator 'tutsmybarreh' claiming it was likely a hardware issue and prematurely closing my questions whilst giving wrong answers), then with @chervonij (who was helpful and pointed to issue being with main repo), and only then did I reach out to you.

I spent time putting together a demo workspace, documenting and providing example outputs with different settings, etc, all so to help u easily replicate and understand the issue.

All that effort, only to be casually dismissed, was what made me really upset -- I did not bother u with a noob qns, but felt treated as if I were.

PS. If you can confirm the Interactive Merger is meant to work even in Windows emulators/virtual machines w/o Nvidia GPUs, I will post an issue and share detailed logs on how the Merger crashed on launch in Parallels on my Mac. Otherwise, the non-interactive Merger on Colab remains my only choice.

@birdstream 
Thanks for offering to try look into the issue. Much, much appreciated.

PS. Understand the Linux/Colab versions are wholly based on the main repo, hence my comments above.

**Comment by dmfp** [comment]
@iperov 
As birdstream rightly pointed out, u graciously open-sourced ur work, and I wud like say a big thank u in this regard. I wasn't expecting u alone to fix all of DFL's bugs, u certainly don't owe anyone anything indeed. I was just taken aback by what I read as u brushing off the problem simply becoz it is a Linux/Colab problem or that u don't use Merge there. Maybe you did not intend it that way.

I had invested weeks on learning and training in DFL; first raised the issue on mrdeepfakes (had a really bad experience with moderator 'tutsmybarreh' claiming it was likely a hardware issue and prematurely closing my questions whilst giving wrong answers), then with @chervonij (who was helpful and pointed to issue being with main repo), and only then did I reach out to you.

I spent time putting together a demo workspace, documenting and providing example outputs with different settings, etc, all so to help u easily replicate and understand the issue.

All that effort, only to be casually dismissed, was what made me really upset -- I did not bother u with a noob qns, but felt treated as if I were.

PS. If you can confirm the Interactive Merger is meant to work even in Windows emulators/virtual machines w/o Nvidia GPUs, I will post an issue and share detailed logs on how the Merger crashed on launch in Parallels on my Mac. Otherwise, the non-interactive Merger on Colab remains my only choice.

@birdstream 
Thanks for offering to try look into the issue. Much, much appreciated.

PS. Understand the Linux/Colab versions are wholly based on the main repo, hence my comments above.

**Comment by TooMuchFun** [comment]
Feel better now?

**Comment by TooMuchFun** [comment]
![DFL mascot](https://raw.githubusercontent.com/iperov/DeepFaceLab/master/doc/meme1.jpg)

**Comment by iperov** [comment]
> PS. If you can confirm the Interactive Merger is meant to work even in Windows emulators/virtual machines w/o Nvidia GPUs, 

before use, run _internal/convert_to_full_cpu_only.bat

> I will post an issue and share detailed logs on how the Merger crashed on launch in Parallels on my Mac. Otherwise, the non-interactive Merger on Colab remains my only choice.

post issue in appropriate fork. This is windows repo.

**Comment by dmfp** [comment]
> > PS. If you can confirm the Interactive Merger is meant to work even in Windows emulators/virtual machines w/o Nvidia GPUs,
> 
> before use, run _internal/convert_to_full_cpu_only.bat
> 
That solved the crash, thanks! Suggest this be in readme/guide so non-Nvidia folks know they can use the wonderful Interactive Merger too!

> > I will post an issue and share detailed logs on how the Merger crashed on launch in Parallels on my Mac. Otherwise, the non-interactive Merger on Colab remains my only choice.
> 
> post issue in appropriate fork. This is windows repo.
If referring to Merger crash issue -- am running a Win 10 virtual machine in Parallels so yes Windows issue. In any case, solved as above thx!

If referring to Merge graphics glitch issue -- if u prefer all bugs arising from Linux/Colab be raised in respective forks (even tho they use 100% main repo code with no adaptation), suggest you leave all non-windows commits (e.g. 'fixes for linux') and files like 'requirements-colab.txt' to the forks. Cleaner this way and u won't have people like me bothering u with Linux issues...

Thanks!

**Comment by dmfp** [comment]
PS. I hope u can take users like me jumping thru hoops to use ur software on non-Windows non-Nvidia machines as an indication that we like ur software -- because it is. Thanks.

**Comment by TooMuchFun** [comment]
> PS. I hope u can take users like me jumping thru hoops to use ur software on non-Windows non-Nvidia machines as an indication that we like ur software -- because it is. Thanks.

Consider a donation, he works hard for folks like you. 😄

**Comment by sergeevii123** [comment]
I reproduced the issue and it turns out that linux opencv makes nan values,
that's why there is an error in merge
```
/app/deepfake/DeepFaceLab/merger/MergeMasked.py:235: RuntimeWarning: invalid value encountered in multiply
  out_img = img_bgr*(1-img_face_mask_a) + (out_img*img_face_mask_a)
```
created a pr to fix this -> tested locally -> no glitches
https://github.com/iperov/DeepFaceLab/pull/769

**Comment by dmfp** [comment]
Just did a test with latest code in Colab with settings (A) from demo workspace and can confirm no glitches.

@sergeevii123 @chervonij @birdstream @iperov thanks! heroes one and all!
