### ISSUE TITLE
Excuse me,Cut out the face, can be manually K frame anchor point (face)

### ISSUE THREAD

**Issue by nbabaiyu** [iperov/DeepFaceLab#764]
Excuse me,Cut out the face, can be manually K frame anchor point (face)？

**Comment by iperov** [comment]
yes I can

**Comment by iperov** [comment]
how much you can donate via paypal for this feature?

**Comment by nbabaiyu** [comment]
$300，Is that OK？

**Comment by iperov** [comment]
ok.
This feature will be available in public.

**Comment by nbabaiyu** [comment]
time

**Comment by nbabaiyu** [comment]
If it's for your own use, how much will it cost

**Comment by iperov** [comment]
no, code will be for all.

**Comment by iperov** [comment]
So, do you need such feature or not?

**Comment by nbabaiyu** [comment]
how long

**Comment by iperov** [comment]
today

**Comment by nbabaiyu** [comment]
Is $100 donation OK, because this is not a unique customization

**Comment by iperov** [comment]
No. I developed this feature specially for your request.

**Comment by nbabaiyu** [comment]
The key is to donate 300. I want to use it independently。 After development, to my email

**Comment by iperov** [comment]
300$ is nothing for tv company.
I did the hard work specially for your request.

**Comment by iperov** [comment]
when you pay for software for example Adobe Premier, new features come to all users, not only for you.

**Comment by nbabaiyu** [comment]
300￥ It's really nothing, mainly because I don't want to share

**Comment by iperov** [comment]
not yuan, us dollars

**Comment by nbabaiyu** [comment]
You can customize the software and use it exclusively. You can charge more for development.

**Comment by iperov** [comment]
no I cannot.

**Comment by iperov** [comment]
The extraction feature is ready to upload.
If you need it right now - donate 300$ to paypal.

**Comment by nbabaiyu** [comment]
yes，us dollars

**Comment by nbabaiyu** [comment]
In addition to this function, I want to develop other functions. Can I enjoy them alone，

**Comment by iperov** [comment]
No.

**Comment by iperov** [comment]
Seems like you don't need new extraction feature.
Nothing to discuss anymore.
Feel free to fix undetectable faces in your own way.
