### ISSUE TITLE
Xsag mask applyed faceset Packed faceset irregular file size increase after Packing

### ISSUE THREAD

**Issue by s1242001** [iperov/DeepFaceLab#765]
## Expected behavior
when dataset are packed the packed file size should be close to the pre-packed size

## Actual behavior
when the faceset is packed,
the package size of the faceset with Xseg mask applyed is significantly larger the then without.

for the 60k dst set I am useing
the original extracted faceset size is **1.77GB**,
when packaged original extracted faceset becomes **1.86GB**,
after the trained **Xseg mask applyed** faceset size is **1.84GB**,
when the dataset is package after **Xsag applyed mask applyed**, the package size becomes **17.3GB**.
9.4 times the file size.

note: I am useing whole face

makeing a separate issue pose thet I found durinig testing of another issue thread.
https://github.com/iperov/DeepFaceLab/issues/758#issuecomment-635778111

## Steps to reproduce
prepare a faceset
note down the file size of the faceset.
pack the faceset, note down the size.
unpack and train Xseg model and apply to the mask onto the faceset
note down the size.
pack the faceset, note down the size.

compare the sizes.

note: by packing I mean: data_dst util faceset pack.bat

## Other relevant information
windows 10 64bit
cpu i5-9300H
ram 16GB
GPU GTX1650 4GB
Build DeepFaceLab_NVIDIA_build_05_06_2020

**Comment by s1242001** [comment]
Behavior does not seems to change with DeepFaceLab_NVIDIA_build_05_31_2020

**Comment by iperov** [comment]
> when dataset are packed the packed file size should be close to the pre-packed size

no, it should not

**Comment by iperov** [comment]
> when dataset are packed the packed file size should be close to the pre-packed size

no, it should not
packed faceset contains additional info for fast load and seek to specific sample

**Comment by s1242001** [comment]
Ok my mastake, if it is working as intended.

I was just a bit alarm by 1.84GB→17.3GB increase.
personally I think 9.4 time size is a bit much (with Xseg mask), and may increase load time.
