### ISSUE TITLE
Resolution vs gpu memory

### ISSUE THREAD

**Issue by Eleganze** [iperov/DeepFaceLab#77]
What is the required menory to bump up the resolution on this technology to the next level? Would 256 output be possible on a Tesla 32 gb gpu?

If someone got the time to make the neccessary changes to the code/model, I would be happy to give it a try.

**Comment by Eleganze** [comment]
It would be interesting to test this. If you combine 8 tesla, you get 128 GB HBM2 memory according to Google.

**Comment by carson-fitzgibbon** [comment]
If you're not doing this independently (ie you're doing research with funding/budget), take a look at the NVIDIA DGX-2. Can't imagine the kind of models you could compute with something like that. High resolution and massive batches running concurrently to train more than one model at once would probably be possible with something like that.

**Comment by Eleganze** [comment]
Well, I can access 8 Teslas for a start. But I have no clue on how to adapt the code. Actually it would be a nice feature if the model layers/resolution automatically scaled based on the GPU memory available.(Similar to what batch size does)
