### ISSUE TITLE
Deepfacelab preview window randomly freezes and causes PC to crash / blue screen.

### ISSUE THREAD

**Issue by House1999** [iperov/DeepFaceLab#773]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

I launch the training (SAE or Quick96) with minimal parameters and i expect the training to run smoothly. Especially that i turned off EVERYTHING while training to maximize the VRAM available.

## Actual behavior

Well, no error is shown. After a random number of iterations (sometimes after 30 sec, sometimes after 3 minutes of training), the preview window just freezes. If i put my mouse over it, it shows the windows 10 loading cursor. And the console, even though it is responding, the iterations don't move. Nothing changes. And i can't quit the training nor close or force close anything. The only choice i have is to either force restart the PC from the tower button, or to wait until it blue screens it.

## Steps to reproduce

I used the facesets that come with deepfacelab. I tried the models with default options (except the batch size that i reduced in every try, from 8 to 2, and the face type i put wf). I just launch the training process, and everything goes smoothly. Sometimes it saves and backs up. But it randomly freezes and stops responding. No crash messages, no error messages. Just a hard reboot.

## Other relevant information

- I tried all versions of deepfacelab. Even the "old" deepfacelab (since it used to work on my PC) yet none of them had a different result.

- I have a RTX2080 Ti and i already successfully ran deep learning algorithms on it without any problems, the last one being 2 weeks ago.

- I have 1 TB of free space. And i have enough VRAM to run it. Even with low batch sizes, i wasn't above 50% of my VRAM (11 GB) yet it still crashed and froze my PC. I tried setting a limit in main.py and i cleaned my PC and aired it out. Really nothing seems to work.

- I have researched this problem for a week now. Noone seems to have the same issue. I found a similar issue which is the issue #334 but he had it during the convert stage and he had an error message. And i tried all the solutions that were suggested in his issue, and none of them worked.
I even turned off quick edit and  insert mode of my command prompt (since i saw that it sometimes causes python to freeze). I will say that it no longer crashes when i use Quick96 but still freezes on SAEHD.

Thank you in advance for any help, and i hope i put all the details that are necessary.

**Comment by HappiestCow22** [comment]
I have an RTX 2080 TI as well and I have the same problem. In older versions of dfl I had blue screens literally every couple minutes if i even launched the training window. I realized it was due to a faulty SSD boot drive (i always ran DFL on a seperate HDD). I got a new one and now instead of blue screens constantly, my training window will just freeze and the CMD prompt window will show that it has stopped training. If i can somehow get it to train longer than a couple minutes, when i come back to check on it overnight my PC has restarted and its just sitting on the welcome screen. Everything is closed and reset. When checking on my backups it seems like the training didn't even last for an hour. This has stopped me from progressing on deepfakes for months now. If i revert back to the older SAE(non hd) version of DFL i can train to my hearts content but the lack of features and quality make it not worth it to continue.

The issue is probably related to RTX and the drivers for DFL. Either DFL is using a corrupted driver or theres a problem in windows. When there was a seperate branch of DFL for RTX only it never had an issue.

**Comment by House1999** [comment]
> I have an RTX 2080 TI as well and I have the same problem. In older versions of dfl I had blue screens literally every couple minutes if i even launched the training window.
> I realized it was due to a faulty SSD boot drive (i always ran DFL on a seperate HDD). I got a new one and now instead of blue screens constantly, my training window will just freeze and the CMD prompt window will show that it has stopped training.
> (the only way to close it and free my VRAM is to close the CMD window and it doesnt save the model)
> If i can somehow get it to train longer than a couple minutes, when i come back to check on it overnight my PC has restarted and its just sitting on the welcome screen. Everything is closed and reset. When checking on my backups it seems like the training didn't even last for an hour.
> This has stopped me from progressing on deepfakes for months now. If i revert back to the older SAE(non hd) version of DFL i can train to my hearts content but the lack of features and quality make it not worth it to continue.
> 
> The issue is probably related to RTX and the drivers for DFL. Either DFL is using a corrupted driver or theres a problem in windows. When there was a seperate branch of DFL for RTX only it never had an issue.

Yes, this is exactly what i was facing. However, by allowing 110% power on my pc and underclocking by 150 (through msi afterburner), i got SAEHD to work for like 4-5h without freezing every time with a batch of 2. With a batch of 8, it freezes right after the 1st 15 min auto-save. 

I think, as u said, there's a problem related to RTX. But i am changing my PSU today, hoping maybe it will help with this issue too. I will let you know if i get any results.

**Comment by HappiestCow22** [comment]
When I train overnight I would usually underclock my gpu a bit as well to keep temperatures down and that did help for a while. Weird.

**Comment by House1999** [comment]
> When I train overnight I would usually underclock my gpu a bit as well to keep temperatures down and that did help for a while. Weird.

Final results : I just swapped my old PSU (corsair RM750x) for a corsair RM1000x (because i found one for the same price as a RM750x) and i kept the same settings we discussed before (underclocking by 150 and keeping the temperature limit at 84 C and closing every program). 

I can say that SAEHD runs smoothly (For now) with a batch 8. I noticed that my MHz and temperature stabalized (it used to move a lot before chaing the PSU). However you need a lot of fans in the pc to keep it cool (i have 3-5 fans outside of GPU fans). But for now, this seems to be a good fix. Maybe you should try it if you're still into deepfakes !

**Comment by HappiestCow22** [comment]
Well shit i'm already $1200 in for this so whats another $200?

**Comment by House1999** [comment]
> Well shit i'm already $1200 in for this so whats another $200?

hahaha right. But i would suggest doing some test to see if it really comes from your PSU like me or not (you will find a lot by googling). or maybe try puting 110% power usage and underclock a bit to see if it runs smoothly for a somewhat long time (~1-2h).
Best to be sure before buying! Good luck
