### ISSUE TITLE
PC crashed, DeepFake error when using autosave

### ISSUE THREAD

**Issue by Nerijus92** [iperov/DeepFaceLab#775]
Hi,

I ran Deepfake for two days and just now my pc froze and crashed. I wanted to continue the process with autosave but it shows an error message. I believe that it can be fixable but I don't have the knowledge to do that. Can someone please help? 
![cmd_oJ3htlYZlM](https://user-images.githubusercontent.com/66636341/84056452-e9d2ad00-a9be-11ea-8c4e-256db58a792e.png)

**Comment by iperov** [comment]
models were corrupted during the save.
Next time enable autobackup every 2-3 hours.
Also use last build of DFL, seems like you are using old version.
