### ISSUE TITLE
Can I get a resolution higher than 192 with a 6gb RTX 2060 ?

### ISSUE THREAD

**Issue by will380** [iperov/DeepFaceLab#779]
Can I get a resolution higher than 192 with a 6gb RTX 2060 ? Because when I try higher values, it seems to crash. And of course, I use multiples of 16.

**Comment by birdstream** [comment]
The answer is..no?
I supposed you have read the guide and tried stuff like turning off the option to put optimizers on gpu etc...

**Comment by will380** [comment]
Yes of course. Thanks anyway, I was just wondering if it was possible.
