### ISSUE TITLE
Loss histogram X axis options - suggestions

### ISSUE THREAD

**Issue by carson-fitzgibbon** [iperov/DeepFaceLab#78]
This is a suggestion for a change regarding the loss histogram displayed above the images during training.

I think it would be useful to have an option for the histogram to display the way it currently does or to switch it so that it displays with the X axis being as long as the target epoch. It's difficult to see a trend down towards lower loss when the full histogram is stretched to fit the window, it would be much easier to predict the trend in a model early on if I could see the histogram in this manner. If I knew a model was making very little progress, I could stop and make changes to the data sets or restart entirely with an entirely new model, rather than waiting until epoch 50,000 to see it's not making any progress.

This is an image of what I am proposing, where the top is the current model and the bottom is the option I would like to have:
![idea](https://user-images.githubusercontent.com/22183296/50258688-61c1a780-03c6-11e9-9925-40c1dc592ee5.png)
The end of the second histogram would be determined by --target-epoch, whereas the default (current) example in the first histogram has the end as the most recent loss values reported by the model.

This example was created in Paint.NET, if I knew how to do this myself I would have done so and submitted it. This is also not a major issue, just a suggestion for a change in the future.

**Comment by iperov** [comment]
fixed
