### ISSUE TITLE
Error while ectractin F from WF collection

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#780]
I`ve got an error while ectractin F from WF collection
` if extract_from_dflimg and len(rects) != 1`: and extraction script stops working

**Comment by iperov** [comment]
you don't need to extract full_face from whole_face

**Comment by wasyleque** [comment]
Thank You for answer, but I need Face not FullFace, there is 256x256 not 512x512. I need it to old version of software, cause it seems to give better results on some scenes.
When I`m extracting faces it seems like just copy files to aligned folder and they are not as expected (still 512x512).
regards

**Comment by iperov** [comment]
old versions are unsupported
