### ISSUE TITLE
Moving SAEHD model from DFL_Colab_1-0.ipynb to DeepFaceLab_1.0_OpenCL_build_01_11_2020

### ISSUE THREAD

**Issue by Orchoidizer** [iperov/DeepFaceLab#790]
## Expected behavior

Was hoping to pretrain a model in Colab and the use it as a base trainer on my PC.
I assumed the data compiled in DFL_Colab_1.0 would be readable in desktop DFL 1.0

## Actual behavior

When attempting to run the pre-compiled model using  6) train SAEHD.bat

Error: module 'keras.backend' has no attribute 'tf' Traceback (most recent call last): File "C:\Users\me2\Apps\DFL_internal\DeepFaceLab\mainscripts\Trainer.py", line 52, in trainerThread device_args=device_args) File "C:\Users\me2\Apps\DFL_internal\DeepFaceLab\models\ModelBase.py", line 146, in init self.onInitialize() File "C:\Users\me2\Apps\DFL_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 499, in onInitialize self.src_dst_opt.get_updates( G_loss, self.model.src_dst_trainable_weights) File "C:\Users\me2\Apps\DFL_internal\DeepFaceLab\nnlib\nnlib.py", line 959, in get_updates e = K.tf.device("/cpu:0") if self.tf_cpu_mode > 0 else None AttributeError: module 'keras.backend' has no attribute 'tf'

## Steps to reproduce

Download pre-trained model I produced in DFL_Colab_1-0 to PC version of DFL_1.0 on my PC. 

Running - python-3.6.8 within DFL_1.0_OpenCL_build_01_11_2020

OS Windows 1903 - 18362.30
eGPU
Radeon RX Vega 64
Discrete/Hybrid/External
VRAM - 8176 MB
HBM2 - 945 MHz
CPU
Intel(R) Core(TM) i7-4770HQ CPU 
@ 2.20/3.4GHz 4 Cores

Thanks for any advice.

**Comment by iperov** [comment]
1.0 is no longer supported

**Comment by Orchoidizer** [comment]
> 
> 
> 1.0 is no longer supported

I know that but I thought if it was a known bug maybe a workaround or solution was somebody would let me know.
