### ISSUE TITLE
Is the pose roll not precise?  i find the roll pose is half_pi or -half_pi in most of time

### ISSUE THREAD

**Issue by Dian-Yi** [iperov/DeepFaceLab#795]
In LandmarksProcessor.estimate_pitch_yaw_roll(), i get pitch, yaw, roll. but i find roll is not precise. In the most of time, it is half_pi or -half_pi.
i want know this phenomenon is it right?
i also find the roll doesnt be used in the code, because is it not precise?

**Comment by iperov** [comment]
roll is unused because faces are aligned vertically

**Comment by kalmsy** [comment]
@iperov Please can you help me understand how to convert these values to conventional degrees?
