### ISSUE TITLE
Unpredictable shutdown when I use 2 GPUs to train one model

### ISSUE THREAD

**Issue by rec8** [iperov/DeepFaceLab#796]
## Expected behavior
Training my model with both GPUs at the same time.

## Actual behavior
My computer shutdown when I train with 2 GPUs. It is totally unexpected; it could happen after 5 minutes or after 1 hour. Longest time training is 2 hours.
Yes, I know this seem clearly hardware related, but I have tested different case scenarios and I think the answer is not so simple (if I am wrong please don’t mind to tell me I am an idiot).
First strange thing: All works fine in build 04_20_2020, but in the later builds I have the issue (In build 04_20_2020 longest training time is 30 hours and I stopped the training, the pc didn’t shutdown suddenly).

## Steps to reproduce
Train SAEHD with my two GPUs (I dont think it could be reproduced)

## Other relevant information
I am using prebuilt windows binary
- Windows 10
- AMD Threadripper 1950X 3.4 GHz 16-Core Processor
- MSI X399 GAMING PRO CARBON ATX
- 64 Gb RAM
- SSD (500 GB free)
- 1 GTX 1080ti 11Gb
- 1 TITAN XP 12Gb
- SeaSonic PRIME Titanium 1000 W 
(PC part picker says my PC estimated wattage is 838W)

As I said all works OK in build 04_20_2020 (longest trainning session using both GPUs in my model is 30 hours). My model is 256px, 296-80-80-22, batch=8. All in GPU.

- If I use just the GTX 1080ti with same model and settings but batch=4, all works fine (training during 24 hours with no issues and using the computer to watch youtube videos, surf the web, etc).
- If I use just the TITAN XP with same model and settings but batch=4, all works fine (training during 24 hours with no issues and using the computer to watch youtube videos, surf the web, etc).
- If I use both GPUs at the same time, each one working in a different folder with a model with the same settings, but batch=4, all works fine (training during 24 hours with no issues and using the computer to watch youtube videos, surf the web, etc).
- If I use both GPUs, both training the same model with batch=8, the issue happens. (I also tried with batch=6, 4 and even 2 and it is the same. My PC shutsdown suddenly after a couple of minutes even without using the PC for anything else besides the training).

Thank you very much.

**Comment by iperov** [comment]
this is hardware issue, not software.
