### ISSUE TITLE
Ran out of memory trying to allocate 128.00MiB

### ISSUE THREAD

**Issue by lookjaklook** [iperov/DeepFaceLab#81]
I was trying to train the model (with 'train DF best GPU'), when suddently, after a few minutes of training, this error appears:
[DeepFaceLabError.txt](https://github.com/iperov/DeepFaceLab/files/2703427/DeepFaceLabError.txt)

I have NVIDIA 980Ti running on Windows 10 64 bit with 16 GB RAM
this error appears in a few minutes after training. What is strange is that when i open Chrome, and only after then start training the DF model, then it works and after a few minutes the error appears. But if i don't open chrome and start to train the model, then after the console says 'Starting. Press Enter...' the computer shuts down/restart and says that too much memory were used.
![too much memory used](https://user-images.githubusercontent.com/36490163/50352917-4f26aa00-054f-11e9-97b7-43955f4ac42a.jpeg)

Is there anything im doing wrong or there anyway to fix it?

**Comment by iperov** [comment]
it is VRAM related error, not RAM.

**Comment by lookjaklook** [comment]
> it is VRAM related error, not RAM.
Yeah i got it now. Even though NVIDIA 980Ti has 6 GB VRAM, i readed about Windows 10 having memory problems overall. So I can't use some models. Now im running H64 and it seems ok

**Comment by gessyoo** [comment]
lookjaklook, Windows 10 video driver reserves about 15% of VRAM.  You could try a lower batch size.

**Comment by lookjaklook** [comment]
> lookjaklook, Windows 10 video driver reserves about 15% of VRAM. You could try a lower batch size.

Ok, ill try it later. First of all ill finish to train with H64 and see how it is. Thanks!

**Comment by iperov** [comment]
try to disable Windows 10 aero desktop

**Comment by lookjaklook** [comment]
> try to disable Windows 10 aero desktop

You mean performance options?
![this?](https://user-images.githubusercontent.com/36490163/50375614-e4d24000-0608-11e9-8052-60ef2d3f59f4.jpg)

**Comment by iperov** [comment]
yes

**Comment by gessyoo** [comment]
Iperov knows better than me but I would edit the training batch file you want to use, for example, edit the "6) train H128 best GPU.bat" and add a line to specify a smaller batch size, e.g. --batch-size 8 rather than the default batch size of 16.

**Comment by revolct** [comment]
Forgot to mention, I'm using the linux version. 
I just changed the value in main.py file, line 84 -             batch_size         = arguments.batch_size,
