### ISSUE TITLE
[RecycleGAN] trying to implement

### ISSUE THREAD

**Issue by iperov** [iperov/DeepFaceLab#82]
My gtx1060 6GB can run recycle only with 1 batch size.

what I got on first epochs, predictings just stuck on dots, is it normal?

![python_2018-12-24_19-07-16](https://user-images.githubusercontent.com/8076202/50402312-28ff4500-07af-11e9-8712-d142dbd9cae2.jpg)

any advices???

**Comment by Arthurzhangsheng** [comment]
As is known to all， GAN is hard to learn, unlike AE.
try to run more epoch/iteration to see what will happen. If you only run a few iteration, it's normal to see this meaningless image.
What‘s more, you can change the resolution to reduce learning difficulty.

**Comment by Arthurzhangsheng** [comment]
Batch size=1 is too erratic, which may go against the learning

**Comment by iperov** [comment]
changed generator to UNet from Resnet, speed increased x2 per epoch. and allows set x4 more batch size.

changed norm layer to GroupNormalization, training became stable...

**Comment by wintdkyo** [comment]
By any chance, could you write a quick instruction on implementing the pasted code or do you @iperov have plans to add it as another model to the code base? I have a powerful GPU, so I can probably test the model with large amounts of training in a short amount of time.

**Comment by iperov** [comment]
yes I have plan to add it to repo in case of success adaptation to keras

**Comment by wanshun123** [comment]
Definitely would be valuable to have this added to DFL, if possible . I've been playing around with the official Recycle-GAN repo but am getting poor results (https://github.com/aayushbansal/Recycle-GAN/issues/9)

**Comment by iperov** [comment]
I found another implementation of RecycleGAN https://github.com/SerialLain3170/VideoProcessing/tree/master/Recycle-GAN
and it is differs from aayushbansal/Recycle-GAN

**Comment by Eleganze** [comment]
I can test this on 4 Tesla GPU’s when the code is ready

Outlook<https://aka.ms/qtex0l> / iOS

________________________________
Fra: iperov <notifications@github.com>
Sendt: fredag, desember 28, 2018 2:56 pm
Til: iperov/DeepFaceLab
Kopi: Subscribed
Emne: Re: [iperov/DeepFaceLab] trying to implement RecycleGAN (#82)


I found another implementation of RecycleGAN https://github.com/SerialLain3170/VideoProcessing/tree/master/Recycle-GAN
and it is differs from aayushbansal/Recycle-GAN

**Comment by iperov** [comment]
@Eleganze 
currently there is no multi-gpu model.
How many VRAM each GPU has ?

**Comment by Eleganze** [comment]
I can only access the 16 gb versions

**Comment by Eleganze** [comment]
4 gpu with 16 gb each

**Comment by iperov** [comment]
@Eleganze I committed. 
Now you can test RecycleGAN.

workspace with Putin/Navalny
https://mega.nz/#!f9k3xCCD!fcJkAlWVBg3FhCVK-6N4nwsKm14K_C0aa73TLOIWUq4
or you can use your own data. Place any square files to aligned folders

6) train RecycleGAN hist.bat :
```
@echo off
call _internal\setenv.bat

%PYTHON_EXECUTABLE% %OPENDEEPFACESWAP_ROOT%\main.py train ^
    --training-data-src-dir %WORKSPACE%\data_src\aligned ^
    --training-data-dst-dir %WORKSPACE%\data_dst\aligned ^
    --model-dir %WORKSPACE%\model ^
    --model RecycleGAN ^
    --write-preview-history
pause
```

model will ask batch size on first run. Find max for your 16GB before OOM please and report me.

also you can change resolution in model py file
> resolution = 128

**Comment by iperov** [comment]
now I started 64x64 with 24 batch size

**Comment by iperov** [comment]
hmm really 24 batch size is more stable

**Comment by Eleganze** [comment]
I will give it a show now!

**Comment by iperov** [comment]
with batch size 24 discriminator fluctuating heavily, but generator stable
![python_2018-12-28_22-57-11](https://user-images.githubusercontent.com/8076202/50525291-fed1be00-0af3-11e9-9411-760d8fc8b533.jpg)

**Comment by Eleganze** [comment]
Project started fine with batch size 16 at 128x128 resolution.

![bs162](https://user-images.githubusercontent.com/37071118/50525377-f9b04700-0ad2-11e9-9dc4-73d62357b0a6.PNG)
![bs16](https://user-images.githubusercontent.com/37071118/50525378-f9b04700-0ad2-11e9-84ab-e6ff5cd1ab9c.PNG)

**Comment by iperov** [comment]
@Eleganze  try 256x256 and 24 batch size

**Comment by iperov** [comment]
and wait I will commit some fixes

**Comment by Eleganze** [comment]
Does not start with 256x256 and batch size 16 :-/

**Comment by iperov** [comment]
I did new commit.
Now resolution and batch size asking on first run.

**Comment by iperov** [comment]
> Does not start with 256x256 and batch size 16 :-/

interesting. So it seems 16GB is not enough for RecycleGAN :D

**Comment by Eleganze** [comment]
Seems like it. I can't even start 256x256 at batch size 8. I downloaded a tool to see GPU memory usage, so I can keep an eye on the memory.

**Comment by iperov** [comment]
and 128x128 x 24 ?

**Comment by iperov** [comment]
Also model sets minimum bs = 16, because less bs is unstable.

**Comment by Eleganze** [comment]
No go at 128x128 x 32. I will try 24

**Comment by Eleganze** [comment]
128x128x16 seems to be the limit unfortunately.

**Comment by iperov** [comment]
Ok then, test whatever you want.
Also you can try not only 'avatar' videos.

**Comment by Eleganze** [comment]
I wish I could do the DF model on 256x256. I had great results with the 128 resolution, but its just not enough for details

**Comment by iperov** [comment]
I mean test RecycleGAN related.

I tried 256x256x16 on CPU - it eats more than 25GB and crashes, because I have no more RAM :D

**Comment by Eleganze** [comment]
I have Dual Xenon with 28 cores (56 hyper) and 64 GB Ram. I can try CPU

**Comment by iperov** [comment]
@Eleganze try 256x256 x 10
official recyclegan repo also has 10 batch size.

**Comment by iperov** [comment]
yes, also try CPU 
cpu mode is activated by arg --cpu-only

**Comment by iperov** [comment]
also you can change Resnet to UNet, it can handle x4 more batch size.

**Comment by Eleganze** [comment]
No luck on 256x256x10

**Comment by Eleganze** [comment]
UNet starts up on 256x256x16!

**Comment by Eleganze** [comment]
Negative on 256x256x32 (UNet)

**Comment by Eleganze** [comment]
Negative on 256x256x24 (UNet)

**Comment by Eleganze** [comment]
128x128x32 (UNet) works fine

**Comment by Eleganze** [comment]
128x128x64 starts and runs, but getting the memory warning

**Comment by Eleganze** [comment]
Result seems to be different / better - but just reach 200 epochs.

![128x128x64unet](https://user-images.githubusercontent.com/37071118/50527116-1aca6500-0ade-11e9-9b04-80721000e114.PNG)

**Comment by keyutao9** [comment]
128 resolution on 2080TI batch size 10, 20 minutes crash, it seems that less than 16 is unable to achieve 128 resolution, 64 resolution batch size 32 is very stable, I do not know if anyone can test this model with TITANRTX

**Comment by keyutao9** [comment]
== Options:
== |== batch_size : 40
== |== multi_gpu : False
== |== created_vram_gb : 11
== |== created_resolution : 64
== |== created_batch_size : 40
== Running on:
== |== [0 : GeForce RTX 2080 Ti]
=========================
Saving...
Starting. Press "Enter" to stop training and save model.
Saving...[#000778][0716ms] G:2.076 DA:0.431 DB:0.50534
Saving...[#001570][0687ms] G:3.395 DA:0.449 DB:0.8019
Saving...[#002397][0692ms] G:2.001 DA:0.436 DB:0.298
Saving...[#003222][0721ms] G:4.284 DA:0.397 DB:0.310529
Saving...[#004019][0686ms] G:2.271 DA:0.509 DB:0.359
Saving...[#004847][0682ms] G:2.156 DA:0.498 DB:0.280
Saving...[#005675][0690ms] G:2.507 DA:0.493 DB:0.247
Saving...[#006493][0722ms] G:1.649 DA:0.501 DB:0.145
Saving...[#007303][0687ms] G:6.363 DA:0.480 DB:0.0549326.898
Saving...[#008134][0688ms] G:6.417 DA:0.476 DB:0.021
Saving...[#008964][0685ms] G:6.764 DA:0.364 DB:0.009
Saving...[#009794][0685ms] G:7.847 DA:0.487 DB:0.005
64x64x40  also got collapse at 6500 epoch

**Comment by TooMuchFun** [comment]
On my 1070GTX I was able to train at 128 resolution with a batch size of 24 on UNET before OOM. With ResNet, 128 resolution allowed only batch-size 8. Will using UNet instead of ResNet affect converted result quality?

I am reproducing that see is that when you get past 5000 epochs the model becomes unstable and collapses after time. It does not collapse on a specific epoch number tho. I see that I can revert to a previous model back up and go past the epoch when it collapsed. However, the model again collapses after about between 500 and 1000 more epochs every time.
