### ISSUE TITLE
Xseg train stuck after selecting batch size

### ISSUE THREAD

**Issue by yibb-y** [iperov/DeepFaceLab#825]
![image](https://user-images.githubusercontent.com/55138417/87071002-e595eb80-c219-11ea-9118-a104a233e411.png)
After selecting a batch size nothing happens. CPU, GPU, RAM are ideling. Are there any log files i can check? Any ideas what's the problem here?

Thanks!

**Comment by jknight44** [comment]
Had this issue as well with no error output.
Fixed it by increasing the windows pagefile size to 50gB (might need more).

**Comment by yibb-y** [comment]
@jknight44 Thanks that worked. Is it in the readme or FAQ? I feel like there should be a section where it says "If you encounter unexpected problems, increase the pagefile size"
