### ISSUE TITLE
--seamless-erode-mask-modifier: introduces face wavering

### ISSUE THREAD

**Issue by Enyakk** [iperov/DeepFaceLab#83]
--seamless-erode-mask-modifier - works as intended!

However it seems if it is activated (set to 80 here) it introduces a small amount of wavering of the face into the final composition. I didn't notice this at first but it's there if you A/B with the option on and off. There is a slight constant drift that is stronger than with the option disabled.

**Comment by tfis2** [comment]
> 
> 
> --seamless-erode-mask-modifier - works as intended!
> 
> However it seems if it is activated (set to 80 here) it introduces a small amount of wavering of the face into the final composition. I didn't notice this at first but it's there if you A/B with the option on and off. There is a slight constant drift that is stronger than with the option disabled.

I can second that. Color matching is fine without flicker, but it seems there is a random micro shift in the face.
