### ISSUE TITLE
buttons don't work when switching language

### ISSUE THREAD

**Issue by ranshaa05** [iperov/DeepFaceLab#830]
When i switch languages in windows (shift+alt) the trainers don't register them. e.g when i press "p" it doesn't refresh unless my language is set to english.
the language I am trying to use is hebrew.
I am running the latest version (07_04_2020) on windows 10 (20161.1000) and python 3.6.9

**Comment by iperov** [comment]
yes, it works only in english lang.

**Comment by ranshaa05** [comment]
> yes, it works only in english lang.

well you should make it work in other languages too... i thought the program was haning because it didnt do anything.
maybe use keys instead of input letters?

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.

**Comment by ranshaa05** [comment]
> Issue solved / already answered (or it seems like user error), please close it.

actually, this is still relevant. it's not been fixed as far as i can see.
this can be an issue because you do not always pay attention to what language you're on, so you might think it's stuck. 
also, some people do not use English keyboard layout.

**Comment by ghost** [comment]
No, this question and suggestion has been made exactly 6 times.. relevance aside, this issue adds nothing, it is known and when time comes it will be changed accordingly. 

Want to keep it open to clutter the issues section? No problem, be my guest.
