### ISSUE TITLE
New bug of train.sh?

### ISSUE THREAD

**Issue by Joevaen** [iperov/DeepFaceLab#835]
I have followed the installation of linux. There was a numpy package in my conda environment, but it still told me "no module named numpy" when I ran the train.sh.
I am doing a work about DL, so I have been using numpy for a long time.
Why this happened?
Thanks!

**Comment by test1230-lab** [comment]
have you not installed requirementscuda.txt?

**Comment by test1230-lab** [comment]
has this been resolved?

**Comment by Joevaen** [comment]
> have you not installed requirementscuda.txt?
I have installed requirementscuda.txt, and I checked the conda package and it is there.

**Comment by test1230-lab** [comment]
pip install numpy or pip3

**Comment by test1230-lab** [comment]
has this been resolved?

**Comment by Joevaen** [comment]
> has this been resolved?
Sorry for late back.I have pip install numpy before and I didn't work.

**Comment by Joevaen** [comment]
> > has this been resolved?
> > Sorry for late back.I have pip install numpy before and it didn't work.
