### ISSUE TITLE
this is a forum problem, sorry but no other way to communicate with you guys

### ISSUE THREAD

**Issue by gargolito** [iperov/DeepFaceLab#836]
## Expected behavior

- Successful login
OR
- Successful registration
OR
- Working contact

## Actual behavior
Clicking on **Login**, prompts to log in - after user name and password are entered, I'm not logged in and the login link is still there, none of the "login required" links are available. Trying to log in again does not prompt to log in anymore and I have to clear cookies and all site data to get the login prompt, but still cannot log in.

Clicking on register, prompts to register I enter a new username with an alternate email address, but I never receive the email confirmation.

Clicking on the envelope icon at the bottom of the page is a 404, could be a malformed mailto: anchor. the url is https://mrdeepfakes.com/forums/hello@mrdeepfakes.com

## Steps to reproduce
I've tested this on MacOS Catalina with chrome, firefox and safari. On Windows with Edge, Chrome and firefox, and on ubuntu linux (focal) with chrome and firefox. I;ve also tested in incognito mode with all the above scenarios. The versions for every browser and OS tested are the latest available as of two days ago.

## Other relevant information
I captured a log with chrome in incognito mode, results are the same for all browsers and os's
[mrdeepfakes.com-1594823402152.log](https://github.com/iperov/DeepFaceLab/files/4928186/mrdeepfakes.com-1594823402152.log)
[mrdeepfakes.com-1594823182962.log](https://github.com/iperov/DeepFaceLab/files/4928187/mrdeepfakes.com-1594823182962.log)

**Comment by test1230-lab** [comment]
iperov doesnt run the site. email the admin

**Comment by gargolito** [comment]
Sorry about that! My bad.
