### ISSUE TITLE
Black screen video

### ISSUE THREAD

**Issue by JanKadic** [iperov/DeepFaceLab#845]
Hello,
When i merge to video format, it only creates black screen with sound. Didnt touch anything in merge SAEHD.

**Comment by TMBdf** [comment]
Please post more info, we don't know what kinda of GPU/OS you're running, what DFL version, what are you doing exactly, etc.

Did you actually correctly merged all faces with the merger? Check your merged folder inside data_dst, if there are now merged frames in there if you run 8) merged to mp4 it iwll output video file with no image and just sound.

**Comment by PigOnSteroids** [comment]
You likely forgot to merge all the frames in step 7. Go through the prompt, and then when you get to the interactive panel, press **shift** + **.** unless you want to edit the faces more precisely.

**Comment by JanKadic** [comment]
Hello guys, Thanks for tips. Im gonna redo training process, so tomorrow i will tell if it works.

**Comment by JanKadic** [comment]
> You likely forgot to merge all the frames in step 7. Go through the prompt, and then when you get to the interactive panel, press **shift** + **.** unless you want to edit the faces more precisely.
Is there any way to just make it faster or i just need to hold shift + , ?

**Comment by JanKadic** [comment]
Oh. i was using cze keyboard and not english keyboard.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
