### ISSUE TITLE
AVATAR Loading saved model weight fails showing ValueError: You are trying to load a weight file containing 1 layers into a model with 9 layers.

### ISSUE THREAD

**Issue by ytn2001** [iperov/DeepFaceLab#85]
AVATAR 
Loading saved model weight fails showing ValueError: You are trying to load a weight file containing 1 layers into a model with 9 layers.

I have the last Repo Version ＆ DeepFaceLab_build1202，Same problem.
Operating system and version: Windows10

**Comment by Eleganze** [comment]
Start a new project using only 1 gpu. This solved the problem for me.
