### ISSUE TITLE
multi-gpus improve perfomance

### ISSUE THREAD

**Issue by cj-edu** [iperov/DeepFaceLab#852]
We encountered a problem when we were using deepfacelab. The problem is that the time of running the deepfacelab using the 4 GPUs is not less than the time of running the deepfacelab using only 1 GPU. What can we do to make the 4 GPUs be used fully to reduce the time of running deepfacelab? We have set the parameter of “Choose one or sevevral GPU idxs(separated by comma)” as “0, 1, 2 ,3”, but it did not work. We set the parameter of using GPU as follows:
![image](https://user-images.githubusercontent.com/55915422/89619386-75ce5b80-d8c0-11ea-8a25-a54e87ed5b42.png)

**Comment by test1230-lab** [comment]
You can increase batch size with more gpus, not speed

**Comment by cj-edu** [comment]
thanks

**Comment by fuorissimo** [comment]
Useless option

> 
> 
> You can increase batch size with more gpus, not speed

So that option is useless. 👎
