### ISSUE TITLE
Deepfacelab problem tensorflow problem (NoneType)

### ISSUE THREAD

**Issue by Akanee31** [iperov/DeepFaceLab#86]
## Expected behavior

Trying to convert my final footage by use command "Convert H128"

## Actual behavior

some problem pop up on my dos window and say :

![capture](https://user-images.githubusercontent.com/45953649/50494446-9fa47880-0a23-11e9-868a-c6620fc444c3.png)

(Screenshot of the actual Behavior)

## Steps to reproduce

Just start converting footage after doing usual step to extract png and faces from Src & Dst...

## Other relevant information
- **Command lined used :** Convert to H128
- **Operating system and version:** Windows 10
- **Python version:** Python with latest DFL bundle from this git.

**Comment by iperov** [comment]
_internal\setenv.bat :
change line to rem
```rem SET TF_SUPPRESS_STD=1```
and try again, post detailed message here

**Comment by Akanee31** [comment]
@iperov changed but still the same error ..

**Comment by Akanee31** [comment]
@iperov now the pop up dos window changed for more details (i don't if it can help..)

![capture2](https://user-images.githubusercontent.com/45953649/50497515-8bb74180-0a38-11e9-98cb-8b2dc0bb9d24.PNG)

**Comment by iperov** [comment]
looks like nothing to convert

**Comment by Akanee31** [comment]
@iperov

Impossible. 3877 aligned SRC and 6983 on DSC. This can happen if I delete all the png that take size next to the aligned folder ? I never keep that frame to frame png I just keep aligned folder ...

**Comment by iperov** [comment]
deleted images? so nothing to convert.

**Comment by iperov** [comment]
Did I delete something in video tutorial?

**Comment by Akanee31** [comment]
No but, it's not impacting the result ... 
I mean, i run extract with full fps the dst video and src video.
When it done i extract faces and i just keep the aligned folder and delete all images extracted that are not on aligned folder ...is it wrong do i need to keep all of those images ? (they take heavy size instead of aligned folder) 

since the update it seems that MrDeepfake have the problem too ...
then maybe it's not my way to do it, maybe the soft is broken ?

**Comment by Akanee31** [comment]
i downloaded your Cage Facesets and it's like what i expected.
There is just facesets (aligned folder) inside the archive that you provided on Mega.
So basically it's like what i do, i keep only that folder for converting video with H128 command.

**Comment by Akanee31** [comment]
Ohhhhhh ok then i need to keep ALL the files :O 
Oh ....but what about the traing that i have done ? 187 000 epoch ....
Do i need to re training all the files ??

**Comment by iperov** [comment]
just extract dst mp4 to data_dst
and run convert

**Comment by Akanee31** [comment]
WORKED ! Thank you so much @iperov !!!!!
One more question please, can you tell me what is the best settings when i run convert command ?
there is a bunch of option but i don't really what i need to check to have best results ...
Usually i use option 3 and 0 for all the rest ..

**Comment by iperov** [comment]
there are no best settings and no best model in DFL.
All depends on data.

**Comment by Akanee31** [comment]
hmmm no option for improve seamless ? 
what do you usually use for best result ? (your personal workflow when you convert video to H128)
What kind of option you choose @iperov ?

**Comment by iperov** [comment]
watch video tutorial

**Comment by Akanee31** [comment]
thanks !
