### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by maha9090** [iperov/DeepFaceLab#87]
https://imgur.com/a/HnaUSKR
It does not change like this.[](url)

**Comment by iperov** [comment]
_internal\setenv.bat :
change line to rem
rem SET TF_SUPPRESS_STD=1
then try again and post detailed message here

**Comment by Akanee31** [comment]
@iperov i have a question about train time.
I past many days for training a src character (200 000 epoch), for a dst .
My question is do i need to train again de src (still at 200k Epoch) 
when i want to put the same src on another dst ?

**Comment by Akanee31** [comment]
@maha9090 i guess there is not enough Png (7/7)
try to get more extracted image from src or dst (run extract at full FPS) 
Try it again and post results here :)

**Comment by tfis2** [comment]
> 
> 
> @iperov i have a question about train time.
> I past many days for training a src character (200 000 epoch), for a dst .
> My question is do i need to train again de src (still at 200k Epoch)
> when i want to put the same src on another dst ?

I'm not iperov, but:
No. Normally you don't need to train again to 200k. Sometimes 1h is enough, sometimes 10 minutes, sometimes overnight. Stop the train process and do some test conversions. Also there is a preview window, which gives you -you guess it-  a preview.

**Comment by Akanee31** [comment]
@tfis2 But.. Then I keep the model folder with the trained model inside ? And just change the DST ?

**Comment by TooMuchFun** [comment]
@Akanee31 

Do u know what minimum or best numbers of Png is to still get good quality?

**Comment by Akanee31** [comment]
@TooMuchFun 1500 should be great for src, but you need less for dst (1 can be usable : for photos)
For videos Full Fps be better (depend on the lenght of the video target (src) )

**Comment by tfis2** [comment]
> 
> 
> @tfis2 But.. Then I keep the model folder with the trained model inside ? And just change the DST ?

Yes. Keep the aligned src images and the model files.

**Comment by Akanee31** [comment]
@tfis2 thank you a lot for your help !
by the way have you got some advides for me for optimizing training time ?
i know there is no miracle about that but maybe ... 

If i add to a model (src) already trained at 0.1, some new aligned face of the same character will it work and detect new face for best results when Deep learning will recreate the face ?

**Comment by tfis2** [comment]
> 
> 
> @tfis2 thank you a lot for your help !
> by the way have you got some advides for me for optimizing training time ?
> i know there is no miracle about that but maybe ...
> 
> Can i add new faces on a trainer already trained at 0.1 ?
> If yes, what will happening ?

I didN#t try it with DFL, but with Fakeapp 1.1 it was possible to add faces (aligned) faces to your source folder.  BTW 0.1 is not ver low.
