### ISSUE TITLE
Feature Request: Weight training on images with high loss value

### ISSUE THREAD

**Issue by gravis778** [iperov/DeepFaceLab#877]
It would be nice if there was a way to weight training (after a training on a dataset for a while) of images with high loss value. Maybe write loss values to a file, and then have the user specify something like "just train images with a loss value over 0.5" or something

**Comment by titanrw** [comment]
It does this automatically already.  See commit:

https://github.com/iperov/DeepFaceLab/commit/c7ab9653c5acd3dd015102c5fc75ec5fa42f2dcf

But having it train only samples with high loss values would be bad.  The model would 'unlearn' everything about the good ones.
