### ISSUE TITLE
LIAEF208

### ISSUE THREAD

**Issue by Enyakk** [iperov/DeepFaceLab#9]
Modifed LIAEF128 -> LIAEF208:
- now 13x13 deepest layer (up from 8x8), total 208x208 resolution
- reduced number of total filters (mostly decoder mask)
- runs on min 8GB GPU, batch-size 3
- 180k+ iter necessary

Results:
<a href="https://ibb.co/h9SZZo"><img src="https://thumb.ibb.co/h9SZZo/LIAF208_2.png" alt="LIAF208_2" border="0"></a>

Benefits:
- Teeth definition
- Eye pupils mostly working

No clever engineering and unwieldy to run, but can post model if wanted.

**Comment by HelpSeeker** [comment]
You can achieve a decent teeth/pupils definition with some of the other models as well, so I don't really see the benefit. Especially when it's this resource-intensive to train.

**Comment by yunanhang** [comment]
dear Enyakk ,Could you tell me how to modify the deepest layer up to 13x13 ?

**Comment by petergerten** [comment]
@Enyakk do you have a modified repo on github or somewhere else? Would love to try
