### ISSUE TITLE
How to change the used VRam ?

### ISSUE THREAD

**Issue by Malando2** [iperov/DeepFaceLab#92]
Hello,

first of all this is my system: 11GB Vram(1080 Ti), 32Gb Ram and i7-8700k.

I want to change the used Vram. at the moment it uses 10,2GB of the GPU. Actually i have no problem with it but everytime when i start training my Power supply (650w BeQuiet) makes some weird clicking noises and i dont like that. I guess it comes from due the power usage of the GPU while training.

oh and i'm using the H128 Bat.

**Comment by gessyoo** [comment]
Malando2, when you train, tensorflow-gpu allocates as much VRAM as it can, and there's no option in DFL to change that.  If your 650-watt power supply is making weird noises during training, then it's telling you that it's struggling to provide enough power to your video card.  Training a model takes many hours and sometimes days of heavy GPU usage.  If you want to protect your computer, invest in a higher wattage power supply.
