### ISSUE TITLE
Face type details.. 

### ISSUE THREAD

**Issue by Aeranstorm** [iperov/DeepFaceLab#927]
As the title stated while executing the CMD there is the options named as "Face type (f/wf/head):
Would you please kind enough to explain the meaning of these F/ wf/ head?

**Comment by IronclawFTW** [comment]
Check this tutorial. Scroll down to the faces: https://mrdeepfakes.com/forums/thread-1-1-sfw-guide-deepfacelab-2-0-guide-recommended-up-to-date
