### ISSUE TITLE
Could not find codec parameters for stream 0 (Video: png, none): unspecified size Consider increasing the value for the 'analyzeduration' and 'probesize' options

### ISSUE THREAD

**Issue by huanghanmei** [iperov/DeepFaceLab#940]
when run the "./8_merged_to_mp4.sh", there are some errors:
Could not find codec parameters for stream 0 (Video: png, none): unspecified size Consider increasing the value for the 'analyzeduration' and 'probesize' options
![Uploading 20201105142433.png…]()
some one can help?

**Comment by mod25** [comment]
how did you fixed?
