### ISSUE TITLE
xseg: Replace the head is not working

### ISSUE THREAD

**Issue by iamrishab** [iperov/DeepFaceLab#958]
## Expected behavior

https://github.com/iperov/DeepFaceLab#replace-the-head

## Actual behavior

```
Running XSeg editor.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

## Steps to reproduce
```
python main.py xseg editor  --input-dir ../../
```

## Other relevant information
- **Operating system and version:** Ubuntu 18.04 LTS
- **Python version:** 3.6.5

**Comment by ydaigo** [comment]
I got similar issue with Docker Linux Containers.
```
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
Cannot load library /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-keysyms.so.1: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-keysyms.so.1: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

```

I solved this issue with this script.

```
apt install libxkbcommon-x11-0
apt install libxcb-icccm4
apt install libxcb-image0
apt install libxcb-keysyms1
apt install libxcb-render-util0
apt install libxcb-xinerama0
apt install libxcb-randr0

```

see https://qiita.com/momomo_rimoto/items/83917d3f9f5dd35457e1

**Comment by iamrishab** [comment]
Thanks @ydaigo 
I have found an alternative approach to solve the usecase. Will surely keep this is mind incase I come across similar issue in future.

**Comment by iamrishab** [comment]
Hi @ydaigo 
Can you tell me if there is any other setup required to get the results apart from what mentioned [here](https://github.com/nagadit/DeepFaceLab_Linux).
Also if you share the exact command you are using to replace the head, given a source and a target image. Thank you.

**Comment by ydaigo** [comment]
Hi @iamrishab 

System Specifications:
OS: Ubuntu 20.04
CPU: Ryzen 7
GPU(s): Nvidia RTX 2060 super

I use docker.

Dockerfile
```
FROM tensorflow/tensorflow:2.4.0rc1-gpu
RUN apt-get update  ; apt-get upgrade -y ; \
apt-get install libsm6 libxrender1 libxext-dev -y&&\
apt-get install -y libgl1-mesa-dev -y&&\
apt-get install libfontconfig1 -y&&\
apt-get install libxkbcommon-x11-0 -y &&\
apt-get install libxcb-icccm4 -y &&\
apt-get install libxcb-image0 -y &&\
apt-get install libxcb-keysyms1 -y &&\
apt-get install libxcb-render-util0 -y &&\
apt-get install libxcb-xinerama0 -y &&\
pip install \
tqdm \
numpy==1.19.3 \
h5py==2.9.0 \
opencv-python==4.1.0.25 \
ffmpeg-python==0.1.17 \
scikit-image==0.14.2 \
scipy==1.4.1 \
colorama \
pyqt5 
WORKDIR /working
ENV QT_X11_NO_MITSHM=1
```

Run the script below. You can make docker image
`docker build -t deepfacelab_img .`

You run your image as a container at directory of deepfacelab. 
`docker run -v $PWD:/working -e DISPLAY=$DISPLAY --gpus all --workdir /working --name deepfacelab_container -it deepfacelab_img  /bin/bash
`

If you don`t run gui application(5_XSeg_data_dst_mask_edit.sh,6_train_SAEHD.sh),run this script.

`xhost local:`

Thank you.

**Comment by iamrishab** [comment]
the issue has been resolved.

**Comment by KDR622** [comment]
hello, how did you solve it?

**Comment by KDR622** [comment]
> 问题已经解决。



> 问题已经解决。

hello, how did you solve it?
