### ISSUE TITLE
BUG REPORT - MULTIGPU does not work correctly

### ISSUE THREAD

**Issue by fuorissimo** [iperov/DeepFaceLab#959]
I would like to report to the community and @iperov that the multi GPU option does not work.
If you launch a project and select 2 GPUs, the iteration time does not actually change (with the same settings).

For example in my case 1 x GPU batch10 = 1200ms and 2 x GPU batch 10 = 1300.

I attach screenshots.
https://ibb.co/Ky20bmK
https://ibb.co/KVkhpVD

**So I tried to run 2 different projects, one for each GPU.**
And in this case everything works correctly because both projects, batch 10, execute each iteration every 1200ms or so (as if it were batch 20 = 1200ms).

https://ibb.co/cx1ChYk

I reported the problem on the forum of the site "mrdeepfakes" but unfortunately I was attacked by the moderators and it was not possible to deepen the subject. I opened a topic here: https://mrdeepfakes.com/forums/thread-bug-report-multigpu-does-not-work-correctly. 

Thanks for the attention, I hope this work of mine is useful for improve this important option.

Best regards.

**Comment by dustydust** [comment]
@fuorissimo 
I looked at the last screenshot and hadn't seen that you chose 2 GPUs. If you you will choose 2 GPUs at the bottom of table you will see 2 devices (two device indexes). Try to type 0,1 (two device indexes separated by comma) when the script requires it

**Comment by fuorissimo** [comment]
> 
> 
> @fuorissimo
> I looked at the last screenshot and hadn't seen that you chose 2 GPUs. If you you will choose 2 GPUs at the bottom of table you will see 2 devices (two device indexes). Try to type 0,1 (two device indexes separated by comma) when the script requires it

Read better

**Comment by iperov** [comment]
1 GPU : 10 bs
2 GPU : 10 bs = 5 bs per gpu.

Set 20 bs when using 2 GPU, and compare time per 1 batch.

Also the speed of DFL is decreased after upgrading to tf 2.x to support RTX 3x

**Comment by iperov** [comment]
also you can use second GPU to train second fake simultaneously

**Comment by fuorissimo** [comment]
> 
> 
> 1 GPU : 10 bs
> 2 GPU : 10 bs = 5 bs per gpu.
> 
> Set 20 bs when using 2 GPU, and compare time per 1 batch.
> 
> Also the speed of DFL is decreased after upgrading to tf 2.x to support RTX 3x

That's what I've already done and explained in this post, attaching the screenshots. In reality the GPU function has no use, it raises the number of batches but also doubles the iteration time. Can't this problem be solved? Those with 2 GPUs have no benefit.

**Comment by iperov** [comment]
nope.
You set 10 bs for 2 GPU.
Set 20 bs and post screenshot.

**Comment by iperov** [comment]
> Those with 2 GPUs have no benefit. 

you can use second GPU to train second fake simultaneously

**Comment by iperov** [comment]
and where did you read that multigpu is for speed increase?
it is for batch size increase.
More batch size - better model accuracy, better quality.

**Comment by fuorissimo** [comment]
> 
> 
> and where did you read that multigpu is for speed increase?
> it is for batch size increase.
> More batch size - better model accuracy, better quality.

Having double BS and double iteration time doesn't make much sense and is useless. The quality depends on the total number of iterations, the BS just makes things faster. But if the time is longer, I don't understand what it is for.

Here are the screenshots

https://ibb.co/X2Sv6xR
https://ibb.co/Vtvn4zY

1 X GPU batch 10 = 1200ms and GPU load 90%

2 X GPU batch 20 = 2400ms and GPU load 40/50%.

The problem is that DFL in multigpu does not use the GPU at 90% and therefore wastes resources.

This is an example. https://ibb.co/rQmWwXG

Before you tell me it is a bottleneck of my PC, it is not because 2 different projects, as you have seen, work perfectly (1200ms for each at bs 10)

**Comment by iperov** [comment]
using multigpu should not be faster. 
It can be faster on small models.

>  The quality depends on the total number of iterations, the BS just makes things faster.

no. Quality also depends on batch size.

**Comment by iperov** [comment]
also GPU waits while CPU prepare samples for the training.

**Comment by fuorissimo** [comment]
Here 2 project at the same time, BS10 each 1200ms and both GPU near to 100% load (task manager show wrong data). That is BS20 at 1200, so double. My system work correctly. 

As indicate before, multiGPU don't use full GPU load but only 20/50% and so, time is half


https://ibb.co/cx1ChYk

**Comment by iperov** [comment]
ok

**Comment by fuorissimo** [comment]
Ok. Problem solved... 👎
