### ISSUE TITLE
Modify AVATAR method to show full video

### ISSUE THREAD

**Issue by wanshun123** [iperov/DeepFaceLab#96]
Currently the AVATAR method only generates a zoomed in cropped face. Is it feasible to generate videos that will be more zoomed-out and show the full face (including hair)?

**Comment by iperov** [comment]
avatar will be excluded from project

**Comment by frosty3907** [comment]
Why?

**Comment by iperov** [comment]
read commit log

**Comment by zhangdanfeng888** [comment]
> Currently the AVATAR method only generates a zoomed in cropped face. Is it feasible to generate videos that will be more zoomed-out and show the full face (including hair)?

Hey man, do you have the avatar model now? If do, can you send the model to me? There is no avatar model now in the rep. My email address is 18625801456@163.com. Thanks a lot!

**Comment by wanshun123** [comment]
> > Currently the AVATAR method only generates a zoomed in cropped face. Is it feasible to generate videos that will be more zoomed-out and show the full face (including hair)?
> 
> Hey man, do you have the avatar model now? If do, can you send the model to me? There is no avatar model now in the rep. My email address is [18625801456@163.com](mailto:18625801456@163.com). Thanks a lot!

You can just download the repo from an earlier commit that still had avatar.
