### ISSUE TITLE
Падение производительности на 4% в сравнении с августовским билдом

### ISSUE THREAD

**Issue by IndeecFOX** [iperov/DeepFaceLab#968]
У меня билд от августа. На нём производительность в тренировке SAEHD выше (Меньше времени на итерации), чем на текущем билде с GitHub. GTX1080 win 10. Разница почти 4%. В сравнение беру начало тренировки, когда до различных GAN ещё далеко. Далее может ещё сильнее упадёт производительность. Я понимаю, что 4% - не много, но всё же. Считаю долгом сообщить об этом.

515ms - Августовский билд
540ms - Скачанный 10.12.20 с GitHub

**Comment by iperov** [comment]
скачай последний билд для 2080ти
