### ISSUE TITLE
Hist Match Threshold missing?

### ISSUE THREAD

**Issue by ZeroCool22** [iperov/DeepFaceLab#98]
Running converter.

Loading model...
===== Model summary =====
== Model name: H128
==
== Current epoch: 8445
==
== Model options:
== Session options:
== |== batch_size : 32
== Running on:
== |== [0 : GeForce GTX 1080 Ti]
=========================
Choose mode: (1) overlay, (2) hist match, (3) hist match bw, (4) seamless (default), (5) seamless hist match : 1
Use predicted mask? (y/n skip:y) :
Choose erode mask modifier [-200..200] (skip:0) : 10
Choose blur mask modifier [-200..200] (skip:0) : 50
Choose output face scale modifier [-50..50] (skip:0) :
Transfer color from dst face to converted final face? (y/n skip:n) : y
Degrade color power of final image [0..100] (skip:0) :
Export png with alpha channel? (y/n skip:n) :

Collecting alignments: 100%|███████████████████████████████████████████████████████| 248/248 [00:00<00:00, 1763.95it/s]

**Comment by iperov** [comment]
you choosed overlay mode
