### ISSUE TITLE
Multi GPU load vs batch size and speed

### ISSUE THREAD

**Issue by titanrw** [iperov/DeepFaceLab#99]
Hi.

I just started playing with DeepFaceLab.  I have 2x 980ti's.

The thing I've noticed is that the gpu load is very 'spiky' when using both cards, causing quite annoying power spikes, which cause lights to flicker throughout part of the house.  Kinda makes sense as power draw goes from as low as 200w to as high as 1,000w multiple times per second.  Here's a gpu load graph training H128 on default batch size of 8:

[https://i.imgur.com/rKZNxLs.png](https://i.imgur.com/rKZNxLs.png)

GPU2 is especially spiky

I tried upping the batch size to 16 and get this:

[https://i.imgur.com/T63Vkgc.png](https://i.imgur.com/T63Vkgc.png)

GPU2 isn't quite as spiky, but it's still varying load quite a bit, still causing flickering lights.

Are there any settings that could be changed to smooth out the gpu usage in multi gpu mode, and therefore the power draw?

As a comparison, limiting training to a single gpu sees much more consistent load on the gpu:

[https://i.imgur.com/vV5YTq4.png](https://i.imgur.com/vV5YTq4.png)

Another question about batch size.  Is the ms per epoch related to batch size?  For example, I'm getting about 500ms per epoch at batch size 8, but 750ms at batch size 16.  Is 8 therefore better because it's faster per epoch, or is 16 better because the batch size doubled, and double the work is being done in only 50% more time? 

Thanks in advance.

**Comment by titanrw** [comment]
Thanks for the reply.  

I don't pretend to understand all the details, but it's too bad multi gpu doesn't work.  Machine learning is one area I thought there'd be a huge push for multi gpu setups.  I guess I can always have two different models training at the same time, each utilizing their own gpu.

Regarding the batch size, is there any need to limit to powers of 2?  Or should you fine tune to the largest batch size that will not produce OOM errors, regardless of the exact number?

**Comment by iperov** [comment]
no limit to powers of 2

**Comment by titanrw** [comment]
Thanks for the help.

**Comment by deyu260** [comment]
> Thanks for the help.

Are you still training on multiple gpu? Whether the efficiency problem is solved, only one gpu is loaded at the same time.

**Comment by iperov** [comment]
dfl not use multi gpu
